# Generated by Django 6.0.4 on 2026-04-15 10:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('seed', models.BigIntegerField(db_index=True)),
                ('ptype', models.CharField(db_index=True, max_length=32)),
                ('features', models.JSONField()),
                ('discovered', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_visited', models.DateTimeField(default=django.utils.timezone.now)),
                ('visit_count', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['-last_visited'],
            },
        ),
    ]
