# Generated by Django 6.0.4 on 2026-04-15 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planet',
            name='primary_language_slug',
            field=models.CharField(blank=True, default='', max_length=140),
        ),
    ]
