# Generated by Django 6.0.4 on 2026-05-13 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('party_a', models.CharField(default='Alice', max_length=40)),
                ('party_b', models.CharField(default='Bob', max_length=40)),
                ('seed_matrix', models.BinaryField(help_text='64 bytes; one PRNG seed per component CA.')),
                ('rule_snapshot', models.BinaryField(help_text='16384 bytes; one 4-state CA output per key.')),
                ('palette', models.JSONField(default=list, help_text='Four [r,g,b] anchors for the four cell states.')),
                ('clock_model', models.CharField(choices=[('synced', 'synced — ticks from launch_time on UTC clock (two viewers anywhere see identical state)'), ('local', 'local — ticks from page-load on viewer clock (time dilation analogue; each viewer diverges)')], default='synced', max_length=8)),
                ('tick_ms', models.PositiveIntegerField(default=180, help_text='Milliseconds per CA generation under synced clock; also the default for local clock.')),
                ('launch_time', models.DateTimeField(help_text='UTC moment the pact "engages".  For synced clock this fixes the tick zero.  Earlier than now → state is already advanced when first opened.')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spoeqi_pacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
