# Generated by Django 6.0.4 on 2026-05-13 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('det', '0005_tournament_source_tournaments'),
        ('spoeqi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pact',
            name='det_candidate',
            field=models.ForeignKey(blank=True, help_text='Optional source Hexhunt class-4 candidate.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spoeqi_pacts', to='det.candidate'),
        ),
    ]
