# Generated by Django 6.0.4 on 2026-05-13 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spoeqi', '0002_pact_det_candidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='pact',
            name='component_grid',
            field=models.PositiveSmallIntegerField(choices=[(8, ' 8 × 8  (tiny, 4,096 cells total)'), (16, '16 × 16 (default, 16,384 cells)'), (24, '24 × 24 (36,864 cells)'), (32, '32 × 32 (65,536 cells)'), (48, '48 × 48 (147,456 cells)'), (64, '64 × 64 (262,144 cells; cells render as pixels)')], default=16, help_text='Side length of each component CA in hex cells.'),
        ),
    ]
