# Generated by Django 6.0.4 on 2026-05-13 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spoeqi', '0003_pact_component_grid'),
    ]

    operations = [
        migrations.AddField(
            model_name='pact',
            name='mutation_density',
            field=models.PositiveSmallIntegerField(default=1024, help_text='When diversity=mutated, number of rule-table entries per component that get flipped from the base rule.  1024 ≈ 6 %% of the 16,384-entry table.'),
        ),
        migrations.AddField(
            model_name='pact',
            name='rule_diversity',
            field=models.CharField(choices=[('shared', 'shared — 1 rule × 64 seeds (current behaviour; cheapest)'), ('mutated', 'mutated — 1 base rule + 64 deterministic perturbations (rule diversity with shared lineage)'), ('fleet', 'fleet — 64 independent Hexhunt class-4 rules (maximum diversity; ~1 MiB rule data)')], default='shared', help_text='How rules are distributed across the 64 components.', max_length=10),
        ),
        migrations.AddField(
            model_name='pact',
            name='rules_snapshot',
            field=models.BinaryField(blank=True, help_text='64 × 16384 = 1048576 bytes; per-component rules, concatenated.  NULL when diversity=shared.', null=True),
        ),
    ]
