# Generated by Django 6.0.4 on 2026-05-13 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spoeqi', '0004_pact_mutation_density_pact_rule_diversity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pact',
            name='fleet_candidate_ids',
            field=models.JSONField(blank=True, default=None, help_text='List of 64 Det Candidate IDs in component order. NULL when diversity != fleet.', null=True),
        ),
    ]
