# Generated by Django 6.0.4 on 2026-05-14 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spoeqi', '0005_pact_fleet_candidate_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='pact',
            name='album_hash',
            field=models.CharField(blank=True, default='', help_text='SHA-256 hex of the normalized album bytes (when this pact was created from an image album).  Empty for non-album pacts.', max_length=64),
        ),
        migrations.AddField(
            model_name='pact',
            name='album_n_images',
            field=models.PositiveSmallIntegerField(blank=True, default=None, help_text='Number of images in the cover album (2, 4, 8, or 16).', null=True),
        ),
        migrations.AddField(
            model_name='pact',
            name='initial_grids',
            field=models.JSONField(blank=True, default=None, help_text='Optional override of the initial CA state.  When set, this is a list of 64 lists, each of side² ints in 0..3 (row-major).  Lets a pact start from an image-derived state instead of the xoshiro expansion of seed_matrix.', null=True),
        ),
    ]
