# Generated by Django 6.0.4 on 2026-05-15 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spoeqi', '0006_pact_album_hash_pact_album_n_images_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pact',
            name='workspace_share_token',
            field=models.CharField(blank=True, help_text='URL-safe token; pair with the slug to fetch workspace ELFs without logging in.', max_length=43),
        ),
    ]
