# Generated by Django 6.0.4 on 2026-05-16 11:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spoeqi', '0008_backfill_workspace_share_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metapact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('notes', models.TextField(blank=True)),
                ('seed_state', models.BinaryField()),
                ('depth', models.PositiveSmallIntegerField(default=10)),
                ('chain_ticks', models.PositiveSmallIntegerField(default=24)),
                ('parent_seed', models.BinaryField(blank=True, null=True)),
                ('ga_generations', models.PositiveIntegerField(default=0)),
                ('ga_pop_size', models.PositiveIntegerField(default=0)),
                ('final_chain_quality', models.FloatField(default=0.0)),
                ('final_class4_depth', models.PositiveIntegerField(default=0)),
                ('final_leaf_fitness', models.FloatField(default=0.0)),
                ('leaf_probe', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
