# Generated by Django 6.0.4 on 2026-04-19 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Circuit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=160)),
                ('tagline', models.CharField(blank=True, max_length=240)),
                ('body_md', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'draft'), ('breadboard', 'breadboard'), ('perfboard', 'perfboard'), ('pcb', 'pcb'), ('shelved', 'shelved')], default='draft', max_length=16)),
                ('diagram_kind', models.CharField(blank=True, help_text="Kroki diagram kind (e.g. 'svgbob', 'tikz', 'ditaa').", max_length=20)),
                ('diagram_source', models.TextField(blank=True, help_text='Diagram source — rendered via codex.rendering.diagrams.')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('mpn', models.CharField(blank=True, help_text='Manufacturer part number.', max_length=120)),
                ('category', models.CharField(choices=[('resistor', 'Resistor'), ('capacitor', 'Capacitor'), ('supercap', 'Supercapacitor'), ('inductor', 'Inductor'), ('diode', 'Diode'), ('schottky', 'Schottky diode'), ('zener', 'Zener diode'), ('led', 'LED'), ('transistor', 'Transistor (BJT)'), ('mosfet', 'MOSFET'), ('ic', 'IC'), ('mcu', 'MCU'), ('regulator', 'Regulator / LDO'), ('comparator', 'Comparator'), ('opamp', 'Op-amp'), ('connector', 'Connector'), ('switch', 'Switch'), ('panel', 'Solar panel'), ('battery', 'Battery'), ('crystal', 'Crystal / oscillator'), ('misc', 'Misc')], default='misc', max_length=20)),
                ('specs', models.JSONField(blank=True, default=dict, help_text='Structured specs, e.g. {"vf_mv": 450, "if_a": 1.0}.')),
                ('datasheet_url', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('est_unit_price_usd', models.DecimalField(blank=True, decimal_places=4, help_text='Average unit price, recomputed from price snapshots.', max_digits=10, null=True)),
                ('price_last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CircuitPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designator', models.CharField(blank=True, help_text='Reference designator, e.g. D1, C2, U1.', max_length=32)),
                ('qty', models.PositiveIntegerField(default=1)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('circuit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom', to='powerlab.circuit')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='circuit_uses', to='powerlab.part')),
            ],
            options={
                'ordering': ['display_order', 'designator', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PartPriceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(max_length=100)),
                ('unit_price_usd', models.DecimalField(decimal_places=4, max_digits=10)),
                ('qty_break', models.PositiveIntegerField(default=1, help_text='Quantity break the price was quoted at (1 = single unit).')),
                ('source_url', models.URLField(blank=True)),
                ('observed_at', models.DateTimeField(auto_now_add=True)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_snapshots', to='powerlab.part')),
            ],
            options={
                'ordering': ['-observed_at'],
            },
        ),
    ]
