# Generated by Django 6.0.4 on 2026-04-19 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerlab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='circuit',
            name='schematic_json',
            field=models.JSONField(blank=True, default=dict, help_text='Browser-edited schematic — { nodes: [...], wires: [...] }.'),
        ),
    ]
