"""Load + generate from a caformer_funnel_tokens trained model.

A funnel_tokens model on disk is just a directory of per-(position, cell)
LUT files: chain_p<NN>_c<C>.lut, each 16,384 bytes (K=4 hex LUT).
Generation is deterministic — no temperature, no sampling.

Trained-prompt length lookup: the demo prompt set is known
(caformer_funnel_tokens default --pairs).  When the user types one of
those prompts, we know the trained response length and truncate output
there to avoid trailing garbage bytes from positions > response_len.
For unknown prompts we emit full max_pos bytes and let the caller see
whatever the chains produce.
"""
from __future__ import annotations

import threading
from pathlib import Path
from typing import Optional

import numpy as np


N_STATES     = 4
LUT_SIZE     = N_STATES ** 7
SIDE         = 4
DECODE_CELLS = 4


def _embed_prompt(prompt: str, side: int = SIDE) -> np.ndarray:
    n_cells = side * side
    bytes_per_board = n_cells // 4
    raw = prompt.encode('utf-8')[:bytes_per_board]
    out = np.zeros(n_cells, dtype=np.uint8)
    for i, b in enumerate(raw):
        out[i * 4 + 0] = (b >> 6) & 3
        out[i * 4 + 1] = (b >> 4) & 3
        out[i * 4 + 2] = (b >> 2) & 3
        out[i * 4 + 3] =  b       & 3
    return out.reshape(side, side)


def _run(rule_arr: np.ndarray, state0: np.ndarray, ticks: int) -> np.ndarray:
    from caformer.primitives import hex_ca_step
    state = state0.copy()
    for _ in range(ticks):
        state = hex_ca_step(state, rule_arr)
    return state


class FunnelModel:
    """One funnel_tokens model loaded from disk.  Thread-safe for read
    (numpy arrays are immutable after load)."""

    def __init__(self, model_dir: Path, ticks: int = 6):
        self.model_dir = Path(model_dir)
        self.ticks = ticks
        self.chains: dict[int, list[np.ndarray]] = {}
        self._load()

    def _load(self):
        files = sorted(self.model_dir.glob('chain_p*_c*.lut'))
        if not files:
            raise FileNotFoundError(
                f'no chain_p*_c*.lut files in {self.model_dir}')
        for f in files:
            stem = f.stem  # chain_pNN_cC
            parts = stem.split('_')
            pos = int(parts[1][1:])
            cell = int(parts[2][1:])
            rule_bytes = f.read_bytes()
            if len(rule_bytes) != LUT_SIZE:
                raise ValueError(
                    f'{f}: expected {LUT_SIZE} bytes, got {len(rule_bytes)}')
            arr = np.frombuffer(rule_bytes, dtype=np.uint8) & 3
            self.chains.setdefault(pos, [None] * DECODE_CELLS)[cell] = arr
        # Validate every position has all DECODE_CELLS cells.
        for pos, cells in self.chains.items():
            if any(c is None for c in cells):
                missing = [i for i, c in enumerate(cells) if c is None]
                raise ValueError(f'pos {pos}: missing cells {missing}')

    @property
    def max_pos(self) -> int:
        return max(self.chains) + 1 if self.chains else 0

    def generate(self, prompt: str, max_pos: Optional[int] = None) -> bytes:
        """Run the chains and return generated bytes (up to max_pos or
        the model's trained position count)."""
        stim = _embed_prompt(prompt)
        n_pos = max_pos if max_pos is not None else self.max_pos
        out = bytearray()
        for i in range(n_pos):
            if i not in self.chains:
                break
            cells = self.chains[i]
            digits = [int(_run(cells[c], stim, self.ticks)[0, 0])
                       for c in range(DECODE_CELLS)]
            byte = (digits[0] << 6) | (digits[1] << 4) | \
                      (digits[2] << 2) | digits[3]
            out.append(byte)
        return bytes(out)


# ── Module-level cache: load once per (path, ticks) ─────────────────
_CACHE: dict[tuple[str, int], FunnelModel] = {}
_LOCK = threading.Lock()


def get_model(model_dir: str | Path, ticks: int = 6) -> FunnelModel:
    key = (str(model_dir), ticks)
    with _LOCK:
        if key not in _CACHE:
            _CACHE[key] = FunnelModel(Path(model_dir), ticks=ticks)
        return _CACHE[key]


def trained_prompt_lengths_for_demo() -> dict[str, int]:
    """The pair → expected-response-length map for the default demo
    model.  Used to truncate output cleanly for the 11 known training
    prompts; unknown prompts show whatever the chains produce.

    These are *actual* QRPair response lengths.  The model must be
    trained to at least max(lengths) = 30 positions or longer responses
    will be silently truncated."""
    return {
        'hi':            5,   # 'hello'
        'goodbye':       4,   # 'bye!'
        'bye':           4,   # 'bye!'
        'see you later':10,   # 'take care!'
        'yo':            7,   # 'y0 d00d'
        '0435':          9,   # 'y0 h4k3r5'
        'hey':           5,   # 'hello'
        'y0 beano':     24,   # 'beano: hey this is beano'
        'bees':         33,   # 'https://en.wikipedia.org/wiki/Bee'
        'HI':            4,   # 'HEY!'
        'hello':         9,   # 'greetings'
        # Extended compositional corpus (2026-05-18) — used by both
        # byte and word layers once their respective models are retrained.
        'look up bees': 33,   # 'https://en.wikipedia.org/wiki/Bee'
        'look up cats': 33,   # 'https://en.wikipedia.org/wiki/Cat'
        'look up dogs': 33,   # 'https://en.wikipedia.org/wiki/Dog'
        'look up ants': 33,   # 'https://en.wikipedia.org/wiki/Ant'
        'cats':          4,   # 'meow'
        'dogs':          4,   # 'woof'
        'ants':         17,   # 'march march march'
    }
