"""Per-token quine-chain genome: one 4 KB origin per token, chain
regenerated by self-application.

The pitch: instead of evolving a 10-rule joint genome per QRPair
(163,840 bytes), assign each distinct target byte a class-4 L0 fixed-
point quine origin from the spoeqi pool.  The "training" reduces to
picking which of the 64 metachain levels of that token's chain to use
as the output rule at each position.  Storage = packed origin = 4096
bytes per token.  Chain levels are regenerated on demand (no storage).

The win: per-token isolation (no shared GA pressure → no rule-slot
collapse from feedback_caformer_rule_diversity), and once the token
bank is built up the marginal cost of a new QRPair is only the unique
tokens it introduces.
"""
from __future__ import annotations

import hashlib
from dataclasses import dataclass, field
from typing import Callable, Dict, List, Optional, Tuple

import numpy as np

from .primitives import hex_ca_step, lcg_bytes, random_rule_table
from .transformer import ca_forward_qkv


GRID_SIDE = 128
RULE_SIZE = 4 ** 7                            # 16,384
BASE_RULE_NAMES = ('q', 'k', 'v', 'score', 'mix', 'merge', 'mlp', 'norm', 'embed')


def _probe_init(origin: bytes, level: int) -> np.ndarray:
    """Per-level deterministic 128×128 probe grid keyed by
    (origin sha, level index).  Used by ``ca_evolution`` chain mode so
    each level samples the origin rule's dynamics from a different
    starting point — a fixed-point quine's metachain collapses to one
    rule, but its CA dynamics from varied inits give us 64 distinct
    grids for free."""
    digest = hashlib.sha256(origin).digest()
    # Seed = first 4 bytes of the digest XOR'd with the level index
    # rotated into a 32-bit slot.  Distinct (origin, level) → distinct seed.
    seed = int.from_bytes(digest[:4], 'big') ^ ((level * 2654435761) & 0xFFFFFFFF)
    bytes_arr = lcg_bytes(seed, GRID_SIDE * GRID_SIDE) & 3
    return bytes_arr.reshape(GRID_SIDE, GRID_SIDE).astype(np.uint8)


# ─── L0 quine pool access ─────────────────────────────────────────────

def load_l0_quine_pool(*, min_fitness: float = 0.999,
                        limit: Optional[int] = None) -> List[Tuple[int, bytes]]:
    """Return [(component_pk, rule_bytes), ...] for the L0 fixed-point
    class-4 quines persisted by spoeqi.l0_quine_search."""
    from .models import ComponentChampion
    qs = (ComponentChampion.objects
          .filter(component_slug='class4_quine', fitness__gte=min_fitness)
          .order_by('pk'))
    if limit:
        qs = qs[:limit]
    return [(c.pk, bytes(c.rules_blob)) for c in qs]


# ─── Metachain expansion (level i+1 = run level i for `ticks` steps) ──

def chain_levels(origin: bytes, *, depth: int = 64,
                  ticks_per_level: int = 16,
                  mode: str = 'ca_evolution') -> List[np.ndarray]:
    """Build a depth-deep level series from an origin rule.

    Two modes:

    - ``ca_evolution`` (default): level i = state of origin rule applied
      to ``_probe_init(origin, i)`` for ``ticks_per_level`` ticks, then
      flattened to a 16,384-byte LUT.  Always produces ``depth`` distinct
      levels — different inits give different orbits, so even a
      fixed-point quine generates variety.

    - ``metachain``: level 0 IS the origin; level i+1 = run level i on
      its own LUT-as-image.  Truncates at first cycle.  For L0 fixed-
      point quines this collapses to a single rule (origin = its own
      next level), which is useless for token routing — kept for
      diagnostic comparison only.

    Returns a list of uint8 (16384,) arrays; length ≤ depth.
    """
    if len(origin) != RULE_SIZE:
        raise ValueError(f'origin must be {RULE_SIZE} bytes, got {len(origin)}')
    rule_arr = np.frombuffer(origin, dtype=np.uint8).copy() & 3

    if mode == 'ca_evolution':
        out: List[np.ndarray] = []
        seen: set[bytes] = set()
        for i in range(depth):
            state = _probe_init(origin, i).copy()
            for _ in range(ticks_per_level):
                state = hex_ca_step(state, rule_arr)
            flat = state.flatten() & 3
            digest = hashlib.sha256(flat.tobytes()).digest()[:12]
            if digest in seen:
                continue
            seen.add(digest)
            out.append(flat.copy())
        return out

    if mode == 'metachain':
        out = [rule_arr.copy()]
        seen = {hashlib.sha256(rule_arr.tobytes()).digest()[:12]}
        for _ in range(depth - 1):
            rule = out[-1]
            state = rule.reshape(GRID_SIDE, GRID_SIDE).copy()
            for _ in range(ticks_per_level):
                state = hex_ca_step(state, rule)
            nxt = state.flatten() & 3
            digest = hashlib.sha256(nxt.tobytes()).digest()[:12]
            out.append(nxt.copy())
            if digest in seen:
                break
            seen.add(digest)
        return out

    raise ValueError(f'unknown chain mode: {mode!r}')


# ─── Base rules (shared across all tokens, frozen) ───────────────────

def build_base_rules(base_seed: int) -> Dict[str, np.ndarray]:
    """Frozen 9 base rules, same construction as
    qr_trainer.train_pair_positional so a fair comparison runs through
    the exact same forward pass."""
    return {n: random_rule_table(base_seed ^ (0x100 * (i + 1)))
            for i, n in enumerate(BASE_RULE_NAMES)}


# ─── Token → quine origin assignment ─────────────────────────────────

def assign_origins(unique_tokens: List[int], pool: List[Tuple[int, bytes]]
                    ) -> Dict[int, Tuple[int, bytes]]:
    """Deterministically assign each unique target byte a distinct
    origin from the pool by hash — no training, no context.  Baseline
    for comparing against context-aware selection."""
    if len(pool) < len(unique_tokens):
        raise ValueError(f'need {len(unique_tokens)} quines, pool has {len(pool)}')
    used: set[int] = set()
    out: Dict[int, Tuple[int, bytes]] = {}
    n = len(pool)
    for tb in sorted(unique_tokens):
        idx = tb % n
        for _ in range(n):
            if idx not in used:
                used.add(idx)
                out[tb] = pool[idx]
                break
            idx = (idx + 1) % n
    return out


def select_origins_by_fitness(target_bytes: List[int],
                                prompt_bytes: List[int],
                                n_blocks: int,
                                pool: List[Tuple[int, bytes]],
                                base: Dict[str, np.ndarray],
                                *, n_candidates: int = 32,
                                chain_depth: int = 16,
                                ticks_per_level: int = 8,
                                chain_mode: str = 'ca_evolution',
                                argmax_bonus: float = 5.0,
                                log: Callable[[str], None] = print,
                                ) -> Dict[int, Tuple[int, bytes]]:
    """Per-token origin selection: for each unique token, score the top
    ``n_candidates`` quines from the pool by the *best-chain-level*
    fitness summed over every position in this corpus where the token
    appears.  Keep the highest-scoring origin per token.

    All candidates use the same shared base rules so the choice
    isolates the origin's contribution.  Distinct quines may be picked
    by multiple tokens — that's fine (no cross-token interference here
    because each token only consumes its own chain at inference).

    Returns {token_byte: (component_pk, origin_bytes)}.
    """
    block_rules_template = [{k: base[k] for k in
                              ('q', 'k', 'v', 'score', 'mix', 'merge', 'mlp')}
                              ] * n_blocks
    unique = sorted(set(target_bytes))
    # Each token's contexts: every position where it's the target.
    token_positions: Dict[int, List[List[int]]] = {tb: [] for tb in unique}
    for pos, tb in enumerate(target_bytes):
        token_positions[tb].append(list(prompt_bytes) + target_bytes[:pos])

    # Limit candidates to the first n_candidates of the pool (sorted by
    # pk → effectively by discovery order; could randomise but
    # determinism is more useful for benchmarking).
    candidates = pool[:n_candidates]
    out: Dict[int, Tuple[int, bytes]] = {}
    for tb in unique:
        contexts = token_positions[tb]
        best_score = -np.inf
        best_pk = -1
        best_origin = b''
        for pk, origin in candidates:
            chain = chain_levels(origin, depth=chain_depth,
                                  ticks_per_level=ticks_per_level,
                                  mode=chain_mode)
            # Token's score under this origin: for each context where
            # the token appears, pick the chain level that best argmaxes
            # it; sum those across contexts.
            token_score = 0.0
            for ctx in contexts:
                pos_best = -np.inf
                for rule in chain:
                    fit, _ = _position_logprob(
                        ctx, n_blocks, base, block_rules_template,
                        rule, tb, argmax_bonus)
                    if fit > pos_best:
                        pos_best = fit
                token_score += pos_best
            if token_score > best_score:
                best_score = token_score
                best_pk = pk
                best_origin = origin
        out[tb] = (best_pk, best_origin)
        log(f'  token {_pretty(tb)} ← quine #{best_pk}  '
            f'score={best_score:+.3f} (over {len(contexts)} context{"s" if len(contexts) != 1 else ""})')
    return out


# ─── Single-position fitness (mirrors qr_trainer._f) ──────────────────

def _position_logprob(ctx: List[int], n_blocks: int,
                       base: Dict[str, np.ndarray],
                       block_rules_template: list,
                       output_rule: np.ndarray,
                       target_byte: int,
                       argmax_bonus: float) -> Tuple[float, int]:
    """Returns (fitness, argmax_idx).  Fitness = log p(target) + bonus
    if argmax == target.  Matches qr_trainer.train_pair_positional._f."""
    logits = ca_forward_qkv(
        ctx, n_blocks=n_blocks,
        embed_rule=base['embed'],
        block_rules=block_rules_template,
        norm_rule=base['norm'],
        output_rule=output_rule,
        vocab_size=256)
    shifted = logits - float(logits.max())
    exp = np.exp(shifted)
    denom = float(exp.sum())
    p_true = float(exp[target_byte] / denom) if denom > 0 else 1e-30
    lp = float(np.log(max(p_true, 1e-30)))
    argmax = int(np.argmax(logits))
    bonus = argmax_bonus if argmax == target_byte else 0.0
    return lp + bonus, argmax


# ─── Per-token chain trainer ─────────────────────────────────────────

@dataclass
class ChainTrainConfig:
    base_seed:       int = 0xBA5E_C0DE      # match qr_trainer for fairness
    chain_depth:     int = 64
    ticks_per_level: int = 16
    chain_mode:      str = 'ca_evolution'   # or 'metachain' (collapses on FP quines)
    argmax_bonus:    float = 5.0
    min_pool_fit:    float = 0.999
    select_origins:  bool = True            # search pool for per-token best
    select_n:        int = 32               # candidates to evaluate per token
    refine_flips:    int = 0                # post-selection hill-climb budget
    refine_sample:   int = 64               # LUT positions sampled per flip
    ga_generations:  int = 0                # 0 = skip GA; >0 = (μ+λ) ES per token
    ga_mu:           int = 4
    ga_lam:          int = 8
    ga_mut_min:      int = 8
    ga_mut_max:      int = 64
    log:             Callable[[str], None] = print


@dataclass
class PositionResult:
    pos:           int
    target_byte:   int
    target_char:   str
    chosen_level:  int
    origin_pk:     int
    fitness:       float
    argmax:        int
    match:         bool


@dataclass
class ChainTrainResult:
    pair_id:        int
    prompt:         str
    expected:       str
    positions:      List[PositionResult] = field(default_factory=list)
    token_origins:  Dict[int, int] = field(default_factory=dict)  # byte → pk
    chain_depth:    int = 0

    @property
    def total_fitness(self) -> float:
        return sum(p.fitness for p in self.positions)

    @property
    def matches(self) -> int:
        return sum(1 for p in self.positions if p.match)

    @property
    def n_unique_tokens(self) -> int:
        return len(self.token_origins)

    def storage_bytes(self) -> dict:
        """Storage accounting.  Per-token chains store only the packed
        origins; the chain levels regenerate at inference time."""
        return {
            'per_token_origins_packed': 4096 * self.n_unique_tokens,
            'base_rules_packed':         4096 * 9,    # shared across all pairs
            'joint_genome_raw':         16384 * 10,   # what we replace
            'per_position_outputs_raw': 16384 * len(self.positions),
        }


def _score_token_origin(origin: bytes, contexts: List[List[int]],
                         target_byte: int, n_blocks: int,
                         base: Dict[str, np.ndarray],
                         block_rules_template: list,
                         chain_depth: int, ticks_per_level: int,
                         chain_mode: str, argmax_bonus: float) -> float:
    """Token's summed best-chain-level fitness across all contexts where
    it appears.  Used by both selection and hill-climb refinement."""
    chain = chain_levels(origin, depth=chain_depth,
                          ticks_per_level=ticks_per_level, mode=chain_mode)
    score = 0.0
    for ctx in contexts:
        pos_best = -np.inf
        for rule in chain:
            fit, _ = _position_logprob(
                ctx, n_blocks, base, block_rules_template,
                rule, target_byte, argmax_bonus)
            if fit > pos_best:
                pos_best = fit
        score += pos_best
    return score


def hill_climb_origin(origin: bytes, contexts: List[List[int]],
                       target_byte: int, n_blocks: int,
                       base: Dict[str, np.ndarray],
                       block_rules_template: list,
                       *, chain_depth: int, ticks_per_level: int,
                       chain_mode: str, argmax_bonus: float,
                       n_flips: int, sample_size: int,
                       rng_seed: int = 0,
                       log: Callable[[str], None] = print,
                       ) -> Tuple[bytes, float]:
    """Single-byte hill-climb on a 16,384-entry origin LUT.  Each flip
    samples ``sample_size`` LUT positions; for each position tries all
    3 alternative K=4 colours; accepts if score improves.  Caps at
    ``n_flips`` accepted flips (not evaluations) so the loop stops
    when no more gains.

    Drops the quine guarantee — refined origins may no longer be
    fixed-points — but storage stays 4096 packed bytes per token
    and the chain still uses the ca_evolution mode (origin's dynamics,
    not metachain self-application), so quine purity wasn't load-bearing
    for chain quality anyway."""
    rng = np.random.default_rng(rng_seed)
    arr = bytearray(np.frombuffer(origin, dtype=np.uint8).copy() & 3)
    cur_score = _score_token_origin(
        bytes(arr), contexts, target_byte, n_blocks, base,
        block_rules_template, chain_depth, ticks_per_level,
        chain_mode, argmax_bonus)
    accepted = 0
    for flip_i in range(n_flips):
        idxs = rng.choice(RULE_SIZE, size=min(sample_size, RULE_SIZE),
                            replace=False)
        improved = False
        for k in idxs:
            original = int(arr[k])
            local_best = cur_score
            local_alt = original
            for alt in range(4):
                if alt == original:
                    continue
                arr[k] = alt
                sc = _score_token_origin(
                    bytes(arr), contexts, target_byte, n_blocks, base,
                    block_rules_template, chain_depth, ticks_per_level,
                    chain_mode, argmax_bonus)
                if sc > local_best:
                    local_best = sc
                    local_alt = alt
            arr[k] = local_alt
            if local_alt != original:
                cur_score = local_best
                accepted += 1
                improved = True
                break        # one accepted flip per pass — re-sample next pass
        if not improved:
            log(f'    hill-climb: plateau at flip {flip_i} '
                f'(accepted={accepted}, score={cur_score:+.3f})')
            break
    return bytes(arr), cur_score


def collect_origin_fire_mask(origin: bytes, chain_depth: int,
                              ticks_per_level: int, chain_mode: str
                              ) -> np.ndarray:
    """For an origin rule, find which LUT keys fire during chain
    construction (the CA running on its own probe inits or self-LUT).
    Returns bool mask of size 16,384.  This is the per-origin analogue
    of collect_fire_masks — mutation should only flip these entries
    because non-firing keys have zero effect on the chain levels.
    """
    from caformer import primitives as prim

    rule_arr = np.frombuffer(origin, dtype=np.uint8).copy() & 3
    fire_set: set = set()
    orig_step = prim.hex_ca_step

    def traced_step(state: np.ndarray, rule_table: np.ndarray) -> np.ndarray:
        # We only care when the origin rule itself fires
        if rule_table is rule_arr or (
                rule_table.shape == rule_arr.shape
                and np.array_equal(rule_table, rule_arr)):
            keys = _compute_hex_keys(state.astype(np.uint8))
            fire_set.update(np.unique(keys).tolist())
        return orig_step(state, rule_table)

    prim.hex_ca_step = traced_step
    try:
        # Recompute chain levels with tracing; reuse chain_levels logic
        if chain_mode == 'ca_evolution':
            for i in range(chain_depth):
                state = _probe_init(origin, i).copy()
                for _ in range(ticks_per_level):
                    state = traced_step(state, rule_arr)
        else:
            current = rule_arr.copy()
            for _ in range(chain_depth):
                state = current.reshape(GRID_SIDE, GRID_SIDE).copy()
                for _ in range(ticks_per_level):
                    state = traced_step(state, current)
                current = state.flatten() & 3
    finally:
        prim.hex_ca_step = orig_step

    mask = np.zeros(RULE_SIZE, dtype=bool)
    if fire_set:
        mask[np.array(sorted(fire_set), dtype=np.int64)] = True
    return mask


def evolve_origin(start_origin: bytes,
                   contexts: List[List[int]],
                   target_byte: int, n_blocks: int,
                   base: Dict[str, np.ndarray],
                   block_rules_template: list,
                   *, chain_depth: int, ticks_per_level: int,
                   chain_mode: str, argmax_bonus: float,
                   mu: int = 4, lam: int = 8, generations: int = 8,
                   mutation_min: int = 8, mutation_max: int = 64,
                   smart_mutation: bool = False,
                   rng_seed: int = 0,
                   log: Callable[[str], None] = print,
                   ) -> Tuple[bytes, float]:
    """(μ+λ) ES on a single 16,384-byte origin.  Pop seeded from the
    selected origin with small N-byte flips, then standard truncation
    selection.  Storage stays 4096 packed bytes (the genome).

    Per-token isolation: only this token's contexts contribute to
    fitness, so the genome can't be tugged by another token's needs.
    """
    rng = np.random.default_rng(rng_seed)
    base_arr = np.frombuffer(start_origin, dtype=np.uint8).copy() & 3

    # Smart mutation: collect fire mask once for this origin family.
    # The mask is recomputed per generation off the current best parent
    # (because mutated origins fire different keys), but as a starting
    # approximation we use the initial origin's mask and refresh only
    # when the elite changes — cheap and good enough.
    fire_mask: Optional[np.ndarray] = None
    if smart_mutation:
        fire_mask = collect_origin_fire_mask(
            start_origin, chain_depth, ticks_per_level, chain_mode)
        n_fire = int(fire_mask.sum())
        log(f'    origin fire mask: {n_fire}/{RULE_SIZE} keys ({100*n_fire/RULE_SIZE:.1f}%)')

    def score(rule_bytes: bytes) -> float:
        return _score_token_origin(
            rule_bytes, contexts, target_byte, n_blocks, base,
            block_rules_template, chain_depth, ticks_per_level,
            chain_mode, argmax_bonus)

    def mutate(parent: np.ndarray, n_flips: int) -> bytes:
        child = parent.copy()
        if smart_mutation and fire_mask is not None and fire_mask.any():
            # Sample n_flips from fired keys only (with replacement allowed
            # if mask is small relative to n_flips).
            fired_idxs = np.where(fire_mask)[0]
            n = min(n_flips, fired_idxs.size)
            idxs = rng.choice(fired_idxs, size=n, replace=False)
        else:
            idxs = rng.choice(RULE_SIZE, size=n_flips, replace=False)
        for k in idxs:
            old = int(child[k])
            new = old
            while new == old:
                new = int(rng.integers(0, 4))
            child[k] = new
        return bytes(child)

    parents: List[Tuple[float, bytes]] = []
    parents.append((score(bytes(base_arr)), bytes(base_arr)))
    for _ in range(mu - 1):
        seed_child = mutate(base_arr, rng.integers(mutation_min, mutation_max + 1))
        parents.append((score(seed_child), seed_child))
    parents.sort(key=lambda t: -t[0])

    history = [parents[0][0]]
    for g in range(generations):
        children: List[Tuple[float, bytes]] = []
        per_parent = max(1, lam // mu)
        for _, p_bytes in parents:
            p_arr = np.frombuffer(p_bytes, dtype=np.uint8).copy() & 3
            for _ in range(per_parent):
                n_flips = int(rng.integers(mutation_min, mutation_max + 1))
                child = mutate(p_arr, n_flips)
                children.append((score(child), child))
        combined = sorted(parents + children, key=lambda t: -t[0])
        parents = combined[:mu]
        history.append(parents[0][0])
        log(f'    gen {g}: best={parents[0][0]:+.3f}  '
            f'(Δ from start: {parents[0][0] - history[0]:+.3f})')

    return parents[0][1], parents[0][0]


def train_per_token_chain(pair_id: int,
                           cfg: Optional[ChainTrainConfig] = None
                           ) -> ChainTrainResult:
    """Per-token quine-chain trainer.  No GA: just pick the best chain
    level per position from the assigned token's chain."""
    from .models import QRPair
    cfg = cfg or ChainTrainConfig()
    log = cfg.log

    pair = QRPair.objects.get(pk=pair_id)
    prompt_bytes = list(pair.prompt.encode('utf-8'))
    target_bytes = list(pair.expected.encode('utf-8'))
    n_blocks = pair.n_blocks

    unique = sorted(set(target_bytes))
    log(f'pair #{pair_id}: {len(target_bytes)} target bytes, '
        f'{len(unique)} unique')

    pool = load_l0_quine_pool(min_fitness=cfg.min_pool_fit)
    log(f'L0 quine pool: {len(pool)} candidates (fit ≥ {cfg.min_pool_fit})')
    if len(pool) < len(unique):
        raise RuntimeError(
            f'pool too small: need {len(unique)} quines, have {len(pool)}')

    base = build_base_rules(cfg.base_seed)
    block_rules_template = [{k: base[k] for k in
                              ('q', 'k', 'v', 'score', 'mix', 'merge', 'mlp')}
                              ] * n_blocks

    if cfg.select_origins:
        log(f'selecting per-token origins (top {cfg.select_n} of pool by fitness)...')
        origins = select_origins_by_fitness(
            target_bytes, prompt_bytes, n_blocks, pool, base,
            n_candidates=cfg.select_n,
            chain_depth=cfg.chain_depth,
            ticks_per_level=cfg.ticks_per_level,
            chain_mode=cfg.chain_mode,
            argmax_bonus=cfg.argmax_bonus, log=log)
    else:
        origins = assign_origins(unique, pool)
        log(f'assigned origins by hash (no selection): {len(origins)} tokens')

    if cfg.refine_flips > 0 or cfg.ga_generations > 0:
        token_positions: Dict[int, List[List[int]]] = {tb: [] for tb in unique}
        for pos, tb in enumerate(target_bytes):
            token_positions[tb].append(list(prompt_bytes) + target_bytes[:pos])

    if cfg.refine_flips > 0:
        log(f'hill-climb {cfg.refine_flips} flips × '
            f'{cfg.refine_sample} sample/token...')
        for tb in unique:
            pk, origin = origins[tb]
            log(f'  refining token {_pretty(tb)} (origin pk={pk}, '
                f'{len(token_positions[tb])} contexts)')
            refined, sc = hill_climb_origin(
                origin, token_positions[tb], tb, n_blocks,
                base, block_rules_template,
                chain_depth=cfg.chain_depth,
                ticks_per_level=cfg.ticks_per_level,
                chain_mode=cfg.chain_mode,
                argmax_bonus=cfg.argmax_bonus,
                n_flips=cfg.refine_flips,
                sample_size=cfg.refine_sample,
                rng_seed=tb * 31337,
                log=log)
            origins[tb] = (-pk if pk > 0 else pk, refined)
            log(f'    → refined score={sc:+.3f}')

    if cfg.ga_generations > 0:
        log(f'per-token GA: (μ={cfg.ga_mu}+λ={cfg.ga_lam}) × '
            f'{cfg.ga_generations} gens, mut={cfg.ga_mut_min}-{cfg.ga_mut_max} flips')
        for tb in unique:
            pk, origin = origins[tb]
            log(f'  evolving token {_pretty(tb)} (start pk={pk}, '
                f'{len(token_positions[tb])} contexts)')
            evolved, sc = evolve_origin(
                origin, token_positions[tb], tb, n_blocks,
                base, block_rules_template,
                chain_depth=cfg.chain_depth,
                ticks_per_level=cfg.ticks_per_level,
                chain_mode=cfg.chain_mode,
                argmax_bonus=cfg.argmax_bonus,
                mu=cfg.ga_mu, lam=cfg.ga_lam,
                generations=cfg.ga_generations,
                mutation_min=cfg.ga_mut_min, mutation_max=cfg.ga_mut_max,
                rng_seed=tb * 99991,
                log=log)
            origins[tb] = (-abs(pk), evolved)
            log(f'    → GA best score={sc:+.3f}')

    # Build all chains for inference — share across positions w/ same token.
    chains: Dict[int, List[np.ndarray]] = {}
    for tb, (pk, origin) in origins.items():
        chains[tb] = chain_levels(origin, depth=cfg.chain_depth,
                                    ticks_per_level=cfg.ticks_per_level,
                                    mode=cfg.chain_mode)
        log(f'  token {_pretty(tb)} ← quine #{pk}: '
            f'chain {len(chains[tb])} deep')

    result = ChainTrainResult(
        pair_id=pair_id, prompt=pair.prompt, expected=pair.expected,
        token_origins={tb: pk for tb, (pk, _) in origins.items()},
        chain_depth=cfg.chain_depth,
    )

    for pos in range(len(target_bytes)):
        tb = target_bytes[pos]
        ctx = list(prompt_bytes) + target_bytes[:pos]   # teacher-forced
        chain = chains[tb]
        best_fit = -np.inf
        best_lvl = 0
        best_arg = -1
        for lvl, rule in enumerate(chain):
            fit, argmax = _position_logprob(
                ctx, n_blocks, base, block_rules_template,
                rule, tb, cfg.argmax_bonus)
            if fit > best_fit:
                best_fit = fit
                best_lvl = lvl
                best_arg = argmax
        pr = PositionResult(
            pos=pos, target_byte=tb, target_char=_pretty(tb),
            chosen_level=best_lvl, origin_pk=origins[tb][0],
            fitness=float(best_fit), argmax=best_arg,
            match=(best_arg == tb),
        )
        result.positions.append(pr)
        marker = '✓' if pr.match else ' '
        log(f'  pos {pos:>2} target={pr.target_char} '
            f'lvl={best_lvl:>2}/{len(chain)}  '
            f'fit={best_fit:+.3f}  arg={_pretty(best_arg)} {marker}')

    return result


def _pretty(b: int) -> str:
    if 32 <= b < 127:
        return repr(chr(b))
    return f'\\x{b:02x}'


# ─── Base-rule co-evolution ──────────────────────────────────────────
#
# Once per-token chains are selected, the residual quality gap comes
# from the shared 9 base rules' "natural prior": they push the post-
# attention state into a basin where most chain levels argmax to the
# same low control bytes regardless of the output rule applied.  The
# fix is to evolve the base rules so the pre-output state is unbiased
# enough that varying output_rule (= varying chain level) can cover
# the byte range we actually need.  Storage of base rules is 36,864 B
# packed, shared across ALL pairs forever.

def _compute_hex_keys(state: np.ndarray) -> np.ndarray:
    """Reconstruct the 14-bit LUT keys hex_ca_step accesses for a given
    state.  Same indexing scheme — see caformer.primitives.hex_ca_step
    for the full derivation.  Returns uint16 array of same shape."""
    H, W = state.shape
    n_up   = np.roll(state, 1, axis=0)
    n_dn   = np.roll(state, -1, axis=0)
    n_l    = np.roll(state, 1, axis=1)
    n_r    = np.roll(state, -1, axis=1)
    n_up_l = np.roll(n_up, 1, axis=1)
    n_up_r = np.roll(n_up, -1, axis=1)
    n_dn_l = np.roll(n_dn, 1, axis=1)
    n_dn_r = np.roll(n_dn, -1, axis=1)
    rows = np.arange(H)[:, None]
    even = (rows & 1) == 0
    n_nw = np.where(even, n_up_l, n_up)
    n_ne = np.where(even, n_up,   n_up_r)
    n_sw = np.where(even, n_dn_l, n_dn)
    n_se = np.where(even, n_dn,   n_dn_r)
    return ((state.astype(np.uint16) << 12)
             | (n_nw.astype(np.uint16) << 10)
             | (n_ne.astype(np.uint16) << 8)
             | (n_r.astype(np.uint16) << 6)
             | (n_se.astype(np.uint16) << 4)
             | (n_sw.astype(np.uint16) << 2)
             | n_l.astype(np.uint16))


def collect_fire_masks(base: Dict[str, np.ndarray],
                        chains: Dict[int, List[np.ndarray]],
                        contexts_by_token: Dict[int, List[Tuple[List[int], int]]],
                        n_blocks_by_pair: Dict[int, int],
                        ) -> Dict[str, np.ndarray]:
    """For each base rule, find which 14-bit LUT entries actually get
    accessed during forward passes on the corpus.  Returns
    ``{rule_name: bool_mask}`` where bool_mask[k] = True iff key k
    fires somewhere in the trace.

    Monkey-patches ``caformer.primitives.hex_ca_step`` for the duration
    of the trace pass; restores on exit even if the body raises.  Uses
    object identity (``id()``) to map rule_table arrays back to their
    name in the base dict.
    """
    from caformer import primitives as prim

    name_by_id = {id(v): k for k, v in base.items()}
    fire_sets: Dict[str, set] = {k: set() for k in base}
    orig_step = prim.hex_ca_step

    def traced_step(state: np.ndarray, rule_table: np.ndarray) -> np.ndarray:
        name = name_by_id.get(id(rule_table))
        if name is not None:
            keys = _compute_hex_keys(state.astype(np.uint8))
            fire_sets[name].update(np.unique(keys).tolist())
        return orig_step(state, rule_table)

    # Both prim.hex_ca_step (used inside primitives.py) AND
    # xfm.hex_ca_step (imported into transformer.py) must be patched
    # for the trace to capture all firings.  Restore both in finally.
    import caformer.transformer as xfm
    orig_step_xfm = xfm.hex_ca_step
    prim.hex_ca_step = traced_step
    xfm.hex_ca_step = traced_step
    try:
        block_tmpls: Dict[int, list] = {}
        for nb in set(n_blocks_by_pair.values()):
            block_tmpls[nb] = [{k: base[k] for k in
                                  ('q', 'k', 'v', 'score', 'mix', 'merge', 'mlp')}
                                  ] * nb
        for tb, items in contexts_by_token.items():
            chain = chains[tb]
            for ctx, pair_id in items:
                nb = n_blocks_by_pair[pair_id]
                for rule in chain:
                    ca_forward_qkv(
                        ctx, n_blocks=nb,
                        embed_rule=base['embed'],
                        block_rules=block_tmpls[nb],
                        norm_rule=base['norm'],
                        output_rule=rule, vocab_size=256)
    finally:
        prim.hex_ca_step = orig_step
        xfm.hex_ca_step = orig_step_xfm

    masks: Dict[str, np.ndarray] = {}
    for k, s in fire_sets.items():
        mask = np.zeros(RULE_SIZE, dtype=bool)
        if s:
            mask[np.array(sorted(s), dtype=np.int64)] = True
        masks[k] = mask
    return masks


def corpus_argmax_matches(base: Dict[str, np.ndarray],
                           chains: Dict[int, List[np.ndarray]],
                           contexts_by_token: Dict[int, List[Tuple[List[int], int]]],
                           n_blocks_by_pair: Dict[int, int],
                           argmax_bonus: float = 0.0,
                           fitness_mode: str = 'matches',
                           top_k: int = 1,
                           ) -> Tuple[int, float]:
    """Score a candidate base across a corpus.  Two modes:

    - ``matches`` (legacy): pick chain level that argmax-matches the
      target (with lp as tie-breaker).  Returns (matches, sum_lp);
      sort GA pop by this tuple.  Creates a step function at the
      match boundary — what stalls vanilla GA.

    - ``lp`` (smooth): pick chain level with highest pure lp.  Returns
      (matches, sum_lp) where matches is still measured but NOT the
      primary objective; sort GA pop by sum_lp only.  Smooth landscape
      everywhere — any cell-distribution change propagates to lp.

    ``contexts_by_token[tb]`` = list of (ctx_bytes, pair_id) tuples;
    we use pair_id to look up the right n_blocks.  Chains were
    precomputed from per-token origins and are independent of base.
    """
    matches = 0
    total_lp = 0.0
    block_tmpls: Dict[int, list] = {}
    for nb in set(n_blocks_by_pair.values()):
        block_tmpls[nb] = [{k: base[k] for k in
                              ('q', 'k', 'v', 'score', 'mix', 'merge', 'mlp')}
                              ] * nb
    for tb, items in contexts_by_token.items():
        chain = chains[tb]
        for ctx, pair_id in items:
            nb = n_blocks_by_pair[pair_id]
            block_template = block_tmpls[nb]
            best_lp = -np.inf
            best_match = 0
            for rule in chain:
                logits = ca_forward_qkv(
                    ctx, n_blocks=nb,
                    embed_rule=base['embed'],
                    block_rules=block_template,
                    norm_rule=base['norm'],
                    output_rule=rule, vocab_size=256,
                    top_k=top_k)
                shifted = logits - float(logits.max())
                exp = np.exp(shifted)
                denom = float(exp.sum())
                p_true = float(exp[tb] / denom) if denom > 0 else 1e-30
                lp = float(np.log(max(p_true, 1e-30)))
                argmax = int(np.argmax(logits))
                match = 1 if argmax == tb else 0
                if fitness_mode == 'lp':
                    # Pure lp selection: take highest-lp level regardless of match
                    if lp > best_lp:
                        best_lp = lp
                        best_match = match
                else:
                    # Legacy: match-first tuple sort
                    if (match, lp) > (best_match, best_lp):
                        best_match = match
                        best_lp = lp
            matches += best_match
            total_lp += best_lp
    return matches, total_lp


@dataclass
class CoevolveConfig:
    pair_ids:      List[int] = field(default_factory=list)
    base_seed:     int = 0xBA5E_C0DE
    chain_depth:   int = 16
    ticks_per_level: int = 8
    chain_mode:    str = 'ca_evolution'
    select_n:      int = 8                # per-token candidates from L0 pool
    pop_size:      int = 8
    generations:   int = 8                # base-GA generations per alt-round
    alt_rounds:    int = 1                # full select+GA alternations
    mu:            int = 3                # elite carried over
    mutation_rate: float = 0.003          # per-byte flip prob (over fired keys if smart_mutation)
    fitness_mode:  str = 'lp'             # 'lp' (smooth) or 'matches' (legacy)
    smart_mutation: bool = True           # restrict flips to keys that actually fire on corpus
    top_k:         int = 1                # top-k soft attention (1 = hard, default; 4-8 = soft blend)
    rng_seed:      int = 0xC0E0_0001
    log:           Callable[[str], None] = print


@dataclass
class CoevolveResult:
    initial_base_matches: int = 0
    initial_base_lp:      float = 0.0
    final_base_matches:   int = 0
    final_base_lp:        float = 0.0
    total_positions:      int = 0
    history:              List[Tuple[int, float]] = field(default_factory=list)  # (gen, best_matches, best_lp)
    final_base:           Optional[Dict[str, np.ndarray]] = None
    token_origins:        Dict[int, int] = field(default_factory=dict)
    per_pair_matches:     Dict[int, Tuple[int, int]] = field(default_factory=dict)  # pair_id → (matches, n_pos)


def coevolve_base(cfg: CoevolveConfig) -> CoevolveResult:
    """Two-phase: (1) pre-select per-token origins using the initial
    random base across the union of corpus tokens, (2) evolve the 9
    base rules to maximise argmax matches across the whole corpus,
    using the fixed pre-selected chains as the per-token output-rule
    libraries."""
    from .models import QRPair
    log = cfg.log
    pairs = [QRPair.objects.get(pk=pk) for pk in cfg.pair_ids]
    log(f'corpus: {len(pairs)} QRPairs')
    for p in pairs:
        log(f'  #{p.pk}: {p.prompt!r} → {p.expected!r}  (n_blocks={p.n_blocks})')

    # Per-pair targets & contexts (teacher-forced).
    pair_targets: Dict[int, List[int]] = {}
    pair_prompts: Dict[int, List[int]] = {}
    n_blocks_by_pair: Dict[int, int] = {}
    for p in pairs:
        pair_targets[p.pk] = list(p.expected.encode('utf-8'))
        pair_prompts[p.pk] = list(p.prompt.encode('utf-8'))
        n_blocks_by_pair[p.pk] = p.n_blocks

    # Union of unique tokens across corpus.
    all_tokens = sorted({tb for tgs in pair_targets.values() for tb in tgs})
    log(f'corpus unique tokens: {len(all_tokens)}')

    # Contexts indexed by token: each (ctx_bytes, pair_id).
    contexts_by_token: Dict[int, List[Tuple[List[int], int]]] = {tb: [] for tb in all_tokens}
    total_positions = 0
    for pk, targets in pair_targets.items():
        for pos, tb in enumerate(targets):
            ctx = pair_prompts[pk] + targets[:pos]
            contexts_by_token[tb].append((ctx, pk))
            total_positions += 1
    log(f'total target positions across corpus: {total_positions}')

    # Initial random base + L0 pool.
    current_base = build_base_rules(cfg.base_seed)
    pool = load_l0_quine_pool()
    log(f'L0 quine pool: {len(pool)}')

    def select_origins_under(base: Dict[str, np.ndarray]
                              ) -> Dict[int, Tuple[int, bytes]]:
        """For each unique token, pick best-of-K origin under `base`."""
        block_tmpls: Dict[int, list] = {}
        for nb in set(n_blocks_by_pair.values()):
            block_tmpls[nb] = [{k: base[k] for k in
                                  ('q', 'k', 'v', 'score', 'mix', 'merge', 'mlp')}
                                  ] * nb
        origins: Dict[int, Tuple[int, bytes]] = {}
        for tb in all_tokens:
            items = contexts_by_token[tb]
            best_score = -np.inf
            best_pk, best_origin = -1, b''
            for pk_c, origin in pool[:cfg.select_n]:
                chain = chain_levels(origin, depth=cfg.chain_depth,
                                      ticks_per_level=cfg.ticks_per_level,
                                      mode=cfg.chain_mode)
                agg = 0.0
                for ctx, pair_id in items:
                    nb = n_blocks_by_pair[pair_id]
                    pos_best = -np.inf
                    for rule in chain:
                        fit, _ = _position_logprob(
                            ctx, nb, base, block_tmpls[nb], rule, tb, 0.0)
                        if fit > pos_best:
                            pos_best = fit
                    agg += pos_best
                if agg > best_score:
                    best_score = agg
                    best_pk, best_origin = pk_c, origin
            origins[tb] = (best_pk, best_origin)
        return origins

    initial_base = {k: v.copy() for k, v in current_base.items()}
    rng = np.random.default_rng(cfg.rng_seed)
    # Fire masks computed once per alt round (after base/chains settle).
    fire_masks: Dict[str, np.ndarray] = {}

    def mutate(parent: Dict[str, np.ndarray]) -> Dict[str, np.ndarray]:
        """Mutate parent.  When smart_mutation, only flip bytes at keys
        that actually fire during the corpus forward pass — fired-only
        ratio is typically <5% of the 16,384-entry LUT, so this
        concentrates the mutation budget ~20× onto entries that matter
        instead of random no-ops on unused keys."""
        out = {}
        for k, v in parent.items():
            arr = v.copy()
            if cfg.smart_mutation and fire_masks:
                mask = fire_masks[k]
                # Effective per-eligible-byte rate = mutation_rate * (n/n_fired)
                # so the EXPECTED flip count matches what untargeted
                # mutation would give: mutation_rate * arr.size flips.
                n_fired = int(mask.sum())
                if n_fired > 0:
                    eff_rate = min(1.0, cfg.mutation_rate * arr.size / n_fired)
                    candidates = rng.random(arr.size) < eff_rate
                    flips = candidates & mask
                else:
                    flips = np.zeros(arr.size, dtype=bool)
            else:
                flips = rng.random(arr.size) < cfg.mutation_rate
            new_vals = rng.integers(0, 4, size=arr.size, dtype=np.uint8)
            arr = np.where(flips, new_vals, arr).astype(np.uint8) & 3
            out[k] = arr
        return out

    history: List[Tuple[int, int, float]] = []
    token_origins: Dict[int, Tuple[int, bytes]] = {}
    chains: Dict[int, List[np.ndarray]] = {}
    init_m = init_lp = 0
    init_recorded = False

    for round_i in range(cfg.alt_rounds):
        # (a) Re-select per-token origins under current base.
        log(f'')
        log(f'═══ alt round {round_i + 1}/{cfg.alt_rounds} ═══')
        log(f'selecting origins under current base (top {cfg.select_n} '
            f'candidates per token)...')
        token_origins = select_origins_under(current_base)
        for tb in all_tokens:
            pk, _ = token_origins[tb]
            log(f'  token {_pretty(tb)} (×{len(contexts_by_token[tb])}) '
                f'← quine #{pk}')
        chains = {tb: chain_levels(orig, depth=cfg.chain_depth,
                                     ticks_per_level=cfg.ticks_per_level,
                                     mode=cfg.chain_mode)
                  for tb, (_, orig) in token_origins.items()}

        if cfg.smart_mutation:
            log(f'tracing fire-keys across corpus...')
            fire_masks = collect_fire_masks(
                current_base, chains, contexts_by_token, n_blocks_by_pair)
            for k in ('embed', 'q', 'k', 'v', 'score', 'mix',
                        'merge', 'mlp', 'norm'):
                n = int(fire_masks[k].sum())
                pct = 100.0 * n / RULE_SIZE
                log(f'  rule {k:>6}: {n:>5}/{RULE_SIZE} keys fire ({pct:.1f}%)')

        pre_ga_m, pre_ga_lp = corpus_argmax_matches(
            current_base, chains, contexts_by_token, n_blocks_by_pair,
            fitness_mode=cfg.fitness_mode)
        log(f'after selection: matches {pre_ga_m}/{total_positions}  '
            f'lp {pre_ga_lp:+.2f}')
        if not init_recorded:
            init_m, init_lp = pre_ga_m, pre_ga_lp
            init_recorded = True

        # (b) Evolve base against the freshly-selected chains.
        log(f'evolving base: pop={cfg.pop_size}, gens={cfg.generations}, '
            f'μ={cfg.mu}, mut_rate={cfg.mutation_rate}, fitness={cfg.fitness_mode}')
        # Sort key: lp-only when smooth-fitness mode, else (matches, lp) tuple.
        sort_key = ((lambda t: -t[1]) if cfg.fitness_mode == 'lp'
                     else (lambda t: (-t[0], -t[1])))
        pop: List[Tuple[int, float, Dict[str, np.ndarray]]] = []
        pop.append((pre_ga_m, pre_ga_lp, {k: v.copy() for k, v in current_base.items()}))
        for _ in range(cfg.pop_size - 1):
            child = mutate(current_base)
            m, lp = corpus_argmax_matches(
                child, chains, contexts_by_token, n_blocks_by_pair,
                fitness_mode=cfg.fitness_mode)
            pop.append((m, lp, child))
        pop.sort(key=sort_key)
        log(f'  gen  0: best matches={pop[0][0]}/{total_positions} '
            f'lp={pop[0][1]:+.2f}')
        gen_offset = len(history)
        history.append((gen_offset, pop[0][0], pop[0][1]))

        for gen in range(1, cfg.generations + 1):
            elites = pop[:cfg.mu]
            children = []
            per_parent = max(1, (cfg.pop_size - cfg.mu) // cfg.mu)
            for _, _, p in elites:
                for _ in range(per_parent):
                    child = mutate(p)
                    m, lp = corpus_argmax_matches(
                        child, chains, contexts_by_token, n_blocks_by_pair,
                        fitness_mode=cfg.fitness_mode)
                    children.append((m, lp, child))
            combined = elites + children
            combined.sort(key=sort_key)
            pop = combined[:cfg.pop_size]
            log(f'  gen {gen:>2}: best matches={pop[0][0]}/{total_positions} '
                f'lp={pop[0][1]:+.2f}')
            history.append((gen_offset + gen, pop[0][0], pop[0][1]))

        # Carry forward the GA winner as next round's base.
        current_base = pop[0][2]
        log(f'round {round_i + 1} done: '
            f'matches {pop[0][0]}/{total_positions}, lp {pop[0][1]:+.2f}')

    result = CoevolveResult(
        initial_base_matches=init_m, initial_base_lp=init_lp,
        total_positions=total_positions,
        token_origins={tb: pk for tb, (pk, _) in token_origins.items()},
        history=history,
    )
    result.final_base_matches = pop[0][0]
    result.final_base_lp = pop[0][1]
    result.final_base = pop[0][2]

    # Per-pair breakdown under the final base.
    final_base = pop[0][2]
    for p in pairs:
        pair_ctx_by_token: Dict[int, List[Tuple[List[int], int]]] = {}
        pair_n_pos = len(pair_targets[p.pk])
        for pos, tb in enumerate(pair_targets[p.pk]):
            ctx = pair_prompts[p.pk] + pair_targets[p.pk][:pos]
            pair_ctx_by_token.setdefault(tb, []).append((ctx, p.pk))
        m, _ = corpus_argmax_matches(
            final_base, chains, pair_ctx_by_token,
            {p.pk: p.n_blocks})
        result.per_pair_matches[p.pk] = (m, pair_n_pos)
    return result
