from django.urls import path
from . import views

app_name = 'caformer'

urlpatterns = [
    path('',                              views.index,         name='index'),
    path('diagram/',                      views.diagram,       name='diagram'),
    path('component/<slug:slug>/',        views.component,     name='component'),
    path('composition/<slug:slug>/',      views.composition,   name='composition'),
    path('dmn/',                          views.dmn_view,      name='dmn'),
    path('dmn/stream/',                   views.dmn_stream,    name='dmn_stream'),
    path('chat/',                         views.chat_view,     name='chat'),
    path('chat/reply/',                   views.chat_reply,    name='chat_reply'),
    path('chat/reply/stream/',            views.chat_reply_stream,
                                                                name='chat_reply_stream'),
    path('train/',                        views.train_view,    name='train'),
    path('train/stream/',                 views.train_stream,  name='train_stream'),
    path('train/save/',                   views.train_save,    name='train_save'),
    path('train/post-corpus/',            views.train_post_corpus,
                                                                name='train_post_corpus'),
    path('train/polish/',                 views.train_polish,  name='train_polish'),
    path('train/from-chat/',              views.train_from_chat,
                                                                name='train_from_chat'),
    path('train/distill/',                views.train_distill, name='train_distill'),
    path('internalize/',                  views.internalize_view,
                                                                name='internalize'),
    path('loopback/',                     views.loopback_view, name='loopback'),
    path('loopback/iterate/',             views.loopback_iterate,
                                                                name='loopback_iterate'),
    path('export/',                       views.train_export,  name='export_best'),
    path('export/<slug:slug>/',           views.train_export,  name='export'),
    path('rules/<slug:slug>.json',        views.rules_json,    name='rules_json'),
    path('rules.json',                    views.rules_json,    name='rules_json_best'),
    path('champions/',                    views.champions,         name='champions'),
    path('champions/stream/',             views.champions_stream,  name='champions_stream'),
    path('champions/compose/',            views.champions_compose, name='champions_compose'),
    path('champions/library/',            views.champions_library, name='champions_library'),
    path('qr/',                           views.qr_index,          name='qr_index'),
    path('pipeline/',                     views.pipeline_view,     name='pipeline'),
    path('pipeline/stream/',              views.pipeline_stream,   name='pipeline_stream'),
    path('pipeline/autotrain/stream/',    views.pipeline_autotrain_stream,
                                                                    name='pipeline_autotrain_stream'),
    path('pipeline/autotrain/save/',      views.pipeline_autotrain_save,
                                                                    name='pipeline_autotrain_save'),
    path('funnel-chat/',                  views.funnel_chat_view,  name='funnel_chat'),
    path('funnel-chat/reply/',            views.funnel_chat_reply, name='funnel_chat_reply'),
    path('funnel-chat/enqueue/',          views.funnel_chat_enqueue,
                                                                    name='funnel_chat_enqueue'),
    path('funnel-chat/status/',           views.funnel_chat_status,
                                                                    name='funnel_chat_status'),
    path('funnel-chat/history/',          views.funnel_chat_history,
                                                                    name='funnel_chat_history'),
    path('funnel-chat/dmn/',              views.funnel_chat_dmn_toggle,
                                                                    name='funnel_chat_dmn'),
    path('about/',                        views.caformer_about_view,
                                                                    name='caformer_about'),
    path('cell8/',                        views.caformer_cell8_view,
                                                                    name='caformer_cell8'),
    path('ruleset-zoo/',                  views.caformer_ruleset_zoo_view,
                                                                    name='caformer_ruleset_zoo'),
    path('tier-compare/',                 views.caformer_tier_compare_view,
                                                                    name='caformer_tier_compare'),
    path('lutview/',                      views.caformer_lutview,
                                                                    name='caformer_lutview'),
    path('lutview/download',              views.caformer_lutview_download,
                                                                    name='caformer_lutview_download'),
    path('funnel-chat/standalone/',       views.caformer_standalone_download,
                                                                    name='caformer_standalone_download'),
    path('quarter-compose/',              views.caformer_quarter_compose_view,
                                                                    name='caformer_quarter_compose'),
    path('quarter-compose/run/',          views.caformer_quarter_compose_run,
                                                                    name='caformer_quarter_compose_run'),
    path('engine-compare/',               views.caformer_engine_compare_view,
                                                                    name='caformer_engine_compare'),
    path('engine-compare/run/',           views.caformer_engine_compare_run,
                                                                    name='caformer_engine_compare_run'),
    path('funnel-chat/cli/binary',        views.funnel_cli_download,
                                                                    {'kind': 'binary'},
                                                                    name='funnel_cli_binary'),
    path('funnel-chat/cli/source',        views.funnel_cli_download,
                                                                    {'kind': 'source'},
                                                                    name='funnel_cli_source'),
    path('funnel-chat/trainer/binary',    views.funnel_trainer_download,
                                                                    {'kind': 'binary'},
                                                                    name='funnel_trainer_binary'),
    path('funnel-chat/trainer/source',    views.funnel_trainer_download,
                                                                    {'kind': 'source'},
                                                                    name='funnel_trainer_source'),
]
