# Generated by Django 6.0.4 on 2026-04-22 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Scholar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('affiliation', models.CharField(blank=True, max_length=200)),
                ('active_years', models.CharField(blank=True, help_text='e.g. "1960–1992" or "active"', max_length=40)),
                ('homepage_url', models.URLField(blank=True, max_length=500)),
                ('bio', models.TextField(blank=True, help_text='Short biographical note.')),
                ('notes', models.TextField(blank=True, help_text='Why you are interested. Feeds the argument workshop.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Argument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('kind', models.CharField(choices=[('across', 'Across scholars'), ('within', 'Within one scholar'), ('essay', 'Free-form essay')], default='across', max_length=16)),
                ('premises_text', models.TextField(blank=True, help_text='Auto-scaffolded on creation — edit freely.')),
                ('tension_text', models.TextField(blank=True, help_text='Shared-vocabulary hints; edit to name real tensions.')),
                ('synthesis_text', models.TextField(blank=True, help_text='Your argument. Studious never writes this.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studious_arguments', to=settings.AUTH_USER_MODEL)),
                ('domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='studious.domain')),
            ],
            options={
                'ordering': ['-modified_at'],
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('kind', models.CharField(choices=[('article', 'Article'), ('book', 'Book'), ('chapter', 'Chapter'), ('thesis', 'Thesis / dissertation'), ('preprint', 'Preprint'), ('talk', 'Talk / lecture'), ('note', 'Note / letter'), ('other', 'Other')], default='article', max_length=16)),
                ('doi', models.CharField(blank=True, max_length=160)),
                ('url', models.URLField(blank=True, max_length=500)),
                ('source_file', models.FileField(blank=True, null=True, upload_to='studious/')),
                ('abstract', models.TextField(blank=True)),
                ('full_text', models.TextField(blank=True, help_text='Plain-text body. Searchable.')),
                ('analysis_json', models.JSONField(blank=True, default=dict, help_text='TF-IDF top terms, token counts, etc.')),
                ('notes', models.TextField(blank=True)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('domains', models.ManyToManyField(blank=True, related_name='works', to='studious.domain')),
                ('scholar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='studious.scholar')),
            ],
            options={
                'ordering': ['-year', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('kind', models.CharField(choices=[('claim', 'Claim'), ('thesis', 'Main thesis'), ('observation', 'Observation'), ('question', 'Open question'), ('hedge', 'Hedge / caveat'), ('counter', 'Counter / objection')], default='claim', max_length=16)),
                ('page_ref', models.CharField(blank=True, help_text='e.g. "p.42" or "§3.1".', max_length=40)),
                ('notes', models.TextField(blank=True)),
                ('auto_extracted', models.BooleanField(default=False, help_text='True if Studious proposed this; user edits clear the flag.')),
                ('score', models.FloatField(default=0.0, help_text='Heuristic claim-likelihood 0..1 when auto-extracted.')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='studious.work')),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArgumentClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('premise', 'Premise'), ('support', 'Support'), ('counter', 'Counter'), ('illustration', 'Illustration'), ('context', 'Context')], default='premise', max_length=16)),
                ('order', models.PositiveIntegerField(default=0)),
                ('note', models.CharField(blank=True, max_length=240)),
                ('argument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='studious.argument')),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='argument_uses', to='studious.claim')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('argument', 'claim')},
            },
        ),
        migrations.AddIndex(
            model_name='work',
            index=models.Index(fields=['scholar', '-year'], name='studious_wo_scholar_d8d15b_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['work', 'order'], name='studious_cl_work_id_a7f783_idx'),
        ),
    ]
