# Generated by Django 6.0.4 on 2026-05-14 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BundlePatchWish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('verb', 'thinking verb'), ('spinner', 'spinner glyph'), ('other', 'other binary string')], default='verb', max_length=16)),
                ('target', models.CharField(help_text='Exact string currently in the binary.', max_length=256)),
                ('replacement', models.CharField(help_text='Desired replacement.  Must be ≤ len(target) bytes unless you intend to relocate (advanced).', max_length=256)),
                ('notes', models.TextField(blank=True)),
                ('applied', models.BooleanField(default=False, help_text='Operator-toggled flag — purely informational, the row is never auto-applied.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SettingsScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('user', 'user (~/.claude/settings.json)'), ('project', 'project (<repo>/.claude/settings.json)'), ('local', 'local  (<repo>/.claude/settings.local.json)')], max_length=32, unique=True)),
                ('path', models.CharField(help_text='Absolute path to a settings.json file.', max_length=512)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
