# Generated by Django 6.0.4 on 2026-05-21 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barding', '0003_swap_in_claudecode_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Harness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('vendor', models.CharField(blank=True, max_length=80)),
                ('surface', models.CharField(choices=[('cli', 'CLI'), ('web', 'web app'), ('ide', 'IDE plugin'), ('api', 'raw API / SDK'), ('mobile', 'mobile app'), ('mixed', 'multi-surface')], default='cli', max_length=12)),
                ('is_open_source', models.BooleanField(default=False, help_text='True if the harness source is publicly inspectable.')),
                ('summary', models.TextField(blank=True, help_text='2–4 sentence orientation: what it is, what makes it distinctive as a harness.')),
                ('home_url', models.URLField(blank=True)),
                ('repo_url', models.URLField(blank=True)),
                ('version_seen', models.CharField(blank=True, help_text='Version string we last observed (free-form).', max_length=40)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Technique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('category', models.CharField(choices=[('pregen', 'pre-generation (prompt + context build)'), ('instream', 'in-stream (visible during generation)'), ('postgen', 'post-generation (repair / hedging / retry)'), ('crossturn', 'cross-turn (memory / compaction / summary)'), ('register', 'register / persona (tone, affect, casual)'), ('tooluse', 'tool-use loop'), ('meta', 'meta / governance (refusals, safety, etc.)')], default='instream', max_length=12)),
                ('description', models.TextField(blank=True, help_text='What the technique is and why it contributes to the "magic" feel.  Be concrete.')),
                ('magic_weight', models.FloatField(default=0.5, help_text='0..1 — subjective contribution to "feels like a person". Used to rank distillation priorities.')),
                ('deterministic_cost', models.CharField(choices=[('trivial', 'trivial'), ('cheap', 'cheap (≤ 1 KB code, no state)'), ('medium', 'medium (a few KB or per-turn state)'), ('heavy', 'heavy (model dependency or large state)'), ('?', 'unknown')], default='?', help_text='Rough cost of implementing this around the deterministic caformer core.', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-magic_weight', 'name'),
            },
        ),
        migrations.CreateModel(
            name='DistillationProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('include', 'include — port faithfully'), ('simplified', 'simplified — port a lighter variant'), ('skip', 'skip — not worth the cost'), ('research', 'research — undecided, needs experiment')], default='research', max_length=12)),
                ('rationale', models.TextField(blank=True, help_text='Why this decision.  What we lose if we skip; what we gain if we include; what the simplified form looks like.')),
                ('byte_budget', models.PositiveIntegerField(blank=True, help_text='Estimated bytes of code/data the implementation would cost.  Helps the low-resource concept stay honest.', null=True)),
                ('implementation_notes', models.TextField(blank=True, help_text='Concrete plan: which caformer module, what hooks, what state, fallback behaviour.')),
                ('priority', models.PositiveSmallIntegerField(default=3, help_text='1=ship first, 5=last.  Lets /barding/distill/ rank.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('technique', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='distill', to='barding.technique')),
            ],
            options={
                'ordering': ('priority', '-technique__magic_weight'),
            },
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_kind', models.CharField(choices=[('binary_string', 'string in binary'), ('source_code', 'source code / repo file'), ('prompt_leak', 'leaked / published system prompt'), ('docs', 'vendor docs / blog post'), ('screenshot', 'screenshot / observed UI'), ('transcript', 'transcript excerpt'), ('reasoned', 'reasoned inference (no direct artifact)')], default='reasoned', max_length=16)),
                ('summary', models.CharField(help_text='One-line summary: what was observed.', max_length=240)),
                ('evidence', models.TextField(blank=True, help_text='Raw evidence — quoted strings, URLs, line refs, paths.')),
                ('confidence', models.FloatField(default=0.7, help_text='0..1 — how confident we are the harness really does this.')),
                ('observed_at', models.DateField(blank=True, help_text='When the observation was made (YYYY-MM-DD).', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('harness', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='barding.harness')),
                ('technique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='barding.technique')),
            ],
            options={
                'ordering': ('-confidence', '-created_at'),
                'indexes': [models.Index(fields=['harness', 'technique'], name='barding_obs_harness_f23b70_idx')],
            },
        ),
    ]
