# Generated by Django 6.0.4 on 2026-04-23 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=40, unique=True)),
                ('code', models.CharField(help_text='Short dept code used in course codes (LING, CS, PHIL).', max_length=8, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='e.g. "fall-2026", "spring-2027".', max_length=20, unique=True)),
                ('name', models.CharField(max_length=40)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('code', models.CharField(help_text='Full course code, e.g. LING100, CS201, PHIL305.', max_length=16, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('credits', models.PositiveSmallIntegerField(default=5, help_text='ECTS credits (5 is the usual Leiden default).')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='agora.department')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('level', models.CharField(choices=[('ba', "Bachelor's (BA/BSc)"), ('ma', "Master's (MA/MSc)"), ('phd', 'Doctorate (PhD)'), ('cert', 'Certificate')], max_length=8)),
                ('description', models.TextField(blank=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programs', to='agora.department')),
            ],
            options={
                'ordering': ['department__code', 'level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_number', models.CharField(default='01', help_text='Distinguishes parallel sections of the same course in the same term (01, 02, ...).', max_length=6)),
                ('meeting_pattern', models.CharField(blank=True, help_text='e.g. "Mon/Wed 10:00–12:00"', max_length=80)),
                ('room', models.CharField(blank=True, max_length=60)),
                ('capacity', models.PositiveIntegerField(default=30)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='agora.course')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agora_sections_taught', to=settings.AUTH_USER_MODEL)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='agora.term')),
            ],
            options={
                'ordering': ['-term__start_date', 'course__code', 'section_number'],
                'unique_together': {('course', 'term', 'section_number')},
            },
        ),
        migrations.CreateModel(
            name='ResourceLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('reading', 'Reading'), ('exercise', 'Exercise'), ('demo', 'Demo / simulation'), ('reference', 'Reference material'), ('assignment', 'Graded assignment'), ('other', 'Other')], default='reference', max_length=16)),
                ('title', models.CharField(help_text='Human-readable label shown to students.', max_length=200)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('external_url', models.URLField(blank=True, help_text='Fallback pointer when the resource lives outside Velour (journal article, dataset, video).')),
                ('notes', models.TextField(blank=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='agora.section')),
            ],
            options={
                'ordering': ['section', 'kind', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('enrolled', 'Enrolled'), ('waitlist', 'Waitlist'), ('withdrawn', 'Withdrawn'), ('completed', 'Completed')], default='enrolled', max_length=12)),
                ('grade', models.CharField(blank=True, help_text='Letter or numeric grade (A, B, 7.5, etc.). Blank until the section ends.', max_length=4)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agora_enrollments', to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='agora.section')),
            ],
            options={
                'ordering': ['-enrolled_at'],
                'unique_together': {('section', 'student')},
            },
        ),
    ]
