# Generated by Django 6.0.4 on 2026-04-23 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agora', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=40, unique=True)),
                ('code', models.CharField(help_text='Short code, e.g. "LEI" for Leiden, "VU" for Velour University.', max_length=16, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('founded', models.PositiveIntegerField(blank=True, help_text='Year founded; 1575 for Leiden.', null=True)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('country', models.CharField(blank=True, max_length=80)),
                ('website', models.URLField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'universities',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['university__code', 'code']},
        ),
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(help_text='Full course code, e.g. LING100, CS201, PHIL305. Unique within a department (two universities may both have a "CS101").', max_length=16),
        ),
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.CharField(help_text='Short dept code used in course codes (LING, CS, PHIL).', max_length=16),
        ),
        migrations.AlterField(
            model_name='department',
            name='slug',
            field=models.SlugField(max_length=40),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('department', 'code'), name='agora_course_department_code_unique'),
        ),
        migrations.AddField(
            model_name='department',
            name='university',
            field=models.ForeignKey(blank=True, help_text='Which university this department belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='agora.university'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('university', 'slug'), name='agora_dept_university_slug_unique'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('university', 'code'), name='agora_dept_university_code_unique'),
        ),
    ]
