# Generated by Django 6.0.4 on 2026-05-13 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('spoeqi', '0005_pact_fleet_candidate_ids'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('component', models.PositiveSmallIntegerField(default=0, help_text='Which of the 64 components serves as the playfield.  Different components = different rules (in fleet mode) = different worlds.')),
                ('monster_count', models.PositiveSmallIntegerField(default=8, help_text='Number of monsters spawned at game start.')),
                ('wall_threshold', models.PositiveSmallIntegerField(default=2, help_text='Cell states ≥ this are walls.  1 dense, 3 sparse.')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doom_sessions', to=settings.AUTH_USER_MODEL)),
                ('pact', models.ForeignKey(help_text='Spoeqi pact providing the underlying CA world.', on_delete=django.db.models.deletion.CASCADE, related_name='doom_sessions', to='spoeqi.pact')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
