# Generated by Django 6.0.4 on 2026-05-13 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doom_ca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='world_mode',
            field=models.CharField(choices=[('overlay', 'overlay — pact rule + JS-tracked player/monsters (camera follows player)'), ('shift', 'shift — pure-CA: 6 directional shift rules anchor the player at centre, world scrolls past'), ('scent', 'scent — pure-CA: single rule, monsters spread fluid-like toward the player; walls block'), ('evolved', 'evolved — pact rule with per-key patches for player-preserve, wall-cluster-stability, monster-attack-adjacent (illustrative GA target)')], default='overlay', help_text='How the CA drives the game world.  See class doc.', max_length=10),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='wall_threshold',
            field=models.PositiveSmallIntegerField(default=2, help_text='Cell states ≥ this are walls.  1 dense, 3 sparse. In overlay mode this is the cell-state cutoff; in shift/scent/evolved modes it is only used at init to derive ground vs wall from the pact seed.'),
        ),
    ]
