# Generated by Django 6.0.4 on 2026-05-13 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doom_ca', '0002_gamesession_world_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='pure_mode',
            field=models.BooleanField(default=False, help_text="If true (and world_mode is shift/scent/evolved), the pact rule is NOT applied on wait ticks; only the mode's own rule + player moves change the world.  Trades atmosphere for predictability."),
        ),
    ]
