# Generated by Django 6.0.4 on 2026-05-13 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doom_ca', '0003_gamesession_pure_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='ammo_pack_count',
            field=models.PositiveSmallIntegerField(default=3, help_text='Ammo packs scattered on reachable ground (each +3 ammo).'),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='door_count',
            field=models.PositiveSmallIntegerField(default=1, help_text='If 1, a locked door + key are placed on the spawn→exit path (0 = open level, just find the exit).'),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='health_pack_count',
            field=models.PositiveSmallIntegerField(default=3, help_text='Medkits scattered on reachable ground (each +25 HP).'),
        ),
    ]
