# Generated by Django 6.0.4 on 2026-05-13 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doom_ca', '0004_gamesession_ammo_pack_count_gamesession_door_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='music_style_idx',
            field=models.PositiveSmallIntegerField(default=0, help_text='Default music meter (0..15). 0=common, 14=doom-march, 15=ambient-drift; user can cycle live with V.'),
        ),
    ]
