# Generated by Django 6.0.4 on 2026-05-13 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doom_ca', '0005_gamesession_music_style_idx'),
        ('retrogames', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='target_game',
            field=models.ForeignKey(blank=True, help_text='Optional: a catalogue entry this evolution is trying to approach.  Used as a hint to the user, not (yet) as a fitness target.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_of_sessions', to='retrogames.game'),
        ),
    ]
