# Generated by Django 6.0.4 on 2026-05-13 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doom_ca', '0006_gamesession_target_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesession',
            name='world_mode',
            field=models.CharField(choices=[('overlay', 'overlay — pact rule + JS-tracked player/monsters (camera follows player)'), ('shift', 'shift — pure-CA: 6 directional shift rules anchor the player at centre, world scrolls past'), ('scent', 'scent — pure-CA: single rule, monsters spread fluid-like toward the player; walls block'), ('evolved', 'evolved — pact rule with per-key patches for player-preserve, wall-cluster-stability, monster-attack-adjacent (illustrative GA target)'), ('platform', 'platform — Cartesian side-scroller, gravity + jump, wall cells are platforms; enemies walk their tops')], default='overlay', help_text='How the CA drives the game world.  See class doc.', max_length=10),
        ),
    ]
