# Generated by Django 6.0.4 on 2026-05-13 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doom_ca', '0007_alter_gamesession_world_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='destruct_wall_2',
            field=models.BooleanField(default=False, help_text='If true, shotgun fire destroys state-2 wall cells (turns them into ground).  State-3 walls always block.'),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='slip_ground_1',
            field=models.BooleanField(default=False, help_text='If true, stepping onto a state-1 ground cell makes the player slide one extra cell in their last direction (if the destination is open).'),
        ),
    ]
