# Generated by Django 6.0.4 on 2026-05-15 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.CharField(help_text='Slug of the component (embedding, attention, ...).', max_length=40)),
                ('pact_slug', models.CharField(blank=True, help_text='Optional spoeqi pact backing this experiment.', max_length=80)),
                ('title', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('inputs', models.JSONField(blank=True, default=dict)),
                ('outputs', models.JSONField(blank=True, default=dict)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
