# Generated by Django 6.0.4 on 2026-05-15 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caformer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('notes', models.TextField(blank=True)),
                ('rule_q', models.BinaryField()),
                ('rule_k', models.BinaryField()),
                ('rule_v', models.BinaryField()),
                ('rule_score', models.BinaryField()),
                ('rule_mix', models.BinaryField()),
                ('rule_merge', models.BinaryField()),
                ('rule_mlp', models.BinaryField()),
                ('rule_norm', models.BinaryField()),
                ('rule_output', models.BinaryField()),
                ('rule_embed', models.BinaryField()),
                ('corpus_excerpt', models.TextField(blank=True, help_text='First ~500 chars of the training corpus, kept so the model can be re-trained on roughly the same data.')),
                ('vocab_size', models.PositiveIntegerField(default=256)),
                ('n_blocks', models.PositiveIntegerField(default=2)),
                ('pop_size', models.PositiveIntegerField(default=8)),
                ('generations', models.PositiveIntegerField(default=6)),
                ('final_fitness', models.FloatField(default=0.0)),
                ('history_json', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
