# Generated by Django 6.0.4 on 2026-05-16 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caformer', '0003_chatturn'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentChampion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_slug', models.CharField(db_index=True, help_text='one of COMPONENT_SPECS keys', max_length=40)),
                ('rules_blob', models.BinaryField()),
                ('rule_names_csv', models.CharField(default='', help_text='comma-separated rule names in on-disk order; matches COMPONENT_SPECS[slug].rules', max_length=120)),
                ('fitness', models.FloatField(db_index=True)),
                ('generation', models.PositiveIntegerField(default=0, help_text='how many lineage hops from a random ancestor')),
                ('run_label', models.CharField(blank=True, help_text='tag for the autotournament run that produced this champion', max_length=40)),
                ('ga_pop_size', models.PositiveIntegerField(default=0)),
                ('ga_generations', models.PositiveIntegerField(default=0)),
                ('eval_count', models.PositiveIntegerField(default=0, help_text='how many fitness evals were spent on this champion')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='caformer.componentchampion')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['component_slug', '-fitness'], name='caformer_co_compone_f549e3_idx')],
            },
        ),
    ]
