# Generated by Django 6.0.4 on 2026-05-16 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caformer', '0004_componentchampion'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.CharField(max_length=200)),
                ('expected', models.CharField(max_length=400)),
                ('n_blocks', models.PositiveSmallIntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
                ('label', models.CharField(blank=True, help_text="free-form tag, e.g. a training run's name", max_length=40)),
                ('best_fitness', models.FloatField(default=-1000000000.0)),
                ('best_genome_blob', models.BinaryField(blank=True, null=True)),
                ('best_output', models.CharField(blank=True, help_text='temperature-0 argmax output of the best genome on prompt', max_length=400)),
                ('best_exact', models.BooleanField(default=False)),
                ('n_evals', models.PositiveIntegerField(default=0)),
                ('total_seconds', models.FloatField(default=0.0)),
                ('restarts', models.PositiveIntegerField(default=0)),
                ('last_phase', models.CharField(blank=True, help_text='ga / polish / restart / done', max_length=24)),
                ('deployed_slug', models.CharField(blank=True, help_text='slug of the TrainedModel this pair has been deployed to (if any)', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-best_exact', '-best_fitness', '-updated_at'),
            },
        ),
    ]
