# Generated by Django 6.0.4 on 2026-05-16 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caformer', '0005_qrpair'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrpair',
            name='positional_output_blob',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
