# Generated by Django 6.0.4 on 2026-05-18 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caformer', '0006_qrpair_positional_output_blob'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrpair',
            name='board128_exact',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='qrpair',
            name='board128_rules_blob',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qrpair',
            name='board128_ticks',
            field=models.PositiveSmallIntegerField(default=128),
        ),
    ]
