# Generated by Django 6.0.4 on 2026-05-19 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caformer', '0007_qrpair_board128_exact_qrpair_board128_rules_blob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrpair',
            name='b008_rules_blob',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qrpair',
            name='b016_rules_blob',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qrpair',
            name='b032_rules_blob',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qrpair',
            name='b064_rules_blob',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qrpair',
            name='last_queried_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
