# Generated by Django 6.0.4 on 2026-05-19 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caformer', '0008_qrpair_b008_rules_blob_qrpair_b016_rules_blob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrpair',
            name='cell8_b256_exact',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='qrpair',
            name='cell8_b256_rules_blob',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qrpair',
            name='cell8_input_source',
            field=models.CharField(blank=True, choices=[('off', 'port held at 0 (no modulation)'), ('dmn', 'DMN heartbeat tick parity'), ('router', 'router 2-bit category'), ('prev_byte', 'previous chain output cell')], default='off', max_length=16),
        ),
    ]
