# Generated by Django 6.0.4 on 2026-05-20 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caformer', '0009_qrpair_cell8_b256'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrpair',
            name='cell8_b008_exact',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='qrpair',
            name='cell8_b008_rules_blob',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qrpair',
            name='cell8_b016_exact',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='qrpair',
            name='cell8_b016_rules_blob',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qrpair',
            name='cell8_b032_exact',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='qrpair',
            name='cell8_b032_rules_blob',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qrpair',
            name='cell8_b064_exact',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='qrpair',
            name='cell8_b064_rules_blob',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qrpair',
            name='cell8_b128_exact',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='qrpair',
            name='cell8_b128_rules_blob',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
