# Generated by Django 6.0.4 on 2026-05-21 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caformer', '0010_qrpair_cell8_multires'),
    ]

    operations = [
        migrations.CreateModel(
            name='HarnessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('persona_name', models.CharField(blank=True, help_text='Short display name, e.g. "Alice", "the librarian".', max_length=80)),
                ('persona_description', models.TextField(blank=True, help_text='2–5 sentence character sketch.  Voice, values, specialities.  Forms the bulk of the system prompt.')),
                ('system_prompt_extra', models.TextField(blank=True, help_text='Additional instructions appended after the persona description.  Use for capability claims, refusal posture, formatting rules.')),
                ('inject_cwd', models.BooleanField(default=False)),
                ('inject_time', models.BooleanField(default=True)),
                ('inject_git', models.BooleanField(default=False)),
                ('inject_identity', models.BooleanField(default=True, help_text='Pull current Velour identity mood into the context block (soft-fails if identity app absent).')),
                ('spinner_verbs_json', models.JSONField(blank=True, help_text='Optional per-category verb overrides.  Map {"0":[...],"1":[...],"2":[...],"3":[...]}.', null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False, help_text='Used by /caformer/harness/ when no slug is pinned.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-is_default', 'persona_name', 'slug'),
            },
        ),
    ]
