# Generated by Django 6.0.4 on 2026-05-21 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caformer', '0011_harnessprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='harnessprofile',
            name='prefilter_mode',
            field=models.CharField(choices=[('router', 'router (single CA classifier, majority vote)'), ('boardstack4', 'boardstack4 (4-board sequential cascade)')], default='router', help_text='Which deterministic prefilter classifies the prompt. boardstack4 emits a 4-colour path for richer routing.', max_length=16),
        ),
    ]
