# Generated by Django 6.0.4 on 2026-05-21 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caformer', '0012_harnessprofile_prefilter_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='PICMVocab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_color', models.PositiveSmallIntegerField(choices=[(0, 'personality'), (1, 'information'), (2, 'command'), (3, 'meta')], help_text='Which boardstack4 routing colour this vocab belongs to.', unique=True)),
                ('bytes_per_token', models.PositiveSmallIntegerField(default=4, help_text='Max ASCII bytes per token.  4 = 1024 tokens fit in 128×128 K=4; 8 = 512 tokens.')),
                ('token_count', models.PositiveSmallIntegerField(default=1024, help_text='Max vocab size.  16,384 cells / (bytes_per_token × 4) is the upper bound.')),
                ('tokens_json', models.JSONField(blank=True, default=list, help_text='Ordered list of token strings.  Truncated to bytes_per_token chars at pack time; longer entries lose their tail.')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('agent_color',),
            },
        ),
    ]
