# Generated by Django 6.0.4 on 2026-05-21 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caformer', '0013_picmvocab'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplatePattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_color', models.PositiveSmallIntegerField(choices=[(0, 'personality'), (1, 'information'), (2, 'command'), (3, 'meta')])),
                ('pattern', models.CharField(help_text="Prompt pattern with [SlotName] markers, e.g. 'look up [X]' or 'how many [item]'.", max_length=240)),
                ('output', models.TextField(help_text='Answer template referencing the same slot names. On match, slot values are substituted in.')),
                ('priority', models.PositiveSmallIntegerField(default=5, help_text='Lower priority wins ties between equally specific patterns.  1 = highest, 9 = lowest.')),
                ('is_active', models.BooleanField(default=True)),
                ('confidence', models.FloatField(default=0.7, help_text='Confidence the harness reports for matches from this template.  0..1.  Templates with no real data backing them (stubs) should be ≤ 0.5.')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('agent_color', 'priority', '-updated_at'),
                'indexes': [models.Index(fields=['agent_color', 'is_active'], name='caformer_te_agent_c_60a3d5_idx')],
            },
        ),
    ]
