# Generated by Django 6.0.4 on 2026-05-21 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caformer', '0014_templatepattern'),
    ]

    operations = [
        migrations.CreateModel(
            name='PICMNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tree_path', models.CharField(help_text="Dot-separated path of K=4 branch indices.  Top level: '0'..'3'.  Children: '0.2', '1.3.0', etc. Max depth 4 (= 8 chars including dots).", max_length=16, unique=True)),
                ('label', models.CharField(help_text="Short human-readable name for this node, e.g. 'information', 'who-queries', 'historical-person'.", max_length=80)),
                ('description', models.TextField(blank=True)),
                ('relevance_tokens', models.JSONField(default=list, help_text='Tokens whose presence in the prompt signals this branch is the right descent.  Short (≤ 4 char) tokens, matched on word boundaries case-insensitively.')),
                ('is_leaf', models.BooleanField(default=False, help_text="When True, descent halts here and the harness dispatches using this node's qrpair_label + template_tag scopes.")),
                ('qrpair_label', models.CharField(blank=True, help_text='When set, leaf dispatch consults only QRPairs with this exact label value.', max_length=80)),
                ('template_tag', models.CharField(blank=True, help_text='When set, leaf dispatch consults only TemplatePatterns whose notes field contains this tag (case-insensitive substring).', max_length=80)),
                ('confidence', models.FloatField(default=0.7, help_text='Confidence reported when this leaf produces a reply.  0..1.')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('tree_path',),
                'indexes': [models.Index(fields=['tree_path'], name='caformer_pi_tree_pa_3dccad_idx')],
            },
        ),
    ]
