# Generated by Django 6.0.4 on 2026-05-21 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caformer', '0015_picmnode'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatepattern',
            name='handler_name',
            field=models.CharField(blank=True, help_text="Optional name of a registered live-data handler (see caformer.harness.handlers.HANDLERS).  When set, the entire ``output`` field is replaced with the handler's return value at match time.  ``output`` is still used as a comment / fallback if the handler is unknown.", max_length=64),
        ),
    ]
