# Generated by Django 6.0.4 on 2026-05-21 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caformer', '0016_templatepattern_handler_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harnessprofile',
            name='prefilter_mode',
            field=models.CharField(choices=[('router', 'router (single CA classifier, majority vote)'), ('boardstack4', 'boardstack4 (4-board sequential cascade)'), ('multiscale', 'multiscale boardstack4 (sides 4/8/16/32, XOR combined)')], default='router', help_text='Which deterministic prefilter classifies the prompt. boardstack4 emits a 4-colour path for richer routing.', max_length=16),
        ),
    ]
