# Generated by Django 6.0.4 on 2026-05-21 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caformer', '0018_alter_harnessprofile_prefilter_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalityModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Stable identifier, e.g. "velour", "david-angel".', max_length=64, unique=True)),
                ('name', models.CharField(help_text='Display name, e.g. "Velour", "David Angel".', max_length=80)),
                ('description', models.TextField(blank=True, help_text='Short character sketch of the personality.')),
                ('subroutes', models.JSONField(default=list, help_text='List of 4 dicts: [{label, tokens: [...], notes}, ...].  tokens are short (≤ 4 char) keyword matches on word boundaries.  Order matters — index 0..3 maps to depth-1 branch indices under personality (0).')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.AddField(
            model_name='harnessprofile',
            name='personality_module_slug',
            field=models.CharField(blank=True, help_text="Optional slug of a PersonalityModule.  When set, this profile's personality route descends into that module's 4 subroutes instead of the shared PICM tree's personality children.", max_length=64),
        ),
    ]
