# Generated by Django 6.0.4 on 2026-05-21 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caformer', '0019_personalitymodule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalitymodule',
            name='axis_slug',
            field=models.CharField(blank=True, choices=[('drive', 'drive (motivation)'), ('expression', 'expression (style)'), ('relation', 'relation (intimacy)'), ('lens', 'lens (perception filter)')], help_text='If kind=axis, which dimension (drive/expression/relation/lens).  Otherwise empty.', max_length=20),
        ),
        migrations.AddField(
            model_name='personalitymodule',
            name='kind',
            field=models.CharField(choices=[('axis', 'axis (defines one dimension)'), ('preset', 'preset (named 4-tuple)')], default='preset', help_text='axis: defines one dimension of PersonalityState. preset: defines a named 4-tuple in that space.', max_length=10),
        ),
        migrations.AddField(
            model_name='personalitymodule',
            name='state_vector',
            field=models.JSONField(default=list, help_text='If kind=preset, the default 4-tuple [d, e, r, l] (each 0..3) this module evokes.  Each of the 4 subroutes may also carry its own state_vector — a different mood within this persona.'),
        ),
    ]
