# Generated by Django 6.0.4 on 2026-04-14 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LegoWorld',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('biome', models.CharField(choices=[('plains', 'Plains'), ('forest', 'Forest'), ('desert', 'Desert'), ('snow', 'Snow'), ('harbor', 'Harbor'), ('autumn', 'Autumn'), ('town', 'Town'), ('dusk', 'Dusk'), ('meadow', 'Meadow'), ('island', 'Island')], default='plains', max_length=16)),
                ('seed', models.IntegerField(default=1)),
                ('baseplate_color', models.CharField(default='#5ea04b', max_length=7)),
                ('n_buildings', models.IntegerField(default=0)),
                ('n_trees', models.IntegerField(default=0)),
                ('n_flowers', models.IntegerField(default=0)),
                ('n_people', models.IntegerField(default=0)),
                ('n_hills', models.IntegerField(default=0)),
                ('n_lamps', models.IntegerField(default=0)),
                ('n_rocks', models.IntegerField(default=0)),
                ('payload', models.JSONField(help_text='Full world JSON (worlds.World.to_json round-trip).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
