# Generated by Django 6.0.4 on 2026-04-14 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legolith', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('kind', models.CharField(choices=[('tree', 'Tree'), ('flower', 'Flower'), ('building', 'Building'), ('person', 'Person'), ('hill', 'Hill'), ('lamp', 'Lamp'), ('rock', 'Rock'), ('vehicle', 'Vehicle'), ('creature', 'Creature'), ('other', 'Other')], default='other', help_text='Category for library filtering; does not constrain the L-System itself.', max_length=16)),
                ('description', models.TextField(blank=True)),
                ('axiom', models.CharField(default='X', max_length=200)),
                ('rules', models.JSONField(default=dict, help_text='{"X": "F[>L][<L]..."} — maps single-char symbols to replacement strings.')),
                ('iterations', models.PositiveSmallIntegerField(default=2)),
                ('init_color', models.CharField(default='#888888', max_length=7)),
                ('init_shape_w', models.PositiveSmallIntegerField(default=1)),
                ('init_shape_d', models.PositiveSmallIntegerField(default=1)),
                ('init_shape_plates', models.PositiveSmallIntegerField(default=3)),
                ('footprint_w', models.PositiveSmallIntegerField(default=2)),
                ('footprint_d', models.PositiveSmallIntegerField(default=2)),
                ('use_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
