# Generated by Django 6.0.4 on 2026-05-09 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick', models.CharField(help_text='IRC nickname this bot will use.  Convention: "velour-<purpose>" so its origin is obvious to anyone watching the channel.', max_length=32)),
                ('server', models.CharField(default='chat.h4ks.com', max_length=120)),
                ('port', models.PositiveSmallIntegerField(default=6697)),
                ('use_tls', models.BooleanField(default=True)),
                ('target', models.CharField(help_text='Either a #channel or a contact nick (PM).', max_length=80)),
                ('purpose', models.CharField(blank=True, help_text='What this bot is here to discuss/do.  Shown in admin and used as part of the LLM system prompt.', max_length=200)),
                ('message_cap', models.PositiveSmallIntegerField(default=5, help_text='Hard cap on PRIVMSG sends per session.  Spam guard.')),
                ('autonomous', models.BooleanField(default=False, help_text='If False, the operator must approve each outgoing message before it sends.')),
                ('status', models.CharField(choices=[('created', 'Created'), ('connecting', 'Connecting'), ('running', 'Running'), ('done', 'Done'), ('error', 'Error')], default='created', max_length=16)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IrcContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick', models.SlugField(max_length=32, unique=True)),
                ('display', models.CharField(max_length=64)),
                ('role', models.CharField(blank=True, help_text='e.g. "h4ks.com admin", "mattfly — vibegames maintainer".', max_length=80)),
                ('timezone', models.CharField(blank=True, max_length=64)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['nick'],
            },
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(help_text='Markdown.  Read this before any automated action that touches the named target.')),
                ('target', models.CharField(choices=[('vibegames', 'games.h4ks.com'), ('shorts', 's.h4ks.com'), ('irc', 'chat.h4ks.com'), ('general', 'h4ks.com (general)')], default='general', max_length=40)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Policies',
                'ordering': ['target', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='VibegamePush',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.SlugField(max_length=80)),
                ('filename', models.CharField(default='index.html', max_length=200)),
                ('source_path', models.CharField(help_text='Local file we pushed (e.g. isolation/artifacts/office/officerpghiresev32.html).', max_length=500)),
                ('bytes_sent', models.PositiveIntegerField(default=0)),
                ('response_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True)),
                ('commit_url', models.URLField(blank=True)),
                ('pushed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-pushed_at'],
            },
        ),
        migrations.CreateModel(
            name='BotMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('out', 'Sent by bot'), ('in', 'Received from peer'), ('sys', 'System / log line')], max_length=4)),
                ('sender', models.CharField(blank=True, max_length=64)),
                ('body', models.TextField()),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='h4kslnk.botsession')),
            ],
            options={
                'ordering': ['session', 'at'],
            },
        ),
    ]
