# Generated by Django 6.0.4 on 2026-04-19 08:50

import agents.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aether', '0008_entity_language_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('founded_year', models.IntegerField(blank=True, help_text='In-fiction founding year; can be negative.', null=True)),
                ('population_target', models.PositiveIntegerField(default=0, help_text="Designer's intended Agent count; informational only.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TownCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q', models.IntegerField()),
                ('r', models.IntegerField()),
                ('label', models.CharField(blank=True, help_text="Optional name (e.g. 'docks', 'temple square').", max_length=80)),
                ('town', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='agents.town')),
                ('world', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='aether.world')),
            ],
            options={
                'ordering': ['town', 'q', 'r'],
            },
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('family_name', models.CharField(blank=True, max_length=80)),
                ('gender', models.CharField(choices=[('f', 'Female'), ('m', 'Male'), ('nb', 'Non-binary'), ('?', 'Unspecified')], default='?', max_length=2)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('face_seed', models.PositiveIntegerField(default=0, help_text='Face Forge replay seed. 0 = unset.')),
                ('bio_json', models.JSONField(default=agents.models.default_bio)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('origin_world', models.ForeignKey(blank=True, help_text='The Aether scene the character is associated with.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='aether.world')),
                ('town', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='residents', to='agents.town')),
                ('current_cell', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitors', to='agents.towncell')),
            ],
            options={
                'ordering': ['name', 'family_name'],
            },
        ),
        migrations.CreateModel(
            name='AgentRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('friend', 'Friend'), ('family', 'Family'), ('coworker', 'Coworker'), ('rival', 'Rival'), ('mentor', 'Mentor'), ('partner', 'Partner'), ('neighbour', 'Neighbour')], max_length=16)),
                ('since', models.DateField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('dst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relations', to='agents.agent')),
                ('src', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relations', to='agents.agent')),
            ],
            options={
                'indexes': [models.Index(fields=['src', 'kind'], name='agents_agen_src_id_abcc9b_idx'), models.Index(fields=['dst', 'kind'], name='agents_agen_dst_id_17da9c_idx')],
                'unique_together': {('src', 'dst', 'kind')},
            },
        ),
        migrations.AddIndex(
            model_name='towncell',
            index=models.Index(fields=['town', 'q', 'r'], name='agents_town_town_id_78cfb4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='towncell',
            unique_together={('town', 'q', 'r')},
        ),
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['town', 'name'], name='agents_agen_town_id_4c4d50_idx'),
        ),
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['origin_world'], name='agents_agen_origin__fce0d8_idx'),
        ),
    ]
