# Generated by Django 6.0.4 on 2026-04-28 21:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=320, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quill_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Position among siblings — smaller comes first.')),
                ('level', models.PositiveSmallIntegerField(default=1, help_text='Outline depth, cached. Top-level = 1.')),
                ('title', models.CharField(blank=True, max_length=300)),
                ('body', models.TextField(blank=True, help_text='HTML body. ProseMirror-ready: structure carried in tags + class names, no inline styling beyond what a Style covers.')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='quill.document')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='quill.section')),
            ],
            options={
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Footnote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('body', models.TextField(blank=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='footnotes', to='quill.section')),
            ],
            options={
                'ordering': ['section', 'order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='CrossReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=200)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_refs', to='quill.section')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_refs', to='quill.section')),
            ],
            options={
                'ordering': ['source', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('kind', models.CharField(choices=[('paragraph', 'Paragraph'), ('character', 'Character'), ('list', 'List')], default='paragraph', max_length=20)),
                ('css_rules', models.JSONField(blank=True, default=dict, help_text='{"font_family": "Charter", "font_size": "11pt", "line_height": 1.45, "margin_top": "0.5em", ...}')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='styles', to='quill.document')),
            ],
            options={
                'ordering': ['kind', 'name'],
            },
        ),
        migrations.AddField(
            model_name='section',
            name='style',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sections', to='quill.style'),
        ),
        migrations.AddConstraint(
            model_name='style',
            constraint=models.UniqueConstraint(fields=('document', 'name'), name='quill_style_name_per_doc'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['document', 'parent', 'order'], name='quill_secti_documen_7614bc_idx'),
        ),
    ]
