# Generated by Django 6.0.4 on 2026-04-28 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quill', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=40, unique=True)),
                ('name', models.CharField(help_text='English name — "Sanskrit", "Tibetan", "Hebrew".', max_length=80)),
                ('native_name', models.CharField(blank=True, help_text='Endonym in its own script — "संस्कृतम्", "བོད་སྐད་", "עברית".', max_length=80)),
                ('bcp47', models.CharField(help_text='BCP-47 tag — "en", "nl", "sa", "bo", "zh-Hans", "he", "ar".', max_length=20)),
                ('direction', models.CharField(choices=[('ltr', 'LTR'), ('rtl', 'RTL')], default='ltr', max_length=4)),
                ('script_name', models.CharField(blank=True, help_text='Script family — "Latin", "Devanagari", "Tibetan", "Han", "Hebrew", "Arabic", "Syriac", "Greek".', max_length=40)),
                ('font_stack', models.CharField(blank=True, help_text='CSS font-family list. Longer stacks fall back gracefully across systems where users may have different fonts.', max_length=400)),
                ('sample_text', models.CharField(blank=True, help_text='A short sample for the language picker — usually a pangram or characteristic phrase.', max_length=200)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='section',
            name='paragraph_direction',
            field=models.CharField(choices=[('ltr', 'LTR (left-to-right)'), ('rtl', 'RTL (right-to-left)'), ('auto', 'Auto (browser detects from first strong char)')], default='ltr', help_text='Block writing direction. RTL languages set this to "rtl" by default; "auto" lets the browser decide from first strong character.', max_length=4),
        ),
        migrations.AlterField(
            model_name='section',
            name='body',
            field=models.TextField(blank=True, help_text='HTML body. Inline language switches are encoded as <span lang="..." dir="...">...</span> — web standard, survives ProseMirror migration.'),
        ),
        migrations.CreateModel(
            name='DocumentLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quill.document')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quill.language')),
            ],
            options={
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='languages',
            field=models.ManyToManyField(blank=True, help_text="Languages enabled in this document's toolbar.", related_name='documents', through='quill.DocumentLanguage', to='quill.language'),
        ),
        migrations.AddField(
            model_name='document',
            name='primary_language',
            field=models.ForeignKey(blank=True, help_text="Default language for new sections. Drives the page's overall direction and base font stack.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_documents', to='quill.language'),
        ),
        migrations.AddField(
            model_name='section',
            name='primary_language',
            field=models.ForeignKey(blank=True, help_text="The section's default language — drives its block direction and base font stack. Inline spans can switch to other languages.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_sections', to='quill.language'),
        ),
        migrations.AddConstraint(
            model_name='documentlanguage',
            constraint=models.UniqueConstraint(fields=('document', 'language'), name='quill_doc_lang_unique'),
        ),
    ]
