# Generated by Django 6.0.4 on 2026-04-20 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StageType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('physical', 'Physical filtration'), ('adsorption', 'Adsorption (carbon, resin)'), ('membrane', 'Membrane (RO, NF, UF, MF)'), ('biological', 'Biological filter'), ('uv', 'UV sterilisation'), ('ozone', 'Ozone disinfection'), ('chemical', 'Chemical dosing'), ('ion_exchange', 'Ion exchange'), ('other', 'Other')], default='other', max_length=16)),
                ('description', models.TextField(blank=True)),
                ('removal', models.JSONField(blank=True, default=dict)),
                ('flow_lpm', models.FloatField(default=0.0, help_text='Nominal flow rate in litres per minute.')),
                ('energy_watts', models.FloatField(default=0.0, help_text='Power draw while operating, watts.')),
                ('cost_eur', models.FloatField(default=0.0, help_text='Replacement / consumable cost per interval, EUR.')),
                ('maintenance_days', models.PositiveIntegerField(default=0, help_text='Typical replacement or cleaning interval in days. 0 = maintenance-free in Phase 1 terms.')),
            ],
            options={
                'ordering': ['kind', 'name'],
            },
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WaterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=120)),
                ('scope', models.CharField(choices=[('source', 'Source water (input)'), ('target', 'Target water (desired)')], default='source', max_length=8)),
                ('values', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['scope', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trace', models.JSONField(default=list, help_text='List of {position, stage, values_after} dicts, one entry per stage in order, plus a final "output" entry.')),
                ('output', models.JSONField(blank=True, default=dict)),
                ('passed', models.BooleanField(blank=True, help_text='True if every target-defined contaminant is <= its target. NULL when no target profile was set.', null=True)),
                ('failures', models.JSONField(default=list, help_text='List of contaminant keys that exceeded the target.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_runs', to='naiad.system')),
                ('source', models.ForeignKey(limit_choices_to={'scope': 'source'}, on_delete=django.db.models.deletion.PROTECT, related_name='test_runs_as_source', to='naiad.waterprofile')),
                ('target', models.ForeignKey(blank=True, limit_choices_to={'scope': 'target'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_runs_as_target', to='naiad.waterprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='system',
            name='source',
            field=models.ForeignKey(help_text='Input water this system is being designed for.', limit_choices_to={'scope': 'source'}, on_delete=django.db.models.deletion.PROTECT, related_name='systems_as_source', to='naiad.waterprofile'),
        ),
        migrations.AddField(
            model_name='system',
            name='target',
            field=models.ForeignKey(blank=True, help_text='Optional output spec. TestRun compares against this.', limit_choices_to={'scope': 'target'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='systems_as_target', to='naiad.waterprofile'),
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(help_text='0-based index of this stage within the system.')),
                ('label', models.CharField(blank=True, help_text='Optional local name; overrides stage_type.name in the UI.', max_length=120)),
                ('notes', models.CharField(blank=True, max_length=240)),
                ('stage_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stage_instances', to='naiad.stagetype')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='naiad.system')),
            ],
            options={
                'ordering': ['system', 'position'],
                'unique_together': {('system', 'position')},
            },
        ),
    ]
