# Generated by Django 6.0.4 on 2026-04-20 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naiad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagetype',
            name='converts',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
