# Generated by Django 6.0.4 on 2026-04-27 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naiad', '0002_stagetype_converts'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagetype',
            name='depth_mm',
            field=models.PositiveIntegerField(default=200),
        ),
        migrations.AddField(
            model_name='stagetype',
            name='height_mm',
            field=models.PositiveIntegerField(default=200),
        ),
        migrations.AddField(
            model_name='stagetype',
            name='width_mm',
            field=models.PositiveIntegerField(default=200),
        ),
    ]
