# Generated by Django 6.0.4 on 2026-04-28 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naiad', '0003_stagetype_dimensions'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagetype',
            name='biomass_g_per_l',
            field=models.FloatField(default=0.0),
        ),
    ]
