# Generated by Django 6.0.4 on 2026-05-09 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naiad', '0004_stagetype_biomass'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='waterprofile',
            options={'ordering': ['domain', 'scope', 'name']},
        ),
        migrations.AddField(
            model_name='stagetype',
            name='domain',
            field=models.CharField(choices=[('water', 'Water purification'), ('data', 'Data communication (OSI 7-layer)')], default='water', help_text='What kind of pipeline this stage belongs to.  Water stages and data stages live in the same catalog but Systems are single-domain.', max_length=8),
        ),
        migrations.AddField(
            model_name='system',
            name='domain',
            field=models.CharField(choices=[('water', 'Water purification'), ('data', 'Data communication (OSI 7-layer)')], default='water', help_text='Mixed-domain pipelines are not supported in Phase 1.', max_length=8),
        ),
        migrations.AddField(
            model_name='testrun',
            name='domain',
            field=models.CharField(choices=[('water', 'Water purification'), ('data', 'Data communication (OSI 7-layer)')], default='water', help_text='Inherited from System at run-time; stored on the run so old runs stay interpretable after a System is repurposed.', max_length=8),
        ),
        migrations.AddField(
            model_name='waterprofile',
            name='domain',
            field=models.CharField(choices=[('water', 'Water purification'), ('data', 'Data communication (OSI 7-layer)')], default='water', help_text='water → values are CONTAMINANTS keys; data → values are NETWORK_METRICS keys.', max_length=8),
        ),
        migrations.AlterField(
            model_name='stagetype',
            name='kind',
            field=models.CharField(choices=[('physical', 'Physical filtration'), ('adsorption', 'Adsorption (carbon, resin)'), ('membrane', 'Membrane (RO, NF, UF, MF)'), ('biological', 'Biological filter'), ('uv', 'UV sterilisation'), ('ozone', 'Ozone disinfection'), ('chemical', 'Chemical dosing'), ('ion_exchange', 'Ion exchange'), ('osi_phy', 'OSI L1 — Physical'), ('osi_dll', 'OSI L2 — Data Link'), ('osi_net', 'OSI L3 — Network'), ('osi_trans', 'OSI L4 — Transport'), ('osi_session', 'OSI L5 — Session'), ('osi_pres', 'OSI L6 — Presentation'), ('osi_app', 'OSI L7 — Application'), ('other', 'Other')], default='other', max_length=16),
        ),
        migrations.AlterField(
            model_name='system',
            name='source',
            field=models.ForeignKey(help_text='Input profile this system is being designed for. Source.domain must match System.domain.', limit_choices_to={'scope': 'source'}, on_delete=django.db.models.deletion.PROTECT, related_name='systems_as_source', to='naiad.waterprofile'),
        ),
    ]
