# Generated by Django 6.0.4 on 2026-05-09 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naiad', '0005_alter_waterprofile_options_stagetype_domain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='fitness_weights',
            field=models.JSONField(blank=True, default=dict, help_text='Per-metric weight overrides for the GA fitness function.  Empty = use domain defaults (data: reliability_pct=5, others=1; water: all=1).  Bigger weight = "evolve harder against this".'),
        ),
    ]
