# Generated by Django 6.0.4 on 2026-04-12 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TileSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('description', models.TextField(blank=True, help_text='What this tile set is for — generative art, procedural texturing, an aperiodic demo, etc.')),
                ('palette', models.JSONField(blank=True, default=list, help_text='List of color names or hex codes used by this tile set. Purely documentary for now; Phase 2 will enforce it.')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Optional human label, e.g. "T1" or "corner-ne".', max_length=80)),
                ('n_color', models.CharField(help_text='Top edge color (name or hex).', max_length=40)),
                ('e_color', models.CharField(help_text='Right edge color.', max_length=40)),
                ('s_color', models.CharField(help_text='Bottom edge color.', max_length=40)),
                ('w_color', models.CharField(help_text='Left edge color.', max_length=40)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tileset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiles', to='tiles.tileset')),
            ],
            options={
                'ordering': ['tileset', 'sort_order', 'id'],
            },
        ),
    ]
