# Generated by Django 6.0.4 on 2026-04-12 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiles', '0002_seed_tile_sets'),
    ]

    operations = [
        migrations.AddField(
            model_name='tileset',
            name='source',
            field=models.CharField(choices=[('operator', 'Operator-authored'), ('seed', 'Seeded at install'), ('identity', 'Generated by Identity from current state')], default='operator', max_length=16),
        ),
        migrations.AddField(
            model_name='tileset',
            name='source_metadata',
            field=models.JSONField(blank=True, default=dict, help_text="For identity-generated sets: the snapshot mood, concerns, aspects, and tick reference that this set came from. Lets Identity's reflection layer trace a tile set back to the state that produced it."),
        ),
    ]
