# Generated by Django 6.0.4 on 2026-04-12 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiles', '0003_tileset_source_tileset_source_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='tile',
            name='ne_color',
            field=models.CharField(blank=True, help_text='Northeast edge. Hex tiles only.', max_length=40),
        ),
        migrations.AddField(
            model_name='tile',
            name='nw_color',
            field=models.CharField(blank=True, help_text='Northwest edge. Hex tiles only.', max_length=40),
        ),
        migrations.AddField(
            model_name='tile',
            name='se_color',
            field=models.CharField(blank=True, help_text='Southeast edge. Hex tiles only.', max_length=40),
        ),
        migrations.AddField(
            model_name='tile',
            name='sw_color',
            field=models.CharField(blank=True, help_text='Southwest edge. Hex tiles only.', max_length=40),
        ),
        migrations.AddField(
            model_name='tileset',
            name='tile_type',
            field=models.CharField(choices=[('square', 'Square (4 edges)'), ('hex', 'Hexagonal (6 edges)')], default='square', max_length=8),
        ),
        migrations.AlterField(
            model_name='tile',
            name='e_color',
            field=models.CharField(blank=True, help_text='Right edge color. Square tiles only.', max_length=40),
        ),
        migrations.AlterField(
            model_name='tile',
            name='n_color',
            field=models.CharField(blank=True, help_text='Top edge color. Used by both square and hex tiles.', max_length=40),
        ),
        migrations.AlterField(
            model_name='tile',
            name='s_color',
            field=models.CharField(blank=True, help_text='Bottom edge color. Used by both square and hex tiles.', max_length=40),
        ),
        migrations.AlterField(
            model_name='tile',
            name='w_color',
            field=models.CharField(blank=True, help_text='Left edge color. Square tiles only.', max_length=40),
        ),
    ]
