# Generated by Django 6.0.4 on 2026-04-30 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automaton', '0004_ruleset_palette'),
        ('tiles', '0004_tile_ne_color_tile_nw_color_tile_se_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tile',
            name='ca_initial_grid',
            field=models.JSONField(blank=True, default=list, help_text='Optional 16×16 array of cell colours (0-3). Empty = random init at render time.'),
        ),
        migrations.AddField(
            model_name='tile',
            name='ca_ruleset',
            field=models.ForeignKey(blank=True, help_text='Optional. The K=4 hex-CA rule this tile animates when rendered through the CA-tiling runner.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='automaton.ruleset'),
        ),
    ]
