# Generated by Django 6.0.4 on 2026-04-21 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True, help_text='What the pipeline does, end-to-end.')),
                ('apps_used', models.CharField(blank=True, help_text='Comma-separated Django app labels involved.', max_length=240)),
                ('notes', models.TextField(blank=True, help_text='Refactoring notes — fields trimmed, classes merged, unused features removed.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IsolationTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(choices=[('cli_oneliner', 'CLI one-liner (≤80 chars)'), ('c_compact', 'Compact C (≤1000 chars)'), ('attiny13a', 'ATtiny13a (1KB flash, 64B RAM)'), ('attiny85', 'ATtiny85 (8KB flash, 512B RAM)'), ('esp8266', 'ESP8266 (~80KB RAM)'), ('esp32', 'ESP32 (~320KB RAM)'), ('pi4', 'Raspberry Pi 4 (Linux)')], max_length=20)),
                ('status', models.CharField(choices=[('not_started', 'Not started'), ('attempted', 'Attempted — does not work'), ('working', 'Working but rough'), ('shipped', 'Shipped — clean MVP'), ('infeasible', 'Infeasible on this platform')], default='not_started', max_length=20)),
                ('artifact_text', models.TextField(blank=True, help_text='Inline source if small enough (oneliner, compact C).')),
                ('artifact_path', models.CharField(blank=True, help_text='Repo-relative path for larger artifacts (firmware tree).', max_length=300)),
                ('size_bytes', models.PositiveIntegerField(blank=True, help_text='Compiled or source size, whichever is the binding constraint.', null=True)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='isolation.pipeline')),
            ],
            options={
                'ordering': ['pipeline', 'target'],
                'unique_together': {('pipeline', 'target')},
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('app_label', models.CharField(help_text='Django app this stage lives in (e.g. "det").', max_length=60)),
                ('entrypoint', models.CharField(help_text='Class, function, or management command (e.g. "det.search.run_search" or "det_search").', max_length=160)),
                ('produces', models.CharField(blank=True, help_text='What this stage outputs (e.g. "SearchRun + Candidate rows").', max_length=240)),
                ('fields_used', models.TextField(blank=True, help_text='Model fields this stage reads/writes — what to keep when isolating. One per line.')),
                ('notes', models.TextField(blank=True, help_text='Branching, side effects, anything Phase-2 codegen needs.')),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='isolation.pipeline')),
            ],
            options={
                'ordering': ['pipeline', 'order'],
                'unique_together': {('pipeline', 'order')},
            },
        ),
    ]
