# Generated by Django 6.0.4 on 2026-04-29 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isolation', '0002_pipeline_origin_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isolationtarget',
            name='target',
            field=models.CharField(choices=[('cli_oneliner', 'CLI one-liner (≤80 chars)'), ('c_compact', 'Compact C (≤1000 chars)'), ('attiny13a', 'ATtiny13a (1KB flash, 64B RAM)'), ('attiny85', 'ATtiny85 (8KB flash, 512B RAM)'), ('esp8266', 'ESP8266 (~80KB RAM)'), ('esp32', 'ESP32 (~320KB RAM)'), ('esp32_s3', 'ESP32-S3 SuperMini (512KB SRAM + PSRAM)'), ('pi4', 'Raspberry Pi 4 (Linux)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='origin_target',
            field=models.CharField(choices=[('cli_oneliner', 'CLI one-liner (≤80 chars)'), ('c_compact', 'Compact C (≤1000 chars)'), ('attiny13a', 'ATtiny13a (1KB flash, 64B RAM)'), ('attiny85', 'ATtiny85 (8KB flash, 512B RAM)'), ('esp8266', 'ESP8266 (~80KB RAM)'), ('esp32', 'ESP32 (~320KB RAM)'), ('esp32_s3', 'ESP32-S3 SuperMini (512KB SRAM + PSRAM)'), ('pi4', 'Raspberry Pi 4 (Linux)')], default='pi4', help_text='The platform this pipeline natively lives on. Targets smaller than origin are distillations; larger are expansions.', max_length=20),
        ),
    ]
