# Generated by Django 6.0.4 on 2026-04-11 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MapPrefs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_scale', models.CharField(choices=[('earth', 'Earth (OpenStreetMap)'), ('mars', 'Mars surface'), ('moon', 'Moon surface'), ('solar_system', 'Solar System'), ('sky', 'Sky / Galaxy / Universe')], default='earth', max_length=16)),
                ('default_lat', models.FloatField(default=52.1601)),
                ('default_lon', models.FloatField(default=4.497)),
                ('default_zoom', models.IntegerField(default=12)),
            ],
            options={
                'verbose_name': 'Map preferences',
                'verbose_name_plural': 'Map preferences',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('scale', models.CharField(choices=[('earth', 'Earth (OpenStreetMap)'), ('mars', 'Mars surface'), ('moon', 'Moon surface'), ('solar_system', 'Solar System'), ('sky', 'Sky / Galaxy / Universe')], default='earth', max_length=16)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('zoom', models.IntegerField(default=10)),
                ('notes', models.TextField(blank=True)),
                ('color', models.CharField(blank=True, help_text='Optional hex color for the marker pin.', max_length=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['scale', 'name'],
                'indexes': [models.Index(fields=['scale'], name='cartography_scale_825aa3_idx')],
            },
        ),
    ]
