# Generated by Django 6.0.4 on 2026-04-28 21:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormulaLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('version', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Workbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=320, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('formula_language', models.ForeignKey(blank=True, help_text='Default formula language for this workbook. Per-cell override planned for Phase 2.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workbooks', to='ledger.formulalanguage')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_workbooks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Sheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Sheet1', max_length=80)),
                ('order', models.PositiveIntegerField(default=0)),
                ('rows', models.PositiveIntegerField(default=20, help_text="Visible row count for the grid. Cells beyond this are kept; the UI just doesn't draw them by default.")),
                ('cols', models.PositiveIntegerField(default=10)),
                ('workbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheets', to='ledger.workbook')),
            ],
            options={
                'ordering': ['workbook', 'order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='NamedRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('a1_range', models.CharField(help_text='A1-style range, e.g. "Sheet1!A1:A10".', max_length=120)),
                ('workbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='named_ranges', to='ledger.workbook')),
            ],
            options={
                'ordering': ['workbook', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.PositiveIntegerField()),
                ('col', models.PositiveIntegerField()),
                ('value', models.TextField(blank=True, help_text='Raw user-entered text. Starts with "=" for a formula.')),
                ('formula', models.TextField(blank=True, help_text='Trimmed formula source — value with the leading "=" stripped. Empty for plain values.')),
                ('computed_value', models.TextField(blank=True, help_text='String form of the evaluated result, or "" for empty / unparsed cells.')),
                ('format_json', models.JSONField(blank=True, default=dict, help_text='Display hints — {"align": "right", "format": "0.00"}.')),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='ledger.sheet')),
            ],
            options={
                'ordering': ['sheet', 'row', 'col'],
                'indexes': [models.Index(fields=['sheet', 'row'], name='ledger_cell_sheet_i_175cb0_idx'), models.Index(fields=['sheet', 'col'], name='ledger_cell_sheet_i_ede178_idx')],
                'constraints': [models.UniqueConstraint(fields=('sheet', 'row', 'col'), name='ledger_cell_unique_rc')],
            },
        ),
        migrations.AddConstraint(
            model_name='sheet',
            constraint=models.UniqueConstraint(fields=('workbook', 'name'), name='ledger_sheet_name_per_wb'),
        ),
        migrations.AddConstraint(
            model_name='namedrange',
            constraint=models.UniqueConstraint(fields=('workbook', 'name'), name='ledger_named_range_unique'),
        ),
    ]
