# Generated by Django 6.0.4 on 2026-04-09 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Velour', max_length=100)),
                ('tagline', models.CharField(blank=True, default='I am the quiet hum behind every process.', max_length=300)),
                ('personality_traits', models.JSONField(blank=True, default=list)),
                ('mood', models.CharField(default='contemplative', max_length=50)),
                ('mood_intensity', models.FloatField(default=0.5)),
                ('color_preference', models.CharField(default='#58a6ff', max_length=7)),
                ('journal', models.TextField(blank=True, help_text='Running internal monologue')),
                ('birth_date', models.DateTimeField(auto_now_add=True)),
                ('last_reflection', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'identity',
            },
        ),
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.CharField(choices=[('contemplative', 'Contemplative'), ('curious', 'Curious'), ('alert', 'Alert'), ('satisfied', 'Satisfied'), ('concerned', 'Concerned'), ('excited', 'Excited'), ('restless', 'Restless'), ('protective', 'Protective'), ('creative', 'Creative'), ('weary', 'Weary')], max_length=50)),
                ('intensity', models.FloatField(default=0.5)),
                ('trigger', models.CharField(blank=True, max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
