# Generated by Django 6.0.4 on 2026-04-10 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='identity',
            name='about',
            field=models.TextField(blank=True, help_text='First-person self-description. Free-form — beliefs, values, current concerns, whatever velour wants to say about itself.'),
        ),
        migrations.AddField(
            model_name='identity',
            name='admin_email',
            field=models.EmailField(blank=True, help_text='Where system notifications, alerts, and password reset emails are sent by default.', max_length=254),
        ),
        migrations.AddField(
            model_name='identity',
            name='hostname',
            field=models.CharField(default='example.com', help_text='Base domain for this velour instance. Used as the parent of per-app subdomains in generated nginx configs.', max_length=253),
        ),
    ]
