# Generated by Django 6.0.4 on 2026-04-11 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_identity_about_identity_admin_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('triggered_by', models.CharField(choices=[('cron', 'Cron'), ('manual', 'Manual'), ('request', 'HTTP request hook'), ('event', 'Event callback'), ('boot', 'Application boot')], default='manual', max_length=16)),
                ('mood', models.CharField(default='contemplative', max_length=50)),
                ('mood_intensity', models.FloatField(default=0.5)),
                ('rule_label', models.CharField(blank=True, help_text='Human-readable reason the winning rule fired.', max_length=200)),
                ('thought', models.TextField(blank=True, help_text='First-person one-liner composed from templates.')),
                ('snapshot', models.JSONField(blank=True, default=dict, help_text='Raw sensor inputs this tick saw.')),
                ('aspects', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['-at'],
                'indexes': [models.Index(fields=['-at'], name='identity_ti_at_c90797_idx'), models.Index(fields=['mood', '-at'], name='identity_ti_mood_65df55_idx')],
            },
        ),
    ]
