# Generated by Django 6.0.4 on 2026-04-11 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0004_backfill_tick_from_mood_and_journal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aspect', models.CharField(db_index=True, help_text='The aspect tag from identity/ticking.py RULES that opened this concern, e.g. "disk_critical".', max_length=64)),
                ('name', models.CharField(blank=True, help_text='Human-readable name for the operator — the rule label that originally fired, e.g. "disk dangerously full".', max_length=120)),
                ('description', models.TextField(blank=True, help_text='Longer free-form context. Usually set by the rule that opened the concern.')),
                ('severity', models.FloatField(default=0.5, help_text='0-1 scalar, same scale as mood intensity. Drives UI color and thought-composition weight.')),
                ('opened_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Most recent tick that re-confirmed this concern. A concern closes automatically when last_seen_at gets stale relative to the tick interval.')),
                ('closed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('reconfirm_count', models.PositiveIntegerField(default=1)),
                ('origin_tick', models.ForeignKey(blank=True, help_text='The Tick row that first observed this concern.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opened_concerns', to='identity.tick')),
            ],
            options={
                'ordering': ['-opened_at'],
                'indexes': [models.Index(fields=['aspect', 'closed_at'], name='identity_co_aspect_e0c3d3_idx'), models.Index(fields=['-opened_at'], name='identity_co_opened__1e29c3_idx')],
            },
        ),
    ]
