# Generated by Django 6.0.4 on 2026-04-11 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0005_concern'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Human-readable label shown on the tick log and in concern names when this rule fires, e.g. "disk dangerously full".', max_length=200)),
                ('aspect', models.CharField(help_text='Tag-like string stored on Tick.aspects when this rule matches, e.g. "disk_critical". Lower-snake case by convention. If `opens_concern` is true, this also becomes the aspect key on the resulting Concern row.', max_length=64)),
                ('condition', models.JSONField(blank=True, default=dict, help_text='JSON expression. Top-level {metric, op, value} for a simple comparison, or {all: [...]} / {any: [...]} for compound conditions. See Rule.__doc__ for the full grammar.')),
                ('mood', models.CharField(default='contemplative', help_text='Mood this rule selects when it wins first-match mood evaluation. Does not have to match Mood.MOOD_CHOICES — novel mood strings are fine, they just do not get a display translation.', max_length=50)),
                ('intensity', models.FloatField(default=0.5, help_text='0-1 scalar, same scale as Tick.mood_intensity.')),
                ('priority', models.IntegerField(default=100, help_text='Lower numbers evaluate first. The first matching rule wins mood selection. Aspect tagging considers every matching rule regardless of priority.')),
                ('opens_concern', models.BooleanField(default=False, help_text='If true, matches of this rule can open a persistent Concern that survives across subsequent ticks until the condition clears for the staleness window.')),
                ('is_active', models.BooleanField(default=True, help_text='Operator toggle. Inactive rules are skipped during evaluation but not deleted — so you can pause a noisy rule without losing its definition.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['priority', 'name'],
            },
        ),
    ]
