# Generated by Django 6.0.4 on 2026-04-11 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0007_seed_rules'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reflection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('hourly', 'Hour'), ('daily', 'Day'), ('weekly', 'Week'), ('monthly', 'Month'), ('yearly', 'Year')], max_length=16)),
                ('period_start', models.DateTimeField(db_index=True, help_text='Beginning of the period this reflection covers.')),
                ('period_end', models.DateTimeField(db_index=True, help_text='End of the period (exclusive).')),
                ('composed_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the reflection was actually generated.')),
                ('title', models.CharField(blank=True, help_text='Human-readable title, usually derived from the period, e.g. "Week of 2026-04-06" or "April 2026".', max_length=200)),
                ('body', models.TextField(help_text='Markdown prose paragraph, first-person voice.')),
                ('ticks_referenced', models.PositiveIntegerField(default=0)),
                ('metrics', models.JSONField(blank=True, default=dict, help_text='Computed aggregates used to compose the body: mood distribution, top aspects, etc. Kept for debugging and for re-rendering if the template library changes.')),
                ('codex_section_slug', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'ordering': ['-period_start'],
                'indexes': [models.Index(fields=['period', '-period_start'], name='identity_re_period_ce05bb_idx')],
                'constraints': [models.UniqueConstraint(fields=('period', 'period_start'), name='identity_reflection_unique_period')],
            },
        ),
    ]
