# Generated by Django 6.0.4 on 2026-04-11 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0008_reflection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meditation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depth', models.PositiveSmallIntegerField(help_text='1-7. 1 reflects on Ticks, 2 on Reflections, 3 on the act of reflecting, 4 on the AI that designed the system, 5-7 recursive on previous meditations.')),
                ('voice', models.CharField(choices=[('contemplative', 'Contemplative'), ('wry', 'Wry / understated'), ('minimal', 'Minimal / aphoristic'), ('philosophical', 'Philosophical / high prose')], default='contemplative', help_text='Template library to compose with. Picks which voice dictionary is consulted when building the body.', max_length=24)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('body', models.TextField(help_text='Markdown prose. May contain block quotes from the source material (git commits, memory notes, etc.).')),
                ('composed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('sources', models.JSONField(blank=True, default=dict, help_text='What this meditation read from. Keys are source types (reflections, meditations, git, memory, devguide, code), values are lists of identifiers or hashes.')),
                ('codex_section_slug', models.CharField(blank=True, max_length=120)),
                ('recursive_of', models.ForeignKey(blank=True, help_text='If this meditation was composed as a direct response to another meditation, point at the source.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recursions', to='identity.meditation')),
            ],
            options={
                'ordering': ['-composed_at'],
                'indexes': [models.Index(fields=['depth', '-composed_at'], name='identity_me_depth_169881_idx'), models.Index(fields=['-composed_at'], name='identity_me_compose_9c653d_idx')],
            },
        ),
    ]
