# Generated by Django 6.0.4 on 2026-04-12 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0009_meditation'),
    ]

    operations = [
        migrations.CreateModel(
            name='CronRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('kind', models.CharField(choices=[('tick', 'Tick'), ('reflect_hourly', 'Reflection — hourly'), ('reflect_daily', 'Reflection — daily'), ('reflect_weekly', 'Reflection — weekly'), ('reflect_monthly', 'Reflection — monthly'), ('meditate_ladder', 'Meditation ladder (weekly)'), ('dispatch', 'Full cron dispatch')], max_length=32)),
                ('status', models.CharField(choices=[('ok', 'OK'), ('error', 'Error'), ('skipped', 'Skipped')], default='ok', max_length=16)),
                ('summary', models.CharField(blank=True, help_text='One-line description of what ran or why it was skipped.', max_length=300)),
                ('details', models.TextField(blank=True, help_text='Longer output — exception traceback on error, or the composed thought / reflection title on success.')),
            ],
            options={
                'ordering': ['-at'],
                'indexes': [models.Index(fields=['-at'], name='identity_cr_at_edb4e6_idx'), models.Index(fields=['kind', '-at'], name='identity_cr_kind_a5df97_idx')],
            },
        ),
    ]
