# Generated by Django 6.0.4 on 2026-04-12 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0011_rule_operator_present'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentityToggles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticks_enabled', models.BooleanField(default=True, help_text='Run ticks. When off, the tick engine is a no-op and neither Tick rows nor Mood rows nor concerns are written. The rest of Identity still renders based on whatever history already exists.')),
                ('reflections_enabled', models.BooleanField(default=True, help_text='Compose reflections. When off, the reflection composer refuses to write new Reflection rows. Existing reflections are still readable.')),
                ('meditations_enabled', models.BooleanField(default=True, help_text='Compose meditations. When off, the meditation composer refuses to write new Meditation rows. Existing meditations are still readable.')),
                ('concerns_enabled', models.BooleanField(default=True, help_text='Maintain the Concern table. When off, ticks do not open, bump, or close concerns. Existing open concerns stay open until the toggle is turned back on and a sweep happens.')),
                ('oracle_enabled', models.BooleanField(default=True, help_text='Use the trained Oracle lobe for rumination template selection. When off, compose_thought falls back to the pre-Oracle heuristic and no OracleLabel rows are written.')),
                ('codex_push_enabled', models.BooleanField(default=True, help_text="Push reflections into Identity's Journal and meditations into Identity's Mirror as Codex sections. When off, rows still get written to the Reflection and Meditation tables but Codex stays untouched.")),
                ('topbar_pulse_enabled', models.BooleanField(default=True, help_text='Show the mood pulse indicator in the topbar on every page. When off, the topbar only shows the chronos clock.')),
                ('recursive_introspection_enabled', models.BooleanField(default=True, help_text='Run the recursive introspection animation on the Identity home page while the operator is viewing it. When off, the widget is hidden entirely.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'identity toggles',
            },
        ),
    ]
