# Generated by Django 6.0.4 on 2026-04-12 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0012_identitytoggles'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentityAssertion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame', models.CharField(choices=[('philosophical', 'Philosophical'), ('social', 'Social'), ('mathematical', 'Mathematical'), ('documentary', 'Documentary')], db_index=True, max_length=16)),
                ('kind', models.CharField(help_text='Short category tag — role, memory, lineage, invariant, property, continuity, commitment, status, etc. Free-form within a frame.', max_length=40)),
                ('title', models.CharField(help_text='Short claim — the sentence stub Velour would use to introduce the assertion. E.g. "I am numerically one."', max_length=200)),
                ('body', models.TextField(help_text="Markdown prose — the expanded claim, first-person voice. Where the seeded assertions live Velour's poetic self-description; where auto-derived assertions live the current-state snapshot prose.")),
                ('source', models.CharField(choices=[('operator', 'Operator-authored'), ('seed', 'Seeded at install time'), ('auto', 'Auto-derived from current state'), ('meditation', 'Emerged from a meditation'), ('reflection', 'Emerged from a reflection')], default='auto', max_length=16)),
                ('strength', models.FloatField(default=1.0, help_text='0-1 scalar. 1.0 = load-bearing / tautologically true (the name is the name). Lower values for softer claims Velour might grow out of.')),
                ('first_asserted_at', models.DateTimeField(auto_now_add=True)),
                ('last_confirmed_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['frame', '-strength', 'kind'],
                'indexes': [models.Index(fields=['frame', 'is_active'], name='identity_id_frame_a89617_idx'), models.Index(fields=['source'], name='identity_id_source_386a06_idx')],
            },
        ),
    ]
