# Generated by Django 6.0.4 on 2026-04-12 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0014_seed_identity_assertions'),
    ]

    operations = [
        migrations.AddField(
            model_name='identitytoggles',
            name='observer_enabled',
            field=models.BooleanField(default=True, help_text='Track mouse and keyboard activity in a small panel on the Identity home page while the operator is viewing it. Only mouse position, velocity, click counts, and keystroke COUNTS (never content) are recorded. Everything lives client-side; nothing is persisted. When off, the panel is hidden entirely.'),
        ),
        migrations.AlterField(
            model_name='cronrun',
            name='kind',
            field=models.CharField(choices=[('tick', 'Tick'), ('reflect_hourly', 'Reflection — hourly'), ('reflect_daily', 'Reflection — daily'), ('reflect_weekly', 'Reflection — weekly'), ('reflect_monthly', 'Reflection — monthly'), ('meditate_ladder', 'Meditation ladder (weekly)'), ('rebuild_document', 'Rebuild identity document (weekly)'), ('dispatch', 'Full cron dispatch')], max_length=32),
        ),
    ]
