# Generated by Django 6.0.4 on 2026-04-12 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0015_identitytoggles_observer_enabled_alter_cronrun_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Human-readable label, e.g. "OpenAI GPT-4o" or "Local Ollama (llama3:8b)".', max_length=100)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('base_url', models.URLField(help_text='Full chat-completions endpoint URL, e.g. https://api.openai.com/v1/chat/completions.')),
                ('model', models.CharField(help_text='Model identifier the API expects in the body, e.g. "gpt-4o-mini", "claude-sonnet-4-5", "llama3:8b".', max_length=100)),
                ('api_key_file', models.CharField(blank=True, help_text='Path relative to BASE_DIR where the API key lives as a chmod-600 plain-text file, e.g. "llm_openai.key". Leave blank for local models that need no auth.', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='identitytoggles',
            name='llm_chat_enabled',
            field=models.BooleanField(default=False, help_text='Enable the LLM chat window on the Identity page. Defaults OFF because LLM queries hit external APIs and cost money. Turn on only after adding at least one LLMProvider with a valid API key.'),
        ),
        migrations.CreateModel(
            name='LLMExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField(help_text='The user prompt (operator-typed or Identity-composed).')),
                ('system_prompt', models.TextField(blank=True, help_text='The system-prompt prefix included in the request. Usually the Identity system prompt that primes the LLM to respond as an observer of Velour.')),
                ('response', models.TextField(blank=True, help_text='The assistant response. Empty if the call errored.')),
                ('tokens_in', models.PositiveIntegerField(default=0)),
                ('tokens_out', models.PositiveIntegerField(default=0)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True, help_text='Error message if the API call failed.')),
                ('ingested_as_assertion', models.BooleanField(default=False, help_text='Whether this exchange has been promoted to an IdentityAssertion row. The operator clicks "Ingest as assertion" from the chat UI.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exchanges', to='identity.llmprovider')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='identity_ll_created_7c9dfa_idx'), models.Index(fields=['provider', '-created_at'], name='identity_ll_provide_82a730_idx')],
            },
        ),
    ]
