# Generated by Django 6.0.4 on 2026-04-12 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0016_llmprovider_identitytoggles_llm_chat_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cronrun',
            name='kind',
            field=models.CharField(choices=[('tick', 'Tick'), ('reflect_hourly', 'Reflection — hourly'), ('reflect_daily', 'Reflection — daily'), ('reflect_weekly', 'Reflection — weekly'), ('reflect_monthly', 'Reflection — monthly'), ('meditate_ladder', 'Meditation ladder (weekly)'), ('rebuild_document', 'Rebuild identity document (weekly)'), ('tile_reflect', 'Tile reflection / autonomous generation'), ('dispatch', 'Full cron dispatch')], max_length=32),
        ),
    ]
