# Generated by Django 6.0.4 on 2026-04-12 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0017_alter_cronrun_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='identitytoggles',
            name='tile_generation_slider',
            field=models.PositiveSmallIntegerField(default=7, help_text='Frequency of autonomous tile set generation. 0=never, 1=1/year, 2=1/month, 3=1/week, 4=1/day, 5=1/hour, 6=1/10min, 7=1/min, 8=1/sec. Default 7 (once per minute). Intervals below the cron cadence fire at the cron cadence rate.'),
        ),
    ]
