# Generated by Django 6.0.4 on 2026-04-12 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0018_identitytoggles_tile_generation_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='identitytoggles',
            name='rumination_stream_enabled',
            field=models.BooleanField(default=True, help_text='Continuous low-CPU rumination stream on the Identity home page. When the page is open and the browser is idle, Velour pairs random artifacts from different data sources (meditations, tilesets, concerns, reflections, calendar events, strange loops, layers) and composes short prose observations about relationships between them. Uses requestIdleCallback and pauses on tab hidden.'),
        ),
    ]
