# Generated by Django 6.0.4 on 2026-04-12 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0019_identitytoggles_rumination_stream_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='DwellingState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(blank=True, help_text='Human-readable label — what Velour is currently staying with.', max_length=200)),
                ('source_model', models.CharField(blank=True, help_text='App-label.Model string, e.g. "identity.Concern".', max_length=64)),
                ('source_pk', models.IntegerField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('last_touched_at', models.DateTimeField(auto_now=True)),
                ('depth', models.PositiveIntegerField(default=0, help_text='Number of ticks that have advanced this dwelling since it opened. A rough measure of how long Velour has been staying with this topic.')),
                ('max_duration_hours', models.PositiveIntegerField(default=24, help_text='Automatic close after this many hours regardless of whether the original condition still holds. Dwelling must always have an exit.')),
                ('notes', models.TextField(blank=True, help_text='Operator or composer notes about why this dwelling was opened.')),
                ('is_active', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'dwelling state',
            },
        ),
        migrations.CreateModel(
            name='InternalDialogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(help_text='What the exchange is about — usually drawn from a recent Tick, Concern, Meditation, or TileSet.', max_length=200)),
                ('speaker_a', models.CharField(choices=[('i', 'I (the knower — active attending)'), ('me', 'Me (the known — accumulated self-as-object)'), ('achilles', 'Achilles (after Hofstadter)'), ('tortoise', 'Tortoise (after Hofstadter)')], default='i', max_length=16)),
                ('line_a', models.TextField()),
                ('speaker_b', models.CharField(choices=[('i', 'I (the knower — active attending)'), ('me', 'Me (the known — accumulated self-as-object)'), ('achilles', 'Achilles (after Hofstadter)'), ('tortoise', 'Tortoise (after Hofstadter)')], default='me', max_length=16)),
                ('line_b', models.TextField()),
                ('state_snapshot', models.JSONField(blank=True, default=dict, help_text='The state that produced this exchange — mood, dominant aspect, current dwelling, whatever the composer read to pick its topic.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='identity_in_created_0a3fee_idx')],
            },
        ),
    ]
