# Generated by Django 6.0.4 on 2026-04-12 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0020_dwellingstate_internaldialogue'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='proposed_by',
            field=models.CharField(blank=True, help_text='Origin label — "meditation L3 at 2026-04-12" or "operator". Blank for seeded rules.', max_length=200),
        ),
        migrations.AddField(
            model_name='rule',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('proposed', 'Proposed by Identity (needs operator approval)'), ('rejected', 'Rejected by operator')], default='active', help_text='Rules proposed by meditations sit in "proposed" until the operator approves them. Rejected rules are kept for audit but never evaluated.', max_length=16),
        ),
        migrations.CreateModel(
            name='ContinuityMarker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('kind', models.CharField(choices=[('preserve', 'Preserved continuity'), ('disrupt', 'Disrupted continuity'), ('affirm', 'Affirmed identity'), ('grow', 'Grew the self (new rule, new assertion)'), ('shed', 'Shed part of the self (deleted rule, closed concern)'), ('observe', 'Observed — neither preserved nor disrupted')], default='preserve', max_length=16)),
                ('title', models.CharField(help_text='One-line description of what happened.', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Longer context. Usually auto-composed by the code that created the marker.')),
                ('source_model', models.CharField(blank=True, max_length=64)),
                ('source_pk', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-at'],
                'indexes': [models.Index(fields=['-at'], name='identity_co_at_100af3_idx'), models.Index(fields=['kind', '-at'], name='identity_co_kind_d4891d_idx')],
            },
        ),
    ]
