# Generated by Django 6.0.4 on 2026-04-12 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0021_rule_proposed_by_rule_status_continuitymarker'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.TextField(help_text='The observation template string. Uses {placeholder} syntax — the same placeholders as the hardcoded OBSERVATIONS in identity/ticking.py. See _format_observation() for the full list.')),
                ('source', models.CharField(blank=True, help_text='Who/what contributed this template — "meditation L3 at ..." or "operator".', max_length=200)),
                ('status', models.CharField(choices=[('active', 'Active (in the pool)'), ('proposed', 'Proposed by meditation (needs operator approval)'), ('rejected', 'Rejected by operator')], default='active', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
