# Generated by Django 6.0.4 on 2026-04-12 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0022_templatecontribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='tick',
            name='micro_meditation',
            field=models.TextField(blank=True, help_text='Optional inline self-reflection, ~10% of ticks.'),
        ),
        migrations.AlterField(
            model_name='meditation',
            name='voice',
            field=models.CharField(choices=[('contemplative', 'Contemplative'), ('wry', 'Wry / understated'), ('minimal', 'Minimal / aphoristic'), ('philosophical', 'Philosophical / high prose'), ('phenomenological', 'Phenomenological (bracketed, raw data only)')], default='contemplative', help_text='Template library to compose with. Picks which voice dictionary is consulted when building the body.', max_length=24),
        ),
    ]
