# Generated by Django 6.0.4 on 2026-04-12 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0023_tick_micro_meditation_alter_meditation_voice'),
    ]

    operations = [
        migrations.AddField(
            model_name='tick',
            name='arousal',
            field=models.FloatField(default=0.0, help_text='-1 (calm) to +1 (aroused)'),
        ),
        migrations.AddField(
            model_name='tick',
            name='valence',
            field=models.FloatField(default=0.0, help_text='-1 (unpleasant) to +1 (pleasant)'),
        ),
    ]
