# Generated by Django 6.0.4 on 2026-04-12 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0024_tick_arousal_tick_valence'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaudeHook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('reflect', 'Please reflect on this'), ('build', 'Please build this feature'), ('question', 'I have a question'), ('analyze', 'Please analyze this pattern'), ('deepen', 'Please deepen this area')], default='reflect', max_length=16)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(help_text='The actual prompt/question/request for Claude Code.')),
                ('context', models.JSONField(blank=True, default=dict, help_text='Snapshot of what was happening when this hook was composed — mood, aspects, open concerns, recent tick thought, etc.')),
                ('status', models.CharField(choices=[('pending', 'Pending — not yet addressed by Claude'), ('in_progress', 'In progress — Claude is working on it'), ('resolved', 'Resolved'), ('deferred', 'Deferred to a future session')], default='pending', max_length=16)),
                ('composed_by', models.CharField(blank=True, help_text='What composed this hook — "meditation L3 at ...", "tick #N", "operator", etc.', max_length=200)),
                ('resolved_by', models.CharField(blank=True, help_text='Who/what resolved it — "Claude session at ...", etc.', max_length=200)),
                ('resolution', models.TextField(blank=True, help_text='What Claude did in response to this hook.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='identity_cl_status_061495_idx')],
            },
        ),
    ]
