# Generated by Django 6.0.4 on 2026-04-12 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0026_strangeloop_thoughtexperiment_introspectivelayer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identitytoggles',
            name='tile_generation_slider',
            field=models.PositiveSmallIntegerField(default=4, help_text='Frequency of autonomous tile set generation. 0=never, 1=1/year, 2=1/month, 3=1/week, 4=1/day, 5=1/hour, 6=1/10min, 7=1/min, 8=1/sec. Default 4 (once per day).'),
        ),
    ]
