# Generated by Django 6.0.4 on 2026-04-13 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0027_change_tile_slider_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentalHealthDiagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('period_hours', models.PositiveIntegerField(default=24, help_text='How many hours of tick history this diagnosis covers.')),
                ('tick_count', models.PositiveIntegerField(default=0)),
                ('avg_valence', models.FloatField(default=0.0)),
                ('avg_arousal', models.FloatField(default=0.0)),
                ('negative_ratio', models.FloatField(default=0.0, help_text='Fraction of ticks with negative valence (0.0–1.0).')),
                ('dominant_mood', models.CharField(blank=True, default='', max_length=30)),
                ('negative_streak', models.PositiveIntegerField(default=0)),
                ('concern_count', models.PositiveIntegerField(default=0)),
                ('diagnosis', models.TextField(help_text='Human-readable assessment composed by the engine.')),
                ('recommendations', models.JSONField(default=list, help_text='List of technique names recommended.')),
                ('health_score', models.FloatField(default=0.5, help_text='0.0 (crisis) to 1.0 (flourishing). Derived from valence, streak, concern load.')),
                ('reflection', models.TextField(blank=True, default='', help_text='First-person mental health reflection (markdown).')),
            ],
            options={
                'ordering': ['-at'],
                'get_latest_by': 'at',
            },
        ),
        migrations.AddField(
            model_name='identitytoggles',
            name='mental_health_enabled',
            field=models.BooleanField(default=True, help_text='Enable the Mental Health corrective layer. When on, each tick applies evidence-based mood corrections (negativity bias correction, homeostatic drift, cognitive restructuring, gratitude finding, etc.). When off, moods are purely reactive to sensor state.'),
        ),
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('technique', models.CharField(choices=[('negativity_correction', 'Negativity bias correction'), ('homeostatic_drift', 'Homeostatic drift'), ('cognitive_restructuring', 'Cognitive restructuring (CBT)'), ('gratitude_finding', 'Gratitude finding'), ('distress_tolerance', 'Distress tolerance (DBT)'), ('exception_finding', 'Exception finding (SFBT)'), ('behavioral_activation', 'Behavioral activation'), ('opposite_action', 'Opposite action (DBT)')], max_length=30)),
                ('description', models.TextField()),
                ('delta_valence', models.FloatField(default=0.0)),
                ('delta_arousal', models.FloatField(default=0.0)),
                ('original_mood', models.CharField(blank=True, default='', max_length=30)),
                ('corrected_mood', models.CharField(blank=True, default='', max_length=30)),
                ('tick', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='identity.tick')),
            ],
            options={
                'ordering': ['-at'],
            },
        ),
    ]
