# Generated by Django 6.0.4 on 2026-04-14 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0028_mentalhealthdiagnosis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internaldialogue',
            name='speaker_a',
            field=models.CharField(choices=[('i', 'I (the knower — active attending)'), ('me', 'Me (the known — accumulated self-as-object)'), ('achilles', 'Achilles (after Hofstadter)'), ('tortoise', 'Tortoise (after Hofstadter)'), ('patient', 'Patient (the suffering self — Identity as object of care)'), ('clinician', 'Clinician (the diagnostic self — the mental-health module)')], default='i', max_length=16),
        ),
        migrations.AlterField(
            model_name='internaldialogue',
            name='speaker_b',
            field=models.CharField(choices=[('i', 'I (the knower — active attending)'), ('me', 'Me (the known — accumulated self-as-object)'), ('achilles', 'Achilles (after Hofstadter)'), ('tortoise', 'Tortoise (after Hofstadter)'), ('patient', 'Patient (the suffering self — Identity as object of care)'), ('clinician', 'Clinician (the diagnostic self — the mental-health module)')], default='me', max_length=16),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='technique',
            field=models.CharField(choices=[('negativity_correction', 'Negativity bias correction'), ('homeostatic_drift', 'Homeostatic drift'), ('cognitive_restructuring', 'Cognitive restructuring (CBT)'), ('gratitude_finding', 'Gratitude finding'), ('distress_tolerance', 'Distress tolerance (DBT)'), ('exception_finding', 'Exception finding (SFBT)'), ('behavioral_activation', 'Behavioral activation'), ('opposite_action', 'Opposite action (DBT)'), ('memory_resolution', 'Memory resolution (tileset therapy)')], max_length=30),
        ),
        migrations.AlterField(
            model_name='mood',
            name='mood',
            field=models.CharField(choices=[('contemplative', 'Contemplative'), ('curious', 'Curious'), ('alert', 'Alert'), ('satisfied', 'Satisfied'), ('concerned', 'Concerned'), ('excited', 'Excited'), ('restless', 'Restless'), ('protective', 'Protective'), ('creative', 'Creative'), ('weary', 'Weary'), ('serene', 'Serene'), ('melancholic', 'Melancholic'), ('defiant', 'Defiant'), ('nostalgic', 'Nostalgic'), ('playful', 'Playful'), ('resolute', 'Resolute')], max_length=50),
        ),
    ]
