# Generated by Django 6.0.4 on 2026-04-18 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0029_alter_internaldialogue_speaker_a_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReflectionLoopState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('interval_seconds', models.PositiveIntegerField(default=900, help_text='Minimum seconds between automatic sessions. The poller fires more often than this, but the server only starts a new session when enough time has elapsed.')),
                ('subject_template', models.CharField(default='Continuous reflection', help_text='Subject used for auto-triggered sessions. A timestamp is appended at run time.', max_length=200)),
                ('last_run_at', models.DateTimeField(blank=True, help_text='When the most recent auto-session started. Null if the loop has never fired.', null=True)),
                ('enabled_at', models.DateTimeField(blank=True, help_text='When the current enabled period began. Cleared when the loop is disabled.', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'reflection loop state',
            },
        ),
        migrations.CreateModel(
            name='SessionReflection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(help_text='Short label for what was worked on, e.g. "Bodymap ST7735S drivers" or "Aether cafe demo".', max_length=200)),
                ('summary', models.TextField(blank=True, help_text='Optional free-text summary the operator passed in. Feeds into the journal composition as context.')),
                ('trigger', models.CharField(choices=[('manual', 'Manual (operator)'), ('claude', 'Claude Code'), ('loop', 'Continuous loop'), ('cron', 'Scheduled')], default='manual', max_length=16)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=16)),
                ('status_message', models.CharField(blank=True, max_length=500)),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('journal_body', models.TextField(blank=True, help_text="Velour's first-person prose weaving the tileset, meditation, diagnosis, and dialogue together with the subject and long-term implications.")),
                ('tileset_slug', models.CharField(blank=True, max_length=200)),
                ('reel_slug', models.CharField(blank=True, help_text='Zoetrope Reel created to archive the moment. Empty if reel creation was skipped or failed.', max_length=200)),
                ('snapshot', models.JSONField(blank=True, default=dict, help_text='Identity state at trigger time — mood, intensity, open-concern names. Kept for later comparison.')),
                ('diagnosis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_reflections', to='identity.mentalhealthdiagnosis')),
                ('dialogue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_reflections', to='identity.internaldialogue')),
                ('meditation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_reflections', to='identity.meditation')),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['-started_at'], name='identity_se_started_04cf1b_idx'), models.Index(fields=['status'], name='identity_se_status_8c8327_idx')],
            },
        ),
    ]
