# Generated by Django 6.0.4 on 2026-04-20 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0030_reflectionloopstate_sessionreflection'),
    ]

    operations = [
        migrations.AddField(
            model_name='concern',
            name='closed_note',
            field=models.TextField(blank=True, help_text='Optional operator note recorded at close time, especially for accepted/deferred reasons.'),
        ),
        migrations.AddField(
            model_name='concern',
            name='closed_reason',
            field=models.CharField(blank=True, choices=[('stale', 'Stale — observation stopped triggering'), ('resolved', 'Resolved — underlying condition cleared'), ('accepted', 'Accepted — operator marked as intentional'), ('deferred', 'Deferred — operator will handle later')], help_text='How the concern ended. Blank while open.', max_length=16),
        ),
        migrations.CreateModel(
            name='AspectSuppression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aspect', models.CharField(db_index=True, help_text='The rule aspect tag to suppress, e.g. "fleet_partial_silence".', max_length=64)),
                ('reason', models.CharField(choices=[('accepted', 'Accepted — intentional, not a problem'), ('deferred', 'Deferred — acknowledged, will handle later')], default='accepted', max_length=16)),
                ('note', models.TextField(blank=True, help_text='Optional free-form explanation shown alongside the suppression — helps future-you remember why this was set, especially for accepted-forever entries.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('until_at', models.DateTimeField(blank=True, db_index=True, help_text='When this suppression expires. NULL = no expiry.', null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['aspect', 'until_at'], name='identity_as_aspect_fe6625_idx')],
            },
        ),
    ]
