# Generated by Django 6.0.4 on 2026-04-26 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0031_concern_closed_note_concern_closed_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='identitytoggles',
            name='llm_daily_cost_cap_usd',
            field=models.DecimalField(decimal_places=4, default=1, help_text="Hard daily cap on LLM spend in USD. Calls that would push today's spend past this number are refused before hitting the network. Default $1.", max_digits=8),
        ),
        migrations.AddField(
            model_name='identitytoggles',
            name='llm_monthly_cost_cap_usd',
            field=models.DecimalField(decimal_places=4, default=10, help_text="Hard monthly cap on LLM spend in USD. Calls that would push this month's spend past this number are refused before hitting the network. Default $10.", max_digits=8),
        ),
        migrations.AddField(
            model_name='llmexchange',
            name='cost_usd',
            field=models.DecimalField(decimal_places=6, default=0, help_text='Computed at save time from token counts and the provider rate snapshot. Frozen on the row so historical cost is auditable even if provider rates change later.', max_digits=10),
        ),
        migrations.AddField(
            model_name='llmprovider',
            name='cost_per_million_input_tokens_usd',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Provider-published price per million input tokens in USD. Used to compute LLMExchange.cost_usd and enforce IdentityToggles cost caps. Leave 0 for free local models.', max_digits=10),
        ),
        migrations.AddField(
            model_name='llmprovider',
            name='cost_per_million_output_tokens_usd',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Provider-published price per million output tokens in USD. Used to compute LLMExchange.cost_usd.', max_digits=10),
        ),
    ]
