# Generated by Django 6.0.4 on 2026-04-26 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0032_identitytoggles_llm_daily_cost_cap_usd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='identitytoggles',
            name='llm_augment_meditations_enabled',
            field=models.BooleanField(default=False, help_text="Allow level-4 meditations to append a short LLM-composed coda commenting on the meditation's real source quote. Defaults OFF. Goes through the cost cap; the rule engine and the deterministic body are unchanged."),
        ),
        migrations.AddField(
            model_name='identitytoggles',
            name='llm_augment_provider',
            field=models.ForeignKey(blank=True, help_text='Provider used for augmentation calls (meditation codas etc.). When null, augmentation is silently skipped even when the toggle is on.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='identity.llmprovider'),
        ),
    ]
