# Generated by Django 6.0.4 on 2026-04-26 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0033_identitytoggles_llm_augment_meditations_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='identitytoggles',
            name='llm_augment_reflections_enabled',
            field=models.BooleanField(default=False, help_text='Allow daily/weekly/monthly reflections (NEVER hourly — too costly) to append a short LLM-composed coda summarising the most-noticed aspects as an outside observer would frame them. Defaults OFF. Cost-capped.'),
        ),
        migrations.AddField(
            model_name='identitytoggles',
            name='llm_augment_rumination_enabled',
            field=models.BooleanField(default=False, help_text='Allow the operator to manually request an LLM commentary on a single rumination pairing from the Identity home page. Per-click only — never auto. Defaults OFF.'),
        ),
    ]
