# Generated by Django 6.0.4 on 2026-04-09 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('order', models.IntegerField(default=0)),
                ('visible', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newspaper_name', models.CharField(default='The Velour Chronicle', max_length=200)),
                ('tagline', models.CharField(default='Dispatches from the digital frontier', max_length=300)),
            ],
            options={
                'verbose_name_plural': 'site settings',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('subtitle', models.CharField(blank=True, max_length=500)),
                ('body', models.TextField()),
                ('image_url', models.URLField(blank=True, help_text='URL to a header image (use picsum.photos or similar for placeholders)')),
                ('image_caption', models.CharField(blank=True, max_length=300)),
                ('is_featured', models.BooleanField(default=False, help_text='Show as the large hero article')),
                ('is_published', models.BooleanField(default=True)),
                ('author', models.CharField(default='Editorial Staff', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='landingpage.section')),
            ],
            options={
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
    ]
