# Generated by Django 6.0.4 on 2026-04-29 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostPoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('status', models.CharField(max_length=16)),
                ('cpu_load', models.FloatField(blank=True, null=True)),
                ('mem_pct', models.FloatField(blank=True, null=True)),
                ('disk_pct', models.FloatField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('snapshot', models.JSONField(blank=True, null=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polls', to='hosts.remotehost')),
            ],
            options={
                'ordering': ['-at'],
                'indexes': [models.Index(fields=['host', '-at'], name='hosts_hostp_host_id_6a9e12_idx')],
            },
        ),
    ]
