"""Auto-generated by datalift genmodels.

Source: dump

Review every model before migrating — Datalift makes best-
effort inferences (field types, FK targets, Laravel timestamp
conventions, ENUM → TextChoices, soft-delete hints). Rename
fields, split tables, promote junction tables to M2M, etc.
"""

from django.db import models


class Answer(models.Model):
    """Generated from legacy table `lime_answers`."""

    qid = models.IntegerField()
    code = models.CharField(max_length=5)
    answer = models.TextField()
    sortorder = models.IntegerField()
    assessment_value = models.IntegerField()
    language = models.CharField(max_length=20, default='en')
    scale_id = models.IntegerField(default=0)

    class Meta:
        db_table = 'lime_answers'
        ordering = ['qid']
        verbose_name_plural = 'lime_answers'
        constraints = [
            models.UniqueConstraint(fields=['qid', 'code', 'language', 'scale_id'], name='lime_answers_pk'),
        ]

    def __str__(self):
        return str(self.code or self.pk)


class Assessment(models.Model):
    """Generated from legacy table `lime_assessments`."""

    id = models.BigAutoField(primary_key=True)
    sid = models.IntegerField(default=0)
    scope = models.CharField(max_length=5)
    gid = models.IntegerField(default=0)
    name = models.TextField()
    minimum = models.CharField(max_length=50)
    maximum = models.CharField(max_length=50)
    message = models.TextField()
    language = models.CharField(max_length=20, default='en')

    class Meta:
        db_table = 'lime_assessments'
        ordering = ['name']
        verbose_name_plural = 'lime_assessments'
        constraints = [
            models.UniqueConstraint(fields=['id', 'language'], name='lime_assessments_pk'),
        ]

    def __str__(self):
        return str(self.name or self.pk)


class Box(models.Model):
    """Generated from legacy table `lime_boxes`."""

    id = models.BigAutoField(primary_key=True)
    position = models.IntegerField(null=True, blank=True)
    url = models.TextField()
    title = models.TextField()
    ico = models.CharField(max_length=255, null=True, blank=True)
    desc = models.TextField()
    page = models.TextField()
    usergroup = models.IntegerField()

    class Meta:
        db_table = 'lime_boxes'
        ordering = ['id']
        verbose_name_plural = 'lime_boxes'

    def __str__(self):
        return str(self.title or self.pk)


class Condition(models.Model):
    """Generated from legacy table `lime_conditions`."""

    cid = models.BigAutoField(primary_key=True)
    qid = models.IntegerField(default=0)
    cqid = models.IntegerField(default=0)
    cfieldname = models.CharField(max_length=50, default='')
    method = models.CharField(max_length=5, default='')
    value = models.CharField(max_length=255, default='')
    scenario = models.IntegerField(default=1)

    class Meta:
        db_table = 'lime_conditions'
        ordering = ['cid']
        verbose_name_plural = 'lime_conditions'


class Defaultvalue(models.Model):
    """Generated from legacy table `lime_defaultvalues`."""

    qid = models.IntegerField(default=0)
    scale_id = models.IntegerField(default=0)
    sqid = models.IntegerField(default=0)
    language = models.CharField(max_length=20)
    specialtype = models.CharField(max_length=20, default='')
    defaultvalue = models.TextField(null=True, blank=True)

    class Meta:
        db_table = 'lime_defaultvalues'
        ordering = ['qid']
        verbose_name_plural = 'lime_defaultvalues'
        constraints = [
            models.UniqueConstraint(fields=['qid', 'specialtype', 'language', 'scale_id', 'sqid'], name='lime_defaultvalues_pk'),
        ]


class ExpressionError(models.Model):
    """Generated from legacy table `lime_expression_errors`."""

    id = models.BigAutoField(primary_key=True)
    errortime = models.CharField(max_length=50, null=True, blank=True)
    sid = models.IntegerField(null=True, blank=True)
    gid = models.IntegerField(null=True, blank=True)
    qid = models.IntegerField(null=True, blank=True)
    gseq = models.IntegerField(null=True, blank=True)
    qseq = models.IntegerField(null=True, blank=True)
    type = models.CharField(max_length=50, null=True, blank=True)
    eqn = models.TextField(null=True, blank=True)
    prettyprint = models.TextField(null=True, blank=True)

    class Meta:
        db_table = 'lime_expression_errors'
        ordering = ['id']
        verbose_name_plural = 'lime_expression_errors'


class FailedLoginAttempt(models.Model):
    """Generated from legacy table `lime_failed_login_attempts`."""

    id = models.BigAutoField(primary_key=True)
    ip = models.GenericIPAddressField()
    last_attempt = models.CharField(max_length=20)
    number_attempts = models.IntegerField()

    class Meta:
        db_table = 'lime_failed_login_attempts'
        ordering = ['id']
        verbose_name_plural = 'lime_failed_login_attempts'


class Group(models.Model):
    """Generated from legacy table `lime_groups`."""

    gid = models.BigAutoField(primary_key=True)
    sid = models.IntegerField(default=0)
    group_name = models.CharField(max_length=100, default='')
    group_order = models.IntegerField(default=0)
    description = models.TextField(null=True, blank=True)
    language = models.CharField(max_length=20, default='en')
    randomization_group = models.CharField(max_length=20, default='')
    grelevance = models.TextField(null=True, blank=True)

    class Meta:
        db_table = 'lime_groups'
        ordering = ['gid']
        verbose_name_plural = 'lime_groups'
        constraints = [
            models.UniqueConstraint(fields=['gid', 'language'], name='lime_groups_pk'),
        ]


class Label(models.Model):
    """Generated from legacy table `lime_labels`."""

    id = models.BigAutoField(primary_key=True)
    lid = models.IntegerField(default=0)
    code = models.CharField(max_length=5, default='')
    title = models.TextField(null=True, blank=True)
    sortorder = models.IntegerField()
    language = models.CharField(max_length=20, default='en')
    assessment_value = models.IntegerField(default=0)

    class Meta:
        db_table = 'lime_labels'
        ordering = ['id']
        verbose_name_plural = 'lime_labels'

    def __str__(self):
        return str(self.title or self.pk)


class Labelset(models.Model):
    """Generated from legacy table `lime_labelsets`."""

    lid = models.BigAutoField(primary_key=True)
    label_name = models.CharField(max_length=100, default='')
    languages = models.CharField(max_length=200, null=True, blank=True, default='en')

    class Meta:
        db_table = 'lime_labelsets'
        ordering = ['lid']
        verbose_name_plural = 'lime_labelsets'


class MapTutorialUser(models.Model):
    """Generated from legacy table `lime_map_tutorial_users`."""

    tid = models.IntegerField()
    uid = models.IntegerField(default=0)
    taken = models.IntegerField(null=True, blank=True, default=1)

    class Meta:
        db_table = 'lime_map_tutorial_users'
        ordering = ['uid']
        verbose_name_plural = 'lime_map_tutorial_users'
        constraints = [
            models.UniqueConstraint(fields=['uid', 'tid'], name='lime_map_tutorial_users_pk'),
        ]


class Notification(models.Model):
    """Generated from legacy table `lime_notifications`."""

    id = models.BigAutoField(primary_key=True)
    entity = models.CharField(max_length=15)
    entity_id = models.IntegerField()
    title = models.CharField(max_length=255)
    message = models.TextField()
    status = models.CharField(max_length=15, default='new')
    importance = models.IntegerField(default=1)
    display_class = models.CharField(max_length=31, null=True, blank=True, default='default')
    hash = models.CharField(max_length=64, null=True, blank=True)
    created = models.DateTimeField(null=True, blank=True)
    first_read = models.DateTimeField(null=True, blank=True)

    class Meta:
        db_table = 'lime_notifications'
        ordering = ['id']
        verbose_name_plural = 'lime_notifications'

    def __str__(self):
        return str(self.title or self.pk)


class ParticipantAttribute(models.Model):
    """Generated from legacy table `lime_participant_attribute`."""

    participant_id = models.CharField(max_length=50)
    attribute_id = models.IntegerField()
    value = models.TextField()

    class Meta:
        db_table = 'lime_participant_attribute'
        ordering = ['participant_id']
        verbose_name_plural = 'lime_participant_attributes'
        constraints = [
            models.UniqueConstraint(fields=['participant_id', 'attribute_id'], name='lime_participant_attribute_pk'),
        ]


class ParticipantAttributeName(models.Model):
    """Generated from legacy table `lime_participant_attribute_names`."""

    attribute_id = models.BigAutoField(primary_key=True)
    attribute_type = models.CharField(max_length=4)
    defaultname = models.CharField(max_length=255)
    visible = models.CharField(max_length=5)

    class Meta:
        db_table = 'lime_participant_attribute_names'
        ordering = ['attribute_id']
        verbose_name_plural = 'lime_participant_attribute_names'
        constraints = [
            models.UniqueConstraint(fields=['attribute_id', 'attribute_type'], name='lime_participant_attribute_names_pk'),
        ]


class ParticipantAttributeNameLang(models.Model):
    """Generated from legacy table `lime_participant_attribute_names_lang`."""

    attribute_id = models.IntegerField()
    attribute_name = models.CharField(max_length=255)
    lang = models.CharField(max_length=20)

    class Meta:
        db_table = 'lime_participant_attribute_names_lang'
        ordering = ['attribute_id']
        verbose_name_plural = 'lime_participant_attribute_names_langs'
        constraints = [
            models.UniqueConstraint(fields=['attribute_id', 'lang'], name='lime_participant_attribute_names_lang_pk'),
        ]


class ParticipantAttributeValue(models.Model):
    """Generated from legacy table `lime_participant_attribute_values`."""

    value_id = models.BigAutoField(primary_key=True)
    attribute_id = models.IntegerField()
    value = models.TextField()

    class Meta:
        db_table = 'lime_participant_attribute_values'
        ordering = ['value_id']
        verbose_name_plural = 'lime_participant_attribute_values'


class ParticipantShare(models.Model):
    """Generated from legacy table `lime_participant_shares`."""

    participant_id = models.CharField(max_length=50)
    share_uid = models.IntegerField()
    date_added = models.DateTimeField()
    can_edit = models.CharField(max_length=5)

    class Meta:
        db_table = 'lime_participant_shares'
        ordering = ['participant_id']
        verbose_name_plural = 'lime_participant_shares'
        constraints = [
            models.UniqueConstraint(fields=['participant_id', 'share_uid'], name='lime_participant_shares_pk'),
        ]


class Participant(models.Model):
    """Generated from legacy table `lime_participants`."""

    participant_id = models.CharField(primary_key=True, max_length=50)
    firstname = models.CharField(max_length=150, null=True, blank=True)
    lastname = models.CharField(max_length=150, null=True, blank=True)
    email = models.TextField(null=True, blank=True)
    language = models.CharField(max_length=40, null=True, blank=True)
    blacklisted = models.CharField(max_length=1)
    owner_uid = models.IntegerField()
    created_by = models.IntegerField()
    created = models.DateTimeField(null=True, blank=True)
    modified = models.DateTimeField(null=True, blank=True)

    class Meta:
        db_table = 'lime_participants'
        ordering = ['participant_id']
        verbose_name_plural = 'lime_participants'

    def __str__(self):
        return str(self.email or self.pk)


class Permission(models.Model):
    """Generated from legacy table `lime_permissions`."""

    id = models.BigAutoField(primary_key=True)
    entity = models.CharField(max_length=50)
    entity_id = models.IntegerField()
    uid = models.IntegerField()
    permission = models.CharField(max_length=100)
    create_p = models.IntegerField(default=0)
    read_p = models.IntegerField(default=0)
    update_p = models.IntegerField(default=0)
    delete_p = models.IntegerField(default=0)
    import_p = models.IntegerField(default=0)
    export_p = models.IntegerField(default=0)

    class Meta:
        db_table = 'lime_permissions'
        ordering = ['id']
        verbose_name_plural = 'lime_permissions'


class PluginSetting(models.Model):
    """Generated from legacy table `lime_plugin_settings`."""

    id = models.BigAutoField(primary_key=True)
    plugin_id = models.IntegerField()
    model = models.CharField(max_length=50, null=True, blank=True)
    model_id = models.IntegerField(null=True, blank=True)
    key = models.CharField(max_length=50)
    value = models.TextField(null=True, blank=True)

    class Meta:
        db_table = 'lime_plugin_settings'
        ordering = ['id']
        verbose_name_plural = 'lime_plugin_settings'


class Plugin(models.Model):
    """Generated from legacy table `lime_plugins`."""

    id = models.BigAutoField(primary_key=True)
    name = models.CharField(max_length=50)
    active = models.IntegerField(default=0)
    version = models.CharField(max_length=32, null=True, blank=True)

    class Meta:
        db_table = 'lime_plugins'
        ordering = ['name']
        verbose_name_plural = 'lime_plugins'

    def __str__(self):
        return str(self.name or self.pk)


class QuestionAttribute(models.Model):
    """Generated from legacy table `lime_question_attributes`."""

    qaid = models.BigAutoField(primary_key=True)
    qid = models.IntegerField(default=0)
    attribute = models.CharField(max_length=50, null=True, blank=True)
    value = models.TextField(null=True, blank=True)
    language = models.CharField(max_length=20, null=True, blank=True)

    class Meta:
        db_table = 'lime_question_attributes'
        ordering = ['qaid']
        verbose_name_plural = 'lime_question_attributes'


class Question(models.Model):
    """Generated from legacy table `lime_questions`."""

    qid = models.BigAutoField(primary_key=True)
    parent_qid = models.IntegerField(default=0)
    sid = models.IntegerField(default=0)
    gid = models.IntegerField(default=0)
    type = models.CharField(max_length=1, default='T')
    title = models.CharField(max_length=20, default='')
    question = models.TextField()
    preg = models.TextField(null=True, blank=True)
    help = models.TextField(null=True, blank=True)
    other = models.CharField(max_length=1, default='N')
    mandatory = models.CharField(max_length=1, null=True, blank=True)
    question_order = models.IntegerField()
    language = models.CharField(max_length=20, default='en')
    scale_id = models.IntegerField(default=0)
    same_default = models.IntegerField(default=0)
    relevance = models.TextField(null=True, blank=True)
    modulename = models.CharField(max_length=255, null=True, blank=True)

    class Meta:
        db_table = 'lime_questions'
        ordering = ['qid']
        verbose_name_plural = 'lime_questions'
        constraints = [
            models.UniqueConstraint(fields=['qid', 'language'], name='lime_questions_pk'),
        ]

    def __str__(self):
        return str(self.title or self.pk)


class Quota(models.Model):
    """Generated from legacy table `lime_quota`."""

    id = models.BigAutoField(primary_key=True)
    sid = models.IntegerField(null=True, blank=True)
    name = models.CharField(max_length=255, null=True, blank=True)
    qlimit = models.IntegerField(null=True, blank=True)
    action = models.IntegerField(null=True, blank=True)
    active = models.IntegerField(default=1)
    autoload_url = models.IntegerField(default=0)

    class Meta:
        db_table = 'lime_quota'
        ordering = ['name']
        verbose_name_plural = 'lime_quotas'

    def __str__(self):
        return str(self.name or self.pk)


class QuotaLanguagesetting(models.Model):
    """Generated from legacy table `lime_quota_languagesettings`."""

    quotals_id = models.BigAutoField(primary_key=True)
    quotals_quota_id = models.IntegerField(default=0)
    quotals_language = models.CharField(max_length=45, default='en')
    quotals_name = models.CharField(max_length=255, null=True, blank=True)
    quotals_message = models.TextField()
    quotals_url = models.URLField(max_length=255, null=True, blank=True)
    quotals_urldescrip = models.CharField(max_length=255, null=True, blank=True)

    class Meta:
        db_table = 'lime_quota_languagesettings'
        ordering = ['quotals_id']
        verbose_name_plural = 'lime_quota_languagesettings'


class QuotaMember(models.Model):
    """Generated from legacy table `lime_quota_members`."""

    id = models.BigAutoField(primary_key=True)
    sid = models.IntegerField(null=True, blank=True)
    qid = models.IntegerField(null=True, blank=True)
    quota_id = models.IntegerField(null=True, blank=True)
    code = models.CharField(max_length=11, null=True, blank=True)

    class Meta:
        db_table = 'lime_quota_members'
        ordering = ['id']
        verbose_name_plural = 'lime_quota_members'

    def __str__(self):
        return str(self.code or self.pk)


class SavedControl(models.Model):
    """Generated from legacy table `lime_saved_control`."""

    scid = models.BigAutoField(primary_key=True)
    sid = models.IntegerField(default=0)
    srid = models.IntegerField(default=0)
    identifier = models.TextField()
    access_code = models.TextField()
    email = models.EmailField(max_length=192, null=True, blank=True)
    ip = models.TextField()
    saved_thisstep = models.TextField()
    status = models.CharField(max_length=1, default='')
    saved_date = models.DateTimeField()
    refurl = models.TextField(null=True, blank=True)

    class Meta:
        db_table = 'lime_saved_control'
        ordering = ['scid']
        verbose_name_plural = 'lime_saved_controls'

    def __str__(self):
        return str(self.email or self.pk)


class Session(models.Model):
    """Generated from legacy table `lime_sessions`."""

    id = models.CharField(primary_key=True, max_length=32)
    expire = models.IntegerField(null=True, blank=True)
    data = models.BinaryField(null=True, blank=True)

    class Meta:
        db_table = 'lime_sessions'
        ordering = ['id']
        verbose_name_plural = 'lime_sessions'


class SettingGlobal(models.Model):
    """Generated from legacy table `lime_settings_global`."""

    stg_name = models.CharField(primary_key=True, max_length=50, default='')
    stg_value = models.TextField()

    class Meta:
        db_table = 'lime_settings_global'
        ordering = ['stg_name']
        verbose_name_plural = 'lime_settings_globals'


class SettingUser(models.Model):
    """Generated from legacy table `lime_settings_user`."""

    id = models.BigAutoField(primary_key=True)
    uid = models.IntegerField()
    entity = models.CharField(max_length=15, null=True, blank=True)
    entity_id = models.CharField(max_length=31, null=True, blank=True)
    stg_name = models.CharField(max_length=63)
    stg_value = models.TextField(null=True, blank=True)

    class Meta:
        db_table = 'lime_settings_user'
        ordering = ['id']
        verbose_name_plural = 'lime_settings_users'


class SurveyLink(models.Model):
    """Generated from legacy table `lime_survey_links`."""

    participant_id = models.CharField(max_length=50)
    token_id = models.IntegerField()
    survey_id = models.IntegerField()
    date_created = models.DateTimeField(null=True, blank=True)
    date_invited = models.DateTimeField(null=True, blank=True)
    date_completed = models.DateTimeField(null=True, blank=True)

    class Meta:
        db_table = 'lime_survey_links'
        ordering = ['participant_id']
        verbose_name_plural = 'lime_survey_links'
        constraints = [
            models.UniqueConstraint(fields=['participant_id', 'token_id', 'survey_id'], name='lime_survey_links_pk'),
        ]


class SurveyUrlParameter(models.Model):
    """Generated from legacy table `lime_survey_url_parameters`."""

    id = models.BigAutoField(primary_key=True)
    sid = models.IntegerField()
    parameter = models.CharField(max_length=50)
    targetqid = models.IntegerField(null=True, blank=True)
    targetsqid = models.IntegerField(null=True, blank=True)

    class Meta:
        db_table = 'lime_survey_url_parameters'
        ordering = ['id']
        verbose_name_plural = 'lime_survey_url_parameters'


class Surveymenu(models.Model):
    """Generated from legacy table `lime_surveymenu`."""

    id = models.BigAutoField(primary_key=True)
    parent_id = models.IntegerField(null=True, blank=True)
    survey_id = models.IntegerField(null=True, blank=True)
    user_id = models.IntegerField(null=True, blank=True)
    name = models.CharField(unique=True, max_length=128)
    ordering = models.IntegerField(null=True, blank=True, default=0)
    level = models.IntegerField(null=True, blank=True, default=0)
    title = models.CharField(max_length=192, default='')
    position = models.CharField(max_length=192, default='side')
    description = models.TextField(null=True, blank=True)
    active = models.IntegerField(default=0)
    changed_at = models.DateTimeField(null=True, blank=True)
    changed_by = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    created_by = models.IntegerField(default=0)

    class Meta:
        db_table = 'lime_surveymenu'
        ordering = ['-created_at']
        verbose_name_plural = 'lime_surveymenus'

    def __str__(self):
        return str(self.name or self.pk)


class SurveymenuEntry(models.Model):
    """Generated from legacy table `lime_surveymenu_entries`."""

    id = models.BigAutoField(primary_key=True)
    menu_id = models.IntegerField(null=True, blank=True)
    user_id = models.IntegerField(null=True, blank=True)
    ordering = models.IntegerField(null=True, blank=True, default=0)
    name = models.CharField(unique=True, max_length=168, default='')
    title = models.CharField(max_length=168, default='')
    menu_title = models.CharField(max_length=168, default='')
    menu_description = models.TextField(null=True, blank=True)
    menu_icon = models.CharField(max_length=192, default='')
    menu_icon_type = models.CharField(max_length=192, default='')
    menu_class = models.CharField(max_length=192, default='')
    menu_link = models.CharField(max_length=192, default='')
    action = models.CharField(max_length=192, default='')
    template = models.CharField(max_length=192, default='')
    partial = models.CharField(max_length=192, default='')
    classes = models.CharField(max_length=192, default='')
    permission = models.CharField(max_length=192, default='')
    permission_grade = models.CharField(max_length=192, null=True, blank=True)
    data = models.TextField(null=True, blank=True)
    getdatamethod = models.CharField(max_length=192, default='')
    language = models.CharField(max_length=32, default='en-GB')
    active = models.IntegerField(default=0)
    changed_at = models.DateTimeField(null=True, blank=True)
    changed_by = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    created_by = models.IntegerField(default=0)

    class Meta:
        db_table = 'lime_surveymenu_entries'
        ordering = ['-created_at']
        verbose_name_plural = 'lime_surveymenu_entries'

    def __str__(self):
        return str(self.name or self.pk)


class Survey(models.Model):
    """Generated from legacy table `lime_surveys`."""

    sid = models.IntegerField(primary_key=True)
    owner_id = models.IntegerField()
    gsid = models.IntegerField(null=True, blank=True, default=1)
    admin = models.CharField(max_length=50, null=True, blank=True)
    active = models.CharField(max_length=1, default='N')
    expires = models.DateTimeField(null=True, blank=True)
    startdate = models.DateTimeField(null=True, blank=True)
    adminemail = models.CharField(max_length=254, null=True, blank=True)
    anonymized = models.CharField(max_length=1, default='N')
    faxto = models.CharField(max_length=20, null=True, blank=True)
    format = models.CharField(max_length=1, null=True, blank=True)
    savetimings = models.CharField(max_length=1, default='N')
    template = models.CharField(max_length=100, null=True, blank=True, default='default')
    language = models.CharField(max_length=50, null=True, blank=True)
    additional_languages = models.CharField(max_length=255, null=True, blank=True)
    datestamp = models.CharField(max_length=1, default='N')
    usecookie = models.CharField(max_length=1, default='N')
    allowregister = models.CharField(max_length=1, default='N')
    allowsave = models.CharField(max_length=1, default='Y')
    autonumber_start = models.IntegerField(default=0)
    autoredirect = models.CharField(max_length=1, default='N')
    allowprev = models.CharField(max_length=1, default='N')
    printanswers = models.CharField(max_length=1, default='N')
    ipaddr = models.CharField(max_length=1, default='N')
    refurl = models.CharField(max_length=1, default='N')
    datecreated = models.DateTimeField(null=True, blank=True)
    publicstatistics = models.CharField(max_length=1, default='N')
    publicgraphs = models.CharField(max_length=1, default='N')
    listpublic = models.CharField(max_length=1, default='N')
    htmlemail = models.CharField(max_length=1, default='N')
    sendconfirmation = models.CharField(max_length=1, default='Y')
    tokenanswerspersistence = models.CharField(max_length=1, default='N')
    assessments = models.CharField(max_length=1, default='N')
    usecaptcha = models.CharField(max_length=1, default='N')
    usetokens = models.CharField(max_length=1, default='N')
    bounce_email = models.EmailField(max_length=254, null=True, blank=True)
    attributedescriptions = models.TextField(null=True, blank=True)
    emailresponseto = models.TextField(null=True, blank=True)
    emailnotificationto = models.TextField(null=True, blank=True)
    tokenlength = models.IntegerField(default=15)
    showxquestions = models.CharField(max_length=1, null=True, blank=True, default='Y')
    showgroupinfo = models.CharField(max_length=1, null=True, blank=True, default='B')
    shownoanswer = models.CharField(max_length=1, null=True, blank=True, default='Y')
    showqnumcode = models.CharField(max_length=1, null=True, blank=True, default='X')
    bouncetime = models.IntegerField(null=True, blank=True)
    bounceprocessing = models.CharField(max_length=1, null=True, blank=True, default='N')
    bounceaccounttype = models.CharField(max_length=4, null=True, blank=True)
    bounceaccounthost = models.CharField(max_length=200, null=True, blank=True)
    bounceaccountpass = models.CharField(max_length=100, null=True, blank=True)
    bounceaccountencryption = models.CharField(max_length=3, null=True, blank=True)
    bounceaccountuser = models.CharField(max_length=200, null=True, blank=True)
    showwelcome = models.CharField(max_length=1, null=True, blank=True, default='Y')
    showprogress = models.CharField(max_length=1, null=True, blank=True, default='Y')
    questionindex = models.IntegerField(default=0)
    navigationdelay = models.IntegerField(default=0)
    nokeyboard = models.CharField(max_length=1, null=True, blank=True, default='N')
    alloweditaftercompletion = models.CharField(max_length=1, null=True, blank=True, default='N')
    googleanalyticsstyle = models.CharField(max_length=1, null=True, blank=True)
    googleanalyticsapikey = models.CharField(max_length=25, null=True, blank=True)

    class Meta:
        db_table = 'lime_surveys'
        ordering = ['sid']
        verbose_name_plural = 'lime_surveys'


class SurveyGroup(models.Model):
    """Generated from legacy table `lime_surveys_groups`."""

    gsid = models.BigAutoField(primary_key=True)
    name = models.CharField(max_length=45)
    title = models.CharField(max_length=100, null=True, blank=True)
    template = models.CharField(max_length=128, null=True, blank=True, default='default')
    description = models.TextField(null=True, blank=True)
    sortorder = models.IntegerField()
    owner_uid = models.IntegerField(null=True, blank=True)
    parent_id = models.IntegerField(null=True, blank=True)
    created = models.DateTimeField(null=True, blank=True)
    modified = models.DateTimeField(null=True, blank=True)
    created_by = models.IntegerField()

    class Meta:
        db_table = 'lime_surveys_groups'
        ordering = ['name']
        verbose_name_plural = 'lime_surveys_groups'

    def __str__(self):
        return str(self.name or self.pk)


class SurveyLanguagesetting(models.Model):
    """Generated from legacy table `lime_surveys_languagesettings`."""

    surveyls_survey_id = models.IntegerField()
    surveyls_language = models.CharField(max_length=45, default='en')
    surveyls_title = models.CharField(max_length=200)
    surveyls_description = models.TextField(null=True, blank=True)
    surveyls_welcometext = models.TextField(null=True, blank=True)
    surveyls_endtext = models.TextField(null=True, blank=True)
    surveyls_url = models.TextField(null=True, blank=True)
    surveyls_urldescription = models.CharField(max_length=255, null=True, blank=True)
    surveyls_email_invite_subj = models.CharField(max_length=255, null=True, blank=True)
    surveyls_email_invite = models.TextField(null=True, blank=True)
    surveyls_email_remind_subj = models.CharField(max_length=255, null=True, blank=True)
    surveyls_email_remind = models.TextField(null=True, blank=True)
    surveyls_email_register_subj = models.CharField(max_length=255, null=True, blank=True)
    surveyls_email_register = models.TextField(null=True, blank=True)
    surveyls_email_confirm_subj = models.CharField(max_length=255, null=True, blank=True)
    surveyls_email_confirm = models.TextField(null=True, blank=True)
    surveyls_dateformat = models.IntegerField(default=1)
    surveyls_attributecaptions = models.TextField(null=True, blank=True)
    email_admin_notification_subj = models.CharField(max_length=255, null=True, blank=True)
    email_admin_notification = models.TextField(null=True, blank=True)
    email_admin_responses_subj = models.CharField(max_length=255, null=True, blank=True)
    email_admin_responses = models.TextField(null=True, blank=True)
    surveyls_numberformat = models.IntegerField(default=0)
    attachments = models.TextField(null=True, blank=True)

    class Meta:
        db_table = 'lime_surveys_languagesettings'
        ordering = ['surveyls_survey_id']
        verbose_name_plural = 'lime_surveys_languagesettings'
        constraints = [
            models.UniqueConstraint(fields=['surveyls_survey_id', 'surveyls_language'], name='lime_surveys_languagesettings_pk'),
        ]


class TemplateConfiguration(models.Model):
    """Generated from legacy table `lime_template_configuration`."""

    id = models.BigAutoField(primary_key=True)
    template_name = models.CharField(max_length=150)
    sid = models.IntegerField(null=True, blank=True)
    gsid = models.IntegerField(null=True, blank=True)
    uid = models.IntegerField(null=True, blank=True)
    files_css = models.TextField(null=True, blank=True)
    files_js = models.TextField(null=True, blank=True)
    files_print_css = models.TextField(null=True, blank=True)
    options = models.TextField(null=True, blank=True)
    cssframework_name = models.CharField(max_length=45, null=True, blank=True)
    cssframework_css = models.TextField(null=True, blank=True)
    cssframework_js = models.TextField(null=True, blank=True)
    packages_to_load = models.TextField(null=True, blank=True)
    packages_ltr = models.TextField(null=True, blank=True)
    packages_rtl = models.TextField(null=True, blank=True)

    class Meta:
        db_table = 'lime_template_configuration'
        ordering = ['id']
        verbose_name_plural = 'lime_template_configurations'


class Template(models.Model):
    """Generated from legacy table `lime_templates`."""

    id = models.BigAutoField(primary_key=True)
    name = models.CharField(max_length=150)
    folder = models.CharField(max_length=45, null=True, blank=True)
    title = models.CharField(max_length=100)
    creation_date = models.DateTimeField(null=True, blank=True)
    author = models.CharField(max_length=150, null=True, blank=True)
    author_email = models.EmailField(max_length=255, null=True, blank=True)
    author_url = models.URLField(max_length=255, null=True, blank=True)
    copyright = models.TextField(null=True, blank=True)
    license = models.TextField(null=True, blank=True)
    version = models.CharField(max_length=45, null=True, blank=True)
    api_version = models.CharField(max_length=45)
    view_folder = models.CharField(max_length=45)
    files_folder = models.CharField(max_length=45)
    description = models.TextField(null=True, blank=True)
    last_update = models.DateTimeField(null=True, blank=True)
    owner_id = models.IntegerField(null=True, blank=True)
    extends = models.CharField(max_length=150, null=True, blank=True)

    class Meta:
        db_table = 'lime_templates'
        ordering = ['name']
        verbose_name_plural = 'lime_templates'

    def __str__(self):
        return str(self.name or self.pk)


class TutorialEntry(models.Model):
    """Generated from legacy table `lime_tutorial_entries`."""

    teid = models.BigAutoField(primary_key=True)
    ordering = models.IntegerField(null=True, blank=True)
    title = models.TextField(null=True, blank=True)
    content = models.TextField(null=True, blank=True)
    settings = models.TextField(null=True, blank=True)

    class Meta:
        db_table = 'lime_tutorial_entries'
        ordering = ['teid']
        verbose_name_plural = 'lime_tutorial_entries'

    def __str__(self):
        return str(self.title or self.pk)


class TutorialEntryRelation(models.Model):
    """Generated from legacy table `lime_tutorial_entry_relation`."""

    teid = models.IntegerField()
    tid = models.IntegerField()
    uid = models.IntegerField(null=True, blank=True)
    sid = models.IntegerField(null=True, blank=True)

    class Meta:
        db_table = 'lime_tutorial_entry_relation'
        ordering = ['teid']
        verbose_name_plural = 'lime_tutorial_entry_relations'
        constraints = [
            models.UniqueConstraint(fields=['teid', 'tid'], name='lime_tutorial_entry_relation_pk'),
        ]


class Tutorial(models.Model):
    """Generated from legacy table `lime_tutorials`."""

    tid = models.BigAutoField(primary_key=True)
    name = models.CharField(unique=True, max_length=128, null=True, blank=True)
    title = models.CharField(max_length=192, null=True, blank=True)
    icon = models.CharField(max_length=64, null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    active = models.IntegerField(null=True, blank=True, default=0)
    settings = models.TextField(null=True, blank=True)
    permission = models.CharField(max_length=128)
    permission_grade = models.CharField(max_length=128)

    class Meta:
        db_table = 'lime_tutorials'
        ordering = ['name']
        verbose_name_plural = 'lime_tutorials'

    def __str__(self):
        return str(self.name or self.pk)


class UserGroup(models.Model):
    """Generated from legacy table `lime_user_groups`."""

    ugid = models.BigAutoField(primary_key=True)
    name = models.CharField(unique=True, max_length=20)
    description = models.TextField()
    owner_id = models.IntegerField()

    class Meta:
        db_table = 'lime_user_groups'
        ordering = ['name']
        verbose_name_plural = 'lime_user_groups'

    def __str__(self):
        return str(self.name or self.pk)


class UserInGroup(models.Model):
    """Generated from legacy table `lime_user_in_groups`."""

    ugid = models.IntegerField()
    uid = models.IntegerField()

    class Meta:
        db_table = 'lime_user_in_groups'
        ordering = ['ugid']
        verbose_name_plural = 'lime_user_in_groups'
        constraints = [
            models.UniqueConstraint(fields=['ugid', 'uid'], name='lime_user_in_groups_pk'),
        ]


class User(models.Model):
    """Generated from legacy table `lime_users`."""

    uid = models.BigAutoField(primary_key=True)
    users_name = models.CharField(unique=True, max_length=64, default='')
    password = models.TextField()
    full_name = models.CharField(max_length=50)
    parent_id = models.IntegerField()
    lang = models.CharField(max_length=20, null=True, blank=True)
    email = models.EmailField(max_length=192, null=True, blank=True)
    htmleditormode = models.CharField(max_length=7, null=True, blank=True, default='default')
    templateeditormode = models.CharField(max_length=7, default='default')
    questionselectormode = models.CharField(max_length=7, default='default')
    one_time_pw = models.BinaryField(null=True, blank=True)
    dateformat = models.IntegerField(default=1)
    created = models.DateTimeField(null=True, blank=True)
    modified = models.DateTimeField(null=True, blank=True)

    class Meta:
        db_table = 'lime_users'
        ordering = ['uid']
        verbose_name_plural = 'lime_users'

    def __str__(self):
        return str(self.email or self.pk)
