"""Automaton — hexagonal cellular automata on Wang tile substrates.

A 4-color hexagonal Game of Life. Each cell has a color (0-3) and
6 neighbors. Rules determine how cells evolve based on their own
color and the colors of their neighbors.

Tilesets from the Tiles app provide the initial conditions and
color palette. Rules can be hand-crafted or generated by Identity
from its current mood state.

The simulation runs client-side on a canvas — the server provides
the initial grid, rules, and palette. The JS animator applies rules
at configurable speed with start/stop/step controls.
"""

from django.db import models
from django.utils.text import slugify


class RuleSet(models.Model):
    """A collection of cellular automaton rules for hex grids."""

    SOURCE_CHOICES = [
        ('operator', 'Operator-authored'),
        ('identity', 'Generated by Identity'),
        ('seed',     'Seeded at install'),
    ]

    name = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=220, unique=True, blank=True)
    description = models.TextField(blank=True)
    n_colors = models.PositiveSmallIntegerField(default=4,
        help_text='Number of cell colors (2-4).')
    source = models.CharField(max_length=16, choices=SOURCE_CHOICES,
                              default='operator')
    source_metadata = models.JSONField(default=dict, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.slug and self.name:
            base = slugify(self.name)[:200] or 'ruleset'
            candidate = base
            n = 2
            while RuleSet.objects.filter(slug=candidate).exclude(pk=self.pk).exists():
                candidate = f'{base}-{n}'
                n += 1
            self.slug = candidate
        super().save(*args, **kwargs)


class Rule(models.Model):
    """One transition rule: if a cell and its neighbors match a
    pattern, the cell becomes a new color on the next tick.

    The pattern is expressed as:
      - self_color: the cell's current color (0-3, or -1 for any)
      - neighbor_count: how many neighbors must have neighbor_color
      - neighbor_color: which color to count (0-3)
      - min_count / max_count: the range that triggers the rule
      - result_color: what the cell becomes

    Example: "If I am color 0 and I have 2-3 neighbors of color 1,
    I become color 2" → self_color=0, neighbor_color=1,
    min_count=2, max_count=3, result_color=2.

    Rules are evaluated in priority order. First matching rule wins.
    If no rule matches, the cell keeps its current color.
    """

    ruleset = models.ForeignKey(RuleSet, on_delete=models.CASCADE,
                                related_name='rules')
    priority = models.IntegerField(default=0,
        help_text='Lower = higher priority. First matching rule wins.')
    self_color = models.SmallIntegerField(default=-1,
        help_text='Cell color to match (-1 = any).')
    neighbor_color = models.SmallIntegerField(default=0,
        help_text='Which neighbor color to count (0-3).')
    min_count = models.PositiveSmallIntegerField(default=0,
        help_text='Minimum neighbors of that color to trigger.')
    max_count = models.PositiveSmallIntegerField(default=6,
        help_text='Maximum neighbors of that color to trigger.')
    result_color = models.SmallIntegerField(default=0,
        help_text='Cell becomes this color.')
    notes = models.CharField(max_length=200, blank=True)

    class Meta:
        ordering = ['ruleset', 'priority']

    def __str__(self):
        self_str = str(self.self_color) if self.self_color >= 0 else '*'
        return (f'[{self.priority}] {self_str} + '
                f'{self.min_count}-{self.max_count}×c{self.neighbor_color} '
                f'→ c{self.result_color}')


class ExactRule(models.Model):
    """A 7-tuple exact match rule: [self n0 n1 n2 n3 n4 n5] -> result.

    Each field specifies the exact color of the cell and each of its
    6 neighbors (in the canonical order N, NE, SE, S, SW, NW).
    If a cell + its neighbors match this exact pattern, the cell
    becomes result_color. -1 means "any" (wildcard).

    With 4 color states, the full rule space is 4^7 = 16384 possible
    7-tuples. Rulesets typically use a small random subset (50-500 rules).
    Unmatched cells keep their current color.
    """

    ruleset = models.ForeignKey(RuleSet, on_delete=models.CASCADE,
                                related_name='exact_rules')
    self_color = models.SmallIntegerField(
        help_text='Cell color (0-3, or -1 for any).')
    n0_color = models.SmallIntegerField(default=-1,
        help_text='N neighbor color (-1 = any).')
    n1_color = models.SmallIntegerField(default=-1,
        help_text='NE neighbor color (-1 = any).')
    n2_color = models.SmallIntegerField(default=-1,
        help_text='SE neighbor color (-1 = any).')
    n3_color = models.SmallIntegerField(default=-1,
        help_text='S neighbor color (-1 = any).')
    n4_color = models.SmallIntegerField(default=-1,
        help_text='SW neighbor color (-1 = any).')
    n5_color = models.SmallIntegerField(default=-1,
        help_text='NW neighbor color (-1 = any).')
    result_color = models.SmallIntegerField(
        help_text='Cell becomes this color.')
    priority = models.IntegerField(default=0,
        help_text='Lower = higher priority. First match wins.')

    class Meta:
        ordering = ['ruleset', 'priority']

    def __str__(self):
        def c(v): return str(v) if v >= 0 else '*'
        return (f'[{c(self.self_color)} {c(self.n0_color)} {c(self.n1_color)} '
                f'{c(self.n2_color)} {c(self.n3_color)} {c(self.n4_color)} '
                f'{c(self.n5_color)}] -> {self.result_color}')

    @property
    def pattern_tuple(self):
        return (self.self_color, self.n0_color, self.n1_color,
                self.n2_color, self.n3_color, self.n4_color, self.n5_color)


class Simulation(models.Model):
    """A saved simulation: initial grid + ruleset + palette."""

    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=220, unique=True, blank=True)
    ruleset = models.ForeignKey(RuleSet, on_delete=models.CASCADE,
                                related_name='simulations')
    tileset = models.ForeignKey('tiles.TileSet', on_delete=models.SET_NULL,
                                null=True, blank=True,
                                help_text='Initial conditions from this tileset.')
    width = models.PositiveIntegerField(default=32)
    height = models.PositiveIntegerField(default=32)
    palette = models.JSONField(default=list, blank=True,
        help_text='4 color hex codes for the cell colors.')
    grid_state = models.JSONField(default=list, blank=True,
        help_text='2D array of color indices (0-3). Empty = random init.')
    tick_count = models.PositiveIntegerField(default=0)
    notes = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.slug and self.name:
            base = slugify(self.name)[:200] or 'sim'
            candidate = base
            n = 2
            while Simulation.objects.filter(slug=candidate).exclude(pk=self.pk).exists():
                candidate = f'{base}-{n}'
                n += 1
            self.slug = candidate
        super().save(*args, **kwargs)
