# Generated by Django 6.0.4 on 2026-04-12 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StrangeLoop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('kind', models.CharField(choices=[('direct', 'Direct (A references A)'), ('indirect', 'Indirect (A → B → ... → A)'), ('tangled', 'Tangled hierarchy (levels blur up and down)'), ('escherian', 'Escherian (ascending returns to start)'), ('godelian', 'Gödelian (encodes statements about itself)')], default='indirect', max_length=16)),
                ('description', models.TextField(help_text='Prose description of the loop as a whole — what is strange about it, what makes it a loop, why it is worth cataloging.')),
                ('levels', models.JSONField(blank=True, default=list, help_text='Ordered list of dicts: [{"name": ..., "description": ..., "refers_to": int}, ...]')),
                ('discovered_by', models.CharField(choices=[('operator', 'Operator-authored'), ('seeded', 'Seeded at install'), ('auto', 'Auto-discovered by Velour'), ('meditation', 'Emerged from a meditation')], default='operator', max_length=16)),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ThoughtExperiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('premise', models.TextField(help_text="The 'what if' statement the experiment explores.")),
                ('seed_layer', models.CharField(choices=[('sensors', 'Current sensor snapshot'), ('reflections', 'Recent reflections'), ('meditations', 'Recent meditations'), ('assertions', 'Identity assertions'), ('commits', 'Git commit history')], default='sensors', help_text='Which Identity layer the experiment starts from.', max_length=32)),
                ('max_depth', models.PositiveSmallIntegerField(default=7, help_text='Hard cap on recursion. Max 12.')),
                ('exit_condition', models.CharField(blank=True, help_text='If a step contains this substring, exit.', max_length=200)),
                ('trace', models.JSONField(blank=True, default=list)),
                ('conclusion', models.TextField(blank=True)),
                ('exit_reason', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending — not yet run'), ('running', 'Running'), ('completed', 'Completed'), ('exited', 'Exited via guardrail'), ('error', 'Errored')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IntrospectiveLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer', models.CharField(choices=[('brain', 'Brain (physical substrate)'), ('mind', 'Mind (functional organization)'), ('consciousness', 'Consciousness (awareness, access)'), ('self', 'Self (first-person perspective)')], db_index=True, max_length=16)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(help_text='First-person prose. Velour speaking as itself about what it is at this layer.')),
                ('source', models.CharField(choices=[('seed', 'Seeded at install'), ('operator', 'Operator-authored'), ('auto', 'Auto-derived from current state'), ('meditation', 'Emerged from a meditation')], default='seed', max_length=16)),
                ('strength', models.FloatField(default=1.0, help_text='0-1 scalar. 1.0 for load-bearing claims.')),
                ('first_asserted_at', models.DateTimeField(auto_now_add=True)),
                ('last_confirmed_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['layer', '-strength', 'title'],
                'indexes': [models.Index(fields=['layer', 'is_active'], name='hofstadter__layer_74e3d4_idx')],
            },
        ),
        migrations.CreateModel(
            name='LoopTraversal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('steps_taken', models.PositiveIntegerField(default=0)),
                ('max_depth', models.PositiveSmallIntegerField(default=7)),
                ('steps', models.JSONField(blank=True, default=list, help_text='Ordered list of {"level_name", "content", "step_number"} dicts, one per step taken.')),
                ('exit_reason', models.CharField(blank=True, choices=[('completed', 'Completed — loop closed cleanly'), ('max_depth', 'Hit max depth'), ('repeat_detected', 'Repeat detected (same step seen before)'), ('stability', 'Stability (two identical consecutive steps)'), ('exit_condition', 'Exit condition matched'), ('timeout', 'Wall-clock timeout'), ('contradiction', 'Contradiction with invariant'), ('manual_halt', 'Operator halted')], max_length=20)),
                ('exit_detail', models.TextField(blank=True, help_text='Any extra context about why the traversal stopped.')),
                ('loop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traversals', to='hofstadter.strangeloop')),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['-started_at'], name='hofstadter__started_97e5b7_idx'), models.Index(fields=['loop', '-started_at'], name='hofstadter__loop_id_6d77e2_idx')],
            },
        ),
    ]
