# Generated by Django 6.0.4 on 2026-04-12 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OracleLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lobe_name', models.CharField(db_index=True, help_text='Which lobe produced this decision, e.g. "rumination_template".', max_length=64)),
                ('happened_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('features', models.JSONField(blank=True, default=list, help_text='Feature vector the lobe saw at decision time, in the order defined by oracle/inference.py FEATURE_NAMES.')),
                ('predicted', models.CharField(help_text='Class label the lobe picked.', max_length=64)),
                ('actual', models.CharField(blank=True, help_text='Ground-truth class the operator says was correct. Empty until feedback arrives.', max_length=64)),
                ('verdict', models.CharField(blank=True, choices=[('good', 'Good — predicted the right thing'), ('bad', 'Bad — predicted the wrong thing'), ('meh', 'Neither clearly right nor wrong')], help_text='Shorthand judgment — the operator may not know which class was correct but can still flag good/bad.', max_length=8)),
                ('actual_source', models.CharField(choices=[('operator', 'Operator feedback'), ('auto', 'Auto-derived from downstream outcome'), ('synthetic', 'Synthetic bootstrap data')], default='operator', max_length=16)),
                ('linked_model', models.CharField(blank=True, help_text='App-label.Model string, e.g. "identity.Tick", if this decision was about a specific domain object.', max_length=64)),
                ('linked_pk', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-happened_at'],
                'indexes': [models.Index(fields=['lobe_name', '-happened_at'], name='oracle_orac_lobe_na_5a3b25_idx'), models.Index(fields=['lobe_name', 'verdict'], name='oracle_orac_lobe_na_297d85_idx')],
            },
        ),
    ]
