# Generated by Django 6.0.4 on 2026-04-15 10:28

import zoetrope.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('tag_filter', models.CharField(blank=True, help_text='Comma-separated tags. Blank = any image.', max_length=200)),
                ('selection_mode', models.CharField(choices=[('recent', 'Most recent'), ('oldest', 'Oldest first'), ('random', 'Random sample')], default='recent', max_length=10)),
                ('image_count', models.PositiveIntegerField(default=10, help_text='How many Attic images to pull into the reel.')),
                ('fps', models.PositiveSmallIntegerField(default=30)),
                ('duration_seconds', models.FloatField(default=6.0)),
                ('width', models.PositiveIntegerField(default=1280)),
                ('height', models.PositiveIntegerField(default=720)),
                ('output', models.FileField(blank=True, null=True, upload_to=zoetrope.models._reel_upload_path)),
                ('poster', models.ImageField(blank=True, null=True, upload_to=zoetrope.models._poster_upload_path)),
                ('status', models.CharField(choices=[('draft', 'Draft (not yet rendered)'), ('rendering', 'Rendering'), ('ready', 'Ready'), ('error', 'Error')], default='draft', max_length=10)),
                ('status_message', models.TextField(blank=True)),
                ('frames_used', models.PositiveIntegerField(default=0)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rendered_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
