# Generated by Django 6.0.4 on 2026-04-15 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoetrope', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reel',
            name='share_url',
            field=models.URLField(blank=True, help_text='Public URL on s.h4ks.com. Expires ~4 hours after upload.'),
        ),
        migrations.AddField(
            model_name='reel',
            name='shared_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
