# Generated by Django 6.0.4 on 2026-04-16 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoetrope', '0002_reel_share_url_reel_shared_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='reel',
            name='speech_sample_count',
            field=models.PositiveSmallIntegerField(default=0, help_text='Number of random Grammar Engine utterances to drop onto the soundtrack. 0 = silent.'),
        ),
        migrations.AddField(
            model_name='reel',
            name='speech_volume',
            field=models.FloatField(default=0.7, help_text='Output gain for the speech track, 0.0–1.0.'),
        ),
    ]
