# Generated by Django 6.0.4 on 2026-04-17 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoetrope', '0003_reel_speech_sample_count_reel_speech_volume'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReelTournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('fitness_mode', models.CharField(choices=[('aesthetic', 'Aesthetic (blended — density + sonority + entropy + noise)'), ('density', 'Density (frames-per-second of final cut)'), ('sonority', 'Sonority (speech samples × volume)'), ('entropy', 'Poster entropy (color richness of the first frame)')], default='aesthetic', max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('error', 'Error')], default='pending', max_length=10)),
                ('results', models.JSONField(blank=True, default=list, help_text='List of {reel_slug, reel_title, score, components} ordered best-first.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournaments_won', to='zoetrope.reel')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
