# Generated by Django 6.0.4 on 2026-04-17 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoetrope', '0004_reeltournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='reel',
            name='frame_order',
            field=models.JSONField(blank=True, default=list, help_text='Hand-picked list of attic.MediaItem PKs in playback order. When non-empty it overrides tag_filter / selection_mode / image_count during render.'),
        ),
    ]
