# Generated by Django 6.0.4 on 2026-04-13 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlantSpecies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('axiom', models.CharField(default='F', max_length=500)),
                ('rules', models.JSONField(default=list)),
                ('iterations', models.PositiveSmallIntegerField(default=4)),
                ('angle', models.FloatField(default=22.5, help_text='Branch angle in degrees')),
                ('length_factor', models.FloatField(default=0.65, help_text='Length reduction per depth')),
                ('start_length', models.FloatField(default=0.8)),
                ('trunk_taper', models.FloatField(default=0.7)),
                ('trunk_radius', models.FloatField(default=0.06)),
                ('trunk_color', models.CharField(default='#5a4020', max_length=20)),
                ('trunk_is_green', models.BooleanField(default=False)),
                ('bark_stripes', models.BooleanField(default=False)),
                ('leaf_color', models.CharField(default='#2a6818', max_length=20)),
                ('leaf_color2', models.CharField(default='#3a7828', max_length=20)),
                ('leaf_size', models.FloatField(default=0.35)),
                ('leaf_density', models.FloatField(default=0.6)),
                ('leaf_shape', models.CharField(choices=[('sphere', 'Sphere'), ('cone', 'Cone'), ('star', 'Star')], default='sphere', max_length=20)),
                ('droop', models.FloatField(default=0.0, help_text='Branch droop per depth level')),
                ('narrow', models.BooleanField(default=False, help_text='Constrain horizontal spread')),
                ('fat_trunk', models.BooleanField(default=False, help_text='Wide baobab-style trunk')),
                ('has_flowers', models.BooleanField(default=False)),
                ('flower_color', models.CharField(blank=True, default='#ff80a0', max_length=20)),
                ('flower_density', models.FloatField(default=0.15)),
                ('has_fronds', models.BooleanField(default=False, help_text='Palm-style fronds at crown')),
                ('has_coconuts', models.BooleanField(default=False)),
                ('has_culms', models.BooleanField(default=False, help_text='Bamboo-style multiple stems')),
                ('has_rosette', models.BooleanField(default=False, help_text='Succulent rosette pattern')),
                ('is_ground_cover', models.BooleanField(default=False)),
                ('category', models.CharField(choices=[('tree', 'Tree'), ('bush', 'Bush/Shrub'), ('flower', 'Flowering Plant'), ('grass', 'Grass/Fern'), ('succulent', 'Succulent/Cactus'), ('aquatic', 'Aquatic'), ('vine', 'Vine/Climber'), ('other', 'Other')], default='tree', max_length=20)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=500)),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'plant species',
                'ordering': ['name'],
            },
        ),
    ]
