# Generated by Django 6.0.4 on 2026-04-13 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lsystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantspecies',
            name='arch_style',
            field=models.CharField(blank=True, choices=[('', 'Generic'), ('medieval', 'Medieval'), ('modern', 'Modern'), ('classical', 'Classical'), ('gothic', 'Gothic'), ('industrial', 'Industrial'), ('cottage', 'Cottage'), ('tower', 'Tower')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='plantspecies',
            name='door_color',
            field=models.CharField(blank=True, default='#5a3818', max_length=20),
        ),
        migrations.AddField(
            model_name='plantspecies',
            name='floor_height',
            field=models.FloatField(default=1.2, help_text='Height per floor/segment'),
        ),
        migrations.AddField(
            model_name='plantspecies',
            name='has_balcony',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plantspecies',
            name='has_chimney',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plantspecies',
            name='has_columns',
            field=models.BooleanField(default=False, help_text='Classical columns at entrance'),
        ),
        migrations.AddField(
            model_name='plantspecies',
            name='has_windows',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='plantspecies',
            name='roof_color',
            field=models.CharField(blank=True, default='#6a3020', max_length=20),
        ),
        migrations.AddField(
            model_name='plantspecies',
            name='roof_style',
            field=models.CharField(blank=True, choices=[('flat', 'Flat'), ('gable', 'Gable'), ('hip', 'Hip'), ('dome', 'Dome'), ('spire', 'Spire'), ('none', 'None')], default='gable', max_length=20),
        ),
        migrations.AddField(
            model_name='plantspecies',
            name='wall_color',
            field=models.CharField(blank=True, default='#a08870', max_length=20),
        ),
        migrations.AddField(
            model_name='plantspecies',
            name='wall_color2',
            field=models.CharField(blank=True, default='#8a7860', help_text='Secondary wall / accent color', max_length=20),
        ),
        migrations.AddField(
            model_name='plantspecies',
            name='wall_width',
            field=models.FloatField(default=1.0, help_text='Wall segment width'),
        ),
        migrations.AddField(
            model_name='plantspecies',
            name='window_color',
            field=models.CharField(blank=True, default='#ffe880', max_length=20),
        ),
        migrations.AddField(
            model_name='plantspecies',
            name='window_density',
            field=models.FloatField(default=0.6, help_text='Proportion of wall faces with windows'),
        ),
        migrations.AlterField(
            model_name='plantspecies',
            name='category',
            field=models.CharField(choices=[('tree', 'Tree'), ('bush', 'Bush/Shrub'), ('flower', 'Flowering Plant'), ('grass', 'Grass/Fern'), ('succulent', 'Succulent/Cactus'), ('aquatic', 'Aquatic'), ('vine', 'Vine/Climber'), ('building', 'Building'), ('tower', 'Tower'), ('bridge', 'Bridge'), ('wall', 'Wall/Fence'), ('other', 'Other')], default='tree', max_length=20),
        ),
    ]
