# Generated by Django 6.0.4 on 2026-04-16 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=120)),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('body_md', models.TextField(blank=True)),
                ('weight_bits', models.PositiveIntegerField(help_text="Number of bits in a single model's weight bitstring.")),
                ('target_family', models.CharField(max_length=120)),
                ('search_method', models.CharField(max_length=80)),
                ('c_source_filename', models.CharField(help_text='Filename under static/casting/sources/ (e.g. byte_model.c).', max_length=80)),
                ('js_module_name', models.CharField(blank=True, help_text='Basename under static/casting/js/ without .js, or blank if C-only.', max_length=80)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
