# Generated by Django 6.0.4 on 2026-04-15 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('seed', models.BigIntegerField(help_text='Deterministic generation seed. Same seed → same language.')),
                ('spec', models.JSONField(blank=True, default=dict, help_text='Frozen language contents: particles, subwords, words, grammars, corpora. Generated from seed on save if empty.')),
                ('notes', models.TextField(blank=True, help_text='Free-form description — speaker demographics, in-world context, audio character notes.')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-modified'],
            },
        ),
    ]
