# Generated by Django 6.0.4 on 2026-04-15 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grammar_engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='last_used',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='language',
            name='use_count',
            field=models.BigIntegerField(default=0, help_text='Incremented every time this language is fetched — Bridge playback, Aether worlds, Evolution imports.'),
        ),
    ]
