# Generated by Django 6.0.4 on 2026-04-20 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Oneliner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('purpose', models.TextField(blank=True, help_text='One-sentence description of what the program does and the trick that makes it fit in 80 cols.')),
                ('code', models.TextField(help_text='The C source. Every line (after rstrip) must be ≤ 80 characters. Trailing blank lines are allowed but ignored for the count.')),
                ('compile_flags', models.CharField(default='-w', help_text='Extra cc flags. `-w` suppresses warnings (most of these programs are deliberately K&R-style and compile with a dozen warnings under -Wall).', max_length=200)),
                ('stdin_fixture', models.TextField(blank=True, help_text='Optional canonical stdin to feed to run(). Stored so the detail page can replay the demo without the operator remembering the input.')),
                ('last_status', models.CharField(choices=[('unknown', 'Not yet compiled'), ('ok', 'Compiled cleanly'), ('warn', 'Compiled with warnings'), ('error', 'Compile failed')], default='unknown', max_length=10)),
                ('last_compile_output', models.TextField(blank=True)),
                ('last_binary_size', models.PositiveIntegerField(blank=True, null=True)),
                ('last_run_stdout', models.TextField(blank=True)),
                ('last_run_exit', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
