# Generated by Django 6.0.4 on 2026-04-21 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneliner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oneliner',
            name='language',
            field=models.CharField(choices=[('c', 'C'), ('bash', 'Bash')], default='c', help_text='"c" compiles with cc and runs the binary; "bash" interprets directly via `bash -c`.', max_length=4),
        ),
        migrations.AlterField(
            model_name='oneliner',
            name='compile_flags',
            field=models.CharField(blank=True, default='-w', help_text='For C: extra cc flags. `-w` suppresses warnings (K&R-style classics trigger many -Wall warnings). For bash: extra flags passed before `-c` (e.g. `-u` for undefined-variable checking).', max_length=200),
        ),
    ]
