"""Inventory every project app's view-level auth decorators.

Generates a structured table of which views have which gates
(`@login_required`, `@staff_member_required`, `user_passes_test`,
`@permission_required`, or none). Drives multi-user policy decisions:
which views to escalate to STAFF, which to keep LOGIN, which to gate
behind real Django permissions.

Usage:
  manage.py audit_view_decorators           # print to stdout
  manage.py audit_view_decorators --update  # rewrite docs/view-decorator-audit.md

The OPEN-views section flags everything anyone-on-the-internet can hit,
which is the most important pre-public-deploy review item.
"""

import re
import sys
from pathlib import Path

from django.conf import settings
from django.core.management.base import BaseCommand


_DEF_RE = re.compile(
    r'((?:^@\w+(?:\([^)]*\))?\s*\n)*)'
    r'^def (\w+)\s*\(',
    re.MULTILINE,
)
_DECO_RE = re.compile(r'^@(\w+)', re.MULTILINE)


def _classify(decos):
    if 'staff_member_required' in decos:
        return 'STAFF'
    if 'user_passes_test' in decos:
        return 'STAFF_OR_SUPER'
    if 'permission_required' in decos:
        return 'PERM'
    if 'login_required' in decos:
        return 'LOGIN'
    return 'OPEN'


def scan_views():
    """Return ``{app_slug: [(view_name, category, [decos])]}`` for every
    project app that has a views.py."""
    from app_factory.app_registry import CORE_APPS, OPTIONAL_BY_SLUG
    apps = sorted(set(CORE_APPS) | set(OPTIONAL_BY_SLUG))
    base = Path(settings.BASE_DIR)
    out = {}
    for app in apps:
        views_py = base / app / 'views.py'
        if not views_py.is_file():
            continue
        text = views_py.read_text()
        views = []
        for m in _DEF_RE.finditer(text):
            deco_block, name = m.group(1), m.group(2)
            if name.startswith('_'):
                continue
            decos = _DECO_RE.findall(deco_block)
            views.append((name, _classify(decos), decos))
        if views:
            out[app] = views
    return out


def render_markdown(detail):
    totals = {'OPEN': 0, 'LOGIN': 0, 'STAFF': 0, 'STAFF_OR_SUPER': 0, 'PERM': 0}
    for views in detail.values():
        for _, cat, _ in views:
            totals[cat] += 1

    L = []
    L.append('# Velour view-decorator audit')
    L.append('')
    L.append('Generated by `manage.py audit_view_decorators` — re-run after')
    L.append('any decorator change to keep this current.')
    L.append('')
    L.append('## Why this exists')
    L.append('')
    L.append('Velour is moving toward a multi-user model with admin users + many')
    L.append("limited-access users. Today's auth model is essentially binary:")
    L.append('a view is either open or `@login_required`. There are exactly')
    L.append('**two** finer-grained gates in the entire codebase (one staff,')
    L.append("one superuser), and **zero** uses of Django's permission system.")
    L.append('This report is the inventory you need to make policy decisions:')
    L.append('which views should stay LOGIN, which should escalate to STAFF or')
    L.append('SUPER, and which need real Django permissions.')
    L.append('')
    L.append('## Summary')
    L.append('')
    L.append('| Gate | Count | Meaning |')
    L.append('|---|---:|---|')
    L.append(f'| OPEN | {totals["OPEN"]} | No auth required at all |')
    L.append(f'| LOGIN | {totals["LOGIN"]} | Any authenticated user |')
    L.append(f'| STAFF | {totals["STAFF"]} | `@staff_member_required` |')
    L.append(f'| SUPER | {totals["STAFF_OR_SUPER"]} | `user_passes_test` checking `is_superuser` |')
    L.append(f'| PERM | {totals["PERM"]} | `@permission_required` (Django perms) |')
    L.append(f'| **Total** | **{sum(totals.values())}** | across {len(detail)} apps |')
    L.append('')
    L.append('## Open views (no auth required)')
    L.append('')
    L.append('These are the views that anyone — logged in or not — can hit.')
    L.append('Some are intentional (public CMS frontends, ESP API endpoints with')
    L.append('token auth, the landing page). Some may be accidental and should')
    L.append('be reviewed before any public-IP deploy.')
    L.append('')
    L.append('| App | View | Notes / decorators |')
    L.append('|---|---|---|')
    for app in sorted(detail):
        for name, cat, decos in sorted(detail[app]):
            if cat == 'OPEN':
                deco_str = ', '.join(f'`@{d}`' for d in decos) if decos else '_(none)_'
                L.append(f'| `{app}` | `{name}` | {deco_str} |')
    L.append('')
    L.append('## Per-app breakdown')
    L.append('')
    L.append('| App | OPEN | LOGIN | STAFF | SUPER | total |')
    L.append('|---|---:|---:|---:|---:|---:|')
    for app in sorted(detail):
        c = {'OPEN': 0, 'LOGIN': 0, 'STAFF': 0, 'STAFF_OR_SUPER': 0, 'PERM': 0}
        for _, cat, _ in detail[app]:
            c[cat] += 1
        if any(c.values()):
            L.append(
                f'| `{app}` | {c["OPEN"]} | {c["LOGIN"]} | '
                f'{c["STAFF"]} | {c["STAFF_OR_SUPER"]} | '
                f'{sum(c.values())} |'
            )
    L.append('')
    L.append('## Recommendations for the multi-user transition')
    L.append('')
    L.append('1. **Audit the OPEN views first.** Some are intentional (displacer,')
    L.append('   landingpage, ESP API endpoints with token auth). Anything in the')
    L.append('   table above that does NOT match a deliberate "should be public"')
    L.append('   intent should be tightened to `@login_required` or stricter.')
    L.append('')
    L.append('2. **Tier the LOGIN views by sensitivity.** 565 views all gated only')
    L.append('   by `is_authenticated` is too coarse for a multi-user deploy.')
    L.append('   Suggested tiers:')
    L.append('   - **System admin (SUPER):** terminal (already done), services,')
    L.append('     security, maintenance, sysinfo, logs, hosts, app_factory,')
    L.append('     databases, winctl, backups')
    L.append('   - **Content editor (STAFF or PERM):** codex, displacer, attic,')
    L.append('     identity (the editorial side), chronos task management')
    L.append('   - **Per-app member (PERM):** most creative apps — give a user')
    L.append('     permission to access aether OR naiad OR studious individually')
    L.append('     so a "limited user" only sees what they have access to')
    L.append('   - **Read-only viewers:** dashboards, briefings, public manuals')
    L.append('')
    L.append('3. **Add MFA before any public-IP deploy.** Tiered permissions')
    L.append('   plus weak password authentication is still weak. The `django-')
    L.append('   two-factor-auth` package is the standard answer.')
    L.append('')
    L.append('4. **Add login-attempt lockout.** `django-axes`. ~30 min to wire.')
    L.append('')
    L.append('## How to keep this current')
    L.append('')
    L.append('```')
    L.append('venv/bin/python manage.py audit_view_decorators --update')
    L.append('```')
    L.append('')
    L.append('Without `--update`, prints the report to stdout for inspection.')
    L.append('With `--update`, rewrites this file in place.')
    L.append('')
    return '\n'.join(L)


class Command(BaseCommand):
    help = 'Audit view-level auth decorators across all project apps.'

    def add_arguments(self, parser):
        parser.add_argument(
            '--update', action='store_true',
            help='Rewrite docs/view-decorator-audit.md in place instead of '
                 'printing to stdout.',
        )

    def handle(self, *args, **opts):
        detail = scan_views()
        md = render_markdown(detail)
        if opts['update']:
            target = Path(settings.BASE_DIR) / 'docs' / 'view-decorator-audit.md'
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(md)
            self.stdout.write(self.style.SUCCESS(
                f'Wrote {target} ({target.stat().st_size} bytes)'
            ))
        else:
            sys.stdout.write(md)
