# Generated by Django 6.0.4 on 2026-04-15 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lsystem', '0002_plantspecies_arch_style_plantspecies_door_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('level', models.PositiveSmallIntegerField(choices=[(0, 'L0 — worker'), (1, 'L1 — meta'), (2, 'L2 — meta-meta')], default=0)),
                ('gene', models.JSONField(default=dict, help_text='L0: {axiom, rules, iterations}. L1/L2: inner-pop params.')),
                ('seed_string', models.CharField(blank=True, help_text='Starting string fed to work() before iterations.', max_length=500)),
                ('script', models.TextField(blank=True, help_text='Optional user-defined JS body — runs in addition to the L-system work step. Receives (agent, ctx) and may return a partial-score contribution.')),
                ('score', models.FloatField(default=0.0, help_text='Best score observed at the moment of saving.')),
                ('notes', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='descendants', to='evolution.agent')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='EvolutionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('level', models.PositiveSmallIntegerField(choices=[(0, 'L0 — worker'), (1, 'L1 — meta'), (2, 'L2 — meta-meta')], default=0)),
                ('goal_string', models.TextField(blank=True, help_text='The string the population is evolving toward. Pasted literal or expanded from `goal_species` at run creation.')),
                ('population_size', models.PositiveSmallIntegerField(default=24)),
                ('generations_target', models.PositiveIntegerField(default=200)),
                ('target_score', models.FloatField(default=0.95, help_text='Stop early once any agent meets this score (0..1).')),
                ('params', models.JSONField(blank=True, default=dict, help_text='Free-form: mutation_rate, inner_size, inner_generations, script (user-defined work hook), seed_string, etc.')),
                ('status', models.CharField(choices=[('idle', 'idle'), ('running', 'running'), ('paused', 'paused'), ('finished', 'finished')], default='idle', max_length=12)),
                ('generation', models.PositiveIntegerField(default=0)),
                ('best_score', models.FloatField(default=0.0)),
                ('notes', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('goal_species', models.ForeignKey(blank=True, help_text='If set, goal_string was expanded from this species.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evolution_runs', to='lsystem.plantspecies')),
                ('seed_agent', models.ForeignKey(blank=True, help_text='Optional saved Agent used as the founding parent.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs_seeded', to='evolution.agent')),
            ],
            options={
                'ordering': ['-modified'],
            },
        ),
        migrations.AddField(
            model_name='agent',
            name='source_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saved_agents', to='evolution.evolutionrun'),
        ),
    ]
