# Generated by Django 6.0.4 on 2026-04-15 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evolution', '0001_initial'),
        ('grammar_engine', '0002_language_last_used_language_use_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='evolutionrun',
            name='goal_language',
            field=models.ForeignKey(blank=True, help_text='If set, goal_string was expanded from a variant of this Grammar Engine language.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evolution_runs', to='grammar_engine.language'),
        ),
        migrations.AddField(
            model_name='evolutionrun',
            name='goal_variant',
            field=models.CharField(blank=True, help_text='"<category>/<variant>" — identifies which variant of goal_language was expanded.', max_length=160),
        ),
    ]
