# Generated by Django 6.0.4 on 2026-04-11 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClockPrefs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_tz', models.CharField(default='Europe/Amsterdam', help_text='IANA timezone name for the local clock shown in the topbar.', max_length=64)),
                ('format_24h', models.BooleanField(default=True, help_text='If True, display times as 14:32:09. If False, 2:32:09 pm.')),
                ('auto_sync_seconds', models.PositiveIntegerField(default=600, help_text='How often the in-page JS clock re-syncs against the server (seconds). Set to 0 to disable auto-sync — manual only.')),
                ('show_seconds', models.BooleanField(default=True, help_text='If True, the topbar clock ticks at 1Hz showing seconds.')),
            ],
            options={
                'verbose_name': 'Clock preferences',
                'verbose_name_plural': 'Clock preferences',
            },
        ),
        migrations.CreateModel(
            name='WatchedTimezone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Display name, e.g. "NYC", "Denver", "Tokyo office".', max_length=80)),
                ('tz_name', models.CharField(help_text='IANA timezone, e.g. "America/New_York", "Asia/Tokyo".', max_length=64)),
                ('sort_order', models.IntegerField(default=0, help_text='Lower values shown first. Ties broken by label.')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sort_order', 'label'],
            },
        ),
    ]
