# Generated by Django 6.0.4 on 2026-04-11 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chronos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchedtimezone',
            name='color',
            field=models.CharField(blank=True, help_text='Optional hex color (e.g. "#B7410E") applied to the label and time on the world-clocks page. Cities of special interest to the project get unique colors; leave blank for the default neutral grey.', max_length=9),
        ),
    ]
