# Generated by Django 6.0.4 on 2026-04-11 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chronos', '0002_watchedtimezone_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220)),
                ('notes', models.TextField(blank=True)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('all_day', models.BooleanField(default=False, help_text='If True, the event spans the whole day(s) regardless of the start/end times.')),
                ('color', models.CharField(blank=True, help_text='Optional hex color (e.g. "#58A6FF") used to tint the event in the month grid.', max_length=9)),
                ('tags', models.CharField(blank=True, help_text='Free-form comma-separated tags.', max_length=200)),
                ('source', models.CharField(choices=[('user', 'User-scheduled'), ('holiday', 'Holiday (auto)'), ('astro', 'Astronomical (auto)'), ('feed', 'External feed')], default='user', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['start', 'pk'],
                'indexes': [models.Index(fields=['start'], name='chronos_cal_start_11a1af_idx'), models.Index(fields=['source', 'start'], name='chronos_cal_source_de7506_idx')],
            },
        ),
    ]
