# Generated by Django 6.0.4 on 2026-04-11 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chronos', '0003_calendarevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tradition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('color', models.CharField(blank=True, help_text='Hex color used to tint holidays from this tradition.', max_length=9)),
                ('enabled', models.BooleanField(default=True, help_text='If unchecked, holidays from this tradition are hidden from calendar views (rows are kept in the database).')),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='clockprefs',
            name='country',
            field=models.CharField(default='NL', help_text='ISO-3166-1 alpha-2 country code, used by the civic holiday adapter to pick which national calendar to pull. NL = Netherlands.', max_length=2),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='tradition',
            field=models.ForeignKey(blank=True, help_text='If this event came from a holiday tradition, link to the Tradition for color + toggleability. Null for user-created events.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='chronos.tradition'),
        ),
    ]
