# Generated by Django 6.0.4 on 2026-04-16 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chronos', '0004_tradition_clockprefs_country_calendarevent_tradition'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('source_app', models.CharField(blank=True, help_text='Free-text app/tag this task belongs to (e.g. "displacement", "aether"). Optional.', max_length=40)),
                ('source_url', models.URLField(blank=True, help_text='Jump-back URL — the page or admin row this task is about. Optional.', max_length=400)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High')], default='normal', max_length=8)),
                ('status', models.CharField(choices=[('open', 'Open'), ('done', 'Done'), ('dropped', 'Dropped')], db_index=True, default='open', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': [models.OrderBy(models.F('due_at'), nulls_last=True), 'priority', '-created_at'],
                'indexes': [models.Index(fields=['status', 'due_at'], name='chronos_tas_status_583500_idx')],
            },
        ),
    ]
