# Generated by Django 6.0.4 on 2026-04-27 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chronos', '0005_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='clockprefs',
            name='home_elev_m',
            field=models.FloatField(default=0.0, help_text='Observer elevation in metres above sea level. Affects horizon for satellite passes; safe to leave at 0.'),
        ),
        migrations.AddField(
            model_name='clockprefs',
            name='home_lat',
            field=models.FloatField(default=52.16, help_text='Observer latitude in degrees, +N. Used by sky views (satellite passes, asteroid alt/az). Default = Leiden.'),
        ),
        migrations.AddField(
            model_name='clockprefs',
            name='home_lon',
            field=models.FloatField(default=4.49, help_text='Observer longitude in degrees, +E. Used by sky views.'),
        ),
        migrations.CreateModel(
            name='TrackedObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('satellite', 'Artificial satellite'), ('asteroid', 'Asteroid'), ('comet', 'Comet'), ('debris', 'Debris')], db_index=True, max_length=16)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('designation', models.CharField(blank=True, help_text='Catalog ID — NORAD CATNR for satellites (e.g. "25544"), provisional designation for asteroids (e.g. "2024 XY12").', max_length=80)),
                ('elements_json', models.JSONField(blank=True, default=dict, help_text='TLE lines for satellites: {"line1": "...", "line2": "..."}. Keplerian elements for asteroids/comets.')),
                ('elements_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('source_url', models.URLField(blank=True, max_length=400)),
                ('notes', models.TextField(blank=True)),
                ('is_watched', models.BooleanField(default=True, help_text='If True, refresh_* commands keep this object current and emit predicted passes / close-approaches into the calendar.')),
                ('magnitude', models.FloatField(blank=True, help_text='Rough visual magnitude. Lower = brighter. ISS ~ -3, Hubble ~ +2, faint NEOs > +20.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['kind', 'name'],
                'indexes': [models.Index(fields=['kind', 'is_watched'], name='chronos_tra_kind_138d7e_idx')],
            },
        ),
    ]
