# Generated by Django 6.0.4 on 2026-04-27 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chronos', '0006_clockprefs_home_elev_m_clockprefs_home_lat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(db_index=True, max_length=40)),
                ('metric', models.CharField(db_index=True, max_length=40)),
                ('value', models.FloatField()),
                ('unit', models.CharField(blank=True, max_length=24)),
                ('at', models.DateTimeField(db_index=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-at'],
                'indexes': [models.Index(fields=['source', 'metric', 'at'], name='chronos_mea_source_fe0ab5_idx'), models.Index(fields=['metric', '-at'], name='chronos_mea_metric_a7a23c_idx')],
                'constraints': [models.UniqueConstraint(fields=('source', 'metric', 'at'), name='measurement_unique_source_metric_at')],
            },
        ),
    ]
