# Generated by Django 6.0.4 on 2026-04-27 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chronos', '0007_measurement'),
    ]

    operations = [
        migrations.AddField(
            model_name='clockprefs',
            name='coast_label',
            field=models.CharField(default='Katwijk aan Zee', help_text='Human label for the coastal point on the dashboard.', max_length=80),
        ),
        migrations.AddField(
            model_name='clockprefs',
            name='coast_lat',
            field=models.FloatField(default=52.2, help_text='Latitude of the nearest coastal point (degrees, +N). Used for the /chronos/coast/ marine dashboard. Default = Katwijk aan Zee (10 km west of Leiden).'),
        ),
        migrations.AddField(
            model_name='clockprefs',
            name='coast_lon',
            field=models.FloatField(default=4.4, help_text='Longitude of the nearest coastal point (degrees, +E).'),
        ),
    ]
