# Generated by Django 6.0.4 on 2026-05-20 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StackGenome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('n_boards', models.PositiveIntegerField(default=16)),
                ('board_side', models.PositiveIntegerField(default=64)),
                ('gene_json', models.JSONField(default=dict)),
                ('fitness', models.FloatField(default=0.0)),
                ('test_set_id', models.CharField(blank=True, help_text='label of the (p,q) test set this was scored against', max_length=80)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-fitness', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='EvolutionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('config_json', models.JSONField(default=dict)),
                ('n_generations', models.PositiveIntegerField(default=0)),
                ('n_evals', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('best_genome', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='best_of_runs', to='boardstack.stackgenome')),
            ],
            options={
                'ordering': ('-started_at',),
            },
        ),
    ]
