# Generated by Django 6.0.4 on 2026-04-19 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FurniturePiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('desk', 'Desk / workbench'), ('chair', 'Chair'), ('shelf', 'Shelf / bookshelf'), ('cabinet', 'Cabinet'), ('rack', 'Server / equipment rack'), ('aquarium', 'Aquarium / tank'), ('lightbox', 'Grow light / lightbox'), ('breadboard', 'Breadboard station'), ('storage', 'Storage tote / bin'), ('other', 'Other')], default='other', max_length=16)),
                ('width_cm', models.PositiveIntegerField()),
                ('depth_cm', models.PositiveIntegerField()),
                ('height_cm', models.PositiveIntegerField(default=0)),
                ('heat_watts', models.PositiveIntegerField(default=0, help_text='Approx heat output in watts (for fire-safety spacing).')),
                ('needs_outlet', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['kind', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=120)),
                ('width_cm', models.PositiveIntegerField(help_text='X-axis extent in cm.')),
                ('length_cm', models.PositiveIntegerField(help_text='Y-axis extent in cm.')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=120)),
                ('x_cm', models.PositiveIntegerField()),
                ('y_cm', models.PositiveIntegerField()),
                ('rotation_deg', models.PositiveSmallIntegerField(default=0, help_text='0 / 90 / 180 / 270')),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='placements', to='roomplanner.furniturepiece')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='roomplanner.room')),
            ],
            options={
                'ordering': ['room', 'label'],
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('door', 'Door'), ('window', 'Window'), ('outlet', 'Power outlet'), ('vent', 'Vent'), ('radiator', 'Radiator'), ('pillar', 'Pillar / column'), ('sink', 'Sink'), ('ethernet', 'Ethernet port'), ('other', 'Other')], max_length=16)),
                ('label', models.CharField(blank=True, max_length=80)),
                ('x_cm', models.PositiveIntegerField()),
                ('y_cm', models.PositiveIntegerField()),
                ('width_cm', models.PositiveIntegerField()),
                ('depth_cm', models.PositiveIntegerField()),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='roomplanner.room')),
            ],
            options={
                'ordering': ['kind', 'label'],
            },
        ),
        migrations.CreateModel(
            name='Constraint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('egress', 'Egress clearance'), ('heat_spacing', 'Heat-source spacing'), ('outlet_near', 'Must be near outlet'), ('walkway', 'Walkway minimum width'), ('wall_clearance', 'Wall clearance'), ('other', 'Other')], max_length=20)),
                ('description', models.CharField(max_length=240)),
                ('value_json', models.JSONField(blank=True, default=dict, help_text='e.g. {"min_cm": 90} for a walkway rule.')),
                ('active', models.BooleanField(default=True)),
                ('room', models.ForeignKey(blank=True, help_text='Leave blank for constraints that apply to all rooms.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='constraints', to='roomplanner.room')),
            ],
            options={
                'ordering': ['kind'],
            },
        ),
    ]
