# Generated by Django 6.0.4 on 2026-04-19 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomplanner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='location_city',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='room',
            name='location_detected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='north_direction',
            field=models.CharField(choices=[('up', 'north is up (top of screen)'), ('right', 'north is right'), ('down', 'north is down (bottom of screen)'), ('left', 'north is left')], default='up', help_text='Which edge of the SVG points to real-world north.', max_length=8),
        ),
    ]
