# Generated by Django 6.0.4 on 2026-04-19 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomplanner', '0002_room_latitude_room_location_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Layout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('snapshot', models.JSONField(default=list, help_text='List of {placement_id, x_cm, y_cm, rotation_deg} recorded at save time.')),
                ('is_auto', models.BooleanField(default=False, help_text='True for auto-snapshots taken before destructive ops.')),
                ('score_total', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layouts', to='roomplanner.room')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
