# Generated by Django 6.0.4 on 2026-04-19 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomplanner', '0003_layout'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=120)),
                ('address', models.CharField(blank=True, max_length=240)),
                ('notes', models.TextField(blank=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(help_text='Storey number: 0 = ground, 1 = first, -1 = basement.')),
                ('name', models.CharField(blank=True, help_text="Optional human name, e.g. 'Attic', 'Ground floor'.", max_length=80)),
                ('notes', models.TextField(blank=True)),
                ('height_cm', models.PositiveIntegerField(default=280)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='roomplanner.building')),
            ],
            options={
                'ordering': ['building', '-level'],
                'unique_together': {('building', 'level')},
            },
        ),
        migrations.AddField(
            model_name='room',
            name='floor',
            field=models.ForeignKey(blank=True, help_text='Which storey this room sits on. Optional for rooms imported before multi-floor support landed.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='roomplanner.floor'),
        ),
    ]
