# Generated by Django 6.0.4 on 2026-04-20 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomplanner', '0005_default_building_floor'),
    ]

    operations = [
        migrations.AddField(
            model_name='furniturepiece',
            name='geometry',
            field=models.JSONField(blank=True, default=dict, help_text='Optional real-geometry payload. Empty = plain box. See FurniturePiece docstring for the accepted shapes.'),
        ),
    ]
