# Generated by Django 6.0.4 on 2026-04-20 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomplanner', '0006_furniturepiece_geometry'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='polygon_cm',
            field=models.JSONField(blank=True, default=list, help_text='Optional closed polygon of [x_cm, y_cm] vertices. Empty = rectangular. Coords in SVG convention, (0,0) top-left, bounded by width_cm × length_cm.'),
        ),
    ]
