# Generated by Django 6.0.4 on 2026-04-11 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('format', models.CharField(choices=[('quickstart', 'Quickstart (1 page, diagrams welcome)'), ('short', 'Short (10–15 pages)'), ('complete', 'Complete (full manual, ~256 pages)')], default='short', max_length=16)),
                ('author', models.CharField(default='Velour', max_length=200)),
                ('version', models.CharField(blank=True, default='0.1', max_length=32)),
                ('abstract', models.TextField(blank=True, help_text='Optional. Renders below the title on the cover page.')),
                ('double_spaced', models.BooleanField(default=False, help_text="Off by default — Tufte's preferred ~1.27 leading is more readable in long form. Turn on for manuscript-style output.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_built_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220)),
                ('body', models.TextField(blank=True, help_text='Markdown. Headings (# ## ###), paragraphs, "- " bullets, **bold**, *italic*.')),
                ('sidenotes', models.TextField(blank=True, help_text='One per line. Rendered in the right margin alongside this section.')),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='codex.manual')),
            ],
            options={
                'ordering': ['sort_order', 'pk'],
                'constraints': [models.UniqueConstraint(fields=('manual', 'slug'), name='codex_unique_section_slug_per_manual')],
            },
        ),
    ]
