# Generated by Django 6.0.4 on 2026-04-11 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Figure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Stable identifier referenced from section bodies as `!fig:<slug>`.', max_length=120)),
                ('kind', models.CharField(choices=[('image', 'Uploaded image (PNG/JPG/SVG)'), ('mermaid', 'Mermaid diagram (rendered via Kroki)')], default='image', max_length=16)),
                ('image', models.FileField(blank=True, upload_to='codex/figures/')),
                ('source', models.TextField(blank=True, help_text='For Mermaid figures: the diagram source. Re-rendered whenever this text changes.')),
                ('source_hash', models.CharField(blank=True, max_length=64)),
                ('caption', models.TextField(blank=True, help_text='Hangs in the right margin alongside the figure.')),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='figures', to='codex.section')),
            ],
            options={
                'ordering': ['sort_order', 'pk'],
                'constraints': [models.UniqueConstraint(fields=('section', 'slug'), name='codex_unique_figure_slug_per_section')],
            },
        ),
    ]
