# Generated by Django 6.0.4 on 2026-04-11 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0002_figure'),
    ]

    operations = [
        migrations.AddField(
            model_name='figure',
            name='caption_position',
            field=models.CharField(choices=[('margin', 'In the right margin (Tufte default)'), ('below', 'Underneath the figure (academic style)')], default='margin', help_text='Margin = the Tufte default (caption hangs in the right sidenote area). Below = academic style with a "Figure N: …" caption underneath the image.', max_length=8),
        ),
        migrations.AlterField(
            model_name='figure',
            name='caption',
            field=models.TextField(blank=True, help_text='Caption text. Where it appears is controlled by caption_position.'),
        ),
    ]
