# Generated by Django 6.0.4 on 2026-04-11 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0003_figure_caption_position_alter_figure_caption'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('contributors', models.CharField(help_text='Comma-separated list of contributor slugs (matching modules in codex/contributions/), in the order they should appear in the report.', max_length=500)),
                ('period_days', models.IntegerField(default=7, help_text='How many days back the report covers.')),
                ('enabled', models.BooleanField(default=True)),
                ('output_manual_slug', models.SlugField(blank=True, help_text='Slug of the Manual produced by build_report. Auto-derived from the recipe slug if blank.', max_length=160)),
                ('last_built_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
