# Generated by Django 6.0.4 on 2026-04-18 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0004_reportrecipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='figure',
            name='kind',
            field=models.CharField(choices=[('image', 'Uploaded image (PNG/JPG/SVG)'), ('mermaid', 'Mermaid — flowcharts / sequences / state'), ('graphviz', 'Graphviz (DOT) — directed graphs, wiring'), ('plantuml', 'PlantUML — UML, sequence, architecture'), ('d2', 'D2 — modern architecture diagrams'), ('blockdiag', 'BlockDiag — block topology'), ('nwdiag', 'NwDiag — network topology'), ('packetdiag', 'PacketDiag — wire packet layout'), ('rackdiag', 'RackDiag — server rack elevation'), ('erd', 'ERD — entity-relationship'), ('ditaa', 'Ditaa — ASCII art → polished'), ('svgbob', 'SvgBob — ASCII art → SVG'), ('wireviz', 'WireViz — cable harnesses'), ('bytefield', 'Bytefield — byte / register layout'), ('wavedrom', 'WaveDrom — timing diagrams'), ('excalidraw', 'Excalidraw — hand-drawn style'), ('nomnoml', 'Nomnoml — simple UML sketches'), ('pikchr', 'Pikchr — compact diagrams'), ('vegalite', 'Vega-Lite — data charts'), ('bpmn', 'BPMN — business process'), ('tikz', 'TikZ — LaTeX diagrams')], default='image', max_length=16),
        ),
    ]
