# Generated by Django 6.0.4 on 2026-04-18 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0005_alter_figure_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='manual',
            name='bibliography',
            field=models.TextField(blank=True, help_text='BibTeX source. Cite entries from section bodies with `[@key]` or `[@key, p. 42]`. Cited entries render in a References section at the end of the PDF.'),
        ),
    ]
