# Generated by Django 6.0.4 on 2026-04-18 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0006_manual_bibliography'),
    ]

    operations = [
        migrations.AddField(
            model_name='manual',
            name='copyright_holder',
            field=models.CharField(blank=True, help_text="Defaults to the manual's author if blank at render time.", max_length=200),
        ),
        migrations.AddField(
            model_name='manual',
            name='copyright_year',
            field=models.CharField(blank=True, help_text='Free text — typically a year or range like "2020–2026".', max_length=16),
        ),
        migrations.AddField(
            model_name='manual',
            name='doi',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='manual',
            name='edition',
            field=models.CharField(blank=True, help_text='e.g. "First edition" or "Second revised edition".', max_length=80),
        ),
        migrations.AddField(
            model_name='manual',
            name='isbn',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='manual',
            name='license',
            field=models.CharField(blank=True, help_text='e.g. "All rights reserved." or "CC BY-SA 4.0".', max_length=200),
        ),
        migrations.AddField(
            model_name='manual',
            name='publication_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manual',
            name='publisher',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='manual',
            name='publisher_city',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
