# Generated by Django 6.0.4 on 2026-04-18 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0007_editions_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('author', models.CharField(default='Velour', max_length=200)),
                ('version', models.CharField(blank=True, default='0.1', max_length=32)),
                ('abstract', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_built_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='VolumeManual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(default=0)),
                ('manual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codex.manual')),
                ('volume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='codex.volume')),
            ],
            options={
                'ordering': ['sort_order', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='volume',
            name='manuals',
            field=models.ManyToManyField(related_name='volumes', through='codex.VolumeManual', to='codex.manual'),
        ),
        migrations.AddConstraint(
            model_name='volumemanual',
            constraint=models.UniqueConstraint(fields=('volume', 'manual'), name='codex_unique_manual_per_volume'),
        ),
    ]
