# Generated by Django 6.0.4 on 2026-05-16 00:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('shape', models.CharField(choices=[('hex', 'hex (K=4 pointy-top)'), ('square', 'square (Wolfram-style)')], default='hex', max_length=8)),
                ('grid_w', models.PositiveSmallIntegerField(default=64)),
                ('grid_h', models.PositiveSmallIntegerField(default=64)),
                ('n_colors', models.PositiveSmallIntegerField(default=4)),
                ('n_frames', models.PositiveSmallIntegerField(default=60)),
                ('rule_genome', models.BinaryField()),
                ('seed', models.PositiveIntegerField(default=3735928559)),
                ('palette_rgb', models.BinaryField(default=b'\x00\x00\x00f\xccf\xccff\xee\xee\xcc')),
                ('source_app', models.CharField(blank=True, max_length=24)),
                ('source_ref', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fitness', models.FloatField()),
                ('metric_name', models.CharField(default='consistency', max_length=40)),
                ('metric_meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='caframe.sequence')),
            ],
            options={
                'ordering': ('-fitness', '-created_at'),
            },
        ),
    ]
