# Generated by Django 6.0.4 on 2026-05-17 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caframe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequence',
            name='grid_h',
            field=models.PositiveSmallIntegerField(default=128),
        ),
        migrations.AlterField(
            model_name='sequence',
            name='grid_w',
            field=models.PositiveSmallIntegerField(default=128),
        ),
    ]
