# Generated by Django 6.0.4 on 2026-04-19 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('endonym', models.CharField(blank=True, help_text='How speakers write the name in the language itself.', max_length=80)),
                ('script', models.CharField(choices=[('latin', 'Latin'), ('cyrillic', 'Cyrillic'), ('greek', 'Greek'), ('hebrew', 'Hebrew'), ('arabic', 'Arabic'), ('devanagari', 'Devanagari'), ('han', 'Han'), ('hiragana', 'Hiragana + kanji'), ('hangul', 'Hangul'), ('other', 'Other')], default='latin', max_length=16)),
                ('rtl', models.BooleanField(default=False)),
                ('low_resource', models.BooleanField(default=False, help_text='Translation quality may be uneven; LLM backend recommended.')),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TranslationCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_hash', models.CharField(db_index=True, max_length=40)),
                ('source_text', models.TextField()),
                ('source_lang', models.CharField(default='en', max_length=16)),
                ('target_lang', models.CharField(max_length=16)),
                ('translation', models.TextField()),
                ('backend', models.CharField(help_text="Adapter that produced this row (e.g. 'claude', 'manual').", max_length=32)),
                ('confidence', models.FloatField(default=0.0, help_text='Self-reported 0.0–1.0. LLM backends default to 0.8.')),
                ('reviewed_by_human', models.BooleanField(default=False)),
                ('tokens_in', models.PositiveIntegerField(default=0)),
                ('tokens_out', models.PositiveIntegerField(default=0)),
                ('hit_count', models.PositiveIntegerField(default=0)),
                ('last_hit_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['target_lang', 'last_hit_at'], name='lingua_tran_target__f7eff8_idx')],
                'unique_together': {('source_hash', 'source_lang', 'target_lang')},
            },
        ),
        migrations.CreateModel(
            name='UserLanguagePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority_codes', models.JSONField(default=list)),
                ('auto_translate', models.BooleanField(default=False, help_text='If set, the hover tooltip is active on every page.')),
                ('hover_modifier', models.CharField(choices=[('alt', 'Alt'), ('ctrl', 'Ctrl'), ('shift', 'Shift'), ('none', 'None')], default='alt', help_text='Modifier key that must be held for the hover tooltip.', max_length=8)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lingua_pref', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
