# Generated by Django 6.0.4 on 2026-04-19 10:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lingua', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_lang', models.CharField(default='en', max_length=16)),
                ('lemma', models.CharField(help_text='Word in the target language.', max_length=200)),
                ('gloss', models.CharField(blank=True, help_text='Meaning in source_lang (usually English).', max_length=400)),
                ('example_src', models.TextField(blank=True)),
                ('example_trg', models.TextField(blank=True)),
                ('freq_rank', models.PositiveIntegerField(blank=True, help_text='Rank in the source frequency list (1 = most common).', null=True)),
                ('backend', models.CharField(blank=True, help_text='Which adapter produced the translation.', max_length=32)),
                ('leitner_box', models.PositiveSmallIntegerField(default=0)),
                ('due_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('correct_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.ForeignKey(help_text='Target language — the one being learned.', on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='lingua.language')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lingua_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['due_at', 'freq_rank'],
                'indexes': [models.Index(fields=['user', 'language', 'due_at'], name='lingua_flas_user_id_ea15bf_idx')],
                'unique_together': {('user', 'language', 'gloss', 'source_lang')},
            },
        ),
    ]
