# Generated by Django 6.0.4 on 2026-04-19 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lingua', '0002_flashcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='pronunciation',
            field=models.CharField(blank=True, help_text='Romanisation / transliteration (e.g. pinyin for zh, romaji for ja).', max_length=200),
        ),
    ]
