# Generated by Django 6.0.4 on 2026-04-19 10:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lingua', '0003_flashcard_pronunciation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='flashcard',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='level',
            field=models.CharField(choices=[('word', 'Single word'), ('phrase', 'Phrase'), ('sentence', 'Full sentence')], default='word', help_text='word / phrase / sentence — controls rendering.', max_length=16),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='theme',
            field=models.CharField(blank=True, default='', help_text='Theme slug, e.g. "body_parts". Empty = general deck.', max_length=60),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='lemma',
            field=models.CharField(help_text='Word/phrase/sentence in the target language.', max_length=400),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='pronunciation',
            field=models.CharField(blank=True, help_text='Romanisation / transliteration (e.g. pinyin for zh, romaji for ja).', max_length=400),
        ),
        migrations.AlterUniqueTogether(
            name='flashcard',
            unique_together={('user', 'language', 'gloss', 'source_lang', 'theme', 'level')},
        ),
        migrations.AddIndex(
            model_name='flashcard',
            index=models.Index(fields=['user', 'language', 'theme', 'level'], name='lingua_flas_user_id_0cd9c1_idx'),
        ),
    ]
