# Generated by Django 6.0.4 on 2026-04-20 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('kind', models.CharField(choices=[('local', 'Local shell'), ('vps', 'VPS (SSH)'), ('slurm', 'HPC (Slurm auto-submit)'), ('slurm_manual', 'HPC (Slurm manual submit)'), ('pi', 'Raspberry Pi'), ('esp', 'ESP node'), ('attiny', 'ATtiny firmware'), ('agent', 'Code agent'), ('http', 'Generic HTTP')], max_length=16)),
                ('host', models.CharField(blank=True, help_text='SSH hostname, API base URL, mDNS name, or identifier — kind-specific.', max_length=200)),
                ('config', models.JSONField(blank=True, default=dict, help_text='Kind-specific config: {ssh_user, ssh_port, partition, account, base_url, ...}')),
                ('enabled', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0, help_text='Higher priority wins when routing picks between eligible targets of the same kind.')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['kind', '-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('shell', 'Shell command'), ('slurm_script', 'Slurm sbatch script'), ('http', 'HTTP request'), ('agent_task', 'Agent task'), ('sensor_read', 'Sensor read'), ('firmware_flash', 'Firmware flash')], default='shell', max_length=20)),
                ('payload', models.JSONField(default=dict, help_text='Kind-specific: shell={command, cwd?, env?, timeout?}; slurm_script={script, cluster_hint?}; http={method, url, body?, headers?}.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('routing', 'Routing'), ('dispatched', 'Dispatched'), ('running', 'Running'), ('handoff', 'Waiting for human submit'), ('done', 'Done'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=12)),
                ('stdout', models.TextField(blank=True)),
                ('stderr', models.TextField(blank=True)),
                ('result', models.JSONField(blank=True, default=dict, help_text='Executor-specific extra return data (HTTP body, sensor reading, etc.).')),
                ('exit_code', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('requester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conduit_jobs', to=settings.AUTH_USER_MODEL)),
                ('requested_target', models.ForeignKey(blank=True, help_text='If set and eligible, the router picks this target over anything else.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_jobs', to='conduit.jobtarget')),
                ('target', models.ForeignKey(blank=True, help_text='Filled in by route(). The target that actually ran it.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatched_jobs', to='conduit.jobtarget')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobHandoff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script_text', models.TextField(help_text='The rendered script (e.g. sbatch file) ready to copy to the cluster and submit.')),
                ('submit_instructions', models.TextField(help_text='Copy-pasteable shell commands for the operator.')),
                ('status', models.CharField(choices=[('pending', 'Waiting for submission'), ('submitted', 'Submitted externally'), ('acknowledged', 'Acknowledged / outcome recorded'), ('cancelled', 'Cancelled')], default='pending', max_length=14)),
                ('external_id', models.CharField(blank=True, help_text='External queue ID (e.g. Slurm job number).', max_length=120)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='handoff', to='conduit.job')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_handoffs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['status', '-job__created_at'],
            },
        ),
    ]
