# Generated by Django 6.0.4 on 2026-05-14 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('iso639_3', models.CharField(blank=True, max_length=8)),
                ('region', models.CharField(blank=True, help_text='Geographic region or country.', max_length=120)),
                ('family', models.CharField(blank=True, help_text='Linguistic family or genealogy, where known.', max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Lemma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gloss', models.CharField(help_text='Conventional all-caps gloss, e.g. "WATER", "HELLO".', max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('semantic_field', models.CharField(blank=True, help_text='Coarse semantic bucket (greeting, kinship, food, ...).', max_length=80)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['gloss'],
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('citation', models.TextField(blank=True, help_text='Full bibliographic citation.')),
                ('url', models.URLField(blank=True)),
                ('doi', models.CharField(blank=True, max_length=80)),
                ('license_text', models.CharField(blank=True, help_text='e.g. CC-BY-4.0, CC0, all-rights-reserved.', max_length=120)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Variety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='varieties', to='signs.language')),
            ],
            options={
                'ordering': ['language__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Sign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('signer', models.CharField(blank=True, help_text='Identifier of the signer; can be a name or anonymised code.', max_length=120)),
                ('recorded_at', models.DateField(blank=True, null=True)),
                ('media_url', models.URLField(blank=True, help_text='Optional video URL of the original recording.')),
                ('notes', models.TextField(blank=True)),
                ('fps', models.PositiveSmallIntegerField(default=30, help_text='Frames per second the recording was sampled at.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signs', to=settings.AUTH_USER_MODEL)),
                ('lemma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signs', to='signs.lemma')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signs', to='signs.source')),
                ('variety', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signs', to='signs.variety')),
            ],
            options={
                'ordering': ['lemma__gloss', 'variety__name'],
            },
        ),
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField(help_text='0-based frame number.')),
                ('duration_ms', models.PositiveSmallIntegerField(default=33, help_text='Display duration in ms; default is 1/30 s.')),
                ('cylinder_rotations', models.JSONField(default=list, help_text='30 × [rx, ry, rz] local Euler radians.')),
                ('wrist_l_rot', models.JSONField(default=list, help_text='[rx, ry, rz] left wrist rotation.')),
                ('wrist_r_rot', models.JSONField(default=list, help_text='[rx, ry, rz] right wrist rotation.')),
                ('palm_l_pos', models.JSONField(default=list, help_text='[x, y, z] left palm position; empty = default.')),
                ('palm_r_pos', models.JSONField(default=list, help_text='[x, y, z] right palm position; empty = default.')),
                ('openpose_joints', models.JSONField(blank=True, default=list, help_text='Raw OpenPose joint positions; empty when the sign was hand-keyed rather than imported.')),
                ('sign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frames', to='signs.sign')),
            ],
            options={
                'ordering': ['sign__slug', 'index'],
                'constraints': [models.UniqueConstraint(fields=('sign', 'index'), name='unique_frame_per_sign')],
            },
        ),
        migrations.AddConstraint(
            model_name='variety',
            constraint=models.UniqueConstraint(fields=('language', 'name'), name='unique_variety_per_language'),
        ),
    ]
