# Generated by Django 6.0.4 on 2026-05-13 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('manufacturer', models.CharField(blank=True, max_length=80)),
                ('year_release', models.PositiveIntegerField(blank=True, help_text='Year the platform first shipped.', null=True)),
                ('year_retire', models.PositiveIntegerField(blank=True, help_text='Year the platform was discontinued (blank if still in production).', null=True)),
                ('bit_depth', models.PositiveSmallIntegerField(blank=True, help_text='Marketed bit depth — 8, 16, 32, 64, 128.', null=True)),
                ('notes', models.TextField(blank=True, help_text='What was distinctive about this platform.')),
            ],
            options={
                'ordering': ['year_release', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=200)),
                ('year', models.PositiveIntegerField(blank=True, help_text='Release year on this platform.', null=True)),
                ('genre', models.CharField(choices=[('action', 'Action'), ('adventure', 'Adventure'), ('rpg', 'Role-playing'), ('platformer', 'Platformer'), ('shooter', 'Shooter / FPS'), ('puzzle', 'Puzzle'), ('fighting', 'Fighting'), ('racing', 'Racing'), ('sports', 'Sports'), ('strategy', 'Strategy'), ('simulation', 'Simulation'), ('maze', 'Maze / collect'), ('shmup', 'Shoot-em-up'), ('beatup', 'Beat-em-up'), ('survival', 'Survival horror'), ('rhythm', 'Rhythm / music'), ('roguelike', 'Roguelike'), ('text', 'Text adventure'), ('other', 'Other')], default='other', max_length=20)),
                ('developer', models.CharField(blank=True, max_length=120)),
                ('publisher', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True, help_text='One-paragraph plain-English description: setting, mechanics, controls, win condition.  This is the text a future "evolve toward description" fitness function will score genes against.')),
                ('mechanics', models.TextField(blank=True, help_text='Comma- or bullet-separated tags: "side-scrolling, jumping, treasure-collection, no shooting" etc.')),
                ('wikipedia_url', models.URLField(blank=True)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='retrogames.platform')),
            ],
            options={
                'ordering': ['platform__year_release', 'year', 'name'],
                'unique_together': {('platform', 'slug')},
            },
        ),
    ]
