# Generated by Django 6.0.4 on 2026-04-22 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('url', models.URLField(max_length=500)),
                ('kind', models.CharField(choices=[('rss', 'RSS / Atom (feedparser)'), ('html', 'HTML scrape (Phase 2 — not yet wired)')], default='rss', max_length=8)),
                ('topics', models.CharField(blank=True, help_text='Comma-separated tags: tech, world, etc.', max_length=240)),
                ('active', models.BooleanField(default=True)),
                ('last_fetched', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('fetch_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(max_length=400)),
                ('title', models.CharField(max_length=400)),
                ('url', models.URLField(max_length=500)),
                ('author', models.CharField(blank=True, max_length=160)),
                ('summary', models.TextField(blank=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='aggregator.feed')),
            ],
            options={
                'ordering': ['-published_at', '-fetched_at'],
            },
        ),
        migrations.CreateModel(
            name='Newspaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('title', models.CharField(default="Today's Velour Herald", max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('window_hours', models.PositiveIntegerField(default=24, help_text='Articles no older than this are considered.')),
                ('article_count', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newspapers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewspaperArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aggregator.article')),
                ('newspaper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='aggregator.newspaper')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['-published_at'], name='aggregator__publish_7cb1f1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='article',
            unique_together={('feed', 'guid')},
        ),
        migrations.AlterUniqueTogether(
            name='newspaperarticle',
            unique_together={('newspaper', 'article')},
        ),
    ]
