# Generated by Django 6.0.4 on 2026-04-22 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='body_error',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='article',
            name='body_fetched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='body_html',
            field=models.TextField(blank=True, help_text='Reader-mode HTML extracted from the article URL.'),
        ),
        migrations.AddField(
            model_name='article',
            name='body_text',
            field=models.TextField(blank=True, help_text='Plain-text form of the body — searchable.'),
        ),
    ]
