# Generated by Django 6.0.4 on 2026-05-10 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('family', models.CharField(blank=True, help_text='RLWE / LWE / GSW / etc.', max_length=64)),
                ('datatype', models.CharField(choices=[('int', 'integer (exact)'), ('float', 'float (approximate)'), ('bool', 'boolean / bit'), ('vector', 'packed vector')], default='int', max_length=16)),
                ('bootstrappable', models.BooleanField(default=False, help_text='Does the scheme support full bootstrapping in practice?')),
                ('year_introduced', models.PositiveIntegerField(blank=True, null=True)),
                ('paper_title', models.CharField(blank=True, max_length=256)),
                ('paper_url', models.URLField(blank=True)),
                ('summary', models.TextField(blank=True, help_text='One-paragraph plain-English description.')),
                ('parameter_notes', models.TextField(blank=True, help_text='Typical poly-modulus / plaintext-modulus / scale choices people use.')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('url', models.URLField()),
                ('kind', models.CharField(choices=[('paper', 'paper'), ('library', 'library'), ('awesome', 'awesome-list'), ('blog', 'blog post'), ('talk', 'talk / video'), ('repo', 'repository'), ('tutorial', 'tutorial')], default='library', max_length=16)),
                ('authors', models.CharField(blank=True, max_length=256)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('summary', models.TextField(blank=True)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated topical tags.', max_length=128)),
                ('schemes', models.ManyToManyField(blank=True, help_text='Schemes implemented or discussed by this resource.', related_name='references', to='umbra.scheme')),
            ],
            options={
                'ordering': ['kind', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('description', models.TextField(blank=True)),
                ('code', models.TextField(blank=True, help_text='Python source.  In phase 1 this is just stored; phase 2 pipes it through a runner.')),
                ('status', models.CharField(choices=[('draft', 'draft'), ('saved', 'saved'), ('running', 'running'), ('done', 'done'), ('failed', 'failed')], default='draft', max_length=16)),
                ('last_output', models.TextField(blank=True, help_text='Captured stdout from the most recent run (phase 2+).')),
                ('last_error', models.TextField(blank=True)),
                ('last_run_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='experiments', to='umbra.scheme')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
