# Generated by Django 6.0.4 on 2026-05-12 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umbra', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CsvLabSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128)),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('original_csv', models.TextField()),
                ('result_csv', models.TextField(blank=True)),
                ('ops_json', models.TextField(blank=True, default='[]', help_text='JSON list of {op, ...} dicts; see csvlab.OP_*.')),
                ('rows', models.PositiveIntegerField(default=0)),
                ('cols', models.PositiveIntegerField(default=0)),
                ('numeric_cells', models.PositiveIntegerField(default=0)),
                ('ciphertext_bytes', models.PositiveIntegerField(default=0, help_text='Total serialized size of all cell ciphertexts.')),
                ('encrypt_ms', models.PositiveIntegerField(default=0)),
                ('ops_ms', models.PositiveIntegerField(default=0)),
                ('decrypt_ms', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
