# Generated by Django 6.0.4 on 2026-05-12 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umbra', '0003_corpuslabsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='corpuslabsession',
            name='language_profile',
            field=models.CharField(default='ascii', help_text="Codepoint alphabet to use under PBS — 'ascii' or 'devanagari'.  See corpuslab.PROFILES.", max_length=32),
        ),
    ]
