# Generated by Django 6.0.4 on 2026-05-17 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umbra', '0005_sealedlexsession_delete_corpuslabsession_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sealedlexsession',
            name='language_profile',
            field=models.CharField(default='ascii', help_text="Codepoint alphabet to use under PBS — 'ascii', 'devanagari', or 'geez'.  See sealedlex.PROFILES.", max_length=32),
        ),
        migrations.AlterField(
            model_name='sealedlexsession',
            name='ops_json',
            field=models.TextField(blank=True, default='[]', help_text='JSON list of {op, ...} dicts; see sealedlex.OP_*.'),
        ),
    ]
