# Generated by Django 6.0.4 on 2026-05-11 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='World',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='untitled', max_length=80)),
                ('mode', models.CharField(choices=[('square', 'square (8×8 chess plate)'), ('hex', 'hex (axial radius)')], default='square', max_length=8)),
                ('dim', models.PositiveIntegerField(default=8)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('parsed', models.JSONField(blank=True, help_text='Cached AST. Null if last parse failed.', null=True)),
                ('parse_error', models.TextField(blank=True, default='')),
                ('target_mode', models.CharField(choices=[('square', 'square only'), ('hex', 'hex only'), ('both', 'both (shared predicates only)')], default='both', max_length=8)),
                ('position', models.PositiveIntegerField(default=0, help_text='Display order within a world.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('world', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sentences', to='tableau.world')),
            ],
            options={
                'ordering': ['world_id', 'position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shape', models.CharField(choices=[('cube', 'cube'), ('tet', 'tetrahedron'), ('dodec', 'dodecahedron')], max_length=8)),
                ('size', models.CharField(choices=[('small', 'small'), ('medium', 'medium'), ('large', 'large')], max_length=8)),
                ('name', models.CharField(blank=True, default='', help_text='Optional name (a..f). Blank = anonymous.', max_length=8)),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='tableau.world')),
            ],
            options={
                'ordering': ['name', 'id'],
                'constraints': [models.UniqueConstraint(fields=('world', 'x', 'y'), name='tableau_block_unique_pos')],
            },
        ),
    ]
