# Generated by Django 6.0.4 on 2026-04-12 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HPCCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(help_text='Human-friendly name for this cluster, e.g. "Leiden Alice" or "SURFsara Snellius".', max_length=100)),
                ('slug', models.SlugField(blank=True, help_text='URL-safe unique identifier. Auto-derived from nickname if blank.', max_length=120, unique=True)),
                ('hostname', models.CharField(help_text='Hostname used for SSH, e.g. "alice.leidenuniv.nl" or "snellius.surf.nl".', max_length=253)),
                ('ssh_user', models.CharField(blank=True, help_text='Username to connect as. Leave blank if it varies per-login or if you use a stanza in ~/.ssh/config.', max_length=64)),
                ('ssh_port', models.PositiveIntegerField(default=22)),
                ('scheduler', models.CharField(choices=[('slurm', 'SLURM'), ('pbs', 'PBS / Torque'), ('sge', 'SGE / UGE'), ('lsf', 'LSF'), ('kubernetes', 'Kubernetes'), ('ray', 'Ray'), ('none', 'No scheduler (interactive only)'), ('other', 'Other / unknown')], default='slurm', max_length=16)),
                ('institution', models.CharField(blank=True, help_text='Organization that owns this cluster, e.g. "Leiden University" or "SURF".', max_length=200)),
                ('grant_code', models.CharField(blank=True, help_text='Optional funding account / allocation code for job accounting, e.g. "NWO-EW.2026.1234".', max_length=100)),
                ('description', models.TextField(blank=True, help_text='What kinds of jobs you run here. Free-form. Shows on the cluster detail page.')),
                ('notes', models.TextField(blank=True, help_text='Operator notes — quirks of this cluster, login steps, specific module loads, lessons learned.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_touched_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nickname'],
            },
        ),
    ]
