# Generated by Django 6.0.4 on 2026-04-26 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(help_text='Absolute path to the tarball.', max_length=500)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('sha256', models.CharField(blank=True, help_text='SHA-256 of the tarball, hex-encoded.', max_length=64)),
                ('retention', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('manual', 'Manual (no auto-prune)')], default='manual', max_length=10)),
                ('contents_summary', models.TextField(blank=True, help_text='What was packed: a short bulleted list of files / database tables / secret files included.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='backups_sna_created_190457_idx'), models.Index(fields=['retention', '-created_at'], name='backups_sna_retenti_f0a9f0_idx')],
            },
        ),
    ]
