# Gunicorn configuration for Velour
# Generated by Velour App Factory. Regenerate with:
#   python manage.py generate_deploy --target <dir> --project velour --user velour

bind = 'unix:/var/www/webapps/velour/run/velour.sock'
workers = 3
user = 'velour'
group = 'velour'
errorlog = '/var/www/webapps/velour/log/gunicorn-error.log'
accesslog = '/var/www/webapps/velour/log/gunicorn-access.log'
loglevel = 'info'
