[program:velour]
command=/home/velour/venv/bin/gunicorn velour.wsgi:application -c /home/velour/deploy/gunicorn.conf.py
directory=/home/velour
user=velour
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/var/www/webapps/velour/log/supervisor.log
environment=DJANGO_SETTINGS_MODULE="velour.settings",DJANGO_DEBUG="False"
