# Generated by Django 6.0.4 on 2026-04-15 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComputeTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('arithmetic', 'Arithmetic'), ('scripting', 'Scripting'), ('web', 'Web & network'), ('db', 'Database'), ('media', 'Media'), ('llm', 'LLM inference'), ('training', 'LLM training'), ('industrial', 'Industrial compute')], default='scripting', max_length=16)),
                ('energy_joules', models.FloatField()),
                ('cost_eur', models.FloatField(default=0.0)),
                ('cost_usd', models.FloatField(default=0.0)),
                ('environmental_score', models.IntegerField(default=0)),
                ('political_score', models.IntegerField(default=0)),
                ('economic_score', models.IntegerField(default=0)),
                ('social_score', models.IntegerField(default=0)),
                ('environmental_note', models.TextField(blank=True)),
                ('political_note', models.TextField(blank=True)),
                ('economic_note', models.TextField(blank=True)),
                ('social_note', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['energy_joules'],
            },
        ),
        migrations.CreateModel(
            name='EnergyComparable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('icon', models.CharField(help_text='Unicode glyph or emoji representing this signpost.', max_length=12)),
                ('energy_joules', models.FloatField()),
                ('note', models.CharField(blank=True, max_length=240)),
            ],
            options={
                'ordering': ['energy_joules'],
            },
        ),
    ]
