# Generated by Django 6.0.4 on 2026-04-15 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reckoner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=240)),
                ('order', models.PositiveIntegerField(default=100)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AppTaskUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_per_day', models.FloatField(default=1.0)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='reckoner.appprofile')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reckoner.computetask')),
            ],
            options={
                'ordering': ['-count_per_day'],
                'unique_together': {('app', 'task')},
            },
        ),
        migrations.AddField(
            model_name='appprofile',
            name='tasks',
            field=models.ManyToManyField(related_name='app_profiles', through='reckoner.AppTaskUsage', to='reckoner.computetask'),
        ),
    ]
