# Generated by Django 6.0.4 on 2026-05-13 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('retrogames', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('archetype', models.CharField(choices=[('doom', 'Doom'), ('pacman', 'Pacman'), ('pitfall', 'Pitfall'), ('blob', 'Boy & His Blob'), ('tmnt', 'TMNT'), ('custom', 'Custom')], default='doom', help_text='Preset bundle to apply on the evolve page.', max_length=20)),
                ('population_size', models.PositiveSmallIntegerField(blank=True, help_text='Population size override.', null=True)),
                ('generations', models.PositiveSmallIntegerField(blank=True, help_text='Generations per run override.', null=True)),
                ('max_turns', models.PositiveSmallIntegerField(blank=True, help_text='Max turns per sim override.', null=True)),
                ('grid_side', models.PositiveSmallIntegerField(blank=True, help_text='Grid size override (16/24/32).', null=True)),
                ('runs_per_batch', models.PositiveSmallIntegerField(default=3, help_text='How many consecutive runs of this Target per batch (survivors compound across runs via the localStorage carry-over, so more runs = more accumulation).')),
                ('archive_top_k', models.PositiveSmallIntegerField(default=3, help_text='How many top-fitness survivors to archive per run.')),
                ('priority', models.SmallIntegerField(default=0, help_text='Higher priority Targets run earlier in a batch sweep.')),
                ('active', models.BooleanField(default=True, help_text='If false, the runner skips this Target.')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('total_runs', models.PositiveIntegerField(default=0)),
                ('target_game', models.ForeignKey(blank=True, help_text='Optional classic game this Target is aspiring toward.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metaevolve_targets', to='retrogames.game')),
            ],
            options={
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ArchivedWinner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fitness', models.FloatField()),
                ('gene_json', models.JSONField(help_text='The full evolved gene: rule bytes, seed_byte, palette, world_mode, monster_count, item counts, music_style_idx, pure_mode, wall_threshold, component_grid.  Rule is stored as a list of 16384 ints 0..3.')),
                ('components_json', models.JSONField(blank=True, help_text='The fitness components breakdown (playability, openness, completion, etc.) at archive time — useful for tracking why this gene won.', null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('materialised_session_slug', models.CharField(blank=True, help_text='If the user has materialised this archived winner into a real doom_ca GameSession, the resulting session slug.', max_length=80)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winners', to='metaevolve.target')),
            ],
            options={
                'ordering': ['-fitness', '-created_at'],
            },
        ),
    ]
