# Generated by Django 6.0.4 on 2026-04-09 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_factory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedapp',
            name='dev_pid',
            field=models.IntegerField(blank=True, help_text='PID of the local dev server process', null=True),
        ),
        migrations.AddField(
            model_name='generatedapp',
            name='dev_port',
            field=models.IntegerField(blank=True, help_text='Port for local dev server (assigned on deploy)', null=True),
        ),
    ]
