# Generated by Django 6.0.4 on 2026-04-28 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_factory', '0002_generatedapp_dev_pid_generatedapp_dev_port'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedapp',
            name='admin_email',
            field=models.EmailField(blank=True, help_text='Default recipient for system mail in the new clone.', max_length=254),
        ),
        migrations.AddField(
            model_name='generatedapp',
            name='hostname',
            field=models.CharField(blank=True, help_text="Base domain baked into the new clone's Identity row. Blank = inherit from the originating install.", max_length=253),
        ),
        migrations.AddField(
            model_name='generatedapp',
            name='instance_label',
            field=models.CharField(blank=True, help_text='What the new clone calls itself in its own UI. Blank = the app name.', max_length=100),
        ),
        migrations.AddField(
            model_name='generatedapp',
            name='maintenance_root',
            field=models.CharField(blank=True, help_text='Host directory nginx serves when the upstream socket is down. Blank = /var/www/maintenance.', max_length=255),
        ),
        migrations.AddField(
            model_name='generatedapp',
            name='server_name',
            field=models.CharField(blank=True, help_text='nginx server_name. Blank = derive as <deploy_user>.<hostname-from-Identity>.', max_length=253),
        ),
    ]
