# Generated by Django 6.0.4 on 2026-04-28 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_factory', '0003_generatedapp_admin_email_generatedapp_hostname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedapp',
            name='selected_apps',
            field=models.TextField(blank=True, help_text='Comma-separated optional-app slugs. Empty = full clone.'),
        ),
    ]
