[program:{{ deploy_user }}]
command=/home/{{ deploy_user }}/venv/bin/gunicorn {{ project_name }}.wsgi:application -c /home/{{ deploy_user }}/deploy/gunicorn.conf.py
directory=/home/{{ deploy_user }}
user={{ deploy_user }}
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/var/www/webapps/{{ deploy_user }}/log/supervisor.log
environment=DJANGO_SETTINGS_MODULE="{{ project_name }}.settings",DJANGO_DEBUG="False"
