"""Quill tests — model invariants + view smoke."""

from django.contrib.auth.models import User
from django.test import TestCase
from django.urls import reverse

from quill.models import Document, Section, Style


class DocumentModelTests(TestCase):
    def test_slug_autogenerated_unique(self):
        a = Document.objects.create(title='Test Title')
        b = Document.objects.create(title='Test Title')
        self.assertEqual(a.slug, 'test-title')
        self.assertNotEqual(a.slug, b.slug)
        self.assertTrue(b.slug.startswith('test-title-'))

    def test_word_count_includes_all_sections(self):
        d = Document.objects.create(title='wc')
        Section.objects.create(document=d, body='one two three')
        Section.objects.create(document=d, body='four <em>five</em> six')
        # Naive whitespace split — HTML tags count as part of their token.
        self.assertEqual(d.word_count(), 6)

    def test_section_count_zero_then_grows(self):
        d = Document.objects.create(title='sc')
        self.assertEqual(d.section_count(), 0)
        Section.objects.create(document=d)
        self.assertEqual(d.section_count(), 1)


class StyleModelTests(TestCase):
    def setUp(self):
        self.doc = Document.objects.create(title='styled')

    def test_inline_css_renders_keys_dasherized(self):
        s = Style.objects.create(
            document=self.doc, name='Body', kind='paragraph',
            css_rules={'font_family': 'Charter', 'line_height': 1.5},
        )
        css = s.as_inline_css()
        self.assertIn('font-family: Charter', css)
        self.assertIn('line-height: 1.5', css)

    def test_unique_name_per_document(self):
        Style.objects.create(document=self.doc, name='X')
        with self.assertRaises(Exception):
            Style.objects.create(document=self.doc, name='X')


class ViewSmokeTests(TestCase):
    def setUp(self):
        self.user = User.objects.create_user('alice', password='pw')
        self.client.force_login(self.user)

    def test_list_renders(self):
        resp = self.client.get(reverse('quill:list'))
        self.assertEqual(resp.status_code, 200)
        self.assertContains(resp, 'Quill')

    def test_new_creates_document_with_default_styles_and_section(self):
        resp = self.client.post(reverse('quill:new'), {'title': 'Essay'})
        self.assertEqual(resp.status_code, 302)
        doc = Document.objects.get(title='Essay')
        self.assertEqual(doc.owner, self.user)
        # Seeded with Body + Heading 1, plus an Introduction section.
        self.assertEqual(doc.styles.count(), 2)
        self.assertEqual(doc.sections.count(), 1)

    def test_detail_renders_after_create(self):
        doc = Document.objects.create(title='Detail Doc', owner=self.user)
        Section.objects.create(document=doc, title='Hi', body='<p>Hello</p>')
        resp = self.client.get(reverse('quill:detail', args=[doc.slug]))
        self.assertEqual(resp.status_code, 200)
        self.assertContains(resp, 'Detail Doc')
        self.assertContains(resp, 'Hello')

    def test_section_add_appends_at_end(self):
        doc = Document.objects.create(title='ordered', owner=self.user)
        Section.objects.create(document=doc, title='first', order=0)
        resp = self.client.post(
            reverse('quill:section_add', args=[doc.slug]),
            {'title': 'second', 'body': '<p>two</p>', 'level': 1, 'style': ''},
        )
        self.assertEqual(resp.status_code, 302)
        self.assertEqual(doc.sections.count(), 2)
        # Newest section has order > existing.
        latest = doc.sections.order_by('-order').first()
        self.assertEqual(latest.title, 'second')

    def test_section_edit_updates(self):
        doc = Document.objects.create(title='editme', owner=self.user)
        sec = Section.objects.create(document=doc, title='before', body='<p>x</p>')
        resp = self.client.post(
            reverse('quill:section_edit', args=[doc.slug, sec.pk]),
            {'title': 'after', 'body': '<p>y</p>', 'level': 1, 'style': ''},
        )
        self.assertEqual(resp.status_code, 302)
        sec.refresh_from_db()
        self.assertEqual(sec.title, 'after')
        self.assertEqual(sec.body, '<p>y</p>')

    def test_style_add_attaches_to_document(self):
        doc = Document.objects.create(title='styled', owner=self.user)
        resp = self.client.post(
            reverse('quill:style_add', args=[doc.slug]),
            {'name': 'Quote', 'kind': 'paragraph', 'css_rules': '{"font_style": "italic"}'},
        )
        self.assertEqual(resp.status_code, 302)
        self.assertTrue(doc.styles.filter(name='Quote').exists())

    def test_delete_removes_document(self):
        doc = Document.objects.create(title='ephemeral', owner=self.user)
        resp = self.client.post(reverse('quill:delete', args=[doc.slug]))
        self.assertEqual(resp.status_code, 302)
        self.assertFalse(Document.objects.filter(pk=doc.pk).exists())
