# Generated by Django 6.0.4 on 2026-05-02 11:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SlotPatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('source_text', models.TextField()),
                ('source_bytes', models.PositiveIntegerField(default=0)),
                ('elf_blob', models.BinaryField()),
                ('elf_bytes', models.PositiveIntegerField(default=0)),
                ('elf_sha1', models.CharField(db_index=True, max_length=40)),
                ('build_time_ms', models.PositiveSmallIntegerField(default=0)),
                ('slot', models.CharField(blank=True, choices=[('', '— (no slot, upload only)'), ('step', 'step'), ('render', 'render'), ('gpio', 'gpio'), ('fitness', 'fitness')], max_length=12)),
                ('last_pushed_to', models.CharField(blank=True, help_text='Last device URL this patch was pushed to.', max_length=200)),
                ('last_push_at', models.DateTimeField(blank=True, null=True)),
                ('push_count', models.PositiveIntegerField(default=0)),
                ('success_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['slot'], name='s3lab_slotp_slot_a096e3_idx'), models.Index(fields=['elf_sha1'], name='s3lab_slotp_elf_sha_69e061_idx')],
            },
        ),
    ]
