"""Translate a Phalcon Volt template tree into Django templates.

Volt is Phalcon's PHP-and-Twig-flavoured template language. It uses
the same `{% %}` and `{{ }}` delimiters as Twig and Django, with a
small set of Volt-specific quirks. This module is intentionally a
thin wrapper around :mod:`datalift.twig_lifter` — the syntactic
overlap is large, and the differences (filename extensions,
`%endfor%` outside braces, no `endset`) are handled here.

What's different from Twig:

* Files end in ``.volt``, not ``.twig``.
* No `extends`/`include` extension remap is needed beyond
  swapping `.volt` for `.html`.
* Volt's ``{%- ... -%}`` whitespace controls match Twig's; Twig
  lifter handles them.
* Volt has the same control flow as Twig.

We reuse the Twig translator's tag table verbatim and only retarget
the file walker.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from pathlib import Path

from datalift.twig_lifter import (
    translate_template as _twig_translate,
)


@dataclass
class TemplateRecord:
    source: Path
    target_name: str
    body: str
    skipped: list[str] = field(default_factory=list)


@dataclass
class LiftResult:
    records: list[TemplateRecord] = field(default_factory=list)
    static_assets: list[Path] = field(default_factory=list)
    unhandled_files: list[Path] = field(default_factory=list)


_VOLT_EXT_RE = re.compile(r"(['\"])([^'\"]+?)\.volt\1")


def translate_template(source: str) -> tuple[str, list[str]]:
    """Translate Volt source to Django via the Twig lifter, with a
    pre-pass to swap ``.volt`` extensions in include/extends paths."""
    pre = _VOLT_EXT_RE.sub(r'\1\2.html\1', source)
    return _twig_translate(pre)


_STATIC_ASSET_EXTS = {
    '.css', '.js', '.png', '.jpg', '.jpeg', '.gif', '.svg', '.webp',
    '.ico', '.woff', '.woff2', '.ttf', '.otf', '.eot',
}


def parse_theme(theme_dir: Path) -> LiftResult:
    """Walk a Volt template directory and translate every `.volt` file."""
    result = LiftResult()
    if not theme_dir.is_dir():
        return result
    for path in sorted(theme_dir.rglob('*')):
        if not path.is_file():
            continue
        rel = path.relative_to(theme_dir)
        ext = path.suffix.lower()
        if ext == '.volt':
            tpl = path.read_text(encoding='utf-8', errors='replace')
            body, skipped = translate_template(tpl)
            target = str(rel.with_suffix('.html'))
            result.records.append(TemplateRecord(
                source=rel, target_name=target, body=body, skipped=skipped,
            ))
        elif ext in _STATIC_ASSET_EXTS:
            result.static_assets.append(rel)
        elif ext in {'.php', '.phtml', '.inc'}:
            result.unhandled_files.append(rel)
    return result


def render_worklist(result: LiftResult, app_label: str, theme_dir: Path) -> str:
    lines = [
        f'# liftvolt worklist — {theme_dir.name}',
        '',
        f'Target app: `{app_label}`. Generated by `datalift liftvolt`.',
        '',
        '## Translated templates',
        '',
    ]
    if not result.records:
        lines.append('_(none)_')
    for rec in result.records:
        skip = f' — **{len(rec.skipped)} unhandled fragments**' if rec.skipped else ''
        lines.append(f'- `{rec.source}` → `templates/{app_label}/{rec.target_name}`{skip}')
    lines += ['', '## Other files', '']
    for p in result.unhandled_files:
        lines.append(f'- `{p}` (PHP code; port by hand)')
    lines += ['', '## Static assets passed through', '']
    for p in result.static_assets:
        lines.append(f'- `{p}` → `static/{app_label}/{p}`')
    lines += ['', '## Per-template unhandled Volt fragments', '']
    saw_any = False
    for rec in result.records:
        if not rec.skipped:
            continue
        saw_any = True
        lines.append(f'### `{rec.source}`')
        for s in rec.skipped:
            lines.append(f'- `{s[:200]}`')
        lines.append('')
    if not saw_any:
        lines.append('_(everything translated cleanly)_')
    return '\n'.join(lines)


def apply(result: LiftResult, project_root: Path, app_label: str,
          dry_run: bool = False) -> list[str]:
    log: list[str] = []
    templates_dir = project_root / 'templates' / app_label
    static_dir = project_root / 'static' / app_label
    if not dry_run:
        templates_dir.mkdir(parents=True, exist_ok=True)
        static_dir.mkdir(parents=True, exist_ok=True)
    for rec in result.records:
        target = templates_dir / rec.target_name
        if not dry_run:
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(rec.body, encoding='utf-8')
        log.append(f'template  {rec.source} → {target.relative_to(project_root)}')
    return log
