# Generated by Django 6.0.4 on 2026-05-04 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Circuit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('description', models.TextField(blank=True)),
                ('width', models.PositiveSmallIntegerField(default=16)),
                ('height', models.PositiveSmallIntegerField(default=16)),
                ('palette', models.JSONField(blank=True, default=list, help_text='List of CSS hex strings, one per cell value. Defaults to the wireworld palette (empty / wire / head / tail) if empty.')),
                ('grid', models.JSONField(blank=True, default=list, help_text='2D array (height x width) of cell values 0..K-1. This is the *initial* state — runs always start from here.')),
                ('rule_sha1', models.CharField(blank=True, default='', max_length=40)),
                ('rule_name', models.CharField(blank=True, default='wireworld-hex-k4', max_length=120)),
                ('ports', models.JSONField(blank=True, default=list)),
                ('target', models.JSONField(blank=True, default=dict, help_text='Free-form target spec.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
