# Generated by Django 6.0.4 on 2026-05-04 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvolutionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], default='queued', max_length=16)),
                ('error', models.TextField(blank=True)),
                ('pop_size', models.PositiveSmallIntegerField(default=32)),
                ('generations', models.PositiveSmallIntegerField(default=30)),
                ('mutation_rate', models.FloatField(default=0.03)),
                ('crossover_rate', models.FloatField(default=0.85)),
                ('tournament_k', models.PositiveSmallIntegerField(default=3)),
                ('init_density', models.FloatField(default=0.2)),
                ('seed', models.IntegerField(default=7)),
                ('target', models.JSONField(blank=True, default=dict)),
                ('current_gen', models.PositiveSmallIntegerField(default=0)),
                ('fitness_history', models.JSONField(blank=True, default=list)),
                ('best_grid', models.JSONField(blank=True, default=list)),
                ('best_fitness', models.FloatField(default=0.0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('circuit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evolution_runs', to='forge.circuit')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
