# Generated by Django 6.0.4 on 2026-05-09 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TessSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('seed', models.IntegerField(default=0, help_text='Master RNG seed; (seed, color_idx) keys each source image so neighbouring colors diverge.')),
                ('tile_px', models.PositiveIntegerField(default=128, help_text='Output tile size in pixels (square).')),
                ('method', models.CharField(choices=[('fbm-tileable', 'fBm noise (toroidally tileable)'), ('hex-ca', 'Hex CA evolved (Velour-style)'), ('domain-warp', 'fBm + domain warp')], default='fbm-tileable', max_length=20)),
                ('palette', models.JSONField(default=list, help_text='Four [r,g,b] RGB anchors, one per edge color. If empty at save time, defaults to a four-hue spread (warm / cool / verdant / amber).')),
                ('blur_sigma', models.FloatField(default=0.0, help_text='Optional Gaussian blur on the composite tile, in pixels.  0 disables.  Soft blurs hide micro-grain mismatches between the corner-region IDW blends in adjacent tiles.')),
                ('blend_power', models.FloatField(default=2.0, help_text='Inverse-distance weighting power.  Higher → sharper edge handover (tile interior reads more as four quadrants); lower → mushier middle.  2.0 is the classical Shepard default.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
