# Generated by Django 6.0.4 on 2026-05-12 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tessera', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tessset',
            name='blend_method',
            field=models.CharField(choices=[('idw', 'IDW blend — Tessera-style seamless math'), ('wedge', 'wedge cut — stained-glass aesthetic')], default='idw', help_text='IDW blends the edge sources smoothly across the interior; wedge slices each source into N triangles around the centre.  Aesthetically very different.', max_length=8),
        ),
        migrations.AddField(
            model_name='tessset',
            name='topology',
            field=models.CharField(choices=[('square', 'square — 4 edges, 4⁴ = 256 tiles'), ('hex', 'hex — 6 edges, 4⁶ = 4096 tiles')], default='square', help_text='Square (4 edges → 256 tiles) or hex (6 edges → 4096 tiles).', max_length=8),
        ),
    ]
