# Generated by Django 6.0.4 on 2026-05-12 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tessera', '0002_tessset_blend_method_tessset_topology'),
    ]

    operations = [
        migrations.AddField(
            model_name='tessset',
            name='upload_a',
            field=models.ImageField(blank=True, null=True, upload_to='tessera/uploads/'),
        ),
        migrations.AddField(
            model_name='tessset',
            name='upload_b',
            field=models.ImageField(blank=True, null=True, upload_to='tessera/uploads/'),
        ),
        migrations.AddField(
            model_name='tessset',
            name='upload_c',
            field=models.ImageField(blank=True, null=True, upload_to='tessera/uploads/'),
        ),
        migrations.AddField(
            model_name='tessset',
            name='upload_d',
            field=models.ImageField(blank=True, null=True, upload_to='tessera/uploads/'),
        ),
        migrations.AlterField(
            model_name='tessset',
            name='method',
            field=models.CharField(choices=[('fbm-tileable', 'fBm noise (toroidally tileable)'), ('hex-ca', 'Hex CA evolved (Velour-style)'), ('domain-warp', 'fBm + domain warp'), ('upload-4', 'upload 4 images (one per colour)'), ('upload-1-palette', 'upload 1 image (4 random palette shifts)')], default='fbm-tileable', max_length=20),
        ),
    ]
