# Generated by Django 6.0.4 on 2026-04-12 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Distillation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('source_app', models.CharField(help_text='Velour app name (e.g. "tiles") or path to external project.', max_length=100)),
                ('source_tier', models.CharField(choices=[('django', 'Tier 1: Django/Python'), ('js', 'Tier 2: JS-only (browser)'), ('esp', 'Tier 3: ESP8266 (microcontroller)'), ('attiny', 'Tier 4: ATTiny13a (1KB flash)'), ('circuit', 'Tier 5: 555 timer circuits')], default='django', max_length=16)),
                ('target_tier', models.CharField(choices=[('django', 'Tier 1: Django/Python'), ('js', 'Tier 2: JS-only (browser)'), ('esp', 'Tier 3: ESP8266 (microcontroller)'), ('attiny', 'Tier 4: ATTiny13a (1KB flash)'), ('circuit', 'Tier 5: 555 timer circuits')], default='js', max_length=16)),
                ('output', models.TextField(blank=True, help_text='The distilled output — HTML/JS, C code, circuit description, etc.')),
                ('output_size_bytes', models.IntegerField(default=0)),
                ('annotations', models.TextField(blank=True, help_text='Gödel markers extracted from the output — prompts for the next pass.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('error', 'Error')], default='pending', max_length=16)),
                ('error_detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
