# Generated by Django 6.0.4 on 2026-04-13 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condenser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distillation',
            name='source_tier',
            field=models.CharField(choices=[('django', 'Tier 1: Django/Python'), ('js', 'Tier 2: JS-only (browser)'), ('esp', 'Tier 3: ESP8266 (microcontroller)'), ('attiny', 'Tier 4: ATTiny13a (1KB flash)'), ('circuit', 'Tier 5: 555 timer circuits'), ('stereokit', 'StereoKit (Quest 3 native)')], default='django', max_length=16),
        ),
        migrations.AlterField(
            model_name='distillation',
            name='target_tier',
            field=models.CharField(choices=[('django', 'Tier 1: Django/Python'), ('js', 'Tier 2: JS-only (browser)'), ('esp', 'Tier 3: ESP8266 (microcontroller)'), ('attiny', 'Tier 4: ATTiny13a (1KB flash)'), ('circuit', 'Tier 5: 555 timer circuits'), ('stereokit', 'StereoKit (Quest 3 native)')], default='js', max_length=16),
        ),
    ]
