# Generated by Django 6.0.4 on 2026-05-09 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('introduced_in', models.CharField(blank=True, help_text='Build label where the canonical variant first shipped this — e.g. "ev16", "v0.3".', max_length=64)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True)),
                ('runtime_kind', models.CharField(choices=[('browser', 'Browser (HTML+JS)'), ('native', 'Native binary (C/C++)'), ('mcu', 'Microcontroller'), ('other', 'Other')], default='other', max_length=24)),
                ('is_canonical', models.BooleanField(default=False, help_text='The variant that defines the reference behaviour. Other variants are scored against this one.')),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PortStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('todo', 'todo'), ('partial', 'partial'), ('done', 'done'), ('na', 'not applicable')], default='todo', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='bidir.feature')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='bidir.variant')),
            ],
            options={
                'ordering': ['feature__sort_order', 'variant__sort_order'],
                'unique_together': {('feature', 'variant')},
            },
        ),
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=64)),
                ('file_path', models.CharField(blank=True, max_length=300)),
                ('git_commit', models.CharField(blank=True, max_length=40)),
                ('bytes_size', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='builds', to='bidir.variant')),
            ],
            options={
                'ordering': ['variant__sort_order', '-created_at'],
                'unique_together': {('variant', 'label')},
            },
        ),
    ]
