# Generated by Django 6.0.4 on 2026-05-09 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TileSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('base_w', models.PositiveIntegerField(default=64)),
                ('base_h', models.PositiveIntegerField(default=64)),
                ('lattice', models.CharField(choices=[('offset-hex', 'Offset hex (officerpg)'), ('square', 'Square — for later')], default='offset-hex', help_text='Tessellation pattern; only offset-hex implemented in v1.', max_length=20)),
                ('edges_json', models.JSONField(default=list, help_text='6-element array, one entry per edge.  Each edge is a sorted list of {"p": <0..1>, "off": <perpendicular outward offset in tile units>} objects.  Corner control points (p=0 and p=1) implicit at off=0; the editor only stores interior CPs.')),
                ('is_preset', models.BooleanField(default=False, help_text='Read-only starter shapes seeded by manage.py seed_tilesmith.')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['is_preset', '-updated_at'],
            },
        ),
    ]
