# Generated by Django 6.0.4 on 2026-04-21 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='backup',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backup',
            name='archived_path',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
