# Generated by Django 6.0.4 on 2026-04-16 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HomeBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('block_id', models.CharField(blank=True, help_text="Source HTML id (e.g. 'waarom-displacetext2'). Used as the rendered <div id=...> for CSS parity.", max_length=120)),
                ('title', models.CharField(max_length=200)),
                ('body_html', models.TextField(blank=True)),
                ('link_zotonic_id', models.PositiveIntegerField(blank=True, help_text="Zid of the Page/Theme/Article the 'Lees meer' button targets. Resolved at render time.", null=True)),
                ('link_label', models.CharField(blank=True, help_text="Visually-hidden text after 'Lees meer' (e.g. 'over Toegankelijkheid').", max_length=120)),
                ('order', models.IntegerField(default=100)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, help_text='Short title for admin use (search-friendly).', max_length=240)),
                ('file', models.FileField(help_text='The image / asset itself.', upload_to='displacer/%Y/%m/')),
                ('caption', models.TextField(blank=True, help_text='Shown as the figcaption under the image on the public site.')),
                ('credit', models.CharField(blank=True, help_text='Photographer / archive credit line.', max_length=240)),
                ('alt_text', models.CharField(blank=True, help_text='Alt text for screen readers (accessibility).', max_length=240)),
                ('original_url', models.URLField(blank=True, help_text='Where the file was ingested from, if applicable.', max_length=500)),
                ('sha256', models.CharField(blank=True, db_index=True, help_text='Hex digest of the file contents — used to dedup re-ingested assets.', max_length=64)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('zotonic_id', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('body_html', models.TextField(blank=True)),
                ('show_in_footer', models.BooleanField(default=False)),
                ('show_in_menu', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=100)),
                ('published', models.BooleanField(default=True)),
                ('original_url', models.URLField(blank=True, max_length=400)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('bio', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_intro', models.TextField(blank=True, help_text='Plain-text intro shown at the very top of the home page.')),
                ('contact_email', models.EmailField(default='info@displace.nl', help_text='Shown in the footer.', max_length=254)),
                ('site_name', models.CharField(default='Displace', max_length=80)),
                ('ga_tracking_id', models.CharField(blank=True, help_text='Google Analytics / GA4 id. Leave blank to disable tracking.', max_length=40)),
            ],
            options={
                'verbose_name': 'Site settings',
                'verbose_name_plural': 'Site settings',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=240)),
                ('slug', models.SlugField(blank=True, help_text='Auto-filled from the title. Edit carefully — changing it breaks existing links.', max_length=260, unique=True)),
                ('zotonic_id', models.PositiveIntegerField(blank=True, help_text='Original numeric id in the Zotonic source site. Used to keep re-ingests idempotent.', null=True, unique=True)),
                ('summary', models.TextField(blank=True, help_text='Lede paragraph shown at the top of the article and in social-media previews. Keep it under 400 chars.')),
                ('body_html', models.TextField(blank=True, help_text='Full article body in HTML. Use the rich-text editor.')),
                ('published', models.BooleanField(default=False, help_text='Unchecked = draft, only visible to staff.')),
                ('published_at', models.DateTimeField(blank=True, help_text='When the article was (or will be) published. Used as the sort date on index pages.', null=True)),
                ('featured', models.BooleanField(default=False, help_text='If True, appears in the "Uitgelicht" strip on the home page.')),
                ('featured_order', models.IntegerField(default=100, help_text='Lower values appear first when Featured.')),
                ('display_order', models.IntegerField(db_index=True, default=1000, help_text='Position on the public Verhalen list. The first 6 are set from the curated source list at ingest time; the rest fall back to recency by zotonic_id.')),
                ('original_url', models.URLField(blank=True, help_text='Canonical URL on the original Zotonic site, if ingested.', max_length=400)),
                ('categories', models.ManyToManyField(blank=True, help_text='Editorial labels shown above the article title.', related_name='articles', to='displacer.category')),
                ('hero_image', models.ForeignKey(blank=True, help_text='Image shown at the top of the article and on list cards.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hero_of_articles', to='displacer.mediaasset')),
            ],
            options={
                'ordering': ['display_order', '-zotonic_id'],
            },
        ),
        migrations.CreateModel(
            name='ArticleCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('author', 'Written by'), ('thanks', 'With thanks to'), ('editor', 'Edited by'), ('photographer', 'Photography by')], default='author', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='displacer.article')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='displacer.person')),
            ],
            options={
                'ordering': ['role', 'order'],
                'unique_together': {('article', 'person', 'role')},
            },
        ),
        migrations.AddField(
            model_name='article',
            name='credits',
            field=models.ManyToManyField(help_text='Authors, thanks-to, editors.', related_name='articles', through='displacer.ArticleCredit', to='displacer.person'),
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('zotonic_id', models.PositiveIntegerField(blank=True, help_text='Original numeric id in the Zotonic source site.', null=True, unique=True)),
                ('subtitle', models.CharField(blank=True, max_length=400)),
                ('summary', models.TextField(blank=True, help_text='Short teaser shown on the themes index.')),
                ('body_html', models.TextField(blank=True, help_text='Rich HTML body — paragraphs, figures, embeds.')),
                ('order', models.IntegerField(default=100)),
                ('published', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('original_url', models.URLField(blank=True, help_text='Canonical URL on the original Zotonic site.', max_length=400)),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hero_of_themes', to='displacer.mediaasset')),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='themes',
            field=models.ManyToManyField(blank=True, help_text='Topical groupings this story belongs to.', related_name='articles', to='displacer.theme'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['published', 'display_order'], name='displacer_a_publish_d3740b_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['featured', 'featured_order'], name='displacer_a_feature_dd9b78_idx'),
        ),
    ]
