# Generated by Django 6.0.4 on 2026-04-10 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Human label used for routing, e.g. "snel-relay" or "gmail-dev".', max_length=100, unique=True)),
                ('enabled', models.BooleanField(default=True, help_text='Disabled accounts are hidden from the default selection and cannot be targeted by routing.')),
                ('is_default', models.BooleanField(default=False, help_text='Exactly one account may be the default. Marking this one as default automatically unmarks any other.')),
                ('smtp_host', models.CharField(max_length=255)),
                ('smtp_port', models.PositiveIntegerField(default=587)),
                ('smtp_username', models.CharField(blank=True, max_length=255)),
                ('smtp_password', models.CharField(blank=True, max_length=500)),
                ('smtp_use_tls', models.BooleanField(default=True)),
                ('smtp_use_ssl', models.BooleanField(default=False)),
                ('from_email', models.EmailField(help_text='Address that will appear in the From: header of outgoing mail. Usually matches smtp_username.', max_length=254)),
                ('from_name', models.CharField(blank=True, help_text='Optional display name shown alongside from_email.', max_length=100)),
                ('imap_host', models.CharField(blank=True, max_length=255)),
                ('imap_port', models.PositiveIntegerField(default=993)),
                ('imap_username', models.CharField(blank=True, max_length=255)),
                ('imap_password', models.CharField(blank=True, max_length=500)),
                ('imap_use_ssl', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('last_tested_at', models.DateTimeField(blank=True, null=True)),
                ('last_test_status', models.CharField(blank=True, max_length=16)),
                ('last_test_error', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-is_default', 'name'],
            },
        ),
    ]
