# Generated by Django 6.0.4 on 2026-04-13 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220)),
                ('asset_type', models.CharField(choices=[('model', 'GLTF/GLB 3D model'), ('texture', 'Image texture (JPG/PNG)'), ('audio', 'Audio clip (MP3/OGG)'), ('hdri', 'HDRI environment map')], default='model', max_length=16)),
                ('file', models.FileField(upload_to='aether/assets/')),
                ('thumbnail', models.ImageField(blank=True, upload_to='aether/thumbnails/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='World',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField(blank=True)),
                ('skybox', models.CharField(choices=[('color', 'Solid color'), ('gradient', 'Gradient sky'), ('hdri', 'HDRI environment'), ('procedural', 'Procedural sky (sun + atmosphere)')], default='procedural', max_length=16)),
                ('sky_color', models.CharField(default='#87CEEB', help_text='Hex color for solid/gradient sky, or tint for procedural.', max_length=7)),
                ('ground_color', models.CharField(default='#3d5c3a', max_length=7)),
                ('ground_size', models.FloatField(default=100.0, help_text='Ground plane radius in meters.')),
                ('ambient_light', models.FloatField(default=0.4, help_text='Ambient light intensity (0-1).')),
                ('fog_near', models.FloatField(default=50.0, help_text='Fog starts at this distance (meters).')),
                ('fog_far', models.FloatField(default=200.0, help_text='Fog fully opaque at this distance.')),
                ('fog_color', models.CharField(default='#c8d8e4', max_length=7)),
                ('gravity', models.FloatField(default=-9.81)),
                ('allow_flight', models.BooleanField(default=False)),
                ('spawn_x', models.FloatField(default=0.0)),
                ('spawn_y', models.FloatField(default=1.6)),
                ('spawn_z', models.FloatField(default=0.0)),
                ('published', models.BooleanField(default=False, help_text='Unpublished worlds are only visible to staff.')),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-featured', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Portal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=100)),
                ('pos_x', models.FloatField(default=0.0)),
                ('pos_y', models.FloatField(default=0.0)),
                ('pos_z', models.FloatField(default=-10.0)),
                ('width', models.FloatField(default=2.0)),
                ('height', models.FloatField(default=3.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portals_out', to='aether.world')),
                ('to_world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portals_in', to='aether.world')),
            ],
            options={
                'ordering': ['from_world', 'to_world'],
            },
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('primitive', models.CharField(blank=True, default='', help_text='box, sphere, cylinder, cone, plane, torus, ring', max_length=16)),
                ('primitive_color', models.CharField(default='#808080', max_length=7)),
                ('pos_x', models.FloatField(default=0.0)),
                ('pos_y', models.FloatField(default=0.0)),
                ('pos_z', models.FloatField(default=-5.0)),
                ('rot_x', models.FloatField(default=0.0, help_text='Degrees')),
                ('rot_y', models.FloatField(default=0.0)),
                ('rot_z', models.FloatField(default=0.0)),
                ('scale_x', models.FloatField(default=1.0)),
                ('scale_y', models.FloatField(default=1.0)),
                ('scale_z', models.FloatField(default=1.0)),
                ('behavior', models.CharField(choices=[('static', 'Static (no interaction)'), ('rotate', 'Continuous rotation'), ('bob', 'Gentle bobbing'), ('clickable', 'Clickable (triggers event)'), ('portal', 'Portal to another world'), ('orbit', 'Orbit around a point'), ('billboard', 'Always face camera')], default='static', max_length=16)),
                ('behavior_speed', models.FloatField(default=1.0, help_text='Speed multiplier for animations.')),
                ('cast_shadow', models.BooleanField(default=True)),
                ('receive_shadow', models.BooleanField(default=True)),
                ('visible', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(blank=True, help_text='Leave blank for primitive geometry (box, sphere, etc.).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='aether.asset')),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='aether.world')),
            ],
            options={
                'verbose_name_plural': 'entities',
                'ordering': ['sort_order', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='world',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='aether.world'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.UniqueConstraint(fields=('world', 'slug'), name='aether_unique_asset_slug_per_world'),
        ),
    ]
