# Generated by Django 6.0.4 on 2026-04-13 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aether', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField(blank=True)),
                ('code', models.TextField(help_text='JavaScript executed in the animation loop. Receives `ctx` object with entity, deltaTime, elapsed, state, camera, scene, events, nearby, props.')),
                ('event', models.CharField(choices=[('start', 'On start (once, when world loads)'), ('update', 'On update (every frame, receives deltaTime)'), ('player_near', 'On player near (within interaction range)'), ('player_far', 'On player leaves range'), ('interact', 'On interact (player clicks/activates)'), ('collide', 'On collision with another entity'), ('timer', 'On timer (fires at configured interval)'), ('custom', 'Custom event (sent by other scripts)')], default='update', help_text='When this script fires.', max_length=16)),
                ('is_builtin', models.BooleanField(default=False, help_text='Built-in scripts shipped with Aether.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='entity',
            name='behavior',
            field=models.CharField(choices=[('static', 'Static (no interaction)'), ('rotate', 'Continuous rotation'), ('bob', 'Gentle bobbing'), ('clickable', 'Clickable (triggers event)'), ('portal', 'Portal to another world'), ('orbit', 'Orbit around a point'), ('billboard', 'Always face camera'), ('scripted', 'Scripted (custom JS behavior)'), ('npc_wander', 'NPC: wander randomly'), ('npc_patrol', 'NPC: patrol waypoints'), ('npc_follow', 'NPC: follow player')], default='static', max_length=16),
        ),
        migrations.CreateModel(
            name='ObjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='aether.objectcategory')),
            ],
            options={
                'verbose_name_plural': 'object categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EntityScript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('props', models.JSONField(blank=True, default=dict, help_text='JSON properties passed to the script as ctx.props. E.g. {"speed": 2, "range": 10, "greeting": "Hello!"}')),
                ('enabled', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scripts', to='aether.entity')),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='aether.script')),
            ],
            options={
                'ordering': ['sort_order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='LibraryObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=320, unique=True)),
                ('description', models.TextField(blank=True)),
                ('tags', models.CharField(blank=True, db_index=True, help_text='Comma-separated tags for search.', max_length=500)),
                ('source', models.CharField(choices=[('sketchfab', 'Sketchfab'), ('polyhaven', 'Poly Haven'), ('khronos', 'Khronos glTF samples'), ('local', 'Local upload')], default='local', max_length=16)),
                ('source_uid', models.CharField(blank=True, db_index=True, help_text='UID from the source platform (e.g. Sketchfab model UID).', max_length=200)),
                ('source_url', models.URLField(blank=True, max_length=500)),
                ('license', models.CharField(choices=[('cc0', 'CC0 (Public Domain)'), ('cc-by', 'CC BY (Attribution)'), ('cc-by-sa', 'CC BY-SA (Attribution-ShareAlike)'), ('cc-by-nc', 'CC BY-NC (Attribution-NonCommercial)'), ('editorial', 'Editorial use only'), ('unknown', 'Unknown')], default='unknown', max_length=16)),
                ('author', models.CharField(blank=True, max_length=200)),
                ('file', models.FileField(blank=True, help_text='Local GLTF/GLB file. Downloaded on first use.', upload_to='aether/library/')),
                ('thumbnail', models.URLField(blank=True, help_text='Thumbnail URL (remote or local).', max_length=500)),
                ('file_size', models.IntegerField(default=0, help_text='File size in bytes.')),
                ('poly_count', models.IntegerField(default=0, help_text='Approximate polygon count.')),
                ('downloaded', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=False)),
                ('use_count', models.IntegerField(default=0, help_text='How many times placed in worlds.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='library_objects', to='aether.objectcategory')),
            ],
            options={
                'ordering': ['-use_count', 'name'],
                'indexes': [models.Index(fields=['source', 'source_uid'], name='aether_lib_source_uid_idx')],
            },
        ),
    ]
