# Generated by Django 6.0.4 on 2026-04-13 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aether', '0002_script_alter_entity_behavior_objectcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='world',
            name='hdri_asset',
            field=models.CharField(blank=True, default='', help_text='Poly Haven HDRI name, e.g. "kloofendal_48d_partly_cloudy".', max_length=120),
        ),
    ]
