# Generated by Django 6.0.4 on 2026-04-13 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aether', '0003_world_hdri_asset'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorldPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('skybox', models.CharField(choices=[('color', 'Solid color'), ('gradient', 'Gradient sky'), ('hdri', 'HDRI environment'), ('procedural', 'Procedural sky (sun + atmosphere)')], default='hdri', max_length=16)),
                ('hdri_asset', models.CharField(blank=True, default='', max_length=120)),
                ('sky_color', models.CharField(default='#87CEEB', max_length=7)),
                ('ground_color', models.CharField(default='#3d5c3a', max_length=7)),
                ('fog_color', models.CharField(default='#c8d8e4', max_length=7)),
                ('fog_near', models.FloatField(default=50.0)),
                ('fog_far', models.FloatField(default=200.0)),
                ('ambient_light', models.FloatField(default=0.4)),
                ('ambient_audio_url', models.URLField(blank=True, default='', help_text='Default ambient sound URL for this preset.')),
                ('ambient_volume', models.FloatField(default=0.4)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='world',
            name='ambient_audio',
            field=models.FileField(blank=True, default='', help_text='Uploaded ambient loop (MP3/OGG). Loops automatically.', upload_to='aether/audio/'),
        ),
        migrations.AddField(
            model_name='world',
            name='ambient_audio_url',
            field=models.URLField(blank=True, default='', help_text='Stream URL (Icecast, internet radio, direct MP3 link).'),
        ),
        migrations.AddField(
            model_name='world',
            name='ambient_volume',
            field=models.FloatField(default=0.4, help_text='Ambient audio volume (0.0–1.0).'),
        ),
    ]
