# Generated by Django 6.0.4 on 2026-04-13 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aether', '0004_worldpreset_world_ambient_audio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='world',
            name='soundscape',
            field=models.CharField(blank=True, default='', help_text='Procedural soundscape name (forest, cafe, city-street, rainy, winter, beach, night, space-station). Used when no audio file/URL is set.', max_length=30),
        ),
    ]
