# Generated by Django 6.0.4 on 2026-04-14 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aether', '0005_world_soundscape'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedFace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('genome', models.JSONField(help_text='Trait dict + palette + L-system rules. Fully reconstructs the face; no image stored.')),
                ('lineage', models.IntegerField(default=0, help_text='How many breeding generations deep this face is.')),
                ('use_count', models.IntegerField(default=0, help_text='How many entities use this face as an avatar.')),
                ('favorite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-favorite', '-created_at'],
            },
        ),
    ]
