# Generated by Django 6.0.4 on 2026-04-14 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aether', '0006_savedface'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='face',
            field=models.ForeignKey(blank=True, help_text="Face Forge avatar to display on this entity's head.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entities', to='aether.savedface'),
        ),
    ]
