# Generated by Django 6.0.4 on 2026-04-15 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aether', '0007_entity_face'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='language_slug',
            field=models.CharField(blank=True, default='', max_length=140),
        ),
    ]
