"""Toy universal-concept vocabulary.

A hand-picked inventory of roughly 600 semantic concepts that
recur across most of the world's languages. Concepts are given
in ALL CAPS to distinguish them from any particular language's
word form. A concept is an idea, not a lexical item — it is
neither declined nor conjugated. Concrete instances (``TREE``,
``WATER``) stand alongside abstract / grammatical concepts
(``PAST``, ``CAUSE``, ``NOT``). Parts of speech are labelled
loosely (``n`` = thing-like, ``v`` = event-like, ``adj`` =
quality-like, ``pro`` = deictic, ``gram`` = grammatical), but
many concepts straddle those boundaries — ``RAIN`` can be a
substance, a state, or an event depending on language.

Three nested tiers:

- ``TIER_10``  — the minimum vocabulary to say *something*.
- ``TIER_100`` — the minimum vocabulary for simple everyday
  reference. A superset of ``TIER_10``.
- ``TIER_FULL`` — the full ~600-concept toy dictionary. A
  superset of ``TIER_100``.

Inspired by the Swadesh 100/207 lists, the Leipzig-Jakarta 100,
and Anna Wierzbicka's Natural Semantic Metalanguage primes, but
not identical to any of them. Concepts are deliberately coarse:
"FISH" covers the whole taxon; "GO" covers every manner of
self-propelled motion that a language might split into walk /
ride / sail.
"""

from __future__ import annotations


# ─── TIER 10 ────────────────────────────────────────────────
# The absolute-minimum vocabulary. Enough to pick someone out,
# point at a thing, refer to the two most essential substances,
# describe movement and perception, evaluate, and negate.

TIER_10 = [
    ('I',       'pro', 'the speaker'),
    ('YOU',     'pro', 'the addressee'),
    ('PERSON',  'n',   'a human being, generic'),
    ('THING',   'n',   'any object, generic'),
    ('WATER',   'n',   'water as substance'),
    ('FIRE',    'n',   'fire, flame, combustion'),
    ('GO',      'v',   'self-propelled movement from one place to another'),
    ('SEE',     'v',   'perceive visually'),
    ('GOOD',    'adj', 'positively evaluated, well-regarded'),
    ('NOT',     'gram','negation of whatever follows'),
]


# ─── TIER 100 ───────────────────────────────────────────────
# A Swadesh-scale core. Superset of TIER_10. Enough for basic
# descriptions of people, places, time, and simple events.

TIER_100_ADDITIONS = [
    # People and kinship
    ('WE',       'pro', 'speaker plus others'),
    ('THEY',     'pro', 'third parties'),
    ('MAN',      'n',   'adult male human'),
    ('WOMAN',    'n',   'adult female human'),
    ('CHILD',    'n',   'young human'),
    ('FATHER',   'n',   'male parent'),
    ('MOTHER',   'n',   'female parent'),
    ('FRIEND',   'n',   'socially bonded non-relative'),
    ('NAME',     'n',   'the label a thing is called by'),

    # Body
    ('BODY',     'n',   'the physical form of a living being'),
    ('HEAD',     'n',   'top body part containing face and brain'),
    ('EYE',      'n',   'organ of sight'),
    ('EAR',      'n',   'organ of hearing'),
    ('MOUTH',    'n',   'orifice for eating and speaking'),
    ('HAND',     'n',   'grasping limb-end'),
    ('FOOT',     'n',   'standing/walking limb-end'),
    ('HAIR',     'n',   'head/body filaments'),
    ('BLOOD',    'n',   'body fluid carrying life'),
    ('BONE',     'n',   'hard internal skeletal material'),
    ('SKIN',     'n',   'body covering'),
    ('HEART',    'n',   'organ of circulation and felt emotion'),

    # Nature
    ('SUN',      'n',   'the daytime sky-light source'),
    ('MOON',     'n',   'the nighttime sky-light'),
    ('STAR',     'n',   'small sky-light'),
    ('SKY',      'n',   'the dome overhead'),
    ('CLOUD',    'n',   'visible water vapor mass'),
    ('RAIN',     'n',   'water falling from sky'),
    ('WIND',     'n',   'moving air'),
    ('EARTH',    'n',   'ground, soil, the world'),
    ('STONE',    'n',   'rock, hard mineral mass'),
    ('MOUNTAIN', 'n',   'large elevated landmass'),
    ('RIVER',    'n',   'flowing fresh water'),
    ('SEA',      'n',   'large body of salt water'),

    # Plants and animals
    ('TREE',     'n',   'large woody plant'),
    ('FLOWER',   'n',   'reproductive plant part, colorful'),
    ('LEAF',     'n',   'flat green plant part'),
    ('SEED',     'n',   'plant reproductive unit'),
    ('ANIMAL',   'n',   'non-human living creature'),
    ('BIRD',     'n',   'feathered flying animal'),
    ('FISH',     'n',   'water-dwelling animal'),
    ('DOG',      'n',   'the domesticated canine'),
    ('EGG',      'n',   'reproductive vessel of birds/reptiles/insects'),

    # Food & drink
    ('FOOD',     'n',   'that which is eaten'),
    ('MEAT',     'n',   'animal flesh as food'),
    ('FRUIT',    'n',   'edible plant reproductive body'),
    ('SALT',     'n',   'the seasoning mineral'),
    ('EAT',      'v',   'take food into the body'),
    ('DRINK',    'v',   'take liquid into the body'),

    # Actions
    ('COME',     'v',   'move toward speaker/reference point'),
    ('STAND',    'v',   'be upright on feet'),
    ('SIT',      'v',   'rest on buttocks'),
    ('LIE',      'v',   'be horizontal, resting'),
    ('SLEEP',    'v',   'be unconscious in rest'),
    ('WAKE',     'v',   'cease sleeping'),
    ('RUN',      'v',   'move fast on feet'),
    ('WALK',     'v',   'move at steady pace on feet'),
    ('FLY',      'v',   'move through air'),
    ('SWIM',     'v',   'move through water'),
    ('HEAR',     'v',   'perceive sound'),
    ('KNOW',     'v',   'hold as true'),
    ('THINK',    'v',   'run a mental process'),
    ('WANT',     'v',   'desire'),
    ('SAY',      'v',   'produce speech'),
    ('GIVE',     'v',   'transfer possession to another'),
    ('TAKE',     'v',   'acquire possession'),
    ('MAKE',     'v',   'cause to exist, create'),
    ('KILL',     'v',   'cause to die'),
    ('DIE',      'v',   'cease to live'),
    ('LIVE',     'v',   'be alive'),
    ('LOVE',     'v',   'feel strong positive bond'),

    # Qualities
    ('BIG',      'adj', 'large in size'),
    ('SMALL',    'adj', 'little in size'),
    ('LONG',     'adj', 'extended in length/time'),
    ('SHORT',    'adj', 'not extended in length/time'),
    ('HOT',      'adj', 'high temperature'),
    ('COLD',     'adj', 'low temperature'),
    ('NEW',      'adj', 'recently existing'),
    ('OLD',      'adj', 'long existing'),
    ('BAD',      'adj', 'negatively evaluated'),
    ('HEAVY',    'adj', 'great mass under gravity'),
    ('LIGHT',    'adj', 'little mass under gravity; or full of light'),
    ('BLACK',    'adj', 'the color of no light'),
    ('WHITE',    'adj', 'the color of all light'),
    ('RED',      'adj', 'color of blood'),
    ('BLUE',     'adj', 'color of clear sky'),
    ('GREEN',    'adj', 'color of fresh leaves'),
    ('YELLOW',   'adj', 'color of sun'),

    # Number & quantity
    ('ONE',      'n',   'the number 1 / single instance'),
    ('TWO',      'n',   'the number 2'),
    ('MANY',     'adj', 'a large quantity'),
    ('ALL',      'gram','the entire set'),

    # Deixis / grammatical
    ('THIS',     'pro', 'the near thing'),
    ('THAT',     'pro', 'the far thing'),
    ('HERE',     'pro', 'the near place'),
    ('THERE',    'pro', 'the far place'),
    ('WHO',      'pro', 'person interrogative'),
    ('WHAT',     'pro', 'thing interrogative'),
    ('WHERE',    'pro', 'place interrogative'),

    # Time
    ('DAY',      'n',   'period of daylight / 24h cycle'),
    ('NIGHT',    'n',   'period of darkness'),
    ('NOW',      'gram','present moment'),
    ('PAST',     'gram','time before now'),
    ('FUTURE',   'gram','time after now'),

    # Logic
    ('YES',      'gram','affirmation'),
    ('AND',      'gram','conjunction of two items'),
    ('IF',       'gram','conditional marker'),
]


# ─── TIER FULL ──────────────────────────────────────────────
# The full ~600-concept toy dictionary. Superset of TIER_100.
# Organized by semantic domain to make editing easy; order is
# not semantically meaningful.

TIER_FULL_ADDITIONS = [
    # People & kinship (beyond TIER_100)
    ('BOY',          'n',   'young male human'),
    ('GIRL',         'n',   'young female human'),
    ('BABY',         'n',   'infant human'),
    ('ELDER',        'n',   'aged person'),
    ('YOUTH',        'n',   'young adult'),
    ('HE',           'pro', 'singular male third person'),
    ('SHE',          'pro', 'singular female third person'),
    ('IT',           'pro', 'singular non-person third person'),
    ('SELF',         'pro', 'the referent itself'),
    ('SOMEONE',      'pro', 'an unspecified person'),
    ('NOBODY',       'pro', 'no person at all'),
    ('PARENT',       'n',   'either mother or father'),
    ('SON',          'n',   'male offspring'),
    ('DAUGHTER',     'n',   'female offspring'),
    ('SIBLING',      'n',   'brother or sister'),
    ('BROTHER',      'n',   'male sibling'),
    ('SISTER',       'n',   'female sibling'),
    ('SPOUSE',       'n',   'marriage partner'),
    ('HUSBAND',      'n',   'male spouse'),
    ('WIFE',         'n',   'female spouse'),
    ('GRANDPARENT',  'n',   'parent of parent'),
    ('GRANDCHILD',   'n',   'child of child'),
    ('COUSIN',       'n',   'child of parent-sibling'),
    ('ANCESTOR',     'n',   'forebear'),
    ('DESCENDANT',   'n',   'direct-line offspring'),
    ('FAMILY',       'n',   'kinship group'),
    ('CLAN',         'n',   'extended kinship group'),
    ('TRIBE',        'n',   'larger social grouping'),
    ('PEOPLE',       'n',   'plural of person; a populace'),
    ('CROWD',        'n',   'many people together'),
    ('ENEMY',        'n',   'hostile other'),
    ('STRANGER',     'n',   'unknown person'),
    ('GUEST',        'n',   'visitor received'),
    ('HOST',         'n',   'receiver of guest'),
    ('LEADER',       'n',   'one who leads'),
    ('TEACHER',      'n',   'one who instructs'),
    ('STUDENT',      'n',   'one who learns'),
    ('HEALER',       'n',   'one who heals others'),
    ('WARRIOR',      'n',   'one who fights'),
    ('HUNTER',       'n',   'one who pursues animals for food'),
    ('FARMER',       'n',   'one who cultivates land'),
    ('TRADER',       'n',   'one who exchanges goods'),
    ('SERVANT',      'n',   'one who serves another'),
    ('NEIGHBOR',     'n',   'one living nearby'),

    # Body (beyond TIER_100)
    ('FACE',         'n',   'front of head'),
    ('FOREHEAD',     'n',   'upper front of head'),
    ('CHEEK',        'n',   'side of face'),
    ('CHIN',         'n',   'lower front of face'),
    ('NOSE',         'n',   'organ of smell'),
    ('TONGUE',       'n',   'organ of taste and speech'),
    ('TOOTH',        'n',   'hard structure for chewing'),
    ('LIP',          'n',   'mouth border'),
    ('NECK',         'n',   'between head and body'),
    ('SHOULDER',     'n',   'joint of arm and body'),
    ('ARM',          'n',   'upper limb'),
    ('ELBOW',        'n',   'middle arm joint'),
    ('WRIST',        'n',   'hand-arm joint'),
    ('FINGER',       'n',   'digit of hand'),
    ('THUMB',        'n',   'opposable digit'),
    ('NAIL',         'n',   'hard plate on digit'),
    ('PALM',         'n',   'inner hand surface'),
    ('CHEST',        'n',   'upper torso front'),
    ('BACK',         'n',   'torso rear'),
    ('BELLY',        'n',   'torso front lower; abdomen'),
    ('WAIST',        'n',   'mid-torso narrowing'),
    ('HIP',          'n',   'torso-leg joint'),
    ('LEG',          'n',   'lower limb'),
    ('KNEE',         'n',   'middle leg joint'),
    ('THIGH',        'n',   'upper leg'),
    ('HEEL',         'n',   'back of foot'),
    ('TOE',          'n',   'digit of foot'),
    ('MUSCLE',       'n',   'contractile flesh'),
    ('BRAIN',        'n',   'organ of cognition'),
    ('LUNG',         'n',   'organ of breathing'),
    ('LIVER',        'n',   'major metabolic organ'),
    ('STOMACH',      'n',   'digestive sac'),
    ('BREAST',       'n',   'chest gland (esp. female)'),
    ('GENITALS',     'n',   'reproductive organs'),
    ('TEAR',         'n',   'eye water of emotion'),
    ('SWEAT',        'n',   'skin water of heat/effort'),
    ('SALIVA',       'n',   'mouth fluid'),
    ('URINE',        'n',   'body waste fluid'),
    ('FECES',        'n',   'body solid waste'),
    ('VOICE',        'n',   'sound of speaking'),
    ('BREATH',       'n',   'act/substance of breathing'),
    ('PULSE',        'n',   'rhythm of heartbeat'),

    # Animals
    ('CAT',          'n',   'the small domesticated feline'),
    ('COW',          'n',   'the large domesticated bovine'),
    ('HORSE',        'n',   'the riding/draft equid'),
    ('PIG',          'n',   'the domesticated swine'),
    ('SHEEP',        'n',   'the wool-producing ovine'),
    ('GOAT',         'n',   'the horned caprine'),
    ('CHICKEN',      'n',   'the domesticated fowl'),
    ('DUCK',         'n',   'the water fowl'),
    ('WOLF',         'n',   'the wild canine'),
    ('LION',         'n',   'the great cat'),
    ('BEAR',         'n',   'the ursine mammal'),
    ('DEER',         'n',   'the antlered mammal'),
    ('RABBIT',       'n',   'the long-eared lagomorph'),
    ('MOUSE',        'n',   'the small rodent'),
    ('MONKEY',       'n',   'the non-human primate'),
    ('ELEPHANT',     'n',   'the large-trunked mammal'),
    ('SNAKE',        'n',   'the legless reptile'),
    ('LIZARD',       'n',   'the small legged reptile'),
    ('FROG',         'n',   'the tailless amphibian'),
    ('TURTLE',       'n',   'the shelled reptile'),
    ('EAGLE',        'n',   'the large raptor'),
    ('OWL',          'n',   'the nocturnal raptor'),
    ('INSECT',       'n',   'the small six-legged arthropod'),
    ('SPIDER',       'n',   'the eight-legged arachnid'),
    ('BEE',          'n',   'the honey-making insect'),
    ('ANT',          'n',   'the social small insect'),
    ('FLY_INSECT',   'n',   'the winged pest insect'),
    ('MOSQUITO',     'n',   'the biting small dipteran'),
    ('BUTTERFLY',    'n',   'the showy-winged lepidopteran'),
    ('WORM',         'n',   'the long soft invertebrate'),
    ('WHALE',        'n',   'the large aquatic mammal'),
    ('SHARK',        'n',   'the cartilaginous fish'),
    ('NEST',         'n',   'animal-built home'),
    ('HIVE',         'n',   'bee colony structure'),
    ('FUR',          'n',   'mammal body hair covering'),
    ('FEATHER',      'n',   'bird body covering'),
    ('SCALE',        'n',   'fish/reptile body plate'),
    ('CLAW',         'n',   'sharp digit of animal'),
    ('HORN',         'n',   'bony head projection'),
    ('TAIL',         'n',   'rear body extension'),
    ('WING',         'n',   'flight appendage'),
    ('BEAK',         'n',   'bird mouthpart'),

    # Plants
    ('PLANT',        'n',   'non-animal growing organism'),
    ('GRASS',        'n',   'the common ground-cover plant'),
    ('ROOT',         'n',   'underground plant anchor'),
    ('STEM',         'n',   'main plant shaft'),
    ('BRANCH',       'n',   'tree limb'),
    ('BARK',         'n',   'outer tree layer'),
    ('VEGETABLE',    'n',   'edible plant part (non-fruit)'),
    ('MUSHROOM',     'n',   'the fungus body'),
    ('MOSS',         'n',   'the soft ground plant'),
    ('WEED',         'n',   'unwanted plant'),
    ('BUSH',         'n',   'small woody plant'),
    ('VINE',         'n',   'climbing plant'),
    ('FOREST',       'n',   'tree-dominated land'),
    ('MEADOW',       'n',   'grass-dominated land'),
    ('FIELD',        'n',   'cultivated or open land'),
    ('GARDEN',       'n',   'cultivated plot'),
    ('GRAIN',        'n',   'cereal seed as food'),
    ('NUT',          'n',   'hard-shelled seed'),
    ('BERRY',        'n',   'small soft fruit'),
    ('HERB',         'n',   'flavoring or medicinal plant'),

    # Nature / elements
    ('SNOW',         'n',   'frozen precipitation'),
    ('ICE',          'n',   'frozen water'),
    ('FROST',        'n',   'surface ice crystals'),
    ('DEW',          'n',   'morning surface water'),
    ('FOG',          'n',   'ground-level cloud'),
    ('STORM',        'n',   'violent weather'),
    ('LIGHTNING',    'n',   'sky electrical flash'),
    ('THUNDER',      'n',   'lightning sound'),
    ('RAINBOW',      'n',   'sky color arc'),
    ('SAND',         'n',   'fine rock grains'),
    ('DUST',         'n',   'fine dry particles'),
    ('MUD',          'n',   'wet earth'),
    ('CLAY',         'n',   'moldable fine earth'),
    ('HILL',         'n',   'small mountain'),
    ('VALLEY',       'n',   'low land between heights'),
    ('CAVE',         'n',   'natural hollow in rock'),
    ('CLIFF',        'n',   'sheer rock face'),
    ('LAKE',         'n',   'enclosed body of fresh water'),
    ('OCEAN',        'n',   'the greatest salt water body'),
    ('STREAM',       'n',   'small flowing water'),
    ('POND',         'n',   'small still water'),
    ('SPRING',       'n',   'water emerging from ground'),
    ('WELL',         'n',   'dug water source'),
    ('WATERFALL',    'n',   'water falling over cliff'),
    ('ISLAND',       'n',   'land surrounded by water'),
    ('SHORE',        'n',   'land-water boundary'),
    ('DAWN',         'n',   'first light'),
    ('DUSK',         'n',   'last light'),
    ('NOON',         'n',   'middle of day'),
    ('MIDNIGHT',     'n',   'middle of night'),
    ('SEASON',       'n',   'recurring yearly weather period'),
    ('SUMMER',       'n',   'hot season'),
    ('WINTER',       'n',   'cold season'),
    ('SPRING_SEASON','n',   'growing season after winter'),
    ('AUTUMN',       'n',   'leaf-falling season'),
    ('SHADOW',       'n',   'absence of light behind object'),
    ('REFLECTION',   'n',   'mirror image'),
    ('ECHO',         'n',   'reflected sound'),

    # Time
    ('TIME',         'n',   'duration/sequence concept'),
    ('MOMENT',       'n',   'very short time'),
    ('ETERNITY',     'n',   'unlimited time'),
    ('MORNING',      'n',   'start of day'),
    ('EVENING',      'n',   'end of day'),
    ('HOUR',         'n',   'unit of 1/24 day'),
    ('WEEK',         'n',   'unit of ~7 days'),
    ('MONTH',        'n',   'unit of ~30 days'),
    ('YEAR',         'n',   'unit of ~365 days'),
    ('YESTERDAY',    'n',   'the previous day'),
    ('TODAY',        'n',   'the present day'),
    ('TOMORROW',     'n',   'the next day'),
    ('BEFORE',       'gram','temporal/ordinal priority'),
    ('AFTER',        'gram','temporal/ordinal posterity'),
    ('SOON',         'adj', 'in a short time'),
    ('LATE',         'adj', 'after expected time'),
    ('EARLY',        'adj', 'before expected time'),
    ('ALWAYS',       'gram','at all times'),
    ('NEVER',        'gram','at no time'),
    ('SOMETIMES',    'gram','at some times'),
    ('OFTEN',        'gram','at many times'),
    ('BEGINNING',    'n',   'start of something'),
    ('END',          'n',   'finish of something'),
    ('MIDDLE',       'n',   'center of something'),
    ('AGAIN',        'gram','repeated occurrence'),

    # Space / direction
    ('PLACE',        'n',   'location'),
    ('WORLD',        'n',   'everything that exists around us'),
    ('EVERYWHERE',   'pro', 'in all places'),
    ('NOWHERE',      'pro', 'in no place'),
    ('UP',           'gram','toward higher position'),
    ('DOWN',         'gram','toward lower position'),
    ('LEFT',         'gram','one side relative to body'),
    ('RIGHT_DIR',    'gram','opposite side relative to body'),
    ('FRONT',        'n',   'facing side'),
    ('BACK_SIDE',    'n',   'opposite of front'),
    ('NORTH',        'n',   'one cardinal direction'),
    ('SOUTH',        'n',   'opposite of north'),
    ('EAST',         'n',   'direction of sunrise'),
    ('WEST',         'n',   'direction of sunset'),
    ('INSIDE',       'gram','within'),
    ('OUTSIDE',      'gram','beyond the boundary of'),
    ('ABOVE',        'gram','higher than'),
    ('BELOW',        'gram','lower than'),
    ('BESIDE',       'gram','next to'),
    ('BETWEEN',      'gram','with things on either side'),
    ('NEAR',         'adj', 'close in space/time'),
    ('FAR',          'adj', 'distant in space/time'),
    ('TOP',          'n',   'highest part'),
    ('BOTTOM',       'n',   'lowest part'),
    ('EDGE',         'n',   'boundary'),
    ('CENTER',       'n',   'middle point'),
    ('CORNER',       'n',   'meeting of two edges'),

    # Actions — motion
    ('MOVE',         'v',   'change position'),
    ('STOP',         'v',   'cease motion'),
    ('JUMP',         'v',   'push off ground'),
    ('CLIMB',        'v',   'move upward on a surface'),
    ('CRAWL',        'v',   'move on hands and knees'),
    ('FALL',         'v',   'move downward uncontrolled'),
    ('RISE',         'v',   'move upward'),
    ('TURN',         'v',   'rotate or change direction'),
    ('ENTER',        'v',   'move into'),
    ('LEAVE',        'v',   'move out of'),
    ('ARRIVE',       'v',   'reach destination'),
    ('DEPART',       'v',   'start going away'),
    ('FOLLOW',       'v',   'move after'),
    ('LEAD',         'v',   'move in front of, guiding'),
    ('CARRY',        'v',   'transport while moving'),
    ('BRING',        'v',   'transport toward'),
    ('THROW',        'v',   'propel through air'),
    ('CATCH',        'v',   'intercept moving object'),
    ('PUSH',         'v',   'apply force away'),
    ('PULL',         'v',   'apply force toward'),
    ('HIT',          'v',   'strike with force'),
    ('HOLD',         'v',   'keep in grasp'),
    ('DROP',         'v',   'release from grasp'),

    # Actions — manipulation
    ('OPEN',         'v',   'make not closed'),
    ('CLOSE',        'v',   'make not open'),
    ('BREAK',        'v',   'cause to become not whole'),
    ('FIX',          'v',   'restore to working order'),
    ('BUILD',        'v',   'construct'),
    ('DESTROY',      'v',   'render un-existent'),
    ('CUT',          'v',   'divide with sharp edge'),
    ('TEAR_RIP',     'v',   'divide by pulling'),
    ('SEW',          'v',   'join with thread'),
    ('TIE',          'v',   'join with rope/cord'),
    ('BEND',         'v',   'curve from straight'),
    ('FOLD',         'v',   'double over'),

    # Actions — sensory
    ('LOOK',         'v',   'direct vision intentionally'),
    ('LISTEN',       'v',   'direct hearing intentionally'),
    ('SMELL',        'v',   'perceive odor'),
    ('TASTE',        'v',   'perceive flavor'),
    ('TOUCH',        'v',   'make physical contact'),
    ('FEEL',         'v',   'perceive tactilely or emotionally'),

    # Actions — cognition
    ('REMEMBER',     'v',   'recall from memory'),
    ('FORGET',       'v',   'fail to recall'),
    ('LEARN',        'v',   'acquire knowledge'),
    ('TEACH',        'v',   'impart knowledge'),
    ('UNDERSTAND',   'v',   'grasp meaning'),
    ('BELIEVE',      'v',   'hold as true without certainty'),
    ('DOUBT',        'v',   'hold as possibly untrue'),
    ('DREAM',        'v',   'have sleep-images'),
    ('IMAGINE',      'v',   'form mental image'),
    ('CHOOSE',       'v',   'select among options'),
    ('GUESS',        'v',   'select without enough info'),

    # Actions — communication
    ('SPEAK',        'v',   'use language in speech'),
    ('TELL',         'v',   'convey information'),
    ('ASK',          'v',   'request information'),
    ('ANSWER',       'v',   'reply to question'),
    ('SHOUT',        'v',   'speak loudly'),
    ('WHISPER',      'v',   'speak very softly'),
    ('LAUGH',        'v',   'express amusement aloud'),
    ('CRY',          'v',   'weep'),
    ('SMILE',        'v',   'express pleasure facially'),
    ('SING',         'v',   'produce musical voice'),
    ('DANCE',        'v',   'move rhythmically to music'),
    ('GREET',        'v',   'acknowledge meeting'),
    ('THANK',        'v',   'express gratitude'),
    ('APOLOGIZE',    'v',   'express regret for wrong'),
    ('PROMISE',      'v',   'commit to future action'),
    ('LIE_FALSE',    'v',   'say what is not true'),

    # Actions — emotion / desire
    ('HATE',         'v',   'feel strong negative bond'),
    ('LIKE',         'v',   'find agreeable'),
    ('FEAR',         'v',   'feel danger-response'),
    ('HOPE',         'v',   'desire with expectation'),
    ('NEED',         'v',   'require for wellbeing'),
    ('ENJOY',        'v',   'take pleasure in'),
    ('MISS',         'v',   'feel absence'),

    # Actions — life
    ('BE_BORN',      'v',   'begin to live'),
    ('GROW',         'v',   'increase in size/age'),
    ('BREATHE',      'v',   'take air in and out'),
    ('BLEED',        'v',   'lose blood'),
    ('HURT',         'v',   'cause or feel pain'),
    ('HEAL',         'v',   'become whole again'),

    # Actions — social
    ('WORK',         'v',   'do productive activity'),
    ('PLAY',         'v',   'engage in enjoyable activity'),
    ('REST',         'v',   'stop activity to recover'),
    ('HUNT',         'v',   'pursue animals for food'),
    ('GATHER',       'v',   'collect from environment'),
    ('COOK',         'v',   'prepare food with heat'),
    ('FARM',         'v',   'cultivate land'),
    ('TRADE',        'v',   'exchange goods'),
    ('BUY',          'v',   'acquire via payment'),
    ('SELL',         'v',   'transfer via payment'),
    ('HELP',         'v',   'aid another'),
    ('HARM',         'v',   'damage another'),
    ('PROTECT',      'v',   'defend from harm'),
    ('ATTACK',       'v',   'initiate hostile action'),
    ('DEFEND',       'v',   'resist attack'),
    ('FIGHT',        'v',   'engage in combat'),
    ('SAVE',         'v',   'preserve from destruction'),
    ('WASH',         'v',   'clean with water'),
    ('CLEAN',        'v',   'remove dirt'),
    ('COUNT',        'v',   'enumerate'),
    ('MEASURE',      'v',   'determine quantity'),
    ('COMPARE',      'v',   'assess similarity/difference'),

    # Qualities — size, shape
    ('TALL',         'adj', 'great in vertical extent'),
    ('WIDE',         'adj', 'great in horizontal extent'),
    ('NARROW',       'adj', 'little in horizontal extent'),
    ('THICK',        'adj', 'great in cross section'),
    ('THIN',         'adj', 'little in cross section'),
    ('DEEP',         'adj', 'great in downward extent'),
    ('SHALLOW',      'adj', 'little in downward extent'),
    ('HIGH',         'adj', 'far above a reference'),
    ('LOW',          'adj', 'near the ground / below a reference'),
    ('ROUND',        'adj', 'circular or spherical'),
    ('STRAIGHT',     'adj', 'not curved'),
    ('CURVED',       'adj', 'not straight'),
    ('FLAT',         'adj', 'with even surface'),
    ('SMOOTH',       'adj', 'without surface roughness'),
    ('ROUGH',        'adj', 'with irregular surface'),
    ('SHARP',        'adj', 'with fine cutting edge/point'),
    ('DULL',         'adj', 'without sharp edge; or not bright'),

    # Qualities — state
    ('HARD',         'adj', 'resisting deformation'),
    ('SOFT',         'adj', 'yielding to deformation'),
    ('WET',          'adj', 'containing liquid'),
    ('DRY',          'adj', 'without liquid'),
    ('FULL',         'adj', 'containing all it can'),
    ('EMPTY',        'adj', 'containing nothing'),
    ('WARM',         'adj', 'mildly hot'),
    ('COOL',         'adj', 'mildly cold'),
    ('CLEAN_ADJ',    'adj', 'free of dirt'),
    ('DIRTY',        'adj', 'containing dirt'),
    ('SICK',         'adj', 'not healthy'),
    ('HEALTHY',      'adj', 'in good bodily state'),
    ('STRONG',       'adj', 'having power'),
    ('WEAK',         'adj', 'lacking power'),
    ('ALIVE',        'adj', 'living'),
    ('DEAD',         'adj', 'not living'),
    ('AWAKE',        'adj', 'not sleeping'),
    ('ASLEEP',       'adj', 'sleeping'),
    ('HUNGRY',       'adj', 'needing food'),
    ('THIRSTY',      'adj', 'needing drink'),
    ('TIRED',        'adj', 'needing rest'),

    # Qualities — color (beyond TIER_100)
    ('GREY',         'adj', 'between black and white'),
    ('BROWN',        'adj', 'color of earth/bark'),
    ('ORANGE',       'adj', 'color between red and yellow'),
    ('PURPLE',       'adj', 'color between red and blue'),
    ('PINK',         'adj', 'pale red'),
    ('BRIGHT',       'adj', 'emitting or reflecting much light'),
    ('DARK',         'adj', 'with little light'),
    ('SHINY',        'adj', 'reflecting light vividly'),

    # Qualities — flavor / smell
    ('SWEET',        'adj', 'sugar-tasting'),
    ('BITTER',       'adj', 'quinine-tasting'),
    ('SOUR',         'adj', 'acid-tasting'),
    ('SALTY',        'adj', 'salt-tasting'),
    ('SPICY',        'adj', 'strongly flavored, pungent'),
    ('BLAND',        'adj', 'without strong flavor'),
    ('FRAGRANT',     'adj', 'pleasantly smelling'),
    ('FOUL',         'adj', 'unpleasantly smelling'),

    # Qualities — value / truth
    ('TRUE',         'adj', 'corresponding to reality'),
    ('FALSE',        'adj', 'not corresponding to reality'),
    ('RIGHT',        'adj', 'morally or factually correct'),
    ('WRONG',        'adj', 'morally or factually incorrect'),
    ('BEAUTIFUL',    'adj', 'aesthetically excellent'),
    ('UGLY',         'adj', 'aesthetically displeasing'),

    # Qualities — emotion
    ('HAPPY',        'adj', 'feeling positive emotion'),
    ('SAD',          'adj', 'feeling negative emotion of loss'),
    ('ANGRY',        'adj', 'feeling hostile agitation'),
    ('CALM',         'adj', 'without agitation'),
    ('SCARED',       'adj', 'feeling fear'),
    ('BRAVE',        'adj', 'not showing fear'),
    ('SHY',          'adj', 'avoiding social exposure'),
    ('PROUD',        'adj', 'feeling self-worth'),
    ('LONELY',       'adj', 'feeling unwanted alone'),
    ('JEALOUS',      'adj', 'resenting another\'s possession'),

    # Qualities — social
    ('KIND',         'adj', 'showing care for others'),
    ('CRUEL',        'adj', 'causing pain intentionally'),
    ('GENEROUS',     'adj', 'giving freely'),
    ('STINGY',       'adj', 'giving reluctantly'),
    ('HONEST',       'adj', 'telling truth'),
    ('WISE',         'adj', 'showing good judgment'),
    ('FOOLISH',      'adj', 'showing poor judgment'),

    # Qualities — speed / difficulty / relations
    ('FAST',         'adj', 'at high speed'),
    ('SLOW',         'adj', 'at low speed'),
    ('EASY',         'adj', 'requiring little effort'),
    ('DIFFICULT',    'adj', 'requiring much effort'),
    ('SAME',         'adj', 'identical'),
    ('DIFFERENT',    'adj', 'not identical'),
    ('SIMILAR',      'adj', 'mostly same'),
    ('OPPOSITE',     'adj', 'completely contrary'),

    # Quantity (beyond TIER_100)
    ('THREE',        'n',   'the number 3'),
    ('FOUR',         'n',   'the number 4'),
    ('FIVE',         'n',   'the number 5'),
    ('SIX',          'n',   'the number 6'),
    ('SEVEN',        'n',   'the number 7'),
    ('EIGHT',        'n',   'the number 8'),
    ('NINE',         'n',   'the number 9'),
    ('TEN',          'n',   'the number 10'),
    ('HUNDRED',      'n',   'the number 100'),
    ('THOUSAND',     'n',   'the number 1000'),
    ('HALF',         'n',   'one of two equal parts'),
    ('WHOLE',        'adj', 'complete, undivided'),
    ('FEW',          'adj', 'small number'),
    ('NONE',         'gram','zero quantity'),
    ('SOME',         'gram','small unspecified quantity'),
    ('ENOUGH',       'adj', 'sufficient'),
    ('MORE',         'gram','greater quantity'),
    ('LESS',         'gram','smaller quantity'),
    ('FIRST',        'adj', 'ordinal 1st'),
    ('LAST',         'adj', 'ordinal final'),
    ('NEXT',         'adj', 'immediately following'),

    # Pronouns / deixis (beyond TIER_100)
    ('THESE',        'pro', 'plural near things'),
    ('THOSE',        'pro', 'plural far things'),
    ('WHEN',         'pro', 'time interrogative'),
    ('WHY',          'pro', 'cause interrogative'),
    ('HOW',          'pro', 'manner interrogative'),
    ('SOMETHING',    'pro', 'an unspecified thing'),
    ('EVERYONE',     'pro', 'all people'),
    ('EVERYTHING',   'pro', 'all things'),
    ('NOTHING',      'pro', 'no thing'),

    # Grammatical (beyond TIER_100)
    ('NO',           'gram','negative answer'),
    ('MAYBE',        'gram','uncertain affirmation'),
    ('OR',           'gram','disjunction'),
    ('BUT',          'gram','adversative'),
    ('BECAUSE',      'gram','causal'),
    ('SO',           'gram','consequential'),
    ('THEN',         'gram','temporal/consequential'),
    ('CAN',          'gram','ability/possibility modal'),
    ('MUST',         'gram','necessity modal'),
    ('MAY',          'gram','permission/possibility modal'),
    ('SHOULD',       'gram','obligation modal'),
    ('WILL',         'gram','future/volition modal'),
    ('OF',           'gram','possession/relation'),
    ('WITH',         'gram','accompaniment/instrument'),
    ('WITHOUT',      'gram','absence of accompaniment'),
    ('FOR',          'gram','beneficiary/purpose'),
    ('FROM',         'gram','source'),
    ('TO',           'gram','destination'),
    ('BE',           'gram','copula / existence'),
    ('HAVE',         'gram','possession'),
    ('BECOME',       'gram','change of state'),
    ('EXIST',        'v',   'be real'),

    # Artifacts — dwelling
    ('HOUSE',        'n',   'permanent dwelling'),
    ('HUT',          'n',   'simple dwelling'),
    ('BUILDING',     'n',   'roofed structure'),
    ('TENT',         'n',   'portable cloth dwelling'),
    ('WALL',         'n',   'vertical barrier'),
    ('ROOF',         'n',   'top of building'),
    ('FLOOR',        'n',   'bottom surface of room'),
    ('DOOR',         'n',   'entry barrier'),
    ('WINDOW',       'n',   'wall opening for light'),
    ('ROOM',         'n',   'interior division'),
    ('STAIR',        'n',   'stepped passage'),
    ('LADDER',       'n',   'portable rung structure'),

    # Artifacts — furniture
    ('BED',          'n',   'sleeping furniture'),
    ('CHAIR',        'n',   'sitting furniture'),
    ('TABLE',        'n',   'flat-topped furniture'),
    ('LAMP',         'n',   'light-making device'),
    ('CANDLE',       'n',   'wax light'),
    ('MIRROR',       'n',   'reflective surface'),

    # Artifacts — containers & utensils
    ('BASKET',       'n',   'woven container'),
    ('BAG',          'n',   'flexible container'),
    ('BOX',          'n',   'rigid container'),
    ('POT',          'n',   'cooking container'),
    ('CUP',          'n',   'small drinking container'),
    ('BOWL',         'n',   'round open container'),
    ('PLATE',        'n',   'flat eating surface'),
    ('SPOON',        'n',   'scoop utensil'),
    ('KNIFE',        'n',   'cutting tool'),

    # Artifacts — clothing
    ('CLOTH',        'n',   'woven fabric'),
    ('SHIRT',        'n',   'upper-body garment'),
    ('DRESS',        'n',   'one-piece female garment'),
    ('TROUSERS',     'n',   'two-legged garment'),
    ('SHOE',         'n',   'foot covering'),
    ('HAT',          'n',   'head covering'),
    ('COAT',         'n',   'outer garment'),
    ('BELT',         'n',   'waist band'),

    # Artifacts — fastenings & fibres
    ('ROPE',         'n',   'thick fiber line'),
    ('STRING',       'n',   'thin fiber line'),
    ('NET',          'n',   'knotted mesh'),
    ('NEEDLE',       'n',   'fine piercing tool'),
    ('THREAD',       'n',   'fine sewing fiber'),

    # Artifacts — tools & weapons
    ('TOOL',         'n',   'implement for work'),
    ('HAMMER',       'n',   'striking tool'),
    ('AXE',          'n',   'chopping tool'),
    ('SAW',          'n',   'toothed cutting tool'),
    ('SHOVEL',       'n',   'digging tool'),
    ('WEAPON',       'n',   'tool for combat'),
    ('SWORD',        'n',   'long blade weapon'),
    ('SPEAR',        'n',   'pointed thrusting weapon'),
    ('BOW',          'n',   'arrow-launching weapon'),
    ('ARROW',        'n',   'projectile for bow'),
    ('SHIELD',       'n',   'defensive weapon'),
    ('TRAP',         'n',   'capture device'),

    # Artifacts — transport
    ('WHEEL',        'n',   'round rolling device'),
    ('CART',         'n',   'small wheeled vehicle'),
    ('BOAT',         'n',   'small water vehicle'),
    ('SHIP',         'n',   'large water vehicle'),
    ('BRIDGE',       'n',   'crossing structure'),
    ('ROAD',         'n',   'prepared path'),
    ('PATH',         'n',   'unprepared way'),

    # Artifacts — records & exchange
    ('BOOK',         'n',   'bound pages'),
    ('PAPER',        'n',   'flat writing material'),
    ('PEN',          'n',   'writing tool'),
    ('INK',          'n',   'writing liquid'),
    ('LETTER_MAIL',  'n',   'written message sent'),
    ('MAP',          'n',   'graphic of place'),
    ('CLOCK',        'n',   'time-measuring device'),
    ('COIN',         'n',   'metal money unit'),
    ('MONEY',        'n',   'medium of exchange'),

    # Food & drink (beyond TIER_100)
    ('MEAL',         'n',   'eating event'),
    ('BREAD',        'n',   'baked grain food'),
    ('MILK',         'n',   'mammal breast-fluid as food'),
    ('CHEESE',       'n',   'curdled milk food'),
    ('BUTTER',       'n',   'churned milk fat'),
    ('HONEY',        'n',   'bee-made sweet'),
    ('SUGAR',        'n',   'refined sweet'),
    ('OIL',          'n',   'plant/animal fat liquid'),
    ('SOUP',         'n',   'liquid food'),
    ('PORRIDGE',     'n',   'boiled-grain food'),
    ('WINE',         'n',   'fermented grape drink'),
    ('BEER',         'n',   'fermented grain drink'),
    ('TEA',          'n',   'steeped-leaf drink'),
    ('RAW',          'adj', 'not cooked'),
    ('COOKED',       'adj', 'prepared with heat'),
    ('RIPE',         'adj', 'ready for harvest/eating'),
    ('ROTTEN',       'adj', 'decomposed'),
    ('FRESH',        'adj', 'recently produced, not spoiled'),

    # Culture & society
    ('WORD',         'n',   'unit of language'),
    ('LANGUAGE',     'n',   'system of communication'),
    ('STORY',        'n',   'narrative'),
    ('SONG',         'n',   'sung composition'),
    ('MUSIC',        'n',   'organized sound art'),
    ('POEM',         'n',   'artistic verbal composition'),
    ('GAME',         'n',   'rule-bound play'),
    ('PRAYER',       'n',   'address to higher power'),
    ('BLESSING',     'n',   'wished good'),
    ('CURSE',        'n',   'wished harm'),
    ('OATH',         'n',   'solemn promise'),
    ('SECRET',       'n',   'hidden knowledge'),
    ('TRUTH',        'n',   'state of being true'),
    ('LIE_NOUN',     'n',   'falsehood stated as truth'),
    ('JOKE',         'n',   'humorous utterance'),
    ('QUESTION',     'n',   'utterance seeking answer'),
    ('LAW',          'n',   'enforced rule'),
    ('CUSTOM',       'n',   'traditional practice'),
    ('RULE',         'n',   'governing instruction'),
    ('RITUAL',       'n',   'formalized ceremonial action'),
    ('MARRIAGE',     'n',   'pair-bond institution'),
    ('FUNERAL',      'n',   'death-rite'),
    ('BIRTH',        'n',   'beginning of life'),
    ('FESTIVAL',     'n',   'celebration'),
    ('WAR',          'n',   'organized group combat'),
    ('PEACE',        'n',   'absence of war'),
    ('GIFT',         'n',   'given thing'),
    ('DEBT',         'n',   'owed obligation'),
    ('ART',          'n',   'expressive making'),
    ('CRAFT',        'n',   'skilled making'),
    ('KNOWLEDGE',    'n',   'that which is known'),
    ('WISDOM',       'n',   'good-judgment knowledge'),

    # Abstract / mental
    ('IDEA',         'n',   'mental content'),
    ('THOUGHT',      'n',   'single mental act'),
    ('MIND',         'n',   'seat of thought'),
    ('REASON',       'n',   'cause or rationality'),
    ('CAUSE',        'n',   'what produces effect'),
    ('EFFECT',       'n',   'what cause produces'),
    ('PURPOSE',      'n',   'intended outcome'),
    ('PLAN',         'n',   'ordered intent'),
    ('CHANCE',       'n',   'random possibility'),
    ('LUCK',         'n',   'favorable chance'),
    ('FATE',         'n',   'predetermined outcome'),
    ('FREEDOM',      'n',   'lack of constraint'),
    ('POWER',        'n',   'ability to act or compel'),
    ('COURAGE',      'n',   'strength against fear'),
    ('JOY',          'n',   'strong positive emotion'),
    ('SORROW',       'n',   'strong negative emotion of loss'),
    ('PAIN',         'n',   'unpleasant bodily feeling'),
    ('PLEASURE',     'n',   'pleasant feeling'),
    ('TRUST',        'n',   'confident reliance'),
    ('LIFE',         'n',   'state of being alive'),
    ('DEATH',        'n',   'state of ceasing to live'),
    ('SOUL',         'n',   'non-physical self'),
    ('SPIRIT',       'n',   'animating essence'),
    ('GOD',          'n',   'supreme being'),
    ('GHOST',        'n',   'spirit of the dead'),
    ('DREAM_NOUN',   'n',   'sleep-vision'),
    ('MEMORY',       'n',   'stored past experience'),
    ('HABIT',        'n',   'repeated practice'),
    ('JUSTICE',      'n',   'fairness in judgment'),
    ('MERCY',        'n',   'compassion in judgment'),
    ('HONOR',        'n',   'worth and esteem'),
    ('SHAME',        'n',   'feeling of unworth'),
]


# ─── Assembly ───────────────────────────────────────────────

TIER_100 = TIER_10 + TIER_100_ADDITIONS
TIER_FULL = TIER_100 + TIER_FULL_ADDITIONS


def as_dict(tier):
    """Turn one of the tier lists into {concept: (pos, gloss)}."""
    return {c: (pos, gloss) for c, pos, gloss in tier}


def concepts(tier):
    """Just the concept names in a tier, in order."""
    return [c for c, _pos, _gloss in tier]


if __name__ == '__main__':
    print(f'TIER_10:   {len(TIER_10):4d} concepts')
    print(f'TIER_100:  {len(TIER_100):4d} concepts')
    print(f'TIER_FULL: {len(TIER_FULL):4d} concepts')
