"""
Django settings for velour project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import getpass
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Landing zone for bulk job outputs arriving from Slurm / remote
# executors via rclone-over-SFTP. Conduit watches this directory for
# per-job subdirectories and surfaces results to app-side importers
# (Det, Naiad, Aether, etc.). One subdirectory per Job.slug.
VELOUR_RESULTS_DIR = Path(os.environ.get(
    'VELOUR_RESULTS_DIR',
    str(Path.home() / 'velour-results'),
))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# On a provisioned server, setup.sh writes a generated key to BASE_DIR/secret_key.txt
# (chmod 600, owned by the project user). Fall back to env var, then to the
# insecure dev default for local runserver sessions.
_secret_key_file = BASE_DIR / 'secret_key.txt'
if _secret_key_file.is_file():
    SECRET_KEY = _secret_key_file.read_text().strip()
else:
    SECRET_KEY = os.environ.get(
        'DJANGO_SECRET_KEY',
        'django-insecure-djorpl5_$%o*z6(+si93gmvz)j%4@%2whuxaug=umrtg-@p*+t',
    )

# Provisioning secret for /api/nodes/register — lets identical-firmware
# fleets (e.g. bodymap) self-register nodes instead of needing per-device
# admin entries. Follows the same file-then-env fallback as SECRET_KEY so
# setup.sh can write a generated value to provisioning_secret.txt. When
# the secret is empty, /api/nodes/register returns 503 and registration
# is effectively disabled — that's the default for existing deployments
# so opting in requires an explicit action.
_provisioning_file = BASE_DIR / 'provisioning_secret.txt'
if _provisioning_file.is_file():
    VELOUR_PROVISIONING_SECRET = _provisioning_file.read_text().strip()
else:
    VELOUR_PROVISIONING_SECRET = os.environ.get('VELOUR_PROVISIONING_SECRET', '')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'True').lower() in ('true', '1', 'yes')

ALLOWED_HOSTS = os.environ.get('DJANGO_ALLOWED_HOSTS', '*,localhost,127.0.0.1').split(',')


# Application definition

INSTALLED_APPS = [
    # `daphne` must precede `django.contrib.staticfiles` so its
    # ASGI-aware runserver overrides Django's WSGI one. Required for
    # the web terminal's WebSocket consumer to handshake correctly.
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'channels',
    'dashboard',
    'terminal',
    'app_factory',
    'sysinfo',
    'agricola',
    'graphs',
    'services',
    'logs',
    'identity',
    'security',
    'landingpage',
    'winctl',
    'maintenance',
    'hosts',
    'mail',
    'experiments',
    'nodes',
    'chronos',
    'databases',
    'codex',
    'attic',
    'cartography',
    'oracle',
    'hpc',
    'tiles',
    'condenser',
    'automaton',
    'aether',
    'lsystem',
    'legolith',
    'datalift',
    'bridge',
    'zoetrope',
    'reckoner',
    'screen_gubi',
    'grammar_engine',
    'evolution',
    'displacer',
    'casting',
    'bodymap',
    'powerlab',
    'roomplanner',
    'lingua',
    'agents',
    'det',
    'naiad',
    'conduit',
    'oneliner',
    'muka',
    'isolation',
    'radiant',
    'camlfornia',
    'aggregator',
    'studious',
    'agora',
    'backups',
    'helix',
    'quill',
    'ledger',
]

MIDDLEWARE = [
    'django.middleware.gzip.GZipMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'velour.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'chronos.context_processors.topbar_clock',
                'identity.context_processors.topbar_pulse',
                'lingua.context_processors.lingua',
                'app_factory.context_processors.installed_app_slugs',
            ],
        },
    },
]

WSGI_APPLICATION = 'velour.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

# Media files (user uploads, codex figures, etc.). Like STATIC_ROOT,
# resolves to /var/www/webapps/<user>/media/ on a provisioned server,
# falls back to BASE_DIR/media/ in local dev.
MEDIA_URL = 'media/'
_media_prod_parent = Path(f'/var/www/webapps/{getpass.getuser()}')
if _media_prod_parent.is_dir():
    MEDIA_ROOT = _media_prod_parent / 'media'
else:
    MEDIA_ROOT = BASE_DIR / 'media'

# Codex Mermaid renderer talks to Kroki by default. Override with a
# self-hosted instance via the CODEX_KROKI_URL env var when desired.
CODEX_KROKI_URL = os.environ.get('CODEX_KROKI_URL', 'https://kroki.io')
# STATIC_ROOT resolves to /var/www/webapps/<user>/static/ on a provisioned
# server (where adminsetup.sh created the directory and chown'd it to the
# project user), matching the path nginx.conf serves from. Local dev — where
# no /var/www/webapps/<user>/ tree exists — falls back to the in-tree
# staticfiles/ directory so `runserver` still works without privileges.
_static_prod_parent = Path(f'/var/www/webapps/{getpass.getuser()}')
if _static_prod_parent.is_dir():
    STATIC_ROOT = _static_prod_parent / 'static'
else:
    STATIC_ROOT = BASE_DIR / 'staticfiles'

# Allow large JSON bodies: Aether's world_film endpoint POSTs batches of
# base64-encoded JPEG frames (a few MB is typical; 10s @ 30fps can be ~20MB).
DATA_UPLOAD_MAX_MEMORY_SIZE = 128 * 1024 * 1024

# Login/logout redirects
LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/'

# ASGI application for channels (web terminal)
ASGI_APPLICATION = 'velour.asgi.application'

# Email: the DynamicMailboxBackend reads the default MailAccount at send
# time, so EMAIL_BACKEND can be static here while the actual SMTP server,
# credentials, and From: address are all editable from /mailboxes/ in the
# web UI. If no account is configured (fresh install), the backend falls
# through to console output so local dev stays functional.
EMAIL_BACKEND = 'mail.backends.DynamicMailboxBackend'
DEFAULT_FROM_EMAIL = 'velour@example.com'

# Directory where the app factory writes newly generated projects. On a
# provisioned cloud server this lives under /var/www/webapps/<user>/apps/
# (a sibling of run/static/log, chown'd to the project user by
# adminsetup.sh). Locally — where no /var/www/webapps/<user>/ tree exists —
# it falls back to the parent of BASE_DIR so generated apps land next to
# the velour-dev checkout and the dev runserver continues to work without
# any privileged setup. DJANGO_APP_OUTPUT_DIR can override either.
_apps_prod_parent = Path(f'/var/www/webapps/{getpass.getuser()}')
if _apps_prod_parent.is_dir():
    APP_OUTPUT_DIR = os.environ.get(
        'APP_OUTPUT_DIR', str(_apps_prod_parent / 'apps'),
    )
else:
    APP_OUTPUT_DIR = os.environ.get('APP_OUTPUT_DIR', str(BASE_DIR.parent))
