# Generated by Django 6.0.4 on 2026-04-13 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('databases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiftJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('job_type', models.CharField(choices=[('convert', 'MySQL → Django + SQLite'), ('anonymize', 'Anonymize Database')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('source_host', models.CharField(default='localhost', max_length=300)),
                ('source_port', models.PositiveIntegerField(default=3306)),
                ('source_user', models.CharField(max_length=200)),
                ('source_password', models.CharField(blank=True, max_length=500)),
                ('source_database', models.CharField(max_length=200)),
                ('output_models_py', models.TextField(blank=True, help_text='Generated Django models.py')),
                ('output_sqlite', models.FileField(blank=True, upload_to='datalift/')),
                ('output_anonymized', models.FileField(blank=True, upload_to='datalift/anon/')),
                ('tables_found', models.PositiveIntegerField(default=0)),
                ('rows_converted', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_db_ref', models.ForeignKey(blank=True, help_text='Use connection from Databases app instead of manual entry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lift_jobs', to='databases.database')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
