# Generated by Django 6.0.4 on 2026-04-13 19:37
# Reworked 2026-04-24 to drop the hard cross-app FK to
# `databases.Database`. `source_db_ref` is now a plain
# PositiveIntegerField (storing the referenced row's PK) so datalift
# is portable to standalone Django projects that don't install the
# velour databases app. Lazy resolution lives on
# LiftJob.resolved_source_db.

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='LiftJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('job_type', models.CharField(choices=[('convert', 'MySQL → Django + SQLite'), ('anonymize', 'Anonymize Database')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('source_host', models.CharField(default='localhost', max_length=300)),
                ('source_port', models.PositiveIntegerField(default=3306)),
                ('source_user', models.CharField(max_length=200)),
                ('source_password', models.CharField(blank=True, max_length=500)),
                ('source_database', models.CharField(max_length=200)),
                ('output_models_py', models.TextField(blank=True, help_text='Generated Django models.py')),
                ('output_sqlite', models.FileField(blank=True, upload_to='datalift/')),
                ('output_anonymized', models.FileField(blank=True, upload_to='datalift/anon/')),
                ('tables_found', models.PositiveIntegerField(default=0)),
                ('rows_converted', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_db_ref', models.PositiveIntegerField(blank=True, help_text='PK of a `databases.Database` row to pull host/port/user/password/database from. Ignored silently if the databases app is not installed.', null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
