# Generated by Django 6.0.4 on 2026-04-29 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('cpu_pct', models.FloatField(default=0)),
                ('mem_used_mb', models.IntegerField(default=0)),
                ('mem_total_mb', models.IntegerField(default=0)),
                ('mem_used_pct', models.FloatField(default=0)),
                ('swap_used_mb', models.IntegerField(default=0)),
                ('swap_total_mb', models.IntegerField(default=0)),
                ('load1', models.FloatField(default=0)),
                ('load5', models.FloatField(default=0)),
                ('load15', models.FloatField(default=0)),
                ('entropy', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-ts'],
            },
        ),
    ]
