# Generated by Django 6.0.4 on 2026-04-17 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('experiments', '0001_initial'),
        ('nodes', '0005_node_self_registered'),
    ]

    operations = [
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('torso', 'Torso'), ('head', 'Head'), ('neck', 'Neck'), ('upper_arm_l', 'Upper arm (left)'), ('upper_arm_r', 'Upper arm (right)'), ('forearm_l', 'Forearm (left)'), ('forearm_r', 'Forearm (right)'), ('upper_leg_l', 'Upper leg (left)'), ('upper_leg_r', 'Upper leg (right)'), ('lower_leg_l', 'Lower leg (left)'), ('lower_leg_r', 'Lower leg (right)'), ('unassigned', 'Unassigned')], default='unassigned', max_length=16)),
                ('confidence', models.FloatField(default=0.0)),
                ('operator_locked', models.BooleanField(default=False, help_text="If True, the firmware's role reports are ignored. Set by an operator when clustering gets it wrong; clear to let the firmware re-assign.")),
                ('assigned_at', models.DateTimeField(auto_now=True)),
                ('experiment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bodymap_segments', to='experiments.experiment')),
                ('node', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bodymap_segment', to='nodes.node')),
            ],
            options={
                'ordering': ['role', 'node__slug'],
            },
        ),
        migrations.CreateModel(
            name='LinkObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peer_mac', models.CharField(max_length=17)),
                ('strength', models.FloatField()),
                ('observed_at', models.DateTimeField(auto_now_add=True)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_observations', to='nodes.node')),
            ],
            options={
                'ordering': ['-observed_at'],
                'indexes': [models.Index(fields=['reporter', 'observed_at'], name='bodymap_lin_reporte_352ffa_idx')],
            },
        ),
    ]
