# Generated by Django 6.0.4 on 2026-04-18 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodymap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttinyTemplate',
            fields=[
                ('slug', models.SlugField(max_length=80, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('summary', models.CharField(blank=True, max_length=240)),
                ('description', models.TextField(blank=True, help_text='Longer explanation shown on the template card and in the editor. Markdown-lite (paragraphs, not headings).')),
                ('mcu', models.CharField(choices=[('attiny85', 'ATtiny85'), ('attiny13a', 'ATtiny13a')], default='attiny85', max_length=12)),
                ('c_source', models.TextField()),
                ('pinout', models.TextField(blank=True, help_text='Free-text pin notes, e.g. "PB2 = pot, PB0 = PWM out".')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AttinyDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('mcu', models.CharField(choices=[('attiny85', 'ATtiny85'), ('attiny13a', 'ATtiny13a')], default='attiny85', max_length=12)),
                ('c_source', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('i2c_address', models.PositiveSmallIntegerField(default=8, help_text='7-bit I2C slave address (0x08–0x77). ESP reads this slot in the per-tick round-robin.')),
                ('compiled_hex', models.TextField(blank=True)),
                ('compile_log', models.TextField(blank=True)),
                ('compiled_at', models.DateTimeField(blank=True, null=True)),
                ('compile_ok', models.BooleanField(default=False)),
                ('program_bytes', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='designs', to='bodymap.attinytemplate')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
