# Generated by Django 6.0.4 on 2026-04-18 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodymap', '0002_attinytemplate_attinydesign'),
        ('nodes', '0005_node_self_registered'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeSensorConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channels', models.JSONField(blank=True, default=list, help_text='List of {channel, kind, ...} dicts. See class docstring for supported kinds and their params.')),
                ('notes', models.TextField(blank=True, help_text='Free-text operator notes — what is soldered where, which ATtiny design sits at which I2C address, etc.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('node', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bodymap_sensor_config', to='nodes.node')),
            ],
            options={
                'ordering': ['node__slug'],
            },
        ),
    ]
