# Generated by Django 6.0.4 on 2026-05-15 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhilologyProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('kind', models.CharField(choices=[('danwsi', 'DANWSI (NW Semitic)'), ('generic_django', 'Generic Django + Excel')], default='danwsi', max_length=40)),
                ('description', models.TextField(blank=True)),
                ('local_path', models.CharField(help_text='Absolute path to the local Django project (the dir containing manage.py).', max_length=500)),
                ('venv_python', models.CharField(help_text='Absolute path to the venv python (e.g. /home/x/proj/venv/bin/python).', max_length=500)),
                ('django_settings_module', models.CharField(help_text="DJANGO_SETTINGS_MODULE value for this project (e.g. 'danwsi_project.settings').", max_length=200)),
                ('data_dir_glob', models.CharField(default='Data_files*', help_text='Glob (relative to local_path) for data-drop directories.', max_length=200)),
                ('data_files_dir_env', models.CharField(default='DATA_FILES_DIR', help_text='Env var the ingest command honours to override the data-drop dir.', max_length=80)),
                ('ingest_command', models.CharField(default='ingest_ground_truth', help_text='manage.py command name that ingests a data drop.', max_length=200)),
                ('remote_host', models.CharField(blank=True, max_length=200)),
                ('remote_user', models.CharField(blank=True, max_length=100)),
                ('remote_path', models.CharField(blank=True, max_length=500)),
                ('remote_python', models.CharField(blank=True, help_text='Remote python path (e.g. /home/x/proj/venv/bin/python).', max_length=500)),
                ('ssh_key_path', models.CharField(blank=True, max_length=500)),
                ('deploy_script', models.CharField(blank=True, help_text='Path to the deploy script relative to local_path (e.g. deploy/deploy.sh).', max_length=500)),
                ('public_url', models.URLField(blank=True)),
                ('local_backup_dir', models.CharField(blank=True, help_text='Where to write local db.sqlite3 backups before risky operations.', max_length=500)),
                ('db_filename', models.CharField(default='db.sqlite3', help_text='Name of the sqlite database file inside the project root.', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('op', models.CharField(choices=[('ingest_local', 'Ingest (local)'), ('ingest_remote', 'Ingest (remote)'), ('deploy', 'Deploy code to remote'), ('backup_local', 'Backup local DB'), ('backup_remote', 'Backup remote DB'), ('restore_local', 'Restore local DB from backup'), ('restore_remote', 'Restore remote DB from backup')], max_length=40)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('ok', 'OK'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('data_dir', models.CharField(blank=True, help_text='For ingest ops: the data-drop dir name that was used.', max_length=300)),
                ('extra_args', models.TextField(blank=True)),
                ('exit_code', models.IntegerField(blank=True, null=True)),
                ('stdout', models.TextField(blank=True)),
                ('stderr', models.TextField(blank=True)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('backup_path', models.CharField(blank=True, max_length=500)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='scriptorium.philologyproject')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scriptorium_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['project', '-started_at'], name='scriptorium_project_fc21c4_idx'), models.Index(fields=['op', '-started_at'], name='scriptorium_op_6ca417_idx')],
            },
        ),
    ]
