# Generated by Django 6.0.4 on 2026-05-05 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Corpus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('url', models.URLField(blank=True)),
                ('license_summary', models.CharField(blank=True, help_text='Short human-readable license statement, e.g. "MIT (Microsoft GitHub release)" or "academic-only; sources extracted from public archive".', max_length=240)),
                ('notes_md', models.TextField(blank=True, help_text='Markdown notes on how to harvest this corpus, gotchas, what subset is in scope here.')),
                ('is_quarantined', models.BooleanField(default=False, help_text='If true, samples from this corpus need an explicit researcher gate before they render. Phase 2 feature; set on virus/worm corpora when we add them.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'corpora',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('family', models.CharField(choices=[('asm', 'Assembly'), ('c', 'C / C++'), ('forth', 'Forth'), ('lisp', 'Lisp / Scheme'), ('basic', 'BASIC'), ('shell', 'Shell / bash'), ('script', 'Perl / Python / Ruby / Tcl'), ('esoteric', 'Esoteric (BF, BLC, subleq…)'), ('other', 'Other')], default='other', max_length=12)),
                ('tier', models.CharField(choices=[('sub_512b', '≤ 512 bytes'), ('sub_4k', '≤ 4 KB'), ('sub_64k', '≤ 64 KB'), ('any', 'No tight bound')], default='any', max_length=10)),
                ('notes_md', models.TextField(blank=True, help_text='What this language is interesting for in viralyst — the trick that makes it produce small binaries, the historical context, where to learn it.')),
            ],
            options={
                'ordering': ['family', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('quine', 'Quine / self-reproducing'), ('virus', 'Virus (source / reconstruction only)'), ('worm', 'Worm (source / reconstruction only)'), ('utility', 'Classic utility (DOS/Unix)'), ('demo', 'Demo / intro'), ('runtime', 'Tiny runtime / language core'), ('golf', 'Code-golf entry'), ('snippet', 'Library snippet / idiom'), ('other', 'Other')], max_length=10)),
                ('year', models.IntegerField(blank=True, help_text='Year the program was published or first widely seen.', null=True)),
                ('author', models.CharField(blank=True, help_text='Free-text author/team. Leave blank for anonymous.', max_length=200)),
                ('origin_url', models.URLField(blank=True, help_text='Permalink to the canonical version (GitHub commit, archive.org item, museum page).')),
                ('license_override', models.CharField(blank=True, help_text='If the sample has a different licence to its corpus (e.g. one MIT file inside an otherwise-shareware CD), state it here. Otherwise leave blank.', max_length=160)),
                ('source_code', models.TextField(help_text='The full source — text only. Phase 1 stores no binaries.')),
                ('binary_size_bytes', models.PositiveIntegerField(blank=True, help_text='Original artifact size if known (DOS .COM size, stripped ELF size, .EXE size). Independent of source-code length.', null=True)),
                ('notes_md', models.TextField(blank=True, help_text='Markdown commentary — the "guided" part. What trick is the program using? What was the era? Why look at this one? Renders above the source on the detail page.')),
                ('is_quarantined', models.BooleanField(default=False, help_text='Set on samples that the researcher gate should hide until opted in. Default off — Phase 1 only seeds public-domain / permissive sources.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('corpus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='samples', to='viralyst.corpus')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='samples', to='viralyst.language')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
