"""Bulk seed: 45 additional illustrative sentences each for Dutch,
Mandarin Chinese, and Spanish — bringing each of those three priority
languages up to 50 trees total (1 from seed_world_languages +
4 from seed_priority_language_sentences + 45 here).

The trees stay intentionally simple: no abstract X-bar, no empty
categories, no movement traces. Labels and depth are chosen so a
student reading a standard reference grammar (Donaldson for Dutch,
Li & Thompson for Mandarin, Butt & Benjamin for Spanish) can match
the tree to the text directly.

Every entry is ``illustrative`` — author-composed using documented
morphology — with one citation per sentence pointing at the relevant
grammar-book section.

Run:      venv/bin/python manage.py seed_bulk_dutch_chinese_spanish
Re-run:   safe — each sentence is update_or_create'd on slug.
"""

from django.core.management.base import BaseCommand
from django.db import transaction

from muka.models import Language, Sentence
from muka.tree import parse_bracket


# ═════════════════════════════════════════════════════════════════════
# DUTCH — 45 additional trees
# ═════════════════════════════════════════════════════════════════════

DUTCH = [
    # ── Simple declaratives (8) ──────────────────────────────────────
    {'slug': 'nld-het-kind-speelt',
     'konso': 'het kind speelt',
     'gloss': 'the  child  play.PRES.3SG',
     'translation': 'The child plays.',
     'tree_bracket': '[S [NP [Det het] [N kind]] [VP [V speelt]]]',
     'notes': 'Neuter gender (het) with an intransitive verb.',
     'source': 'illustrative',
     'citation': 'Donaldson (2008), §3.1.'},
    {'slug': 'nld-de-vrouw-loopt-snel',
     'konso': 'de vrouw loopt snel',
     'gloss': 'the  woman  walk.PRES.3SG  fast',
     'translation': 'The woman walks fast.',
     'tree_bracket': ('[S [NP [Det de] [N vrouw]] '
                      '[VP [V loopt] [AdvP [Adv snel]]]]'),
     'notes': 'Manner adverb follows the finite verb in a V2 main clause.',
     'source': 'illustrative',
     'citation': 'Donaldson (2008), §16.2.'},
    {'slug': 'nld-de-hond-blaft-hard',
     'konso': 'de hond blaft hard',
     'gloss': 'the  dog  bark.PRES.3SG  hard',
     'translation': 'The dog barks loudly.',
     'tree_bracket': ('[S [NP [Det de] [N hond]] '
                      '[VP [V blaft] [AdvP [Adv hard]]]]'),
     'notes': 'Intensity adverb *hard* functions adverbially here.',
     'source': 'illustrative',
     'citation': 'Donaldson (2008), §16.1.'},
    {'slug': 'nld-de-zon-schijnt',
     'konso': 'de zon schijnt',
     'gloss': 'the  sun  shine.PRES.3SG',
     'translation': 'The sun shines.',
     'tree_bracket': '[S [NP [Det de] [N zon]] [VP [V schijnt]]]',
     'notes': 'Common-gender *de zon*; intransitive weather-ish verb.',
     'source': 'illustrative',
     'citation': 'Donaldson (2008), §3.2.'},
    {'slug': 'nld-het-regent-hard',
     'konso': 'het regent hard',
     'gloss': 'EXPL  rain.PRES.3SG  hard',
     'translation': 'It is raining hard.',
     'tree_bracket': ('[S [NP [Expl het]] '
                      '[VP [V regent] [AdvP [Adv hard]]]]'),
     'notes': 'Weather expletive *het* fills the subject slot.',
     'source': 'illustrative',
     'citation': 'Donaldson (2008), §11.8.'},
    {'slug': 'nld-wij-wonen-in-leiden',
     'konso': 'wij wonen in Leiden',
     'gloss': '1PL  live.PRES.1PL  in  Leiden',
     'translation': 'We live in Leiden.',
     'tree_bracket': ('[S [NP [Pron wij]] '
                      '[VP [V wonen] [PP [P in] [NP [N Leiden]]]]]'),
     'notes': 'Locative PP after the finite verb.',
     'source': 'illustrative',
     'citation': 'Donaldson (2008), §12.3.'},
    {'slug': 'nld-jan-koopt-een-fiets',
     'konso': 'Jan koopt een fiets',
     'gloss': 'Jan  buy.PRES.3SG  a  bicycle',
     'translation': 'Jan buys a bicycle.',
     'tree_bracket': ('[S [NP [N Jan]] '
                      '[VP [V koopt] [NP [Det een] [N fiets]]]]'),
     'notes': 'Indefinite article *een* (cf. numeral *één* with diacritic).',
     'source': 'illustrative',
     'citation': 'Donaldson (2008), §3.3.'},
    {'slug': 'nld-de-leraar-leest-een-boek',
     'konso': 'de leraar leest een boek',
     'gloss': 'the  teacher  read.PRES.3SG  a  book',
     'translation': 'The teacher reads a book.',
     'tree_bracket': ('[S [NP [Det de] [N leraar]] '
                      '[VP [V leest] [NP [Det een] [N boek]]]]'),
     'notes': 'Canonical SVO frame in a V2 main clause.',
     'source': 'illustrative',
     'citation': 'Donaldson (2008), §10.1.'},

    # ── V2 inversion (6) ─────────────────────────────────────────────
    {'slug': 'nld-gisteren-zag-ik-haar',
     'konso': 'gisteren zag ik haar',
     'gloss': 'yesterday  see.PST.1SG  1SG  3SG.F.ACC',
     'translation': 'Yesterday I saw her.',
     'tree_bracket': ('[S [AdvP [Adv gisteren]] '
                      '[V zag] [NP [Pron ik]] '
                      '[NP [Pron haar]]]'),
     'notes': 'Fronted time adverb triggers subject-verb inversion.',
     'source': 'illustrative',
     'citation': 'Broekhuis & Corver (2015), §9.1.'},
    {'slug': 'nld-vandaag-regent-het',
     'konso': 'vandaag regent het',
     'gloss': 'today  rain.PRES.3SG  EXPL',
     'translation': 'Today it rains.',
     'tree_bracket': ('[S [AdvP [Adv vandaag]] [V regent] '
                      '[NP [Expl het]]]'),
     'notes': 'Expletive *het* inverts with the verb under V2.',
     'source': 'illustrative',
     'citation': 'Donaldson (2008), §11.8.'},
    {'slug': 'nld-in-amsterdam-wonen-veel-mensen',
     'konso': 'in Amsterdam wonen veel mensen',
     'gloss': 'in  Amsterdam  live.PRES.3PL  many  people',
     'translation': 'In Amsterdam many people live.',
     'tree_bracket': ('[S [PP [P in] [NP [N Amsterdam]]] '
                      '[V wonen] '
                      '[NP [Q veel] [N mensen]]]'),
     'notes': 'Fronted PP in the first slot; bare plural subject follows.',
     'source': 'illustrative',
     'citation': 'Broekhuis & Corver (2015), §9.2.'},
    {'slug': 'nld-boeken-leest-hij-graag',
     'konso': 'boeken leest hij graag',
     'gloss': 'books  read.PRES.3SG  3SG.M  gladly',
     'translation': 'Books, he reads with pleasure.',
     'tree_bracket': ('[S [NP [N boeken]] '
                      '[V leest] [NP [Pron hij]] '
                      '[AdvP [Adv graag]]]'),
     'notes': 'Bare-plural object fronted for contrastive focus.',
     'source': 'illustrative',
     'citation': 'Broekhuis & Corver (2015), §11.4.'},
    {'slug': 'nld-dat-wist-ik-niet',
     'konso': 'dat wist ik niet',
     'gloss': 'that  know.PST.1SG  1SG  NEG',
     'translation': "That, I didn't know.",
     'tree_bracket': ('[S [NP [Dem dat]] '
                      '[V wist] [NP [Pron ik]] '
                      '[Neg niet]]'),
     'notes': 'Demonstrative object fronted; sentence negator *niet* last.',
     'source': 'illustrative',
     'citation': 'Donaldson (2008), §11.6.'},
    {'slug': 'nld-nu-begrijp-ik-het',
     'konso': 'nu begrijp ik het',
     'gloss': 'now  understand.PRES.1SG  1SG  3SG.N.ACC',
     'translation': 'Now I understand it.',
     'tree_bracket': ('[S [AdvP [Adv nu]] [V begrijp] '
                      '[NP [Pron ik]] [NP [Pron het]]]'),
     'notes': 'Neuter pronoun *het* as direct object.',
     'source': 'illustrative',
     'citation': 'Donaldson (2008), §8.1.'},

    # ── Modals (5) ───────────────────────────────────────────────────
    {'slug': 'nld-ik-kan-nederlands-spreken',
     'konso': 'ik kan Nederlands spreken',
     'gloss': '1SG  can.PRES.1SG  Dutch  speak.INF',
     'translation': 'I can speak Dutch.',
     'tree_bracket': ('[S [NP [Pron ik]] '
                      '[VP [Mod kan] '
                      '[VP [NP [N Nederlands]] [V spreken]]]]'),
     'notes': 'Modal *kunnen* + bare infinitive clause-final.',
     'source': 'illustrative',
     'citation': 'Donaldson (2008), §11.10.'},
    {'slug': 'nld-hij-moet-werken',
     'konso': 'hij moet werken',
     'gloss': '3SG.M  must.PRES.3SG  work.INF',
     'translation': 'He must work.',
     'tree_bracket': ('[S [NP [Pron hij]] '
                      '[VP [Mod moet] [V werken]]]'),
     'notes': 'Deontic *moeten* "must, have to".',
     'source': 'illustrative',
     'citation': 'Donaldson (2008), §11.10.'},
    {'slug': 'nld-wij-willen-blijven',
     'konso': 'wij willen blijven',
     'gloss': '1PL  want.PRES.1PL  stay.INF',
     'translation': 'We want to stay.',
     'tree_bracket': ('[S [NP [Pron wij]] '
                      '[VP [Mod willen] [V blijven]]]'),
     'notes': 'Volitional *willen*.',
     'source': 'illustrative',
     'citation': 'Donaldson (2008), §11.10.'},
    {'slug': 'nld-je-mag-komen',
     'konso': 'je mag komen',
     'gloss': '2SG  may.PRES.2SG  come.INF',
     'translation': 'You may come.',
     'tree_bracket': ('[S [NP [Pron je]] '
                      '[VP [Mod mag] [V komen]]]'),
     'notes': 'Permissive *mogen*; 2sg form is *mag*.',
     'source': 'illustrative',
     'citation': 'Donaldson (2008), §11.10.'},
    {'slug': 'nld-ze-zou-het-doen',
     'konso': 'ze zou het doen',
     'gloss': '3SG.F  would.PST.3SG  3SG.N.ACC  do.INF',
     'translation': 'She would do it.',
     'tree_bracket': ('[S [NP [Pron ze]] '
                      '[VP [Mod zou] [NP [Pron het]] [V doen]]]'),
     'notes': 'Conditional via *zou* (preterite of *zullen*) + infinitive.',
     'source': 'illustrative',
     'citation': 'Donaldson (2008), §11.10.'},

    # ── Perfect / past tenses (5) ────────────────────────────────────
    {'slug': 'nld-ik-heb-gegeten',
     'konso': 'ik heb gegeten',
     'gloss': '1SG  have.PRES.1SG  eat.PTCP',
     'translation': 'I have eaten.',
     'tree_bracket': ('[S [NP [Pron ik]] '
                      '[VP [Aux heb] [V gegeten]]]'),
     'notes': 'Present perfect with *hebben* + past participle.',
     'source': 'illustrative',
     'citation': 'Donaldson (2008), §11.3.'},
    {'slug': 'nld-zij-is-gekomen',
     'konso': 'zij is gekomen',
     'gloss': '3SG.F  be.PRES.3SG  come.PTCP',
     'translation': 'She has come.',
     'tree_bracket': ('[S [NP [Pron zij]] '
                      '[VP [Aux is] [V gekomen]]]'),
     'notes': 'Motion verbs take *zijn* as perfect auxiliary.',
     'source': 'illustrative',
     'citation': 'Donaldson (2008), §11.3.'},
    {'slug': 'nld-wij-hadden-het-gezien',
     'konso': 'wij hadden het gezien',
     'gloss': '1PL  have.PST.1PL  3SG.N.ACC  see.PTCP',
     'translation': 'We had seen it.',
     'tree_bracket': ('[S [NP [Pron wij]] '
                      '[VP [Aux hadden] '
                      '[NP [Pron het]] [V gezien]]]'),
     'notes': 'Pluperfect with *hebben* (past form *hadden*).',
     'source': 'illustrative',
     'citation': 'Donaldson (2008), §11.4.'},
    {'slug': 'nld-de-trein-is-vertrokken',
     'konso': 'de trein is vertrokken',
     'gloss': 'the  train  be.PRES.3SG  depart.PTCP',
     'translation': 'The train has left.',
     'tree_bracket': ('[S [NP [Det de] [N trein]] '
                      '[VP [Aux is] [V vertrokken]]]'),
     'notes': 'Change-of-state verb selects *zijn*.',
     'source': 'illustrative',
     'citation': 'Donaldson (2008), §11.3.'},
    {'slug': 'nld-ze-zijn-naar-huis-gegaan',
     'konso': 'ze zijn naar huis gegaan',
     'gloss': '3PL  be.PRES.3PL  to  home  go.PTCP',
     'translation': 'They have gone home.',
     'tree_bracket': ('[S [NP [Pron ze]] '
                      '[VP [Aux zijn] '
                      '[PP [P naar] [NP [N huis]]] '
                      '[V gegaan]]]'),
     'notes': 'PP wedged inside the Germanic brace; participle clause-final.',
     'source': 'illustrative',
     'citation': 'Donaldson (2008), §11.3.'},

    # ── Questions (5) ────────────────────────────────────────────────
    {'slug': 'nld-heb-je-honger',
     'konso': 'heb je honger?',
     'gloss': 'have.PRES.2SG  2SG  hunger',
     'translation': 'Are you hungry?',
     'tree_bracket': ('[S [V heb] [NP [Pron je]] '
                      '[NP [N honger]]]'),
     'notes': 'Yes/no question via subject-verb inversion; *honger hebben* is idiomatic.',
     'source': 'illustrative',
     'citation': 'Donaldson (2008), §22.2.'},
    {'slug': 'nld-wie-komt-er',
     'konso': 'wie komt er?',
     'gloss': 'who  come.PRES.3SG  EXPL',
     'translation': 'Who is coming?',
     'tree_bracket': ('[S [NP [Wh wie]] '
                      '[VP [V komt] [NP [Expl er]]]]'),
     'notes': 'Subject wh-question with an expletive *er* placeholder.',
     'source': 'illustrative',
     'citation': 'Donaldson (2008), §22.3.'},
    {'slug': 'nld-wat-doe-je',
     'konso': 'wat doe je?',
     'gloss': 'what  do.PRES.2SG  2SG',
     'translation': 'What are you doing?',
     'tree_bracket': ('[S [NP [Wh wat]] '
                      '[V doe] [NP [Pron je]]]'),
     'notes': 'Fronted wh-object; finite verb still V2.',
     'source': 'illustrative',
     'citation': 'Donaldson (2008), §22.3.'},
    {'slug': 'nld-waar-woon-je',
     'konso': 'waar woon je?',
     'gloss': 'where  live.PRES.2SG  2SG',
     'translation': 'Where do you live?',
     'tree_bracket': ('[S [AdvP [Wh waar]] '
                      '[V woon] [NP [Pron je]]]'),
     'notes': 'Locative wh-word *waar*; no do-support needed.',
     'source': 'illustrative',
     'citation': 'Donaldson (2008), §22.3.'},
    {'slug': 'nld-hoeveel-kost-het',
     'konso': 'hoeveel kost het?',
     'gloss': 'how-much  cost.PRES.3SG  3SG.N',
     'translation': 'How much does it cost?',
     'tree_bracket': ('[S [NP [Wh hoeveel]] '
                      '[V kost] [NP [Pron het]]]'),
     'notes': 'Quantitative wh-phrase *hoeveel* fronted.',
     'source': 'illustrative',
     'citation': 'Donaldson (2008), §22.3.'},

    # ── Subordinate clauses (5) ──────────────────────────────────────
    {'slug': 'nld-ik-denk-dat-hij-komt',
     'konso': 'ik denk dat hij komt',
     'gloss': '1SG  think.PRES.1SG  that  3SG.M  come.PRES.3SG',
     'translation': "I think that he's coming.",
     'tree_bracket': ('[S [NP [Pron ik]] '
                      '[VP [V denk] '
                      '[CP [C dat] '
                      '[S [NP [Pron hij]] [VP [V komt]]]]]]'),
     'notes': 'Subordinate *dat*-clause with verb-final order.',
     'source': 'illustrative',
     'citation': 'Broekhuis & Corver (2016), §14.2.'},
    {'slug': 'nld-ze-slaapt-omdat-ze-moe-is',
     'konso': 'ze slaapt omdat ze moe is',
     'gloss': '3SG.F  sleep.PRES.3SG  because  3SG.F  tired  be.PRES.3SG',
     'translation': "She sleeps because she's tired.",
     'tree_bracket': ('[S [NP [Pron ze]] '
                      '[VP [V slaapt] '
                      '[CP [C omdat] '
                      '[S [NP [Pron ze]] [VP [AP [A moe]] [V is]]]]]]'),
     'notes': 'Causal *omdat* governs verb-final subordinate.',
     'source': 'illustrative',
     'citation': 'Broekhuis & Corver (2016), §14.4.'},
    {'slug': 'nld-als-het-regent-blijf-ik-thuis',
     'konso': 'als het regent blijf ik thuis',
     'gloss': 'if  EXPL  rain.PRES.3SG  stay.PRES.1SG  1SG  home',
     'translation': 'If it rains, I stay home.',
     'tree_bracket': ('[S [CP [C als] '
                      '[S [NP [Expl het]] [VP [V regent]]]] '
                      '[V blijf] [NP [Pron ik]] '
                      '[AdvP [Adv thuis]]]'),
     'notes': 'Fronted *als*-clause fills the first slot; main verb is V2.',
     'source': 'illustrative',
     'citation': 'Broekhuis & Corver (2016), §14.5.'},
    {'slug': 'nld-toen-ik-klein-was-woonden-we-in-utrecht',
     'konso': 'toen ik klein was, woonden we in Utrecht',
     'gloss': 'when  1SG  small  be.PST.1SG  live.PST.1PL  1PL  in  Utrecht',
     'translation': 'When I was small, we lived in Utrecht.',
     'tree_bracket': ('[S [CP [C toen] '
                      '[S [NP [Pron ik]] '
                      '[VP [AP [A klein]] [V was]]]] '
                      '[V woonden] [NP [Pron we]] '
                      '[PP [P in] [NP [N Utrecht]]]]'),
     'notes': 'Past *toen* (≠ present *wanneer*); fronted subordinate triggers inversion.',
     'source': 'illustrative',
     'citation': 'Broekhuis & Corver (2016), §14.5.'},
    {'slug': 'nld-terwijl-hij-las-kookte-ik',
     'konso': 'terwijl hij las, kookte ik',
     'gloss': 'while  3SG.M  read.PST.3SG  cook.PST.1SG  1SG',
     'translation': 'While he read, I cooked.',
     'tree_bracket': ('[S [CP [C terwijl] '
                      '[S [NP [Pron hij]] [VP [V las]]]] '
                      '[V kookte] [NP [Pron ik]]]'),
     'notes': 'Simultaneous *terwijl*.',
     'source': 'illustrative',
     'citation': 'Broekhuis & Corver (2016), §14.5.'},

    # ── Relatives (3) ────────────────────────────────────────────────
    {'slug': 'nld-de-man-die-daar-staat-is-mijn-vader',
     'konso': 'de man die daar staat is mijn vader',
     'gloss': 'the  man  REL  there  stand.PRES.3SG  '
              'be.PRES.3SG  1SG.POSS  father',
     'translation': 'The man who is standing there is my father.',
     'tree_bracket': ('[S [NP [Det de] [N man] '
                      '[CP [Rel die] '
                      '[S [AdvP [Adv daar]] [VP [V staat]]]]] '
                      '[VP [V is] [NP [Poss mijn] [N vader]]]]'),
     'notes': 'Common-gender relative pronoun *die*; relative clause is verb-final.',
     'source': 'illustrative',
     'citation': 'Donaldson (2008), §8.3.'},
    {'slug': 'nld-het-boek-dat-ik-lees-is-goed',
     'konso': 'het boek dat ik lees is goed',
     'gloss': 'the  book  REL  1SG  read.PRES.1SG  be.PRES.3SG  good',
     'translation': 'The book that I am reading is good.',
     'tree_bracket': ('[S [NP [Det het] [N boek] '
                      '[CP [Rel dat] '
                      '[S [NP [Pron ik]] [VP [V lees]]]]] '
                      '[VP [V is] [AP [A goed]]]]'),
     'notes': 'Neuter antecedent selects relative *dat*.',
     'source': 'illustrative',
     'citation': 'Donaldson (2008), §8.3.'},
    {'slug': 'nld-de-vrouw-met-wie-ik-sprak',
     'konso': 'de vrouw met wie ik sprak',
     'gloss': 'the  woman  with  REL  1SG  speak.PST.1SG',
     'translation': 'The woman with whom I spoke.',
     'tree_bracket': ('[NP [Det de] [N vrouw] '
                      '[CP [PP [P met] [Rel wie]] '
                      '[S [NP [Pron ik]] [VP [V sprak]]]]]'),
     'notes': 'Pied-piped preposition + *wie* for animate, oblique antecedents.',
     'source': 'illustrative',
     'citation': 'Donaldson (2008), §8.3.'},

    # ── Passives (2) ─────────────────────────────────────────────────
    {'slug': 'nld-het-huis-wordt-gebouwd',
     'konso': 'het huis wordt gebouwd',
     'gloss': 'the  house  become.PRES.3SG  build.PTCP',
     'translation': 'The house is being built.',
     'tree_bracket': ('[S [NP [Det het] [N huis]] '
                      '[VP [Aux wordt] [V gebouwd]]]'),
     'notes': 'Eventive passive with *worden* + past participle.',
     'source': 'illustrative',
     'citation': 'Donaldson (2008), §11.9.'},
    {'slug': 'nld-het-boek-is-geschreven',
     'konso': 'het boek is geschreven',
     'gloss': 'the  book  be.PRES.3SG  write.PTCP',
     'translation': 'The book has been written.',
     'tree_bracket': ('[S [NP [Det het] [N boek]] '
                      '[VP [Aux is] [V geschreven]]]'),
     'notes': 'Stative passive with *zijn*: the state resulting from the action.',
     'source': 'illustrative',
     'citation': 'Donaldson (2008), §11.9.'},

    # ── Imperatives (2) ──────────────────────────────────────────────
    {'slug': 'nld-kom-hier',
     'konso': 'kom hier',
     'gloss': 'come.IMP  here',
     'translation': 'Come here.',
     'tree_bracket': '[S [VP [V kom] [AdvP [Adv hier]]]]',
     'notes': 'Bare imperative stem; no overt subject.',
     'source': 'illustrative',
     'citation': 'Donaldson (2008), §11.7.'},
    {'slug': 'nld-ga-zitten',
     'konso': 'ga zitten',
     'gloss': 'go.IMP  sit.INF',
     'translation': 'Sit down.',
     'tree_bracket': '[S [VP [V ga] [V zitten]]]',
     'notes': '*ga zitten* = periphrastic imperative, literally "go sit".',
     'source': 'illustrative',
     'citation': 'Donaldson (2008), §11.7.'},

    # ── Er-constructions + idioms (4) ────────────────────────────────
    {'slug': 'nld-er-staat-een-boom-in-de-tuin',
     'konso': 'er staat een boom in de tuin',
     'gloss': 'EXPL  stand.PRES.3SG  a  tree  in  the  garden',
     'translation': 'A tree stands in the garden.',
     'tree_bracket': ('[S [NP [Expl er]] '
                      '[V staat] '
                      '[NP [Det een] [N boom]] '
                      '[PP [P in] [NP [Det de] [N tuin]]]]'),
     'notes': 'Presentational *er* — Dutch version of existential "there".',
     'source': 'illustrative',
     'citation': 'Donaldson (2008), §15.'},
    {'slug': 'nld-er-zijn-veel-mensen-hier',
     'konso': 'er zijn veel mensen hier',
     'gloss': 'EXPL  be.PRES.3PL  many  people  here',
     'translation': 'There are many people here.',
     'tree_bracket': ('[S [NP [Expl er]] [V zijn] '
                      '[NP [Q veel] [N mensen]] '
                      '[AdvP [Adv hier]]]'),
     'notes': 'Existential *er zijn*.',
     'source': 'illustrative',
     'citation': 'Donaldson (2008), §15.'},
    {'slug': 'nld-het-meisje-leest-een-boekje',
     'konso': 'het meisje leest een boekje',
     'gloss': 'the  girl  read.PRES.3SG  a  book.DIM',
     'translation': 'The girl reads a little book.',
     'tree_bracket': ('[S [NP [Det het] [N meisje]] '
                      '[VP [V leest] '
                      '[NP [Det een] [N [N boek] [Dim -je]]]]]'),
     'notes': '*meisje* itself is historically the diminutive of *meid*. '
              '*-je* is the productive Dutch diminutive.',
     'source': 'illustrative',
     'citation': 'Donaldson (2008), §4.3.'},
    {'slug': 'nld-het-spijt-me',
     'konso': 'het spijt me',
     'gloss': 'EXPL  sorry.PRES.3SG  1SG.DAT',
     'translation': "I'm sorry.",
     'tree_bracket': ('[S [NP [Expl het]] '
                      '[VP [V spijt] [NP [Pron me]]]]'),
     'notes': 'Dative-experiencer construction: lit. "it sorrows me".',
     'source': 'illustrative',
     'citation': 'Donaldson (2008), §8.2.'},
]


# ═════════════════════════════════════════════════════════════════════
# MANDARIN — 45 additional trees
# ═════════════════════════════════════════════════════════════════════

MANDARIN = [
    # ── Simple SVO (5) ───────────────────────────────────────────────
    {'slug': 'cmn-wo-ai-ni',
     'konso': '我爱你',
     'gloss': '1SG  love  2SG',
     'translation': 'I love you.',
     'tree_bracket': ('[S [NP [Pron 我|wǒ]] [VP [V 爱|ài] [NP [Pron 你|nǐ]]]]'),
     'notes': 'Minimal transitive — no tense, no aspect, no marking.',
     'source': 'illustrative',
     'citation': 'Li & Thompson (1981), §2.1.'},
    {'slug': 'cmn-ta-chi-pingguo',
     'konso': '他吃苹果',
     'gloss': '3SG  eat  apple',
     'translation': 'He eats an apple.',
     'tree_bracket': ('[S [NP [Pron 他|tā]] [VP [V 吃|chī] [NP [N 苹果|píng guǒ]]]]'),
     'notes': 'Bare-noun object is unspecified for number and definiteness.',
     'source': 'illustrative',
     'citation': 'Li & Thompson (1981), §4.2.'},
    {'slug': 'cmn-mao-zhua-laoshu',
     'konso': '猫抓老鼠',
     'gloss': 'cat  catch  mouse',
     'translation': 'Cats catch mice.',
     'tree_bracket': ('[S [NP [N 猫|māo]] [VP [V 抓|zhuā] [NP [N 老鼠|lǎo shǔ]]]]'),
     'notes': 'Generic statement — no aspect, no classifiers.',
     'source': 'illustrative',
     'citation': 'Li & Thompson (1981), §4.2.'},
    {'slug': 'cmn-xiaohai-xue-zhongwen',
     'konso': '小孩学中文',
     'gloss': 'child  learn  Chinese',
     'translation': 'Children learn Chinese.',
     'tree_bracket': ('[S [NP [N 小孩|xiǎo hái]] [VP [V 学|xué] [NP [N 中文|Zhōng wén]]]]'),
     'notes': '*小孩* = "child / children"; no plural marking needed.',
     'source': 'illustrative',
     'citation': 'Li & Thompson (1981), §4.2.'},
    {'slug': 'cmn-yisheng-bangzhu-binren',
     'konso': '医生帮助病人',
     'gloss': 'doctor  help  patient',
     'translation': 'The doctor helps the patient.',
     'tree_bracket': ('[S [NP [N 医生|yī shēng]] [VP [V 帮助|bāng zhù] [NP [N 病人|bìng rén]]]]'),
     'notes': 'Disyllabic verb *帮助* "help".',
     'source': 'illustrative',
     'citation': 'Li & Thompson (1981), §2.3.'},

    # ── Classifiers (6) ──────────────────────────────────────────────
    {'slug': 'cmn-yi-ben-shu',
     'konso': '一本书',
     'gloss': 'one  CL.bound  book',
     'translation': 'one book',
     'tree_bracket': ('[NP [Num 一|yī] [Cl 本|běn] [N 书|shū]]'),
     'notes': 'Classifier *本* is used for bound objects — books, notebooks.',
     'source': 'illustrative',
     'citation': 'Li & Thompson (1981), §4.1.'},
    {'slug': 'cmn-san-zhi-mao',
     'konso': '三只猫',
     'gloss': 'three  CL.small-animal  cat',
     'translation': 'three cats',
     'tree_bracket': '[NP [Num 三|sān] [Cl 只|zhī] [N 猫|māo]]',
     'notes': 'Classifier *只* for small animals (and one of a paired item).',
     'source': 'illustrative',
     'citation': 'Li & Thompson (1981), §4.1.'},
    {'slug': 'cmn-liang-ge-ren',
     'konso': '两个人',
     'gloss': 'two  CL.general  person',
     'translation': 'two people',
     'tree_bracket': '[NP [Num 两|liǎng] [Cl 个|gè] [N 人|rén]]',
     'notes': '*两* is the numeral used before classifiers (not *二*). '
              '*个* is the generic classifier.',
     'source': 'illustrative',
     'citation': 'Li & Thompson (1981), §4.1.'},
    {'slug': 'cmn-yi-tiao-he',
     'konso': '一条河',
     'gloss': 'one  CL.long-thin  river',
     'translation': 'one river',
     'tree_bracket': '[NP [Num 一|yī] [Cl 条|tiáo] [N 河|hé]]',
     'notes': 'Classifier *条* for long thin objects: rivers, fish, roads.',
     'source': 'illustrative',
     'citation': 'Li & Thompson (1981), §4.1.'},
    {'slug': 'cmn-yi-zhang-zhi',
     'konso': '一张纸',
     'gloss': 'one  CL.flat  paper',
     'translation': 'one sheet of paper',
     'tree_bracket': '[NP [Num 一|yī] [Cl 张|zhāng] [N 纸|zhǐ]]',
     'notes': 'Classifier *张* for flat objects.',
     'source': 'illustrative',
     'citation': 'Li & Thompson (1981), §4.1.'},
    {'slug': 'cmn-wo-you-liang-ge-gege',
     'konso': '我有两个哥哥',
     'gloss': '1SG  have  two  CL.general  elder-brother',
     'translation': 'I have two older brothers.',
     'tree_bracket': ('[S [NP [Pron 我|wǒ]] [VP [V 有|yǒu] [NP [Num 两|liǎng] [Cl 个|gè] [N 哥哥|gē ge]]]]'),
     'notes': 'Possession with *有*; classifier obligatory after numerals.',
     'source': 'illustrative',
     'citation': 'Li & Thompson (1981), §12.'},

    # ── Aspect markers (6) ───────────────────────────────────────────
    {'slug': 'cmn-wo-chi-le-fan',
     'konso': '我吃了饭',
     'gloss': '1SG  eat  PFV  rice',
     'translation': 'I ate.',
     'tree_bracket': ('[S [NP [Pron 我|wǒ]] [VP [V 吃|chī] [Asp 了|le] [NP [N 饭|fàn]]]]'),
     'notes': 'Verbal *了* = perfective (completion), not past tense.',
     'source': 'illustrative',
     'citation': 'Li & Thompson (1981), §6.1.'},
    {'slug': 'cmn-ta-qu-guo-riben',
     'konso': '他去过日本',
     'gloss': '3SG  go  EXP  Japan',
     'translation': 'He has been to Japan (at some point).',
     'tree_bracket': ('[S [NP [Pron 他|tā]] [VP [V 去|qù] [Asp 过|guò] [NP [N 日本|Rì běn]]]]'),
     'notes': 'Experiential *过* "has ever" — at least once in the past.',
     'source': 'illustrative',
     'citation': 'Li & Thompson (1981), §6.2.'},
    {'slug': 'cmn-men-kai-zhe',
     'konso': '门开着',
     'gloss': 'door  open  DUR',
     'translation': 'The door is open / standing open.',
     'tree_bracket': ('[S [NP [N 门|mén]] [VP [V 开|kāi] [Asp 着|zhe]]]'),
     'notes': 'Durative *着*: the state of being open persists.',
     'source': 'illustrative',
     'citation': 'Li & Thompson (1981), §6.3.'},
    {'slug': 'cmn-wo-zai-kan-dianshi',
     'konso': '我在看电视',
     'gloss': '1SG  PROG  watch  TV',
     'translation': 'I am watching TV.',
     'tree_bracket': ('[S [NP [Pron 我|wǒ]] [VP [Asp 在|zài] [V 看|kàn] [NP [N 电视|diàn shì]]]]'),
     'notes': 'Preverbal *在* = progressive aspect.',
     'source': 'illustrative',
     'citation': 'Li & Thompson (1981), §6.4.'},
    {'slug': 'cmn-ta-zhengzai-xie-xin',
     'konso': '他正在写信',
     'gloss': '3SG  PROG.emphatic  write  letter',
     'translation': 'He is (in the middle of) writing a letter.',
     'tree_bracket': ('[S [NP [Pron 他|tā]] [VP [Asp 正在|zhèng zài] [V 写|xiě] [NP [N 信|xìn]]]]'),
     'notes': '*正在* emphasizes "right now, in the middle of".',
     'source': 'illustrative',
     'citation': 'Li & Thompson (1981), §6.4.'},
    {'slug': 'cmn-wo-chi-fan-le',
     'konso': '我吃饭了',
     'gloss': '1SG  eat  rice  CRS',
     'translation': "I've eaten now.",
     'tree_bracket': ('[S [NP [Pron 我|wǒ]] [VP [V 吃|chī] [NP [N 饭|fàn]] [Part 了|le]]]'),
     'notes': 'Sentence-final *了* signals a currently-relevant state — '
              'distinct from the verbal perfective 了.',
     'source': 'illustrative',
     'citation': 'Li & Thompson (1981), §7.1.'},

    # ── Modals (4) ───────────────────────────────────────────────────
    {'slug': 'cmn-wo-hui-shuo-yingyu',
     'konso': '我会说英语',
     'gloss': '1SG  can.learned  speak  English',
     'translation': 'I can speak English.',
     'tree_bracket': ('[S [NP [Pron 我|wǒ]] [VP [Mod 会|huì] [V 说|shuō] [NP [N 英语|Yīng yǔ]]]]'),
     'notes': '*会* = learned ability (as opposed to raw capability *能*).',
     'source': 'illustrative',
     'citation': 'Li & Thompson (1981), §5.2.'},
    {'slug': 'cmn-ni-neng-lai-ma',
     'konso': '你能来吗?',
     'gloss': '2SG  can.able  come  Q',
     'translation': 'Can you come?',
     'tree_bracket': ('[S [NP [Pron 你|nǐ]] [VP [Mod 能|néng] [V 来|lái]] [Part 吗|ma]]'),
     'notes': '*能* = circumstantial possibility / physical ability.',
     'source': 'illustrative',
     'citation': 'Li & Thompson (1981), §5.2.'},
    {'slug': 'cmn-ni-keyi-jin-lai',
     'konso': '你可以进来',
     'gloss': '2SG  may  enter  come',
     'translation': 'You may come in.',
     'tree_bracket': ('[S [NP [Pron 你|nǐ]] [VP [Mod 可以|kě yǐ] [V 进|jìn] [V 来|lái]]]'),
     'notes': '*可以* = permission; *进来* is a directional compound.',
     'source': 'illustrative',
     'citation': 'Li & Thompson (1981), §5.2.'},
    {'slug': 'cmn-wo-yao-qu',
     'konso': '我要去',
     'gloss': '1SG  want/will  go',
     'translation': 'I want to go / I will go.',
     'tree_bracket': ('[S [NP [Pron 我|wǒ]] [VP [Mod 要|yào] [V 去|qù]]]'),
     'notes': '*要* is ambiguous between volition and near future.',
     'source': 'illustrative',
     'citation': 'Li & Thompson (1981), §5.2.'},

    # ── Questions (6) ────────────────────────────────────────────────
    {'slug': 'cmn-ni-hao-ma',
     'konso': '你好吗?',
     'gloss': '2SG  good  Q',
     'translation': 'How are you?',
     'tree_bracket': ('[S [NP [Pron 你|nǐ]] [VP [A 好|hǎo]] [Part 吗|ma]]'),
     'notes': 'Standard greeting; *吗* turns any declarative into a y/n Q.',
     'source': 'illustrative',
     'citation': 'Li & Thompson (1981), §18.1.'},
    {'slug': 'cmn-ni-chi-bu-chi',
     'konso': '你吃不吃?',
     'gloss': '2SG  eat  NEG  eat',
     'translation': 'Are you eating (or not)?',
     'tree_bracket': ('[S [NP [Pron 你|nǐ]] [VP [V 吃|chī] [Neg 不|bù] [V 吃|chī]]]'),
     'notes': 'A-not-A question — alternative to *吗*, slightly more neutral.',
     'source': 'illustrative',
     'citation': 'Li & Thompson (1981), §18.2.'},
    {'slug': 'cmn-ta-shi-shui',
     'konso': '他是谁?',
     'gloss': '3SG  be  who',
     'translation': 'Who is he?',
     'tree_bracket': ('[S [NP [Pron 他|tā]] [VP [V 是|shì] [NP [Wh 谁|shéi]]]]'),
     'notes': 'Wh-word *谁* stays in situ as a predicate nominal.',
     'source': 'illustrative',
     'citation': 'Li & Thompson (1981), §18.3.'},
    {'slug': 'cmn-zhe-shi-shenme',
     'konso': '这是什么?',
     'gloss': 'this  be  what',
     'translation': 'What is this?',
     'tree_bracket': ('[S [NP [Dem 这|zhè]] [VP [V 是|shì] [NP [Wh 什么|shén me]]]]'),
     'notes': '*什么* is the in-situ wh-word for things.',
     'source': 'illustrative',
     'citation': 'Li & Thompson (1981), §18.3.'},
    {'slug': 'cmn-ni-ne',
     'konso': '你呢?',
     'gloss': '2SG  CONTRAST',
     'translation': 'And you?',
     'tree_bracket': '[S [NP [Pron 你|nǐ]] [Part 呢|ne]]',
     'notes': 'Contrastive particle *呢* — "what about you?"',
     'source': 'illustrative',
     'citation': 'Li & Thompson (1981), §8.6.'},
    {'slug': 'cmn-wei-shenme-ni-bu-lai',
     'konso': '为什么你不来?',
     'gloss': 'why  2SG  NEG  come',
     'translation': "Why aren't you coming?",
     'tree_bracket': ('[S [AdvP [Wh 为什么|wèi shén me]] [NP [Pron 你|nǐ]] [VP [Neg 不|bù] [V 来|lái]]]'),
     'notes': '*为什么* "why" is typically fronted, though it may also stay in situ.',
     'source': 'illustrative',
     'citation': 'Li & Thompson (1981), §18.3.'},

    # ── Negation (3) ─────────────────────────────────────────────────
    {'slug': 'cmn-wo-bu-zhidao',
     'konso': '我不知道',
     'gloss': '1SG  NEG  know',
     'translation': "I don't know.",
     'tree_bracket': ('[S [NP [Pron 我|wǒ]] [VP [Neg 不|bù] [V 知道|zhī dào]]]'),
     'notes': '*不* negates non-past / non-perfective verbs and states.',
     'source': 'illustrative',
     'citation': 'Li & Thompson (1981), §10.1.'},
    {'slug': 'cmn-ta-mei-lai',
     'konso': '他没来',
     'gloss': '3SG  NEG.PFV  come',
     'translation': "He hasn't come.",
     'tree_bracket': ('[S [NP [Pron 他|tā]] [VP [Neg 没|méi] [V 来|lái]]]'),
     'notes': '*没* (< *没有*) negates perfective/experiential — blocks 了/过.',
     'source': 'illustrative',
     'citation': 'Li & Thompson (1981), §10.2.'},
    {'slug': 'cmn-bie-shuo',
     'konso': '别说',
     'gloss': 'PROH  speak',
     'translation': "Don't speak.",
     'tree_bracket': '[S [VP [Neg 别|bié] [V 说|shuō]]]',
     'notes': 'Prohibitive *别* — imperative negator.',
     'source': 'illustrative',
     'citation': 'Li & Thompson (1981), §10.5.'},

    # ── Serial verbs / directionals (3) ──────────────────────────────
    {'slug': 'cmn-ta-pao-chu-qu',
     'konso': '他跑出去',
     'gloss': '3SG  run  exit  go',
     'translation': 'He runs out.',
     'tree_bracket': ('[S [NP [Pron 他|tā]] [VP [V 跑|pǎo] [V 出|chū] [V 去|qù]]]'),
     'notes': 'Directional complement *出去* attaches to the lexical verb.',
     'source': 'illustrative',
     'citation': 'Li & Thompson (1981), §3.2.'},
    {'slug': 'cmn-wo-qu-kan-dianying',
     'konso': '我去看电影',
     'gloss': '1SG  go  watch  movie',
     'translation': 'I go watch a movie.',
     'tree_bracket': ('[S [NP [Pron 我|wǒ]] [VP [V 去|qù] [VP [V 看|kàn] [NP [N 电影|diàn yǐng]]]]]'),
     'notes': 'Serial-verb purposive: motion + purpose verb in one clause.',
     'source': 'illustrative',
     'citation': 'Li & Thompson (1981), §9.'},
    {'slug': 'cmn-dai-jiaozi-lai',
     'konso': '带饺子来',
     'gloss': 'bring  dumpling  come',
     'translation': 'Bring dumplings.',
     'tree_bracket': ('[S [VP [V 带|dài] [NP [N 饺子|jiǎo zi]] [V 来|lái]]]'),
     'notes': 'Directional *来* "toward speaker" terminates the VP.',
     'source': 'illustrative',
     'citation': 'Li & Thompson (1981), §3.2.'},

    # ── Comparatives (2) ─────────────────────────────────────────────
    {'slug': 'cmn-ta-bi-wo-gao',
     'konso': '他比我高',
     'gloss': '3SG  COMPARE  1SG  tall',
     'translation': 'He is taller than I.',
     'tree_bracket': ('[S [NP [Pron 他|tā]] [PP [P 比|bǐ] [NP [Pron 我|wǒ]]] [VP [A 高|gāo]]]'),
     'notes': '*比* + standard + adjective — Mandarin has no -er suffix.',
     'source': 'illustrative',
     'citation': 'Li & Thompson (1981), §19.'},
    {'slug': 'cmn-zhe-ge-geng-hao',
     'konso': '这个更好',
     'gloss': 'this  CL  even-more  good',
     'translation': 'This one is better.',
     'tree_bracket': ('[S [NP [Dem 这|zhè] [Cl 个|gè]] [VP [Adv 更|gèng] [A 好|hǎo]]]'),
     'notes': '*更* intensifies the adjective when comparison is implicit.',
     'source': 'illustrative',
     'citation': 'Li & Thompson (1981), §19.'},

    # ── Resultative complements (3) ──────────────────────────────────
    {'slug': 'cmn-wo-xie-wan-le',
     'konso': '我写完了',
     'gloss': '1SG  write  finish  PFV',
     'translation': 'I have finished writing.',
     'tree_bracket': ('[S [NP [Pron 我|wǒ]] [VP [V 写|xiě] [V 完|wán] [Asp 了|le]]]'),
     'notes': '*完* is a resultative "to completion".',
     'source': 'illustrative',
     'citation': 'Li & Thompson (1981), §3.2.2.'},
    {'slug': 'cmn-ta-ting-dong-le',
     'konso': '他听懂了',
     'gloss': '3SG  listen  understand  PFV',
     'translation': 'He understood (by listening).',
     'tree_bracket': ('[S [NP [Pron 他|tā]] [VP [V 听|tīng] [V 懂|dǒng] [Asp 了|le]]]'),
     'notes': 'Result *懂* "understand" specifies the outcome of the listening.',
     'source': 'illustrative',
     'citation': 'Li & Thompson (1981), §3.2.2.'},
    {'slug': 'cmn-wo-da-po-le-beizi',
     'konso': '我打破了杯子',
     'gloss': '1SG  hit  break  PFV  cup',
     'translation': 'I broke the cup.',
     'tree_bracket': ('[S [NP [Pron 我|wǒ]] [VP [V 打|dǎ] [V 破|pò] [Asp 了|le] [NP [N 杯子|bēi zi]]]]'),
     'notes': 'Resultative *破* "broken" attached to the causing verb *打*.',
     'source': 'illustrative',
     'citation': 'Li & Thompson (1981), §3.2.2.'},

    # ── Existentials / locatives (3) ─────────────────────────────────
    {'slug': 'cmn-you-san-ben-shu',
     'konso': '有三本书',
     'gloss': 'exist  three  CL.bound  book',
     'translation': 'There are three books.',
     'tree_bracket': ('[S [VP [V 有|yǒu] [NP [Num 三|sān] [Cl 本|běn] [N 书|shū]]]]'),
     'notes': 'Existential *有* "there is/are" — subject omitted.',
     'source': 'illustrative',
     'citation': 'Li & Thompson (1981), §17.1.'},
    {'slug': 'cmn-shu-zai-zhuozi-shang',
     'konso': '书在桌子上',
     'gloss': 'book  LOC  table  on',
     'translation': 'The book is on the table.',
     'tree_bracket': ('[S [NP [N 书|shū]] [VP [V 在|zài] [NP [N 桌子|zhuō zi] [Loc 上|shàng]]]]'),
     'notes': 'Locative *在*; postnominal *上* is the locative particle.',
     'source': 'illustrative',
     'citation': 'Li & Thompson (1981), §17.2.'},
    {'slug': 'cmn-zhuozi-shang-you-shu',
     'konso': '桌子上有书',
     'gloss': 'table  on  exist  book',
     'translation': 'There are books on the table.',
     'tree_bracket': ('[S [NP [N 桌子|zhuō zi] [Loc 上|shàng]] [VP [V 有|yǒu] [NP [N 书|shū]]]]'),
     'notes': 'Topic-first locative existential — a common variant of *在*.',
     'source': 'illustrative',
     'citation': 'Li & Thompson (1981), §17.3.'},

    # ── Ba-construction (2) ──────────────────────────────────────────
    {'slug': 'cmn-ba-men-guan-shang',
     'konso': '把门关上',
     'gloss': 'BA  door  close  up',
     'translation': 'Close the door.',
     'tree_bracket': ('[S [VP [BA 把|bǎ] [NP [N 门|mén]] [V 关|guān] [V 上|shàng]]]'),
     'notes': 'Imperative *把*-disposal with a resultative/directional.',
     'source': 'illustrative',
     'citation': 'Li & Thompson (1981), §15.'},
    {'slug': 'cmn-wo-ba-ta-da-le',
     'konso': '我把他打了',
     'gloss': '1SG  BA  3SG  hit  PFV',
     'translation': 'I hit him.',
     'tree_bracket': ('[S [NP [Pron 我|wǒ]] [VP [BA 把|bǎ] [NP [Pron 他|tā]] [V 打|dǎ] [Asp 了|le]]]'),
     'notes': 'Affected pronoun in *把*: emphasizes what was done to him.',
     'source': 'illustrative',
     'citation': 'Li & Thompson (1981), §15.'},

    # ── Bei passive (2) ──────────────────────────────────────────────
    {'slug': 'cmn-ta-bei-yu-lin-le',
     'konso': '他被雨淋了',
     'gloss': '3SG  PASS  rain  soak  PFV',
     'translation': 'He got rained on.',
     'tree_bracket': ('[S [NP [Pron 他|tā]] [VP [Pass 被|bèi] [NP [N 雨|yǔ]] [V 淋|lín] [Asp 了|le]]]'),
     'notes': 'Adversative *被* — classic "bad things happened to him" flavour.',
     'source': 'illustrative',
     'citation': 'Li & Thompson (1981), §16.'},
    {'slug': 'cmn-shu-bei-ta-du-le',
     'konso': '书被他读了',
     'gloss': 'book  PASS  3SG  read  PFV',
     'translation': 'The book was read by him.',
     'tree_bracket': ('[S [NP [N 书|shū]] [VP [Pass 被|bèi] [NP [Pron 他|tā]] [V 读|dú] [Asp 了|le]]]'),
     'notes': 'Neutral *被* — closer to English "by"-passive.',
     'source': 'illustrative',
     'citation': 'Li & Thompson (1981), §16.'},
]


# ═════════════════════════════════════════════════════════════════════
# SPANISH — 45 additional trees
# ═════════════════════════════════════════════════════════════════════

SPANISH = [
    # ── Simple SVO (5) ───────────────────────────────────────────────
    {'slug': 'spa-el-perro-ladra',
     'konso': 'el perro ladra',
     'gloss': 'the.MSG  dog.MSG  bark.PRES.3SG',
     'translation': 'The dog barks.',
     'tree_bracket': ('[S [NP [Det el] [N perro]] '
                      '[VP [V ladra]]]'),
     'notes': 'Agreement in gender and number between article and noun.',
     'source': 'illustrative',
     'citation': 'Butt & Benjamin (2011), §3.'},
    {'slug': 'spa-hablo-espanol',
     'konso': 'hablo español',
     'gloss': 'speak.PRES.1SG  Spanish',
     'translation': 'I speak Spanish.',
     'tree_bracket': ('[S [VP [V hablo] [NP [N español]]]]'),
     'notes': 'Pro-drop 1sg: the verb ending *-o* identifies the subject.',
     'source': 'illustrative',
     'citation': 'Butt & Benjamin (2011), §11.1.'},
    {'slug': 'spa-maria-come-pan',
     'konso': 'María come pan',
     'gloss': 'María  eat.PRES.3SG  bread',
     'translation': 'María eats bread.',
     'tree_bracket': ('[S [NP [N María]] '
                      '[VP [V come] [NP [N pan]]]]'),
     'notes': 'Bare proper name subject; mass-noun object without article.',
     'source': 'illustrative',
     'citation': 'Butt & Benjamin (2011), §3.3.'},
    {'slug': 'spa-los-ninos-juegan',
     'konso': 'los niños juegan',
     'gloss': 'the.MPL  children.MPL  play.PRES.3PL',
     'translation': 'The children play.',
     'tree_bracket': ('[S [NP [Det los] [N niños]] '
                      '[VP [V juegan]]]'),
     'notes': 'Plural agreement across the NP and VP.',
     'source': 'illustrative',
     'citation': 'Butt & Benjamin (2011), §3.1.'},
    {'slug': 'spa-mi-madre-cocina-arroz',
     'konso': 'mi madre cocina arroz',
     'gloss': '1SG.POSS  mother  cook.PRES.3SG  rice',
     'translation': 'My mother cooks rice.',
     'tree_bracket': ('[S [NP [Poss mi] [N madre]] '
                      '[VP [V cocina] [NP [N arroz]]]]'),
     'notes': 'Pre-nominal unstressed possessive *mi*.',
     'source': 'illustrative',
     'citation': 'Butt & Benjamin (2011), §8.'},

    # ── Ser vs estar (5) ─────────────────────────────────────────────
    {'slug': 'spa-soy-medico',
     'konso': 'soy médico',
     'gloss': 'be.PRES.1SG  doctor',
     'translation': 'I am a doctor.',
     'tree_bracket': ('[S [VP [V soy] [NP [N médico]]]]'),
     'notes': 'Profession → *ser*; no article with bare professions.',
     'source': 'illustrative',
     'citation': 'Butt & Benjamin (2011), §29.2.'},
    {'slug': 'spa-estoy-cansado',
     'konso': 'estoy cansado',
     'gloss': 'be.PRES.1SG.MSG  tired.MSG',
     'translation': 'I am tired.',
     'tree_bracket': ('[S [VP [V estoy] [AP [A cansado]]]]'),
     'notes': 'Temporary state → *estar*; adjective agrees in gender.',
     'source': 'illustrative',
     'citation': 'Butt & Benjamin (2011), §29.3.'},
    {'slug': 'spa-la-casa-es-grande',
     'konso': 'la casa es grande',
     'gloss': 'the.FSG  house.FSG  be.PRES.3SG  big',
     'translation': 'The house is big.',
     'tree_bracket': ('[S [NP [Det la] [N casa]] '
                      '[VP [V es] [AP [A grande]]]]'),
     'notes': 'Inherent property → *ser*. *grande* is invariant in gender.',
     'source': 'illustrative',
     'citation': 'Butt & Benjamin (2011), §29.2.'},
    {'slug': 'spa-esta-en-madrid',
     'konso': 'está en Madrid',
     'gloss': 'be.PRES.3SG  in  Madrid',
     'translation': 'He/she is in Madrid.',
     'tree_bracket': ('[S [VP [V está] '
                      '[PP [P en] [NP [N Madrid]]]]]'),
     'notes': 'Location → *estar*. Pro-drop subject.',
     'source': 'illustrative',
     'citation': 'Butt & Benjamin (2011), §29.3.'},
    {'slug': 'spa-esta-lloviendo',
     'konso': 'está lloviendo',
     'gloss': 'be.PRES.3SG  rain.GER',
     'translation': 'It is raining.',
     'tree_bracket': ('[S [VP [Aux está] [V lloviendo]]]'),
     'notes': 'Progressive = *estar* + gerund; weather verbs are impersonal.',
     'source': 'illustrative',
     'citation': 'Butt & Benjamin (2011), §15.'},

    # ── Clitics (5) ──────────────────────────────────────────────────
    {'slug': 'spa-lo-veo',
     'konso': 'lo veo',
     'gloss': '3SG.M.ACC  see.PRES.1SG',
     'translation': 'I see him / it.',
     'tree_bracket': ('[S [VP [Clitic lo] [V veo]]]'),
     'notes': 'Accusative clitic proclitic to the finite verb.',
     'source': 'illustrative',
     'citation': 'Butt & Benjamin (2011), §11.'},
    {'slug': 'spa-le-doy-un-libro',
     'konso': 'le doy un libro',
     'gloss': '3SG.DAT  give.PRES.1SG  a  book',
     'translation': 'I give him/her a book.',
     'tree_bracket': ('[S [VP [Clitic le] [V doy] '
                      '[NP [Det un] [N libro]]]]'),
     'notes': 'Dative *le* — recipient argument of *dar*.',
     'source': 'illustrative',
     'citation': 'Butt & Benjamin (2011), §11.7.'},
    {'slug': 'spa-se-lo-digo',
     'konso': 'se lo digo',
     'gloss': '3SG.DAT  3SG.M.ACC  say.PRES.1SG',
     'translation': 'I tell it to him.',
     'tree_bracket': ('[S [VP [Clitic se] [Clitic lo] '
                      '[V digo]]]'),
     'notes': 'Spurious *se*: dative *le* becomes *se* before another l-clitic.',
     'source': 'illustrative',
     'citation': 'Butt & Benjamin (2011), §11.10.'},
    {'slug': 'spa-me-gusta-el-cafe',
     'konso': 'me gusta el café',
     'gloss': '1SG.DAT  please.PRES.3SG  the  coffee',
     'translation': 'I like coffee. (lit. Coffee pleases me.)',
     'tree_bracket': ('[S [VP [Clitic me] [V gusta] '
                      '[NP [Det el] [N café]]]]'),
     'notes': 'Gustar-type verb: the liker is the dative, the liked is the subject.',
     'source': 'illustrative',
     'citation': 'Butt & Benjamin (2011), §26.'},
    {'slug': 'spa-nos-vemos',
     'konso': 'nos vemos',
     'gloss': '1PL.RECP  see.PRES.1PL',
     'translation': 'See you! (lit. We see each other.)',
     'tree_bracket': ('[S [VP [Clitic nos] [V vemos]]]'),
     'notes': 'Reciprocal *nos* — standard Spanish goodbye.',
     'source': 'illustrative',
     'citation': 'Butt & Benjamin (2011), §11.15.'},

    # ── Tenses (6) ───────────────────────────────────────────────────
    {'slug': 'spa-llegue-tarde',
     'konso': 'llegué tarde',
     'gloss': 'arrive.PRET.1SG  late',
     'translation': 'I arrived late.',
     'tree_bracket': ('[S [VP [V llegué] [AdvP [Adv tarde]]]]'),
     'notes': 'Preterite — a single completed past event.',
     'source': 'illustrative',
     'citation': 'Butt & Benjamin (2011), §14.4.'},
    {'slug': 'spa-siempre-comiamos-juntos',
     'konso': 'siempre comíamos juntos',
     'gloss': 'always  eat.IMPF.1PL  together',
     'translation': 'We always ate together.',
     'tree_bracket': ('[S [AdvP [Adv siempre]] '
                      '[VP [V comíamos] [AdvP [Adv juntos]]]]'),
     'notes': 'Imperfect — habitual / ongoing past.',
     'source': 'illustrative',
     'citation': 'Butt & Benjamin (2011), §14.5.'},
    {'slug': 'spa-ire-manana',
     'konso': 'iré mañana',
     'gloss': 'go.FUT.1SG  tomorrow',
     'translation': "I'll go tomorrow.",
     'tree_bracket': ('[S [VP [V iré] [AdvP [Adv mañana]]]]'),
     'notes': 'Synthetic future *iré* < *ir + he* (OSp. auxiliary fusion).',
     'source': 'illustrative',
     'citation': 'Butt & Benjamin (2011), §14.6.'},
    {'slug': 'spa-hablaria-mas',
     'konso': 'hablaría más',
     'gloss': 'speak.COND.1SG  more',
     'translation': 'I would speak more.',
     'tree_bracket': ('[S [VP [V hablaría] [AdvP [Adv más]]]]'),
     'notes': 'Conditional form — polite or hypothetical.',
     'source': 'illustrative',
     'citation': 'Butt & Benjamin (2011), §14.7.'},
    {'slug': 'spa-he-terminado',
     'konso': 'he terminado',
     'gloss': 'have.PRES.1SG  finish.PTCP',
     'translation': 'I have finished.',
     'tree_bracket': ('[S [VP [Aux he] [V terminado]]]'),
     'notes': 'Present perfect; participle is invariant with *haber*.',
     'source': 'illustrative',
     'citation': 'Butt & Benjamin (2011), §14.9.'},
    {'slug': 'spa-ya-habia-llegado',
     'konso': 'ya había llegado',
     'gloss': 'already  have.IMPF.3SG  arrive.PTCP',
     'translation': 'He/she had already arrived.',
     'tree_bracket': ('[S [AdvP [Adv ya]] '
                      '[VP [Aux había] [V llegado]]]'),
     'notes': 'Pluperfect — past action completed before another past reference.',
     'source': 'illustrative',
     'citation': 'Butt & Benjamin (2011), §14.10.'},

    # ── Subjunctive (4) ──────────────────────────────────────────────
    {'slug': 'spa-ojala-llueva',
     'konso': 'ojalá llueva',
     'gloss': 'hopefully  rain.PRES.SBJV.3SG',
     'translation': 'I hope it rains.',
     'tree_bracket': ('[S [AdvP [Adv ojalá]] [VP [V llueva]]]'),
     'notes': '*ojalá* (< Ar. *wa-šā\' llāh*) always takes the subjunctive.',
     'source': 'illustrative',
     'citation': 'Butt & Benjamin (2011), §16.4.'},
    {'slug': 'spa-si-tuviera-tiempo-iria',
     'konso': 'si tuviera tiempo, iría',
     'gloss': 'if  have.IMPF.SBJV.1SG  time  go.COND.1SG',
     'translation': 'If I had time, I would go.',
     'tree_bracket': ('[S [CP [C si] '
                      '[S [VP [V tuviera] [NP [N tiempo]]]]] '
                      '[VP [V iría]]]'),
     'notes': 'Counterfactual *si*-clause: past subjunctive + conditional.',
     'source': 'illustrative',
     'citation': 'Butt & Benjamin (2011), §25.'},
    {'slug': 'spa-quiero-que-vengas',
     'konso': 'quiero que vengas',
     'gloss': 'want.PRES.1SG  that  come.PRES.SBJV.2SG',
     'translation': 'I want you to come.',
     'tree_bracket': ('[S [VP [V quiero] '
                      '[CP [C que] '
                      '[S [VP [V vengas]]]]]]'),
     'notes': 'Volitional matrix verb → subjunctive complement.',
     'source': 'illustrative',
     'citation': 'Butt & Benjamin (2011), §16.2.'},
    {'slug': 'spa-es-importante-que-estudies',
     'konso': 'es importante que estudies',
     'gloss': 'be.PRES.3SG  important  that  study.PRES.SBJV.2SG',
     'translation': 'It is important that you study.',
     'tree_bracket': ('[S [VP [V es] [AP [A importante]] '
                      '[CP [C que] '
                      '[S [VP [V estudies]]]]]]'),
     'notes': 'Impersonal evaluative matrix → subjunctive.',
     'source': 'illustrative',
     'citation': 'Butt & Benjamin (2011), §16.3.'},

    # ── Negation (2) ─────────────────────────────────────────────────
    {'slug': 'spa-no-tengo-dinero',
     'konso': 'no tengo dinero',
     'gloss': 'NEG  have.PRES.1SG  money',
     'translation': "I don't have money.",
     'tree_bracket': ('[S [VP [Neg no] [V tengo] [NP [N dinero]]]]'),
     'notes': 'Preverbal *no*; no article on mass-noun object.',
     'source': 'illustrative',
     'citation': 'Butt & Benjamin (2011), §23.'},
    {'slug': 'spa-no-veo-nada',
     'konso': 'no veo nada',
     'gloss': 'NEG  see.PRES.1SG  nothing',
     'translation': 'I see nothing. / I don\'t see anything.',
     'tree_bracket': ('[S [VP [Neg no] [V veo] [NP [N nada]]]]'),
     'notes': 'Negative concord — both *no* and *nada* must be present.',
     'source': 'illustrative',
     'citation': 'Butt & Benjamin (2011), §23.5.'},

    # ── Questions (4) ────────────────────────────────────────────────
    {'slug': 'spa-donde-vives',
     'konso': '¿dónde vives?',
     'gloss': 'where  live.PRES.2SG',
     'translation': 'Where do you live?',
     'tree_bracket': ('[S [AdvP [Wh dónde]] [VP [V vives]]]'),
     'notes': 'Accented wh-word; pro-drop 2sg recovered from morphology.',
     'source': 'illustrative',
     'citation': 'Butt & Benjamin (2011), §24.'},
    {'slug': 'spa-que-hora-es',
     'konso': '¿qué hora es?',
     'gloss': 'what  hour  be.PRES.3SG',
     'translation': 'What time is it?',
     'tree_bracket': ('[S [NP [Wh qué] [N hora]] [VP [V es]]]'),
     'notes': '*qué* as a determiner inside an NP.',
     'source': 'illustrative',
     'citation': 'Butt & Benjamin (2011), §24.4.'},
    {'slug': 'spa-quien-es',
     'konso': '¿quién es?',
     'gloss': 'who  be.PRES.3SG',
     'translation': 'Who is it?',
     'tree_bracket': ('[S [NP [Wh quién]] [VP [V es]]]'),
     'notes': 'Animate wh-word *quién*.',
     'source': 'illustrative',
     'citation': 'Butt & Benjamin (2011), §24.'},
    {'slug': 'spa-por-que-lloras',
     'konso': '¿por qué lloras?',
     'gloss': 'for  what  cry.PRES.2SG',
     'translation': 'Why are you crying?',
     'tree_bracket': ('[S [PP [P por] [Wh qué]] '
                      '[VP [V lloras]]]'),
     'notes': '*por qué* = "why"; compare *porque* "because" (one word).',
     'source': 'illustrative',
     'citation': 'Butt & Benjamin (2011), §24.'},

    # ── Relatives (3) ────────────────────────────────────────────────
    {'slug': 'spa-el-hombre-que-habla-es-mi-tio',
     'konso': 'el hombre que habla es mi tío',
     'gloss': 'the  man  REL  speak.PRES.3SG  be.PRES.3SG  1SG.POSS  uncle',
     'translation': 'The man who speaks is my uncle.',
     'tree_bracket': ('[S [NP [Det el] [N hombre] '
                      '[CP [Rel que] [S [VP [V habla]]]]] '
                      '[VP [V es] [NP [Poss mi] [N tío]]]]'),
     'notes': 'Multipurpose relative *que* — subject of the embedded clause.',
     'source': 'illustrative',
     'citation': 'Butt & Benjamin (2011), §35.'},
    {'slug': 'spa-la-mujer-con-quien-baile',
     'konso': 'la mujer con quien bailé',
     'gloss': 'the  woman  with  REL.ANIM  dance.PRET.1SG',
     'translation': 'The woman with whom I danced.',
     'tree_bracket': ('[NP [Det la] [N mujer] '
                      '[CP [PP [P con] [Rel quien]] '
                      '[S [VP [V bailé]]]]]'),
     'notes': 'Animate oblique relative *quien* after a preposition.',
     'source': 'illustrative',
     'citation': 'Butt & Benjamin (2011), §35.6.'},
    {'slug': 'spa-la-casa-donde-viven-mis-padres',
     'konso': 'la casa donde viven mis padres',
     'gloss': 'the  house  where  live.PRES.3PL  1SG.POSS.PL  parents',
     'translation': 'The house where my parents live.',
     'tree_bracket': ('[NP [Det la] [N casa] '
                      '[CP [Rel donde] '
                      '[S [VP [V viven] '
                      '[NP [Poss mis] [N padres]]]]]]'),
     'notes': 'Locative relative *donde* substitutes for *en que*.',
     'source': 'illustrative',
     'citation': 'Butt & Benjamin (2011), §35.10.'},

    # ── Commands (3) ─────────────────────────────────────────────────
    {'slug': 'spa-habla-mas-despacio',
     'konso': 'habla más despacio',
     'gloss': 'speak.IMP.2SG  more  slowly',
     'translation': 'Speak more slowly.',
     'tree_bracket': ('[S [VP [V habla] '
                      '[AdvP [Adv más] [Adv despacio]]]]'),
     'notes': 'Tú-imperative = 3sg indicative form (*habla*).',
     'source': 'illustrative',
     'citation': 'Butt & Benjamin (2011), §17.'},
    {'slug': 'spa-no-hables',
     'konso': 'no hables',
     'gloss': 'NEG  speak.PRES.SBJV.2SG',
     'translation': "Don't speak.",
     'tree_bracket': ('[S [VP [Neg no] [V hables]]]'),
     'notes': 'Negative tú-imperative uses the present subjunctive.',
     'source': 'illustrative',
     'citation': 'Butt & Benjamin (2011), §17.4.'},
    {'slug': 'spa-vamos-al-parque',
     'konso': 'vamos al parque',
     'gloss': 'go.IMP.1PL  to-the  park',
     'translation': "Let's go to the park.",
     'tree_bracket': ('[S [VP [V vamos] '
                      '[PP [P al] [NP [N parque]]]]]'),
     'notes': 'Hortative 1pl — built on the indicative *vamos*, not subjunctive.',
     'source': 'illustrative',
     'citation': 'Butt & Benjamin (2011), §17.5.'},

    # ── Impersonal se (2) ────────────────────────────────────────────
    {'slug': 'spa-se-venden-casas',
     'konso': 'se venden casas',
     'gloss': 'IMPERS  sell.PRES.3PL  houses',
     'translation': 'Houses (are) for sale.',
     'tree_bracket': ('[S [VP [Clitic se] [V venden] '
                      '[NP [N casas]]]]'),
     'notes': 'Passive *se* — verb agrees with the patient NP.',
     'source': 'illustrative',
     'citation': 'Butt & Benjamin (2011), §28.'},
    {'slug': 'spa-aqui-se-come-bien',
     'konso': 'aquí se come bien',
     'gloss': 'here  IMPERS  eat.PRES.3SG  well',
     'translation': 'One eats well here.',
     'tree_bracket': ('[S [AdvP [Adv aquí]] '
                      '[VP [Clitic se] [V come] '
                      '[AdvP [Adv bien]]]]'),
     'notes': 'Impersonal *se* — always 3sg verb, no overt subject.',
     'source': 'illustrative',
     'citation': 'Butt & Benjamin (2011), §28.5.'},

    # ── Prepositions (3) ─────────────────────────────────────────────
    {'slug': 'spa-voy-a-madrid',
     'konso': 'voy a Madrid',
     'gloss': 'go.PRES.1SG  to  Madrid',
     'translation': 'I am going to Madrid.',
     'tree_bracket': ('[S [VP [V voy] '
                      '[PP [P a] [NP [N Madrid]]]]]'),
     'notes': '*a* marks both allative ("to") and animate direct objects.',
     'source': 'illustrative',
     'citation': 'Butt & Benjamin (2011), §34.'},
    {'slug': 'spa-hablo-de-ti',
     'konso': 'hablo de ti',
     'gloss': 'speak.PRES.1SG  about  2SG.OBL',
     'translation': 'I am talking about you.',
     'tree_bracket': ('[S [VP [V hablo] '
                      '[PP [P de] [NP [Pron ti]]]]]'),
     'notes': 'Oblique pronoun *ti* follows a preposition.',
     'source': 'illustrative',
     'citation': 'Butt & Benjamin (2011), §34.2.'},
    {'slug': 'spa-por-ti-lo-hago',
     'konso': 'por ti lo hago',
     'gloss': 'for  2SG.OBL  3SG.M.ACC  do.PRES.1SG',
     'translation': 'I do it for you.',
     'tree_bracket': ('[S [PP [P por] [NP [Pron ti]]] '
                      '[VP [Clitic lo] [V hago]]]'),
     'notes': 'Fronted PP for topic; compare *para ti* "intended for you".',
     'source': 'illustrative',
     'citation': 'Butt & Benjamin (2011), §34.14.'},

    # ── Idiomatic (3) ────────────────────────────────────────────────
    {'slug': 'spa-tengo-hambre',
     'konso': 'tengo hambre',
     'gloss': 'have.PRES.1SG  hunger',
     'translation': "I'm hungry.",
     'tree_bracket': ('[S [VP [V tengo] [NP [N hambre]]]]'),
     'notes': 'Spanish expresses many bodily states as *tener* + bare noun.',
     'source': 'illustrative',
     'citation': 'Butt & Benjamin (2011), §27.'},
    {'slug': 'spa-hace-frio',
     'konso': 'hace frío',
     'gloss': 'make.PRES.3SG  cold',
     'translation': "It's cold.",
     'tree_bracket': ('[S [VP [V hace] [NP [N frío]]]]'),
     'notes': 'Weather *hacer* + noun — always 3sg, no subject.',
     'source': 'illustrative',
     'citation': 'Butt & Benjamin (2011), §31.'},
    {'slug': 'spa-hay-mucha-gente',
     'konso': 'hay mucha gente',
     'gloss': 'EXIST  much.FSG  people.FSG',
     'translation': 'There are many people.',
     'tree_bracket': ('[S [VP [V hay] '
                      '[NP [Q mucha] [N gente]]]]'),
     'notes': '*hay* is an invariant existential (< *ha + y* "there").',
     'source': 'illustrative',
     'citation': 'Butt & Benjamin (2011), §30.'},
]


SEEDS = {
    'dutch':    DUTCH,
    'mandarin': MANDARIN,
    'spanish':  SPANISH,
}


class Command(BaseCommand):
    help = ('Bulk seed: 45 additional sentences each for Dutch, '
            'Mandarin, and Spanish (bringing each to 50 trees '
            'total). Additive — safe to re-run. Run '
            'seed_world_languages first so the Language rows exist.')

    def handle(self, *args, **opts):
        made_sent, updated_sent, bad_trees, missing_lang = 0, 0, 0, 0

        for lang_slug, sentences in SEEDS.items():
            try:
                lang = Language.objects.get(slug=lang_slug)
            except Language.DoesNotExist:
                missing_lang += 1
                self.stderr.write(self.style.WARNING(
                    f'! Language {lang_slug!r} not found — run '
                    f'seed_world_languages first. Skipping '
                    f'{len(sentences)} sentences.'))
                continue

            self.stdout.write(
                f'· {lang_slug} ({lang.english_name}) — '
                f'{len(sentences)} to ingest')
            with transaction.atomic():
                for row in sentences:
                    try:
                        parse_bracket(row['tree_bracket'])
                    except Exception as e:
                        bad_trees += 1
                        self.stderr.write(self.style.ERROR(
                            f'  ! {row["slug"]}: bad tree ({e})'))
                        continue
                    defaults = {**{k: v for k, v in row.items()
                                   if k != 'slug'},
                                'language': lang}
                    _, was_new = Sentence.objects.update_or_create(
                        slug=row['slug'], defaults=defaults)
                    if was_new:
                        made_sent += 1
                    else:
                        updated_sent += 1

        msg = (f'Sentences: +{made_sent} new, ~{updated_sent} updated, '
               f'{bad_trees} bad trees')
        if missing_lang:
            msg += f', {missing_lang} languages missing'
        self.stdout.write(self.style.SUCCESS(msg + '.'))
