# Generated by Django 6.0.4 on 2026-04-10 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mailboxes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InboundMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(help_text='IMAP UID for this message within the mailbox. Used for dedup across polls.', max_length=64)),
                ('from_addr', models.CharField(blank=True, max_length=500)),
                ('to_addr', models.CharField(blank=True, max_length=1000)),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('body_text', models.TextField(blank=True)),
                ('body_html', models.TextField(blank=True)),
                ('attachment_names', models.JSONField(blank=True, default=list)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('raw', models.TextField(blank=True)),
                ('read', models.BooleanField(default=False)),
                ('handled', models.BooleanField(default=False)),
                ('handler_notes', models.TextField(blank=True)),
                ('mailbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbound_messages', to='mailboxes.mailaccount')),
            ],
            options={
                'ordering': ['-received_at', '-fetched_at'],
                'indexes': [models.Index(fields=['mailbox', 'read'], name='mailroom_in_mailbox_b4f620_idx'), models.Index(fields=['-fetched_at'], name='mailroom_in_fetched_08826f_idx')],
                'unique_together': {('mailbox', 'uid')},
            },
        ),
    ]
