# Generated by Django 6.0.4 on 2026-04-21 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GrowthAssumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.CharField(max_length=200)),
                ('unit', models.CharField(blank=True, max_length=60)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('role', models.CharField(choices=[('main', 'Main — mixed production'), ('wordpress', 'WordPress — classroom'), ('experimental', 'Experimental — isolated'), ('development', 'Development'), ('admin', 'Admin / pipeline'), ('planned', 'Planned purchase')], default='main', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('planned', 'Planned'), ('decommissioned', 'Decommissioned')], default='active', max_length=20)),
                ('ram_gb', models.PositiveIntegerField(default=16)),
                ('storage_gb', models.PositiveIntegerField(default=200)),
                ('cpu_cores', models.PositiveIntegerField(default=4)),
                ('ram_used_gb', models.FloatField(default=0, help_text='Snapshot of current RAM usage in GB.')),
                ('storage_used_gb', models.FloatField(default=0, help_text='Snapshot of current storage usage in GB.')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['role', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WorkloadClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('description', models.TextField(blank=True)),
                ('typical_ram_mb', models.PositiveIntegerField(default=100, help_text='RAM footprint of a typical project in this class, in MB.')),
                ('typical_storage_mb', models.PositiveIntegerField(default=500, help_text='Storage footprint of a typical project, in MB.')),
                ('peak_concurrency', models.PositiveIntegerField(default=1, help_text='Peak concurrent users per project under load.')),
                ('new_per_year', models.FloatField(default=0, help_text='Rate of new projects per year in this class.')),
                ('saturation_count', models.PositiveIntegerField(default=0, help_text='Asymptotic ceiling used by the logistic regime. 0 = unbounded growth (not realistic; only for early sanity).')),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Workload classes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HostedProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=240, unique=True)),
                ('framework', models.CharField(blank=True, help_text='django, wordpress, custom, etc.', max_length=60)),
                ('ram_mb', models.PositiveIntegerField(default=0, help_text='Measured RAM; 0 = use class default.')),
                ('storage_mb', models.PositiveIntegerField(default=0, help_text='Measured storage; 0 = use class default.')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='radiant.server')),
                ('workload_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hosted_projects', to='radiant.workloadclass')),
            ],
            options={
                'ordering': ['server', 'name'],
            },
        ),
    ]
