# Generated by Django 6.0.4 on 2026-04-21 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radiant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True)),
                ('purpose', models.CharField(choices=[('unified', 'Unified — everything'), ('django', 'Django production'), ('wordpress', 'WordPress classroom'), ('experimental', 'Experimental / isolated'), ('development', 'Development'), ('admin', 'Admin / pipeline')], default='unified', max_length=20)),
                ('ram_gb', models.PositiveIntegerField(default=32)),
                ('storage_gb', models.PositiveIntegerField(default=500)),
                ('cpu_cores', models.PositiveIntegerField(default=8)),
                ('approximate_cost_eur', models.PositiveIntegerField(default=0, help_text='Rough purchase cost in euros. 0 = unknown.')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['purpose', 'ram_gb'],
            },
        ),
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('notes', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict, help_text='forecast_rows + recommendation + classes + servers captured at snapshot time.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='workloadclass',
            name='active_fraction',
            field=models.FloatField(default=0.3, help_text='Fraction of projects in this class that are at peak simultaneously. WordPress classroom is typically 0.1-0.2 (only a few classes in session at once); quiet Django production is ~0.2-0.4.'),
        ),
        migrations.AlterField(
            model_name='workloadclass',
            name='peak_concurrency',
            field=models.PositiveIntegerField(default=1, help_text='Peak concurrent users per project when that project is actually in session.'),
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidates', models.ManyToManyField(blank=True, related_name='scenarios', to='radiant.candidate')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
