# Generated by Django 6.0.4 on 2026-04-21 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radiant', '0002_candidate_snapshot_workloadclass_active_fraction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='monthly_cost_eur',
            field=models.PositiveIntegerField(default=0, help_text='Monthly rental cost in euros for hosted options. 0 = owned hardware.'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='approximate_cost_eur',
            field=models.PositiveIntegerField(default=0, help_text='One-time upfront cost in euros (purchase or setup). 0 = none / rental.'),
        ),
    ]
