# Generated by Django 6.0.4 on 2026-04-21 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radiant', '0003_candidate_monthly_cost_eur_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvoMetaTournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('notes', models.TextField(blank=True)),
                ('rounds', models.PositiveSmallIntegerField(default=4)),
                ('tournament_rounds', models.PositiveSmallIntegerField(default=6)),
                ('generations', models.PositiveIntegerField(default=25)),
                ('population_size', models.PositiveSmallIntegerField(default=20)),
                ('weight_jitter', models.FloatField(default=0.35, help_text='+/- fraction by which each weight is perturbed per round.')),
                ('leaderboard', models.JSONField(blank=True, default=list)),
                ('champion_genome_ids', models.JSONField(blank=True, default=list)),
                ('champion_fitness', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EvoPopulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('notes', models.TextField(blank=True)),
                ('population_size', models.PositiveSmallIntegerField(default=32)),
                ('min_boxes', models.PositiveSmallIntegerField(default=1)),
                ('max_boxes', models.PositiveSmallIntegerField(default=5)),
                ('mutation_rate', models.FloatField(default=0.3)),
                ('elitism', models.PositiveSmallIntegerField(default=2)),
                ('weight_lifetime', models.FloatField(default=1.0)),
                ('weight_tco', models.FloatField(default=0.5)),
                ('weight_isolation', models.FloatField(default=2.0)),
                ('weight_simplicity', models.FloatField(default=0.3)),
                ('weight_headroom', models.FloatField(default=1.0)),
                ('generation', models.PositiveIntegerField(default=0)),
                ('best_fitness', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'evolved population',
                'verbose_name_plural': 'evolved populations',
                'ordering': ['-modified_at'],
            },
        ),
        migrations.CreateModel(
            name='EvoTournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('notes', models.TextField(blank=True)),
                ('rounds', models.PositiveSmallIntegerField(default=8)),
                ('generations', models.PositiveIntegerField(default=30)),
                ('population_size', models.PositiveSmallIntegerField(default=24)),
                ('mutation_rate', models.FloatField(default=0.3)),
                ('weights_json', models.JSONField(blank=True, default=dict, help_text='Snapshot of the weight vector used for scoring.')),
                ('leaderboard', models.JSONField(blank=True, default=list, help_text='[{round, fitness, genome_ids, summary}, ...] sorted by fitness desc. Top row is the tournament champion.')),
                ('champion_genome_ids', models.JSONField(blank=True, default=list)),
                ('champion_fitness', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EvoIndividual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generation', models.PositiveIntegerField(default=0)),
                ('genome_ids', models.JSONField(default=list, help_text='List of Candidate.pk values — the bundle this genome encodes.')),
                ('fitness', models.FloatField(default=0.0)),
                ('breakdown', models.JSONField(blank=True, default=dict, help_text="Fitness components: lifetime_years, tco_eur, isolation_bonus, simplicity_bonus, headroom_bonus, plus totals so the detail page doesn't need to re-evaluate.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offspring_a', to='radiant.evoindividual')),
                ('parent_b', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offspring_b', to='radiant.evoindividual')),
                ('population', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individuals', to='radiant.evopopulation')),
            ],
            options={
                'ordering': ['-fitness', 'id'],
            },
        ),
    ]
