# Generated by Django 6.0.4 on 2026-04-19 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('automaton', '0003_simulation_analysis'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, help_text='Optional human label. Auto-generated from params if left blank.', max_length=200)),
                ('n_colors', models.PositiveSmallIntegerField(default=4, help_text='Number of cell colors (2-4). n=0 and n=1 are trivially deterministic and not useful here.')),
                ('n_candidates', models.PositiveIntegerField(default=200, help_text='How many random rulesets to generate and score.')),
                ('n_rules_per_candidate', models.PositiveIntegerField(default=80, help_text='How many 7-tuple rules in each candidate ruleset.')),
                ('wildcard_pct', models.PositiveSmallIntegerField(default=25, help_text='Fraction of neighbor positions that are wildcards (-1 / "any"). Higher = coarser rules, more coverage of the 7-tuple space but noisier dynamics.')),
                ('screen_width', models.PositiveSmallIntegerField(default=20, help_text='Grid width used to screen candidates (kept small so a sweep is interactive).')),
                ('screen_height', models.PositiveSmallIntegerField(default=20)),
                ('horizon', models.PositiveSmallIntegerField(default=40, help_text='Max ticks to step each candidate forward before measuring.')),
                ('seed', models.CharField(blank=True, help_text='RNG seed for reproducibility. Auto-set from timestamp if blank.', max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('finished', 'Finished'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('error', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rules_json', models.JSONField(default=list, help_text='List of dicts with keys s, n (6-tuple), r — same shape automaton.detector.step_exact consumes.')),
                ('n_rules', models.PositiveIntegerField(default=0)),
                ('rules_hash', models.CharField(db_index=True, help_text='Stable short hash of the rules list so duplicates can be deduped within a run.', max_length=16)),
                ('score', models.FloatField(default=0.0, help_text='Class-4-likeness, higher is better. Composed in det.search.score_candidate.')),
                ('est_class', models.CharField(choices=[('class1', 'Class 1 — uniform'), ('class2', 'Class 2 — periodic'), ('class3', 'Class 3 — chaotic'), ('class4', 'Class 4 — complex / edge of chaos'), ('unknown', 'Unknown')], default='unknown', max_length=16)),
                ('analysis', models.JSONField(default=dict, help_text='Raw measurements: uniform, period, activity_rate, block_entropy, density_profile, color_diversity, ended_at_tick.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('promoted_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='det_candidates', to='automaton.ruleset')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='det.searchrun')),
            ],
            options={
                'ordering': ['-score', 'id'],
                'indexes': [models.Index(fields=['run', '-score'], name='det_candida_run_id_4d8f4c_idx')],
            },
        ),
    ]
