# Generated by Django 6.0.4 on 2026-04-20 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('det', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchrun',
            name='horizon',
            field=models.PositiveSmallIntegerField(default=60, help_text='Max ticks to step each candidate forward before measuring. Needs to be long enough that early transients settle — 40 wasn’t.'),
        ),
        migrations.AlterField(
            model_name='searchrun',
            name='n_colors',
            field=models.PositiveSmallIntegerField(default=3, help_text='Number of cell colors (2-4). n=0 and n=1 are trivially deterministic and not useful here. 3 is the empirical sweet spot — 4 needs many more rules to cover the 7-tuple space and most candidates freeze as class2.'),
        ),
        migrations.AlterField(
            model_name='searchrun',
            name='n_rules_per_candidate',
            field=models.PositiveIntegerField(default=100, help_text='How many 7-tuple rules in each candidate ruleset. Denser rule tables produce richer dynamics.'),
        ),
        migrations.AlterField(
            model_name='searchrun',
            name='screen_height',
            field=models.PositiveSmallIntegerField(default=16),
        ),
        migrations.AlterField(
            model_name='searchrun',
            name='screen_width',
            field=models.PositiveSmallIntegerField(default=18, help_text='Grid width used to screen candidates (kept small so a sweep is interactive).'),
        ),
        migrations.AlterField(
            model_name='searchrun',
            name='wildcard_pct',
            field=models.PositiveSmallIntegerField(default=35, help_text='Fraction of neighbor positions that are wildcards (-1 / "any"). Higher = coarser rules, more coverage of the 7-tuple space but noisier dynamics. ~35 is where class4 density peaks in practice.'),
        ),
    ]
