# Generated by Django 6.0.4 on 2026-04-20 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('det', '0002_alter_searchrun_horizon_alter_searchrun_n_colors_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=200)),
                ('n_colors', models.PositiveSmallIntegerField(default=3)),
                ('n_seeds', models.PositiveSmallIntegerField(default=5, help_text='How many shared initial grids each entry is scored against.')),
                ('screen_width', models.PositiveSmallIntegerField(default=18)),
                ('screen_height', models.PositiveSmallIntegerField(default=16)),
                ('horizon', models.PositiveSmallIntegerField(default=60)),
                ('master_seed', models.CharField(blank=True, help_text='Derives the per-round seeds. Auto-set from timestamp if blank.', max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('finished', 'Finished'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('error', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TournamentEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aggregate_score', models.FloatField(default=0.0, help_text='Mean of per_seed scores. Ranking sort key.')),
                ('per_seed', models.JSONField(default=list, help_text='List of {seed, score, est_class, analysis} dicts — one per shared grid.')),
                ('rank', models.PositiveIntegerField(blank=True, help_text='1-based, set after execute. Null until run finishes or if disqualified.', null=True)),
                ('disqualified', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_entries', to='det.candidate')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='det.tournament')),
            ],
            options={
                'ordering': ['rank', '-aggregate_score', 'id'],
                'indexes': [models.Index(fields=['tournament', '-aggregate_score'], name='det_tournam_tournam_e95701_idx')],
                'unique_together': {('tournament', 'candidate')},
            },
        ),
    ]
