# Generated by Django 6.0.4 on 2026-04-21 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('det', '0003_tournament_tournamententry'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='auto_promote_top',
            field=models.PositiveSmallIntegerField(default=0, help_text='After run, auto-promote up to this many top-ranked entries (whose native class is 4 and whose aggregate stayed in the class-4 band) to Automaton + Evolution. 0 = no auto-promotion.'),
        ),
    ]
