# Generated by Django 6.0.4 on 2026-04-21 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('det', '0004_tournament_auto_promote_top'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='source_tournaments',
            field=models.JSONField(blank=True, default=list, help_text='For meta-tournaments (tournament-of-tournaments): list of parent Tournament IDs whose top-K winners were pooled to build this roster. Empty list for regular tournaments.'),
        ),
    ]
