# Generated by Django 6.0.4 on 2026-05-13 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('det', '0005_tournament_source_tournaments'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchrun',
            name='horizon_mode',
            field=models.CharField(choices=[('off', 'off - score only on class-4-likeness'), ('available', 'available - add horizon-band score as a bonus signal alongside class-4 signals'), ('use_only', 'use only - score is the horizon-band score alone, ignore class-4 signals')], default='off', help_text='How to weight the "horizon profile" metric: rewards final grids whose colours run in horizontal bands (high horizontal-neighbour match, low vertical match). Useful for hunting CAs whose attractors look like landscape strata.', max_length=12),
        ),
    ]
