# Generated by Django 6.0.4 on 2026-05-13 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('det', '0006_searchrun_horizon_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchrun',
            name='deep_chaos_mode',
            field=models.CharField(choices=[('off', 'off - skip the deep-aperiodicity measurement'), ('available', 'available - measure aperiodic_runtime, add it as a log-scaled bonus alongside class-4 signals'), ('use_only', 'use only - score is the deep aperiodicity measurement alone, ignore class-4 signals')], default='off', help_text='Measure how many ticks each candidate stays aperiodic, with an extended horizon (~10x the normal one) and a deeper cycle-detector lookback. Costs ~5-10x per-candidate evaluation but actually discriminates between "loops at tick 80" and "still aperiodic at tick 600". Off by default.', max_length=12),
        ),
    ]
