# Generated by Django 6.0.4 on 2026-05-14 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Walk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(blank=True, max_length=160)),
                ('notes', models.TextField(blank=True)),
                ('gene_json', models.JSONField(default=list)),
                ('n_steps', models.PositiveIntegerField(default=0)),
                ('fitness_final', models.FloatField(default=0.0)),
                ('fitness_max', models.FloatField(default=0.0)),
                ('fitness_mean', models.FloatField(default=0.0)),
                ('end_cx', models.FloatField(default=-0.5)),
                ('end_cy', models.FloatField(default=0.0)),
                ('end_span', models.FloatField(default=3.0)),
                ('end_iter', models.PositiveIntegerField(default=192)),
                ('thumbnail_b64', models.TextField(blank=True)),
                ('thumbnail_w', models.PositiveSmallIntegerField(default=128)),
                ('thumbnail_h', models.PositiveSmallIntegerField(default=128)),
                ('method', models.CharField(choices=[('manual', 'Manual save'), ('agent', 'Agent walk'), ('replay', 'Replayed walk')], default='manual', max_length=12)),
                ('population_id', models.CharField(blank=True, db_index=True, max_length=24)),
                ('parent_slug', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
