# Generated by Django 6.0.4 on 2026-04-21 20:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('order', models.PositiveSmallIntegerField(default=100, help_text='Sort key for the curriculum listing.')),
                ('title', models.CharField(max_length=160)),
                ('difficulty', models.CharField(choices=[('intro', 'Intro'), ('basic', 'Basic'), ('interm', 'Intermediate'), ('advanced', 'Advanced')], default='intro', max_length=16)),
                ('prompt_md', models.TextField(help_text='Lesson body in Markdown — explanation + task.')),
                ('starter_code', models.TextField(blank=True, help_text='The editor is prefilled with this.')),
                ('solution_code', models.TextField(blank=True, help_text='Reference solution shown after the first attempt.')),
                ('expected_output', models.TextField(blank=True, help_text='Optional exact-match stdout check; blank skips the check.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('stdout', models.TextField(blank=True)),
                ('stderr', models.TextField(blank=True)),
                ('exit_code', models.IntegerField(blank=True, null=True)),
                ('passed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='camlfornia.lesson')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
