"""Taxon — canonical CA rule library + classification.

`Rule` stores the 4,096-byte K=4 hex packed-positional genome that
s3lab, automaton, helix.hexhunt, and the ESP32-S3 firmware all share.
A 4-byte ANSI-256 palette rides along so renders are byte-identical
to the source app.

`MetricRun` records one metric value applied to one rule under a
given seed + grid + horizon. Re-running a metric writes a new row;
the most recent value per (rule, metric) is what classification reads.

`Classification` snapshots a Wolfram-class assignment (1–4) plus the
metric vector that drove it, so a re-classification can compare and
flag drift.

`EvolutionRun` is a session of target-class GA — population_size,
target (class or metric), generations, fitness curve, best rule.
"""
from __future__ import annotations

import hashlib

from django.db import models
from django.utils import timezone


# The genome formats taxon understands.
# - HXC4: 4,096-byte K=4 packed-positional (the original; what s3lab
#   classic / cellular / automaton / helix.hexhunt all share).
# - HXNN: K-dialable nearest-neighbor used by /hexnn/, stratum, strateta.
#   Stored as taxon's HXNN blob format: b'HXNN' + u32 K + u32 N_entries
#   + N*7 keys + N outs. ~131 KB at the canonical N=16384.
KIND_HEX_K4_PACKED = 'hex_k4_packed'
KIND_HEX_NN        = 'hex_nn'

KIND_CHOICES = [
    (KIND_HEX_K4_PACKED, 'Hex K=4 packed (HXC4)'),
    (KIND_HEX_NN,        'Hex NN (K-dialable, hexnn-genome / strateta)'),
]


# Source apps a rule can be imported from. 'manual' = uploaded HXC4,
# 'random' = generated by taxon evolve, 'mutation' = bred locally.
SOURCE_CHOICES = [
    ('automaton',   'Automaton'),
    ('s3lab',       'S3 Lab'),
    ('helix',       'Helix Hex Hunt'),
    ('stratum',     'S3 Lab Stratum'),
    ('strateta',    'S3 Lab Strateta'),
    ('hexnn',       'HexNN'),
    ('manual',      'Manual upload'),
    ('random',      'Random init'),
    ('mutation',    'Mutation'),
    ('crossover',   'Crossover'),
    ('evolve',      'Taxon evolve'),
]


WOLFRAM_CLASSES = [
    (1, 'Class 1 — homogeneous (settles to fixed value)'),
    (2, 'Class 2 — periodic (settles to oscillator/still life)'),
    (3, 'Class 3 — chaotic (random-looking, no structure)'),
    (4, 'Class 4 — complex (edge of chaos, gliders, computation)'),
]


class Rule(models.Model):
    """A 4,096-byte hex K=4 packed-positional CA genome.

    The genome bytes are content-addressed by sha1; importing the
    same blob twice updates the existing row instead of creating a
    duplicate. Source/origin metadata is informational — the genome
    is the identity.
    """
    slug = models.SlugField(max_length=80, unique=True)
    name = models.CharField(max_length=120, blank=True)
    notes = models.TextField(blank=True)

    kind = models.CharField(
        max_length=24, choices=KIND_CHOICES, default=KIND_HEX_K4_PACKED,
    )
    n_colors = models.PositiveSmallIntegerField(default=4)
    genome = models.BinaryField()
    palette_ansi = models.BinaryField(default=b'\x00\x01\x02\x03')
    sha1 = models.CharField(max_length=40, db_index=True)

    source = models.CharField(
        max_length=16, choices=SOURCE_CHOICES, default='manual',
    )
    source_ref = models.CharField(
        max_length=200, blank=True,
        help_text='Free-form provenance — e.g. an automaton ruleset slug, '
                  'helix HuntRule slug, parent rule sha for a mutation.',
    )

    created_at = models.DateTimeField(default=timezone.now)
    last_run_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        ordering = ('-created_at',)
        indexes = [
            models.Index(fields=['sha1']),
            models.Index(fields=['source']),
        ]

    def __str__(self) -> str:
        return f'{self.name or self.slug} ({self.sha1[:10]})'

    def save(self, *args, **kwargs):
        if self.genome and not self.sha1:
            self.sha1 = hashlib.sha1(bytes(self.genome)).hexdigest()
        super().save(*args, **kwargs)

    @property
    def palette_hex(self) -> list[str]:
        """ANSI-256 indices → CSS hex strings, one per cell colour."""
        from automaton.packed import ansi256_to_hex
        return [ansi256_to_hex(b) for b in bytes(self.palette_ansi)]

    @property
    def latest_classification(self):
        return self.classifications.order_by('-assigned_at').first()

    def latest_metric(self, name: str):
        return (self.metric_runs
                .filter(metric=name)
                .order_by('-computed_at')
                .first())


class MetricRun(models.Model):
    """One metric value computed against one rule.

    Multiple rows accumulate over time; the most recent per
    (rule, metric) is treated as authoritative. Older rows are
    kept as a paper trail (a metric can be re-implemented and the
    drift inspected).
    """
    rule = models.ForeignKey(
        Rule, on_delete=models.CASCADE, related_name='metric_runs',
    )
    metric = models.CharField(max_length=40)
    value = models.FloatField()
    grid_w = models.PositiveSmallIntegerField(default=24)
    grid_h = models.PositiveSmallIntegerField(default=24)
    horizon = models.PositiveSmallIntegerField(default=120)
    seed = models.PositiveIntegerField(default=0)
    extra_json = models.JSONField(default=dict, blank=True)
    computed_at = models.DateTimeField(default=timezone.now)

    class Meta:
        ordering = ('-computed_at',)
        indexes = [
            models.Index(fields=['rule', 'metric']),
        ]

    def __str__(self) -> str:
        return f'{self.metric}={self.value:.4f} for {self.rule.slug}'


class Classification(models.Model):
    """A Wolfram-class assignment with the metric vector that drove it."""
    rule = models.ForeignKey(
        Rule, on_delete=models.CASCADE, related_name='classifications',
    )
    wolfram_class = models.PositiveSmallIntegerField(choices=WOLFRAM_CLASSES)
    confidence = models.FloatField(default=0.0)
    basis_json = models.JSONField(default=dict, blank=True)
    assigned_at = models.DateTimeField(default=timezone.now)

    class Meta:
        ordering = ('-assigned_at',)

    def __str__(self) -> str:
        return f'{self.rule.slug} → class {self.wolfram_class}'


class AutoSearch(models.Model):
    """Background loop that hunts for K=4 packed-positional rules of a
    target Wolfram class. Settings drive: how rules are minted (random,
    mutated from existing matches, or a hybrid), how strict the
    classification gate is, and how long the loop runs.

    The runner thread updates ``last_heartbeat`` every iteration and
    increments ``rules_tried`` / ``rules_kept`` in place via F-expressions
    so the user-facing status flag isn't trampled. Found rules land in
    the regular ``Rule`` table with ``source='evolve'`` and a
    ``source_ref`` of ``autosearch=<slug>`` for back-linking.
    """
    STATUS_QUEUED   = 'queued'
    STATUS_RUNNING  = 'running'
    STATUS_PAUSED   = 'paused'
    STATUS_STOPPED  = 'stopped'
    STATUS_FINISHED = 'finished'
    STATUS_CRASHED  = 'crashed'
    STATUS_CHOICES = [
        (STATUS_QUEUED,   'Queued'),
        (STATUS_RUNNING,  'Running'),
        (STATUS_PAUSED,   'Paused'),
        (STATUS_STOPPED,  'Stopped'),
        (STATUS_FINISHED, 'Finished'),
        (STATUS_CRASHED,  'Crashed'),
    ]
    SEED_RANDOM = 'random'
    SEED_MUTATE = 'mutate'
    SEED_HYBRID = 'hybrid'
    SEED_CHOICES = [
        (SEED_RANDOM, 'Random new genomes only'),
        (SEED_MUTATE, 'Mutate existing class matches'),
        (SEED_HYBRID, 'Hybrid (random + mutate)'),
    ]

    slug = models.SlugField(max_length=80, unique=True)
    name = models.CharField(max_length=120, blank=True)

    target_class = models.PositiveSmallIntegerField(choices=WOLFRAM_CLASSES)
    target_min_confidence = models.FloatField(default=0.6)
    seed_strategy = models.CharField(
        max_length=8, choices=SEED_CHOICES, default=SEED_HYBRID,
    )
    mutation_rate = models.FloatField(default=0.005)

    grid = models.PositiveSmallIntegerField(default=24)
    horizon = models.PositiveSmallIntegerField(default=120)
    seed = models.PositiveIntegerField(default=42)

    max_seconds = models.PositiveIntegerField(default=300)
    max_found   = models.PositiveIntegerField(default=20)

    status = models.CharField(
        max_length=12, choices=STATUS_CHOICES, default=STATUS_QUEUED,
    )
    started_at  = models.DateTimeField(default=timezone.now)
    finished_at = models.DateTimeField(null=True, blank=True)
    last_heartbeat = models.DateTimeField(null=True, blank=True)

    rules_tried = models.PositiveIntegerField(default=0)
    rules_kept  = models.PositiveIntegerField(default=0)
    last_log    = models.TextField(blank=True)

    class Meta:
        ordering = ('-started_at',)
        indexes = [
            models.Index(fields=['status']),
        ]

    def __str__(self) -> str:
        return f'{self.name or self.slug} → class {self.target_class}'

    @property
    def is_active(self) -> bool:
        return self.status in (self.STATUS_QUEUED, self.STATUS_RUNNING)


class EvolutionRun(models.Model):
    """Target-based GA session — evolve toward a Wolfram class or
    a target metric value.

    Phase 1 stores intent + best result; the GA itself runs in the
    browser (cheap to iterate, no server compute) and posts the
    elite genome back when the user is satisfied.
    """
    TARGET_CHOICES = [
        ('class', 'Wolfram class'),
        ('metric', 'Target metric value'),
    ]

    slug = models.SlugField(max_length=80, unique=True)
    name = models.CharField(max_length=120, blank=True)
    target_kind = models.CharField(max_length=10, choices=TARGET_CHOICES)
    target_class = models.PositiveSmallIntegerField(
        null=True, blank=True, choices=WOLFRAM_CLASSES,
    )
    target_metric = models.CharField(max_length=40, blank=True)
    target_value = models.FloatField(null=True, blank=True)

    population_size = models.PositiveSmallIntegerField(default=24)
    generations = models.PositiveIntegerField(default=0)
    mutation_rate = models.FloatField(default=0.003)

    seed_rule = models.ForeignKey(
        Rule, on_delete=models.SET_NULL, null=True, blank=True,
        related_name='+',
    )
    best_rule = models.ForeignKey(
        Rule, on_delete=models.SET_NULL, null=True, blank=True,
        related_name='+',
    )
    best_fitness = models.FloatField(default=0.0)
    fitness_curve = models.JSONField(default=list, blank=True)

    started_at = models.DateTimeField(default=timezone.now)
    finished_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        ordering = ('-started_at',)

    def __str__(self) -> str:
        if self.target_kind == 'class':
            tgt = f'class {self.target_class}'
        else:
            tgt = f'{self.target_metric}={self.target_value}'
        return f'{self.name or self.slug} → {tgt}'
