# Generated by Django 6.0.4 on 2026-05-13 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Origin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(blank=True, max_length=160)),
                ('year', models.CharField(blank=True, help_text='Free-form: "1897", "c. 1730", "oral, 19th c."', max_length=24)),
                ('details', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['author', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Tradition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('region', models.CharField(blank=True, help_text='e.g. "Romania (Wallachia, Moldavia, Transylvania)"', max_length=160)),
                ('era', models.CharField(blank=True, help_text='Free-form: "medieval", "18th–19th c.", "oral, ongoing"', max_length=80)),
                ('summary', models.TextField(blank=True, help_text='2–4 sentences situating this tradition in its culture.')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Trait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('kind', models.CharField(choices=[('physical', 'physical'), ('behavioural', 'behavioural'), ('supernatural', 'supernatural'), ('apotropaic', 'apotropaic (something that wards them off)')], default='physical', max_length=14)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['kind', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Weakness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True)),
                ('destroys', models.BooleanField(default=False, help_text='True if this kills/dissolves the creature.  False if it only wards, repels, or weakens.')),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-destroys', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Creature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True)),
                ('alt_names', models.CharField(blank=True, help_text='Comma-separated other names and spellings.', max_length=400)),
                ('summary', models.TextField(blank=True, help_text='2–5 sentences: what the creature is, what it does.')),
                ('appearance', models.TextField(blank=True, help_text='Physical form: corpse, bloated, skeletal, fanged, severed head with entrails, …')),
                ('behaviour', models.TextField(blank=True, help_text='Hunting pattern, diet, social habits, time-of-day, etc.')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('origins', models.ManyToManyField(blank=True, related_name='creatures', to='vampyrik.origin')),
                ('sources', models.ManyToManyField(blank=True, related_name='creatures', to='vampyrik.source')),
                ('tradition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creatures', to='vampyrik.tradition')),
                ('traits', models.ManyToManyField(blank=True, related_name='creatures', to='vampyrik.trait')),
                ('weaknesses', models.ManyToManyField(blank=True, related_name='creatures', to='vampyrik.weakness')),
            ],
            options={
                'ordering': ['tradition__name', 'name'],
                'unique_together': {('tradition', 'name')},
            },
        ),
    ]
