# Generated by Django 6.0.4 on 2026-04-12 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tiles', '0004_tile_ne_color_tile_nw_color_tile_se_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField(blank=True)),
                ('n_colors', models.PositiveSmallIntegerField(default=4, help_text='Number of cell colors (2-4).')),
                ('source', models.CharField(choices=[('operator', 'Operator-authored'), ('identity', 'Generated by Identity'), ('seed', 'Seeded at install')], default='operator', max_length=16)),
                ('source_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(default=0, help_text='Lower = higher priority. First matching rule wins.')),
                ('self_color', models.SmallIntegerField(default=-1, help_text='Cell color to match (-1 = any).')),
                ('neighbor_color', models.SmallIntegerField(default=0, help_text='Which neighbor color to count (0-3).')),
                ('min_count', models.PositiveSmallIntegerField(default=0, help_text='Minimum neighbors of that color to trigger.')),
                ('max_count', models.PositiveSmallIntegerField(default=6, help_text='Maximum neighbors of that color to trigger.')),
                ('result_color', models.SmallIntegerField(default=0, help_text='Cell becomes this color.')),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('ruleset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='automaton.ruleset')),
            ],
            options={
                'ordering': ['ruleset', 'priority'],
            },
        ),
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('width', models.PositiveIntegerField(default=32)),
                ('height', models.PositiveIntegerField(default=32)),
                ('palette', models.JSONField(blank=True, default=list, help_text='4 color hex codes for the cell colors.')),
                ('grid_state', models.JSONField(blank=True, default=list, help_text='2D array of color indices (0-3). Empty = random init.')),
                ('tick_count', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ruleset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulations', to='automaton.ruleset')),
                ('tileset', models.ForeignKey(blank=True, help_text='Initial conditions from this tileset.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tiles.tileset')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
