# Generated by Django 6.0.4 on 2026-04-13 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automaton', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExactRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('self_color', models.SmallIntegerField(help_text='Cell color (0-3, or -1 for any).')),
                ('n0_color', models.SmallIntegerField(default=-1, help_text='N neighbor color (-1 = any).')),
                ('n1_color', models.SmallIntegerField(default=-1, help_text='NE neighbor color (-1 = any).')),
                ('n2_color', models.SmallIntegerField(default=-1, help_text='SE neighbor color (-1 = any).')),
                ('n3_color', models.SmallIntegerField(default=-1, help_text='S neighbor color (-1 = any).')),
                ('n4_color', models.SmallIntegerField(default=-1, help_text='SW neighbor color (-1 = any).')),
                ('n5_color', models.SmallIntegerField(default=-1, help_text='NW neighbor color (-1 = any).')),
                ('result_color', models.SmallIntegerField(help_text='Cell becomes this color.')),
                ('priority', models.IntegerField(default=0, help_text='Lower = higher priority. First match wins.')),
                ('ruleset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exact_rules', to='automaton.ruleset')),
            ],
            options={
                'ordering': ['ruleset', 'priority'],
            },
        ),
    ]
