# Generated by Django 6.0.4 on 2026-04-18 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automaton', '0002_exact_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='analysis',
            field=models.JSONField(blank=True, default=dict, help_text='Pattern-detection findings from detect_patterns: the tick at which the grid entered a cycle, the cycle period, and whether the cycle is a still life or oscillator. Empty until detect_patterns has run.'),
        ),
    ]
