# Generated by Django 6.0.4 on 2026-04-21 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automaton', '0003_simulation_analysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruleset',
            name='palette',
            field=models.JSONField(blank=True, default=list, help_text='Canonical cell-colour palette. Empty = use the built-in default. New simulations inherit this; palette edits on any simulation sync back here; merges inherit from parent A.'),
        ),
    ]
