# Generated by Django 6.0.4 on 2026-05-17 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automaton', '0004_ruleset_palette'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulation',
            name='height',
            field=models.PositiveIntegerField(default=128),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='width',
            field=models.PositiveIntegerField(default=128),
        ),
    ]
