# Generated by Django 6.0.4 on 2026-04-28 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SequenceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Human label — defaults to FASTA description or GenBank definition line.', max_length=300)),
                ('accession', models.CharField(blank=True, help_text='NCBI/EMBL accession if the source had one.', max_length=80)),
                ('organism', models.CharField(blank=True, help_text='From GenBank ORGANISM field. Blank for FASTA.', max_length=200)),
                ('sequence_type', models.CharField(choices=[('DNA', 'DNA'), ('RNA', 'RNA'), ('protein', 'Protein')], default='DNA', max_length=10)),
                ('sequence', models.TextField(help_text='Bases or amino acids, uppercase, no whitespace.')),
                ('length_bp', models.PositiveIntegerField(default=0, help_text='Cached length of `sequence` for fast list / detail rendering. Recomputed on save.')),
                ('source_format', models.CharField(choices=[('fasta', 'FASTA'), ('genbank', 'GenBank')], max_length=20)),
                ('source_filename', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Format-specific metadata: GenBank molecule_type, date, keywords, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnnotationFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_type', models.CharField(help_text="GenBank feature type — 'gene', 'CDS', 'mRNA', 'regulatory', 'misc_feature', etc.", max_length=40)),
                ('start', models.PositiveIntegerField(help_text='0-based inclusive start.')),
                ('end', models.PositiveIntegerField(help_text='0-based exclusive end.')),
                ('strand', models.IntegerField(choices=[(1, '+ (forward)'), (-1, '- (reverse)'), (0, '. (unstranded)')], default=1)),
                ('qualifiers', models.JSONField(blank=True, default=dict, help_text='GenBank qualifiers — gene name, product, locus_tag, note, db_xref, etc.')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='helix.sequencerecord')),
            ],
            options={
                'ordering': ['start', 'end'],
            },
        ),
        migrations.AddIndex(
            model_name='sequencerecord',
            index=models.Index(fields=['accession'], name='helix_seque_accessi_0e3c90_idx'),
        ),
        migrations.AddIndex(
            model_name='annotationfeature',
            index=models.Index(fields=['record', 'start'], name='helix_annot_record__7b189f_idx'),
        ),
        migrations.AddIndex(
            model_name='annotationfeature',
            index=models.Index(fields=['feature_type'], name='helix_annot_feature_56afc3_idx'),
        ),
    ]
