# Generated by Django 6.0.4 on 2026-04-30 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helix', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HuntCorpus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('feature_type', models.CharField(blank=True, help_text='AnnotationFeature.feature_type the windows were drawn from. Blank = mixed / no feature filter.', max_length=40)),
                ('window_size', models.PositiveIntegerField(default=256)),
                ('windows_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HuntRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('table', models.BinaryField(help_text='4,096 bytes — PackedRuleset.data for K=4.')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('class_label', models.CharField(blank=True, help_text="Wolfram class best-guess: 'I' / 'II' / 'III' / 'IV'. Optional; populated by analysis, not the engine.", max_length=8)),
                ('provenance_json', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='helix.huntrule')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HuntRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('params_json', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=12)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('scoreboard_json', models.JSONField(blank=True, default=list, help_text='Top-N entries from the final generation: [{"rule_slug":..., "score":..., "rank":...}].')),
                ('generation_log_json', models.JSONField(blank=True, default=list, help_text='Per-generation summary: [{"gen":i,"best":x,"mean":y}].')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('corpus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='helix.huntcorpus')),
                ('top_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='helix.huntrule')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RuleFilterScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('window_size', models.PositiveIntegerField(default=256)),
                ('stride', models.PositiveIntegerField(default=128)),
                ('scoring_fn', models.CharField(default='gzip', max_length=40)),
                ('track_json', models.JSONField(blank=True, default=list, help_text='[[start, end, score], ...] — sorted by start.')),
                ('n_windows', models.PositiveIntegerField(default=0)),
                ('score_min', models.FloatField(default=0.0)),
                ('score_max', models.FloatField(default=0.0)),
                ('score_mean', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='helix.sequencerecord')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='helix.huntrule')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HuntWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.PositiveIntegerField()),
                ('end', models.PositiveIntegerField()),
                ('idx', models.PositiveIntegerField(default=0)),
                ('corpus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='windows', to='helix.huntcorpus')),
                ('feature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='helix.annotationfeature')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='helix.sequencerecord')),
            ],
            options={
                'ordering': ['corpus', 'idx'],
                'indexes': [models.Index(fields=['corpus', 'idx'], name='helix_huntw_corpus__02bca8_idx')],
            },
        ),
    ]
