# Generated by Django 6.0.4 on 2026-05-01 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helix', '0002_huntcorpus_huntrule_huntrun_rulefilterscan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rulefilterscan',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='rulefilterscan',
            name='status',
            field=models.CharField(choices=[('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], default='done', help_text="Default 'done' so historical rows remain valid.", max_length=10),
        ),
        migrations.AddField(
            model_name='rulefilterscan',
            name='total_windows',
            field=models.PositiveIntegerField(default=0, help_text='Expected window count, set at launch time.'),
        ),
        migrations.AlterField(
            model_name='rulefilterscan',
            name='n_windows',
            field=models.PositiveIntegerField(default=0, help_text='Windows processed so far. Equals total_windows when done.'),
        ),
    ]
