# Generated by Django 6.0.4 on 2026-05-01 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helix', '0003_rulefilterscan_notes_rulefilterscan_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='huntrun',
            name='last_heartbeat_at',
            field=models.DateTimeField(blank=True, help_text='Updated by the runner thread on every progress callback. If a row is status=running but stale, the process likely died (e.g. runserver auto-reload).', null=True),
        ),
        migrations.AddField(
            model_name='rulefilterscan',
            name='last_heartbeat_at',
            field=models.DateTimeField(blank=True, help_text='Updated by the runner thread on every progress callback. If a row is status=running but stale, the process likely died (e.g. runserver auto-reload).', null=True),
        ),
    ]
