# Generated by Django 6.0.4 on 2026-04-12 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Human label used for routing, e.g. "snel-relay" or "gmail-dev".', max_length=100, unique=True)),
                ('enabled', models.BooleanField(default=True, help_text='Disabled accounts are hidden from the default selection and cannot be targeted by routing.')),
                ('is_default', models.BooleanField(default=False, help_text='Exactly one account may be the default. Marking this one as default automatically unmarks any other.')),
                ('smtp_host', models.CharField(max_length=255)),
                ('smtp_port', models.PositiveIntegerField(default=587)),
                ('smtp_username', models.CharField(blank=True, max_length=255)),
                ('smtp_password', models.CharField(blank=True, max_length=500)),
                ('smtp_use_tls', models.BooleanField(default=True)),
                ('smtp_use_ssl', models.BooleanField(default=False)),
                ('from_email', models.EmailField(help_text='Address that will appear in the From: header of outgoing mail. Usually matches smtp_username.', max_length=254)),
                ('from_name', models.CharField(blank=True, help_text='Optional display name shown alongside from_email.', max_length=100)),
                ('imap_host', models.CharField(blank=True, max_length=255)),
                ('imap_port', models.PositiveIntegerField(default=993)),
                ('imap_username', models.CharField(blank=True, max_length=255)),
                ('imap_password', models.CharField(blank=True, max_length=500)),
                ('imap_use_ssl', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('last_tested_at', models.DateTimeField(blank=True, null=True)),
                ('last_test_status', models.CharField(blank=True, max_length=16)),
                ('last_test_error', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SMTPServerConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(default='127.0.0.1', help_text='Address the SMTP server binds to. 127.0.0.1 for local-only; 0.0.0.0 to accept from LAN (including ESP nodes with mail capability).', max_length=253)),
                ('port', models.IntegerField(default=2525, help_text='Port the SMTP server listens on. 2525 is the conventional non-privileged testing port.')),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SMTP server config',
                'verbose_name_plural': 'SMTP server config',
            },
        ),
        migrations.CreateModel(
            name='LocalDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_addr', models.CharField(db_index=True, max_length=500)),
                ('to_addrs', models.JSONField(default=list, help_text='List of recipient addresses (RCPT TO values).')),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('body_text', models.TextField(blank=True, help_text='Plain-text body (text/plain part or decoded fallback).')),
                ('body_html', models.TextField(blank=True, help_text='HTML body (text/html part) if present.')),
                ('raw', models.TextField(blank=True, help_text='Full RFC822 source. Stored for reprocessing.')),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('peer_ip', models.GenericIPAddressField(blank=True, help_text='IP address of the sending client.', null=True)),
                ('read', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'local deliveries',
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['-received_at'], name='mail_locald_receive_9edf4a_idx'), models.Index(fields=['read', '-received_at'], name='mail_locald_read_59756c_idx')],
            },
        ),
        migrations.CreateModel(
            name='InboundMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(help_text='IMAP UID for this message within the mailbox. Used for dedup across polls.', max_length=64)),
                ('from_addr', models.CharField(blank=True, max_length=500)),
                ('to_addr', models.CharField(blank=True, max_length=1000)),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('body_text', models.TextField(blank=True)),
                ('body_html', models.TextField(blank=True)),
                ('attachment_names', models.JSONField(blank=True, default=list)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('raw', models.TextField(blank=True)),
                ('read', models.BooleanField(default=False)),
                ('handled', models.BooleanField(default=False)),
                ('handler_notes', models.TextField(blank=True)),
                ('mailbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbound_messages', to='mail.mailaccount')),
            ],
            options={
                'ordering': ['-received_at', '-fetched_at'],
                'indexes': [models.Index(fields=['mailbox', 'read'], name='mail_inboun_mailbox_415779_idx'), models.Index(fields=['-fetched_at'], name='mail_inboun_fetched_00e167_idx')],
                'unique_together': {('mailbox', 'uid')},
            },
        ),
    ]
