# Generated by Django 6.0.4 on 2026-05-14 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Composition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('group_slug', models.CharField(default='p4m', max_length=8)),
                ('motif_kind', models.CharField(choices=[('stock', 'Stock motif'), ('spoeqi_component', 'spoeqi component frame')], default='stock', max_length=24)),
                ('motif_spec', models.JSONField(default=dict, help_text='Stock: {"slug": "comma"}.  spoeqi_component: {"pact": "<slug>", "component": K, "generation": N}.')),
                ('tile_mm', models.FloatField(default=30.0)),
                ('landscape', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
