# Generated by Django 6.0.4 on 2026-05-14 19:29

import escher.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedMotif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('original_name', models.CharField(blank=True, max_length=200)),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('file', models.FileField(upload_to=escher.models._upload_to)),
                ('content_type', models.CharField(default='image/png', max_length=80)),
                ('width', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AlterField(
            model_name='composition',
            name='motif_kind',
            field=models.CharField(choices=[('stock', 'Stock motif'), ('spoeqi_component', 'spoeqi component frame'), ('tilesmith_tile', 'tilesmith tile silhouette'), ('upload', 'Uploaded bitmap')], default='stock', max_length=24),
        ),
    ]
