# Generated by Django 6.0.4 on 2026-04-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SMTPServerConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(default='127.0.0.1', help_text='Address the SMTP server binds to. 127.0.0.1 for local-only; 0.0.0.0 to accept from LAN (including ESP nodes with mail capability).', max_length=253)),
                ('port', models.IntegerField(default=2525, help_text='Port the SMTP server listens on. 2525 is the conventional non-privileged testing port.')),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SMTP server config',
                'verbose_name_plural': 'SMTP server config',
            },
        ),
        migrations.CreateModel(
            name='LocalDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_addr', models.CharField(db_index=True, max_length=500)),
                ('to_addrs', models.JSONField(default=list, help_text='List of recipient addresses (RCPT TO values).')),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('body_text', models.TextField(blank=True, help_text='Plain-text body (text/plain part or decoded fallback).')),
                ('body_html', models.TextField(blank=True, help_text='HTML body (text/html part) if present.')),
                ('raw', models.TextField(blank=True, help_text='Full RFC822 source. Stored for reprocessing.')),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('peer_ip', models.GenericIPAddressField(blank=True, help_text='IP address of the sending client.', null=True)),
                ('read', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'local deliveries',
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['-received_at'], name='mailserver__receive_92e838_idx'), models.Index(fields=['read', '-received_at'], name='mailserver__read_7ab2e1_idx')],
            },
        ),
    ]
