# Generated by Django 6.0.4 on 2026-04-21 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('konso', models.CharField(help_text="The sentence in Konso orthography. Use doubled vowels for length (aa, ee…), `ny` and `sh` as digraphs, and `'` for the glottal stop.", max_length=240)),
                ('gloss', models.CharField(blank=True, help_text='Morpheme-by-morpheme interlinear gloss. One gloss per space-separated Konso word; hyphens for morpheme boundaries (e.g. `gup-e` = build-PST).', max_length=400)),
                ('translation', models.CharField(help_text='Free English translation.', max_length=240)),
                ('tree_bracket', models.TextField(help_text='Tree in labelled-bracket notation. Example: [S [NP nama] [VP [NP tika] [V gupe]]]. Node labels are non-terminals; bare tokens at the bottom of each bracket are the Konso terminals.')),
                ('notes', models.TextField(blank=True, help_text='What to watch for — case clitic, relative clause, focus marker, SOV reminder, etc.')),
                ('source', models.CharField(choices=[('literature', 'From the literature — verify citation'), ('illustrative', 'Illustrative — author-reconstructed, verify'), ('operator', 'Operator-contributed')], default='illustrative', max_length=20)),
                ('citation', models.CharField(blank=True, help_text='Author, year, page — if this sentence is taken from the literature.', max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
    ]
