# Generated by Django 6.0.4 on 2026-04-21 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muka', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(help_text='Autoglottonym — what speakers call the language.', max_length=120)),
                ('english_name', models.CharField(help_text='Name used in English linguistic literature.', max_length=120)),
                ('family', models.CharField(choices=[('afroasiatic', 'Afroasiatic'), ('niger-congo', 'Niger-Congo'), ('nilo-saharan', 'Nilo-Saharan'), ('khoe-kwadi', 'Khoe-Kwadi / "Khoisan"'), ('austronesian', 'Austronesian'), ('indo-european', 'Indo-European'), ('isolate', 'Language isolate'), ('creole', 'Creole / Pidgin'), ('other', 'Other / unclassified')], default='other', max_length=20)),
                ('subgroup', models.CharField(blank=True, help_text='Branch within the family (e.g. Bantu, Cushitic, Kwa).', max_length=80)),
                ('region', models.CharField(blank=True, help_text='Primary geographic region (country or area).', max_length=120)),
                ('iso639_3', models.CharField(blank=True, help_text='ISO 639-3 three-letter code if assigned.', max_length=3)),
                ('speakers', models.PositiveIntegerField(default=0, help_text='Approximate number of speakers. 0 = unknown.')),
                ('word_order', models.CharField(choices=[('sov', 'SOV'), ('svo', 'SVO'), ('vso', 'VSO'), ('vos', 'VOS'), ('osv', 'OSV'), ('ovs', 'OVS'), ('free', 'Free / pragmatic'), ('mixed', 'Mixed / context-dependent'), ('unknown', 'Unknown / disputed')], default='unknown', max_length=8)),
                ('notes', models.TextField(blank=True, help_text='Typological highlights, notable features, orthographic quirks.')),
            ],
            options={
                'ordering': ['family', 'english_name'],
            },
        ),
        migrations.AlterField(
            model_name='sentence',
            name='konso',
            field=models.CharField(help_text="The sentence in the language's own orthography. Field name kept as `konso` for historical compat; the text can be any language.", max_length=240),
        ),
        migrations.AddField(
            model_name='sentence',
            name='language',
            field=models.ForeignKey(blank=True, help_text='Which language this sentence is in. Left blank only for legacy / pre-expansion rows.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sentences', to='muka.language'),
        ),
    ]
