# Generated by Django 6.0.4 on 2026-04-21 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muka', '0002_language_alter_sentence_konso_sentence_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='extinct',
            field=models.BooleanField(default=False, help_text='No living native speakers (Latin, Hittite, Ancient Egyptian, etc.). Remains True for liturgical / classical languages.'),
        ),
        migrations.AddField(
            model_name='language',
            name='family_name',
            field=models.CharField(blank=True, help_text='Glottolog top-family display name, e.g. "Indo-European", "Sino-Tibetan". Kept alongside the slug for readability.', max_length=80),
        ),
        migrations.AddField(
            model_name='language',
            name='glottocode',
            field=models.CharField(blank=True, db_index=True, help_text='Glottolog 8-char glottocode (e.g. stan1293 for Standard English). Blank for rows that predate Glottolog import.', max_length=10),
        ),
        migrations.AddField(
            model_name='language',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='language',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='language',
            name='macroarea',
            field=models.CharField(blank=True, help_text='Glottolog macroarea: Africa, Eurasia, Papunesia, Australia, North America, South America.', max_length=30),
        ),
        migrations.AddField(
            model_name='language',
            name='script',
            field=models.CharField(blank=True, help_text='Primary writing system (Devanagari, Latin, Chinese, Hieroglyphs, Tibetan, Hebrew, etc.).', max_length=60),
        ),
        migrations.AlterField(
            model_name='language',
            name='family',
            field=models.CharField(choices=[('afroasiatic', 'Afroasiatic'), ('niger-congo', 'Atlantic-Congo (Niger-Congo)'), ('nilo-saharan', 'Nilo-Saharan'), ('khoe-kwadi', 'Khoe-Kwadi / "Khoisan"'), ('austronesian', 'Austronesian'), ('austroasiatic', 'Austroasiatic'), ('tai-kadai', 'Tai-Kadai'), ('sino-tibetan', 'Sino-Tibetan'), ('japonic', 'Japonic'), ('koreanic', 'Koreanic'), ('dravidian', 'Dravidian'), ('turkic', 'Turkic'), ('uralic', 'Uralic'), ('mongolic', 'Mongolic'), ('indo-european', 'Indo-European'), ('trans-new-guinea', 'Nuclear Trans-New-Guinea'), ('pama-nyungan', 'Pama-Nyungan'), ('otomanguean', 'Otomanguean'), ('na-dene', 'Na-Dene'), ('algic', 'Algic'), ('quechuan', 'Quechuan'), ('arawakan', 'Arawakan'), ('tupian', 'Tupian'), ('sign-language', 'Sign Language'), ('pidgin', 'Pidgin'), ('creole', 'Creole'), ('isolate', 'Language isolate'), ('other', 'Other / unclassified')], default='other', max_length=30),
        ),
    ]
