# Generated by Django 6.0.4 on 2026-04-21 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muka', '0003_language_extinct_language_family_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='family',
            field=models.CharField(choices=[('afroasiatic', 'Afroasiatic'), ('niger-congo', 'Atlantic-Congo (Niger-Congo)'), ('nilo-saharan', 'Nilo-Saharan'), ('khoe-kwadi', 'Khoe-Kwadi / "Khoisan"'), ('austronesian', 'Austronesian'), ('austroasiatic', 'Austroasiatic'), ('tai-kadai', 'Tai-Kadai'), ('sino-tibetan', 'Sino-Tibetan'), ('japonic', 'Japonic'), ('koreanic', 'Koreanic'), ('dravidian', 'Dravidian'), ('turkic', 'Turkic'), ('uralic', 'Uralic'), ('mongolic', 'Mongolic'), ('indo-european', 'Indo-European'), ('trans-new-guinea', 'Nuclear Trans-New-Guinea'), ('pama-nyungan', 'Pama-Nyungan'), ('otomanguean', 'Otomanguean'), ('na-dene', 'Na-Dene'), ('algic', 'Algic'), ('iroquoian', 'Iroquoian'), ('uto-aztecan', 'Uto-Aztecan'), ('mayan', 'Mayan'), ('eskimo-aleut', 'Eskimo-Aleut'), ('quechuan', 'Quechuan'), ('aymaran', 'Aymaran'), ('arawakan', 'Arawakan'), ('tupian', 'Tupian'), ('kartvelian', 'Kartvelian'), ('sign-language', 'Sign Language'), ('pidgin', 'Pidgin'), ('creole', 'Creole'), ('constructed', 'Constructed'), ('isolate', 'Language isolate'), ('other', 'Other / unclassified')], default='other', max_length=30),
        ),
    ]
