# Generated by Django 6.0.4 on 2026-04-11 14:47

import attic.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Human-readable label. If blank, the filename is used.', max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('file', models.FileField(upload_to=attic.models._media_upload_path)),
                ('thumbnail', models.ImageField(blank=True, help_text='Auto-generated for image kind. Skipped for other kinds.', null=True, upload_to=attic.models._thumb_upload_path)),
                ('kind', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('document', 'Document'), ('other', 'Other')], default='other', help_text='Auto-derived from mime on save.', max_length=12)),
                ('mime', models.CharField(blank=True, max_length=120)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('sha256', models.CharField(blank=True, help_text='Hash of the file contents. Used for dedup detection — if two MediaItems have the same sha256 you have a duplicate upload.', max_length=64)),
                ('caption', models.TextField(blank=True)),
                ('alt_text', models.CharField(blank=True, help_text='Accessibility text for screen readers / image fallback.', max_length=300)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated. Free-form.', max_length=300)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attic_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['kind', '-uploaded_at'], name='attic_media_kind_befc40_idx'), models.Index(fields=['sha256'], name='attic_media_sha256_72228d_idx')],
            },
        ),
    ]
