#!/usr/bin/env python3
"""Bake soul.bin + tokenizer.json into a single soul_data.h header
that officesoul.c #includes.  Run from this directory:

    python3 gen_soul_data.py path/to/soul.bin path/to/tokenizer.json

Writes soul_data.h next to it.

The header exposes:
    SOUL_BIN_DATA[]  — raw bytes of soul.bin (v3 format)
    SOUL_BIN_LEN     — its length
    VOCAB_STR_BLOB[] — concatenated vocab tokens, NUL-terminated each
    VOCAB_OFFSETS[]  — 128 offsets into VOCAB_STR_BLOB
    VOCAB_LEN_TBL[]  — 128 lengths
    MERGES_AB[][2]   — (a_id, b_id) per merge
    MERGES_ID[]      — merged-token id per merge
    MERGES_N         — number of merges

Tokens are stored as raw UTF-8 / ASCII bytes (no escaping); the
upstream tokenizer's keys are all single-byte ASCII for this model.
"""
import json, sys
from pathlib import Path


def main():
    soul_path = Path(sys.argv[1] if len(sys.argv) > 1
                     else "../soulplayer/soul.bin")
    tok_path  = Path(sys.argv[2] if len(sys.argv) > 2
                     else "../soulplayer/tokenizer.json")

    soul = soul_path.read_bytes()
    tok  = json.loads(tok_path.read_text())

    vocab = tok["vocab"]
    merges_raw = tok["merges"]

    # vocab is dict {token: id}; build a 128-entry table.
    id_to_str = [""] * 128
    for tokstr, tid in vocab.items():
        if not (0 <= tid < 128):
            continue
        id_to_str[tid] = tokstr

    # Pack vocab strings.
    blob = bytearray()
    offsets = []
    lengths = []
    for s in id_to_str:
        offsets.append(len(blob))
        b = s.encode("utf-8")
        lengths.append(len(b))
        blob.extend(b)
        blob.append(0)   # NUL terminator (helps debugging, doesn't matter to us)

    # Resolve merges: each is [a_str, b_str]; need a_id, b_id, merged_id.
    str_to_id = {s: i for i, s in enumerate(id_to_str) if s}
    merges = []
    for a, b in merges_raw:
        merged = a + b
        if a not in str_to_id or b not in str_to_id:
            continue
        if merged not in str_to_id:
            continue
        merges.append((str_to_id[a], str_to_id[b], str_to_id[merged]))

    # Emit header.
    out = []
    w = out.append
    w("/* AUTO-GENERATED by gen_soul_data.py — do not edit by hand. */\n")
    w("#ifndef SOUL_DATA_H\n#define SOUL_DATA_H\n\n")
    w(f"#define SOUL_BIN_LEN  {len(soul)}\n")
    w(f"#define VOCAB_STR_BLOB_LEN {len(blob)}\n")
    w(f"#define MERGES_N      {len(merges)}\n\n")

    def hexdump(prefix, data, width=24):
        w(f"static const unsigned char {prefix}[{len(data)}] = {{\n")
        for i in range(0, len(data), width):
            chunk = data[i:i+width]
            w("    " + ", ".join(f"0x{b:02x}" for b in chunk) + ",\n")
        w("};\n\n")

    hexdump("SOUL_BIN_DATA", soul)
    hexdump("VOCAB_STR_BLOB", bytes(blob))

    w("static const unsigned short VOCAB_OFFSETS[128] = {\n")
    for i in range(0, 128, 16):
        w("    " + ", ".join(f"{x:5d}" for x in offsets[i:i+16]) + ",\n")
    w("};\n\n")

    w("static const unsigned char VOCAB_LEN_TBL[128] = {\n")
    for i in range(0, 128, 16):
        w("    " + ", ".join(f"{x:3d}" for x in lengths[i:i+16]) + ",\n")
    w("};\n\n")

    w(f"static const unsigned char MERGES_AB[{len(merges)}][2] = {{\n")
    for a, b, _ in merges:
        w(f"    {{ {a}, {b} }},\n")
    w("};\n\n")

    w(f"static const unsigned char MERGES_ID[{len(merges)}] = {{\n")
    for i in range(0, len(merges), 16):
        w("    " + ", ".join(f"{m[2]:3d}" for m in merges[i:i+16]) + ",\n")
    w("};\n\n")

    w("#endif /* SOUL_DATA_H */\n")

    out_path = Path(__file__).resolve().parent / "soul_data.h"
    out_path.write_text("".join(out))
    print(f"wrote {out_path} — {out_path.stat().st_size} bytes "
          f"({len(soul)} weight bytes, {len(merges)} merges, {len(blob)} blob bytes)")


if __name__ == "__main__":
    main()
