# Generated by Django 6.0.4 on 2026-04-10 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('experiments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HardwareProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Board name as you\'d recognize it in a parts box, e.g. "ESP32-WROOM-32", "Wemos D1 mini", "TTGO LoRa32 v1.6".', max_length=120, unique=True)),
                ('mcu', models.CharField(choices=[('esp8266', 'ESP8266'), ('esp32', 'ESP32 (classic, WROOM/WROVER)'), ('esp32s2', 'ESP32-S2'), ('esp32s3', 'ESP32-S3'), ('esp32c3', 'ESP32-C3'), ('esp32c6', 'ESP32-C6'), ('esp32h2', 'ESP32-H2'), ('rp2040', 'Raspberry Pi Pico (RP2040)'), ('avr', 'AVR (Arduino classic)'), ('other', 'Other / unknown')], default='esp32', max_length=16)),
                ('flash_mb', models.PositiveIntegerField(blank=True, help_text='Flash size in MB.', null=True)),
                ('ram_kb', models.PositiveIntegerField(blank=True, help_text='SRAM in KB.', null=True)),
                ('has_wifi', models.BooleanField(default=True)),
                ('has_bluetooth', models.BooleanField(default=False)),
                ('has_lora', models.BooleanField(default=False)),
                ('has_psram', models.BooleanField(default=False)),
                ('adc_bits', models.PositiveIntegerField(blank=True, help_text='ADC resolution in bits.', null=True)),
                ('gpio_count', models.PositiveIntegerField(blank=True, help_text='Usable GPIO count.', null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(help_text='Human-friendly name, e.g. "Gary". Not required to be unique.', max_length=100)),
                ('slug', models.SlugField(blank=True, help_text='URL-safe unique ID. Auto-derived from nickname if blank.', max_length=120, unique=True)),
                ('mac_address', models.CharField(blank=True, help_text='Hardware MAC address, e.g. AA:BB:CC:DD:EE:FF. Leave blank until known.', max_length=32)),
                ('hostname', models.CharField(blank=True, help_text='Optional network hostname, e.g. "gary.local" for mDNS.', max_length=253)),
                ('last_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('power_mode', models.CharField(choices=[('always_on', 'Always on (wall power)'), ('solar', 'Solar (dormant without sun)'), ('battery', 'Battery (finite runtime)'), ('on_demand', 'On demand (manually powered)'), ('unknown', 'Unknown / not specified')], default='unknown', max_length=16)),
                ('firmware_version', models.CharField(blank=True, max_length=64)),
                ('api_token', models.CharField(blank=True, help_text='Auto-generated on save. Sent by the ESP as Authorization: Bearer <token> when posting telemetry.', max_length=64, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('commissioned_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('experiment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nodes', to='experiments.experiment')),
                ('hardware_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nodes', to='nodes.hardwareprofile')),
            ],
            options={
                'ordering': ['nickname', 'slug'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('mac_address', ''), _negated=True), fields=('mac_address',), name='nodes_unique_mac_when_set')],
            },
        ),
    ]
