# Generated by Django 6.0.4 on 2026-04-10 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0002_seed_hardware_profiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(max_length=100)),
                ('value', models.FloatField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('raw_json', models.JSONField(blank=True, null=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='nodes.node')),
            ],
            options={
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['node', 'channel', '-received_at'], name='nodes_senso_node_id_384a34_idx'), models.Index(fields=['-received_at'], name='nodes_senso_receive_11e904_idx')],
            },
        ),
    ]
