# Generated by Django 6.0.4 on 2026-04-11 20:02

import django.db.models.deletion
import nodes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0003_sensorreading'),
    ]

    operations = [
        migrations.CreateModel(
            name='Firmware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Human label, e.g. "gary-aht20-sensor" or "greenhouse-monitor".', max_length=120)),
                ('version', models.CharField(help_text='Version string the sketch reports via firmware_version, e.g. "0.1.2". Compared byte-for-byte against what the node currently runs.', max_length=32)),
                ('bin_file', models.FileField(upload_to=nodes.models._firmware_upload_path)),
                ('sha256', models.CharField(blank=True, max_length=64)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=False, help_text='Exactly one row per HardwareProfile should be active. Enabling a new row clears the flag on siblings in save().')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('hardware_profile', models.ForeignKey(help_text='Any Node with this hardware profile is eligible to pull this firmware.', on_delete=django.db.models.deletion.CASCADE, related_name='firmwares', to='nodes.hardwareprofile')),
            ],
            options={
                'ordering': ['-uploaded_at'],
                'constraints': [models.UniqueConstraint(fields=('hardware_profile', 'version'), name='nodes_firmware_unique_profile_version')],
            },
        ),
    ]
