# Generated by Django 6.0.4 on 2026-04-26 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0005_node_self_registered'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardwareprofile',
            name='depth_mm',
            field=models.PositiveSmallIntegerField(default=55),
        ),
        migrations.AddField(
            model_name='hardwareprofile',
            name='height_mm',
            field=models.PositiveSmallIntegerField(default=15),
        ),
        migrations.AddField(
            model_name='hardwareprofile',
            name='width_mm',
            field=models.PositiveSmallIntegerField(default=28),
        ),
    ]
