# Generated by Django 6.0.4 on 2026-05-17 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotebookProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('path', models.CharField(help_text='Path to the .ipynb file relative to BASE_DIR (e.g. "notebooks/spoeqi_quine_pact_pipeline.ipynb").', max_length=400)),
                ('summary', models.TextField(blank=True, help_text='One-line description shown in the catalogue.')),
                ('description', models.TextField(blank=True, help_text='Longer prose; markdown OK. Shown on the detail page.')),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags (e.g. "spoeqi, quines, demo").', max_length=200)),
                ('related_apps', models.CharField(blank=True, help_text='Comma-separated Velour app slugs the notebook touches (e.g. "spoeqi, caformer").', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pinned', models.BooleanField(default=False, help_text='Show at the top of the catalogue.')),
            ],
            options={
                'ordering': ['-pinned', '-updated_at'],
            },
        ),
    ]
