# Generated by Django 6.0.4 on 2026-04-11 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(help_text='Human label, e.g. "Production users", "Gary aquarium logs".', max_length=120)),
                ('slug', models.SlugField(blank=True, help_text='URL-safe unique ID. Auto-derived from nickname if blank.', max_length=140, unique=True)),
                ('engine', models.CharField(choices=[('mysql', 'MySQL / MariaDB'), ('postgresql', 'PostgreSQL')], default='postgresql', max_length=16)),
                ('host', models.CharField(default='localhost', help_text='Hostname or IP, e.g. "db.internal", "10.0.0.5", "localhost".', max_length=253)),
                ('port', models.PositiveIntegerField(blank=True, help_text='TCP port. Leave blank to use the engine default (MySQL 3306, PostgreSQL 5432).', null=True)),
                ('username', models.CharField(blank=True, max_length=120)),
                ('password', models.CharField(blank=True, max_length=255)),
                ('database_name', models.CharField(blank=True, help_text='Database / schema to connect to. Optional — leave blank to connect to the server without selecting one.', max_length=120)),
                ('ssl_mode', models.CharField(blank=True, choices=[('', 'Default (no preference)'), ('disable', 'disable'), ('allow', 'allow'), ('prefer', 'prefer'), ('require', 'require'), ('verify-ca', 'verify-ca'), ('verify-full', 'verify-full')], default='', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('last_tested_at', models.DateTimeField(blank=True, null=True)),
                ('last_test_status', models.CharField(choices=[('untested', 'Not yet tested'), ('ok', 'OK'), ('failed', 'Failed')], default='untested', max_length=16)),
                ('last_test_error', models.TextField(blank=True)),
                ('last_test_server_version', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nickname', 'slug'],
            },
        ),
    ]
