# Generated by Django 6.0.4 on 2026-04-13 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='file_path',
            field=models.CharField(blank=True, help_text='Absolute path to the .sqlite3 file. Auto-set for new SQLite databases.', max_length=500),
        ),
        migrations.AlterField(
            model_name='database',
            name='database_name',
            field=models.CharField(blank=True, help_text='Database / schema name. Not used for SQLite.', max_length=120),
        ),
        migrations.AlterField(
            model_name='database',
            name='engine',
            field=models.CharField(choices=[('sqlite', 'SQLite (local file)'), ('mysql', 'MySQL / MariaDB'), ('postgresql', 'PostgreSQL')], default='sqlite', max_length=16),
        ),
        migrations.AlterField(
            model_name='database',
            name='host',
            field=models.CharField(blank=True, default='localhost', help_text='Hostname or IP. Not used for SQLite.', max_length=253),
        ),
        migrations.AlterField(
            model_name='database',
            name='port',
            field=models.PositiveIntegerField(blank=True, help_text='TCP port. Leave blank to use the engine default.', null=True),
        ),
    ]
