# Generated by Django 6.0.4 on 2026-05-09 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('cols', models.PositiveIntegerField(default=80)),
                ('rows', models.PositiveIntegerField(default=24)),
                ('notes', models.TextField(blank=True)),
                ('blob', models.BinaryField(help_text='Raw ANSI bytes — exactly what the program would have written to the terminal.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
