# Generated by Django 6.0.4 on 2026-05-02 09:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('kind', models.CharField(choices=[('hex_k4_packed', 'Hex K=4 packed (HXC4)')], default='hex_k4_packed', max_length=24)),
                ('n_colors', models.PositiveSmallIntegerField(default=4)),
                ('genome', models.BinaryField()),
                ('palette_ansi', models.BinaryField(default=b'\x00\x01\x02\x03')),
                ('sha1', models.CharField(db_index=True, max_length=40)),
                ('source', models.CharField(choices=[('automaton', 'Automaton'), ('s3lab', 'S3 Lab'), ('helix', 'Helix Hex Hunt'), ('stratum', 'S3 Lab Stratum'), ('hexnn', 'HexNN'), ('manual', 'Manual upload'), ('random', 'Random init'), ('mutation', 'Mutation'), ('crossover', 'Crossover'), ('evolve', 'Taxon evolve')], default='manual', max_length=16)),
                ('source_ref', models.CharField(blank=True, help_text='Free-form provenance — e.g. an automaton ruleset slug, helix HuntRule slug, parent rule sha for a mutation.', max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['sha1'], name='taxon_rule_sha1_b5356a_idx'), models.Index(fields=['source'], name='taxon_rule_source_3fff14_idx')],
            },
        ),
        migrations.CreateModel(
            name='EvolutionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(blank=True, max_length=120)),
                ('target_kind', models.CharField(choices=[('class', 'Wolfram class'), ('metric', 'Target metric value')], max_length=10)),
                ('target_class', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Class 1 — homogeneous (settles to fixed value)'), (2, 'Class 2 — periodic (settles to oscillator/still life)'), (3, 'Class 3 — chaotic (random-looking, no structure)'), (4, 'Class 4 — complex (edge of chaos, gliders, computation)')], null=True)),
                ('target_metric', models.CharField(blank=True, max_length=40)),
                ('target_value', models.FloatField(blank=True, null=True)),
                ('population_size', models.PositiveSmallIntegerField(default=24)),
                ('generations', models.PositiveIntegerField(default=0)),
                ('mutation_rate', models.FloatField(default=0.003)),
                ('best_fitness', models.FloatField(default=0.0)),
                ('fitness_curve', models.JSONField(blank=True, default=list)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('best_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='taxon.rule')),
                ('seed_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='taxon.rule')),
            ],
            options={
                'ordering': ('-started_at',),
            },
        ),
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wolfram_class', models.PositiveSmallIntegerField(choices=[(1, 'Class 1 — homogeneous (settles to fixed value)'), (2, 'Class 2 — periodic (settles to oscillator/still life)'), (3, 'Class 3 — chaotic (random-looking, no structure)'), (4, 'Class 4 — complex (edge of chaos, gliders, computation)')])),
                ('confidence', models.FloatField(default=0.0)),
                ('basis_json', models.JSONField(blank=True, default=dict)),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classifications', to='taxon.rule')),
            ],
            options={
                'ordering': ('-assigned_at',),
            },
        ),
        migrations.CreateModel(
            name='MetricRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(max_length=40)),
                ('value', models.FloatField()),
                ('grid_w', models.PositiveSmallIntegerField(default=24)),
                ('grid_h', models.PositiveSmallIntegerField(default=24)),
                ('horizon', models.PositiveSmallIntegerField(default=120)),
                ('seed', models.PositiveIntegerField(default=0)),
                ('extra_json', models.JSONField(blank=True, default=dict)),
                ('computed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_runs', to='taxon.rule')),
            ],
            options={
                'ordering': ('-computed_at',),
                'indexes': [models.Index(fields=['rule', 'metric'], name='taxon_metri_rule_id_1525e1_idx')],
            },
        ),
    ]
