# Generated by Django 6.0.4 on 2026-05-02 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='kind',
            field=models.CharField(choices=[('hex_k4_packed', 'Hex K=4 packed (HXC4)'), ('hex_nn', 'Hex NN (K-dialable, hexnn-genome / strateta)')], default='hex_k4_packed', max_length=24),
        ),
        migrations.AlterField(
            model_name='rule',
            name='source',
            field=models.CharField(choices=[('automaton', 'Automaton'), ('s3lab', 'S3 Lab'), ('helix', 'Helix Hex Hunt'), ('stratum', 'S3 Lab Stratum'), ('strateta', 'S3 Lab Strateta'), ('hexnn', 'HexNN'), ('manual', 'Manual upload'), ('random', 'Random init'), ('mutation', 'Mutation'), ('crossover', 'Crossover'), ('evolve', 'Taxon evolve')], default='manual', max_length=16),
        ),
    ]
