# Generated by Django 6.0.4 on 2026-05-02 19:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxon', '0002_alter_rule_kind_alter_rule_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(blank=True, max_length=120)),
                ('target_class', models.PositiveSmallIntegerField(choices=[(1, 'Class 1 — homogeneous (settles to fixed value)'), (2, 'Class 2 — periodic (settles to oscillator/still life)'), (3, 'Class 3 — chaotic (random-looking, no structure)'), (4, 'Class 4 — complex (edge of chaos, gliders, computation)')])),
                ('target_min_confidence', models.FloatField(default=0.6)),
                ('seed_strategy', models.CharField(choices=[('random', 'Random new genomes only'), ('mutate', 'Mutate existing class matches'), ('hybrid', 'Hybrid (random + mutate)')], default='hybrid', max_length=8)),
                ('mutation_rate', models.FloatField(default=0.005)),
                ('grid', models.PositiveSmallIntegerField(default=24)),
                ('horizon', models.PositiveSmallIntegerField(default=120)),
                ('seed', models.PositiveIntegerField(default=42)),
                ('max_seconds', models.PositiveIntegerField(default=300)),
                ('max_found', models.PositiveIntegerField(default=20)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('paused', 'Paused'), ('stopped', 'Stopped'), ('finished', 'Finished'), ('crashed', 'Crashed')], default='queued', max_length=12)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True)),
                ('rules_tried', models.PositiveIntegerField(default=0)),
                ('rules_kept', models.PositiveIntegerField(default=0)),
                ('last_log', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('-started_at',),
                'indexes': [models.Index(fields=['status'], name='taxon_autos_status_2fcf68_idx')],
            },
        ),
    ]
