# Generated by Django 6.0.4 on 2026-05-02 20:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxon', '0003_autosearch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(blank=True, max_length=120)),
                ('palette_ansi', models.BinaryField()),
                ('notes', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False, help_text='True for the agent whose palette is mirrored into Rule.palette_ansi (drives downloads, device pushes, card thumbnails). Exactly one per rule.')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='taxon.rule')),
            ],
            options={
                'ordering': ('-is_default', '-created_at'),
                'indexes': [models.Index(fields=['rule', 'is_default'], name='taxon_agent_rule_id_602e7a_idx')],
            },
        ),
    ]
