# Generated by Django 6.0.4 on 2026-05-16 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxon', '0005_backfill_default_agents'),
    ]

    operations = [
        migrations.AddField(
            model_name='classification',
            name='is_quine',
            field=models.BooleanField(db_index=True, default=False, help_text='True if the rule reproduces its own LUT-as-image under self-application above the SR threshold.'),
        ),
        migrations.AddField(
            model_name='classification',
            name='nest_depth',
            field=models.PositiveSmallIntegerField(db_index=True, default=0, help_text='Metachain run length: how many successive nested quine levels stay class-4 before tipping.'),
        ),
        migrations.AddField(
            model_name='classification',
            name='quine_origin',
            field=models.CharField(blank=True, help_text='Free-form provenance ("spoeqi quine #42 chain L3").', max_length=200),
        ),
        migrations.AddField(
            model_name='classification',
            name='sr_arbsigma',
            field=models.FloatField(blank=True, help_text='Histogram-overlap similarity (palette/position invariant) — looser σ-quine metric, ∈ [0, 1].', null=True),
        ),
        migrations.AddField(
            model_name='classification',
            name='sr_strict',
            field=models.FloatField(blank=True, help_text='Strict 16-tick Hamming similarity between final state and the rule LUT itself, ∈ [0, 1].', null=True),
        ),
        migrations.AlterField(
            model_name='rule',
            name='kind',
            field=models.CharField(choices=[('hex_k4_packed', 'Hex K=4 packed (HXC4)'), ('hex_nn', 'Hex NN (K-dialable, hexnn-genome / strateta)'), ('hex_k4_lut', 'Hex K=4 full LUT (HX4L, spoeqi quine)')], default='hex_k4_packed', max_length=24),
        ),
        migrations.AlterField(
            model_name='rule',
            name='source',
            field=models.CharField(choices=[('automaton', 'Automaton'), ('s3lab', 'S3 Lab'), ('helix', 'Helix Hex Hunt'), ('stratum', 'S3 Lab Stratum'), ('strateta', 'S3 Lab Strateta'), ('hexnn', 'HexNN'), ('spoeqi', 'Spoeqi (quine / metachain)'), ('manual', 'Manual upload'), ('random', 'Random init'), ('mutation', 'Mutation'), ('crossover', 'Crossover'), ('evolve', 'Taxon evolve')], default='manual', max_length=16),
        ),
    ]
