# Generated by Django 6.0.4 on 2026-05-17 22:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxon', '0006_quine_classification_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleStructureTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('manual', 'Manually assigned'), ('auto', 'Auto-detected')], default='manual', max_length=10)),
                ('confidence', models.FloatField(default=1.0, help_text='1.0 for manual assignments; lower for noisy auto-taggers.')),
                ('notes', models.TextField(blank=True)),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structure_tag_assignments', to='taxon.rule')),
            ],
            options={
                'ordering': ('-assigned_at',),
            },
        ),
        migrations.CreateModel(
            name='StructureTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True, help_text='What this tag means and what to look for visually.')),
                ('color_hex', models.CharField(default='#7ee787', help_text='Hex (#rrggbb) used on category chips and the legend.', max_length=7)),
                ('sort_order', models.PositiveSmallIntegerField(default=100, help_text='Lower = shown first on the structures index.')),
                ('references', models.TextField(blank=True, help_text='Citations, links, or one-line notes on prior art for this kind of structure.')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('rules', models.ManyToManyField(blank=True, related_name='structure_tags', through='taxon.RuleStructureTag', to='taxon.rule')),
            ],
            options={
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.AddField(
            model_name='rulestructuretag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_assignments', to='taxon.structuretag'),
        ),
        migrations.AlterUniqueTogether(
            name='rulestructuretag',
            unique_together={('rule', 'tag')},
        ),
    ]
